### ISSUE TITLE
"Save as PDF" only has the first page saved

### ISSUE THREAD

**Issue by catchandrelease** [hakimel/reveal.js#1000]
I have select "all" in page section, but page number showed is still 1/1. 
I am using Chrome, version is 36.0.1985.143 m.

**Comment by darenwelsh** [comment]
I can only get one page when I try it on my presentation:

http://enterprisemediawiki.github.io/slides/MeetingMinutes/

Chrome 39.0.2171.95 (64-bit) on Mac 10.8.5

**Comment by darenwelsh** [comment]
After a little more research, I discovered that this works:

http://enterprisemediawiki.github.io/slides/MeetingMinutes/?print-pdf#/

I don't know enough about how the github presentation hosting works to fully understand it, but maybe your documentation could include a note about this.

**Comment by hakimel** [comment]
@darenwelsh The requirement for the `print-pdf` query is included in the PDF printing instructions at https://github.com/hakimel/reveal.js#pdf-export

Everyone who's had problems with this; can you please try printing a PDF from http://lab.hakim.se/reveal-js?print-pdf and let me know if it still only prints one page? There's been some significant changes to how PDFs are laid out in reveal.js 3.0.

**Comment by demoneaux** [comment]
I think this can be closed, as it works seems to work pretty well now.

**Comment by prakriti-patra** [comment]
Hi, I have made a presentation using RevealJS that uses PlotlyJS in its slides. The presentation works fine in Chrome and FireFox. However, the PDF Download functionality is not working in FireFox as expected. Only one page gets printed which has the first 2 slides. Each slide does not break into a different page. In Chrome, it works perfectly fine though. I am using Firefox Version 49.0.2.

I have initialized my Reveal code using


```
Reveal.initialize({
          controls: true,
          progress: false,
          history: false,
          center: true,
          theme: Reveal.getQueryHash().theme, 
          transition: Reveal.getQueryHash().transition || 'default', 
        });
```

I have also included the pdf.css file using 

```
<script>
  var link = document.createElement( 'link' );
  link.rel = 'stylesheet';
  link.type = 'text/css';
  var url = window.location.href;
  var inst = url.match('print-pdf');
  link.href = (inst && inst.length && inst.length > 0) ? '/assets/pdf.css' : '/assets/paper.css';
  document.getElementsByTagName('head')[0].appendChild(link);
</script>
```
I am also including the print-pdf tag in the url. Is there anything else that I need to do specific to FireFox?
