### ISSUE TITLE
Element Attributes don't work consistently in markdown

### ISSUE THREAD

**Issue by jammon** [hakimel/reveal.js#1001]
When I write something like

```
      <section data-markdown><script type="text/template">
        - First talking point
        - Second one<!-- .element: class="fragment" -->
        - Third *very important* argument<!-- .element: class="fragment" -->
      </script></section>
```

I expect the list elements to appear one after the other. But I get something like this:

``` html
<li>
    First talking point
</li>
<li class="fragment" data-fragment-index="0">
    Second one <!--         -->
</li>
<li>
    Third <em class="fragment" data-fragment-index="1">very important</em> argument <!--         -->
</li>
```

The last line is visible from the beginning with only the emphasized part hidden, which is definitely not what I intended. 

Is there a workaround for this?

**Comment by cifkao** [comment]
@hakimel @humrochagf This now gets rendered as (with the asterisks):
> - Third \*very important\* argument

Rather than:
> - Third *very important* argument

Any idea what has changed?
