### ISSUE TITLE
"none" transition effect makes text blurry

### ISSUE THREAD

**Issue by ntrrgc** [hakimel/reveal.js#1002]
When `none` transition effect is used, the entire slides are blurry on Chrome and Linux. Interestingly, they are not blurry while the transition is in progress, i.e. until the progress bar at the bottom edge of the screen gets still.

Setting a different transition effect, e.g. `linear` does not reproduce the effect.

Screenshot after `none` transition:

![Screenshot](https://i.imgur.com/VXcso4P.png)

Screenshot after `linear` transition:

![Screenshot](https://i.imgur.com/CedlZ4b.png)

**Comment by bsletten** [comment]
I don't think it is just 'none' nor just on Chrome and Linux. On OS X (Yosemite), several of the transition styles (none, fade, slide and zoom) but not others (default or concave) have a dramatic and annoying "bolding" effect when you go from one slide to the next. It isn't super noticeable on Firefox on OS X, but it is on Chrome as well.

**Comment by ISO50** [comment]
On Yosemite with Firefox 44a2 this style helps:

```css
<style>
  .reveal > .slides > section > section {
    transform-style: flat;
  }
</style> 
```

Safari seems to be free of font blurring issues.

**Comment by tofi86** [comment]
> On Yosemite with Firefox 44a2 this style helps:

Thanks! This also prevents blurry text on Windows in Firefox 47.

**Comment by hakimel** [comment]
Thanks @ISO50, that's really useful. 

Transitions now use a flat transform-style by default, so content should no longer be blurred when using the slide, none or fade transitions. Other transitions – like concave and convex – still use preserve-3d.
