### ISSUE TITLE
Recommendation for how to do Reveal.js plugins?

### ISSUE THREAD

**Issue by jwlrs** [hakimel/reveal.js#1012]
I have a few little add on scripts I've written to tweak Reveal.js out of the box behavior.  I don't think they are appropriate to add to the library directly.  So anyway, I'd like to release them as a bundle of separate modules.  Any existing Reveal.js plugin approach?  Is it ok if I use "Reveal.js" in the name?

**Comment by joelarson4** [comment]
@hakimel - in case you want a chance to give feedback, I will probably go public with this soon: http://joelarson4.github.io/radReveal/
