### ISSUE TITLE
pdf.css sets too large font size

### ISSUE THREAD

**Issue by VladimirAlexiev** [hakimel/reveal.js#1021]
To fit a reasonable amount of text, I set width:1200, height:925 (same ratio as css/print/pdf.css: width: 297mm; height: 229mm).

The problem then is that print.pdf sets too big font size, which often causes page overflows. 
#992 describes images disappearing because of overflow: the same sometimes happens for tables, or a bulleted list that extends past the bottom.

I don't think the solution in #922 to break slides in two is good. I often have a couple of lines followed by a large image: I don't WANT that image moved to a new page.

I've overcome this by setting this in pdf.css (TWICE):
```
	font-size: 20pt !important;
```
but of course this solution is a bit crude

**Comment by demoneaux** [comment]
Closing this as the print stylesheets [already set font size to 20pt](https://github.com/hakimel/reveal.js/blob/e0d723be/css/print/paper.css#L23).
