### ISSUE TITLE
data-background-video not working on chrome mobile (android)

### ISSUE THREAD

**Issue by vitorcarvalhoml** [hakimel/reveal.js#1027]
Hello, the new option found in dev branch 'data-background-video' doesn't work on some android device using chrome.

On android 4.4 works when using the controls to move between slides.
On android 4.2.2 doesn't works  even when using controls to move in slideshow

How can I get more debug info about this?

**Comment by demoneaux** [comment]
This works for me in Android. Closing for now until there are more details provided.

**Comment by robertop87** [comment]
Reopen please @hakimel 
The issue persists.
Background videos does not play in Chrome/Firefox for Android
Sometime just plays the first video frame. This is possible disabling the transition effect, but in other case the background video does not play at all

Android Version: 4.4.4
Chrome version: any
RevealJs version: 3.4.1
Mobile: Samsung J5
