### ISSUE TITLE
Question: offline usage

### ISSUE THREAD

**Issue by faxm0dem** [hakimel/reveal.js#1031]
It seems to me using the default example index.html, a lot of remote access is being carried out (syntax highlighting, google fonts api, etc.).
How can I configure my presentation so it has all bells and whistles (all plugins) but doesn't require external web access?

**Comment by lamortenera** [comment]
I have to say that the default fallbacks for Google fonts can be really terrible.
This is what the title of my slides looked like when I was offline and I couldn't download the "Lato" or the "News Cycle" font family:
![fallback](https://user-images.githubusercontent.com/327763/59164590-23a07780-8b0f-11e9-9ddc-994c1d53f7ae.png)
The titles are almost unreadable.
I kind of fixed the situation by removing the css definitions that needed those font families.
Can we improve these fallbacks for the offline case?
