### ISSUE TITLE
data-background-video enhancements ideas

### ISSUE THREAD

**Issue by felquis** [hakimel/reveal.js#1049]
I'm using Branch DEV to test the `data-background-video` attribute in Google Chrome 38

I really liked this feature! I'm working on a talk for tomorrow and I have some insights about the use of `data-background-video` and I want to share.

1 [seems like a bug] When the video start playing and for some reason I come back to the previous slide, the video keep running, the video only go to the initial point when the video ends. I expect the video plays from the start always I go to the slide.

2 - I really like `background-cover`, would be great if, together with `data-background-video` we put a `data-background-video-cover`, to work just like a `background-size: cover` works for images. Actually I care about what is in the center of my video, so there's no problem to lose a bit of content in the corners of my video.

3 - Would be great to have a feature like `data-background-video-next-slide-on="end"` (default to false), or specify a point to go to the next slide, for example 1000ms before the video ends, trigger next slide data-background-video-go-to-next-slide-on="-1000", or go to next slide after video playing for 3 seconds `data-background-video-go-to-next-slide-on="3000"

I can work on some of this stuffs but, I just like to know if someone already thought about these things and if this is something useful.

Thanks (and sorry for my bad English) (sorry if here is the wrong place to share these ideas)

**Comment by rajgoel** [comment]
I would like to add another point.

4 - It would be great to be able to prevent the background video from always playing automatically (especially if the video has sound). I managed to access and control the background video using the ```getSlideBackground( x, y )``` function, but it appears impossible to prevent the video from playing automatically when navigating to the slide. I tried it to pause the video when the ```slidechanged``` event fires, but at that time it is to early to stop the video as playing of the video is started later.

**Comment by metamind16** [comment]
Also, could we have a configuration option? I'd like to set the video to mute, like you can with the video attributes in HTML. Would that work for background video's?

**Comment by diegoalsan** [comment]
It'd be amazing being able to mute background videos.

**Comment by diegoalsan** [comment]
It's possible since 3.3.0 release. :-)
[Releases](https://github.com/hakimel/reveal.js/releases)

**Comment by felquis** [comment]
Thanks @diegoalsan
