### ISSUE TITLE
Markdown table column alignment

### ISSUE THREAD

**Issue by dnmfarrell** [hakimel/reveal.js#1050]
Cell alignment in markdown is ignored:

    |ID|Name|Value|
    |------|:---:|-----:|
    |001|Bank ABC|5,740.00|
    |002|Super Fund|1,2280.00|
    |003|Big Savings Bank|430.00|

Should display as:

|ID|Name|Value|
|------|:---:|-----:|
|001|Bank ABC|5,740.00|
|002|Super Fund|1,2280.00|
|003|Big Savings Bank|430.00|

Instead you have to type this:

    |ID|Name|Value|
    |------|---|-----|
    |001|Bank ABC|5,740.00|
    |002|Super Fund|1,2280.00|
    |003|Big Savings Bank|430.00|

To get revealjs to display properly. The flexibility is helpful but this reduces the benefits of using a markdown approach as the syntax is ugly and verbose. This is a barrier in getting revealjs adopted at $work, particularly by non-technical users. 

Please just respect the markdown formatting!

Thanks

**Comment by fehmer** [comment]
+1

**Comment by GitHub-Lover** [comment]
+1

**Comment by hakimel** [comment]
Fixed by @fehmer in #1149

**Comment by dnmfarrell** [comment]
Thank you **very** much!
