### ISSUE TITLE
Regex for markdown data-seperator  

### ISSUE THREAD

**Issue by trcook** [hakimel/reveal.js#1051]
Hi, This is a great package. Thanks for developing.
I'm having an issue with the markdown import feature. Specifically, i'm trying to setup the data-seperator using a regex lookahead and it doesn't appear to be functioning properly. I'd chalk this up to some sort of limitation in the way the data-seperator is employed in the javascript (I'm not fluent in js), but the look ahead feature works fine with the data-vertical argument. Example:

``` html
<section data-markdown="../my_talk.md"  data-separator="^\n(?=# )"  
         data-vertical="^\n(?=## )"  
         data-notes="^Note:"  ></section>
<section data-title="comparative statics">
```

In this code, the vertical slides are appropriately separated (with the level 2 heading preserved -- hence the lookahead), but the horizontal slides are not. The whole file reads in as one long series of vertical slides. Crucially, it appears that the regex is matching -- that is, reveal is creating a new slide, but it's not separating it out to a new horizontal section. 

This occurs regardless of the setting of the data-vertical -- so it doesn't appear to be the case that the data-vertical setting is directly interfering with the data-section setting. Further, any regex with a lookahead fails for the data-section setting.

**Comment by anantshri** [comment]
It would be awesome if we can have something much more simpler like 

<section data-markdown="test.md" data-separator="\n#" data-vertical-separator="\n##" data-notes="^Notes:">


At this point doing something like this divides the proper sections but only horizontally no vertical sections work.

Would be awesome if /b or simmilar notation is available to denote blankspace then we can use # and ## as seperator's directory without using any external entity in the system.

**Comment by demoneaux** [comment]
@trcook: seems like one of your data-attributes is wrong. As [mentioned here](https://github.com/hakimel/reveal.js#markdown), the attribute for the vertical separator should be `data-separator-vertical`.

@anantshri: for the separator regexes, we are using native JS regex syntax, hence we will not be able to add additional features. You will probably need to use lookaheads in your regex, like `data-separator="\n(?=#\n)"`.
