### ISSUE TITLE
Vertical slides don't work well for print-pdf in dev branch 

### ISSUE THREAD

**Issue by aspergerish** [hakimel/reveal.js#1053]
The vertical slides can "leak" upwards in the PDF produced, i.e., parts of slides below can appear in slides above.

Edit: Sorry, vertical slides using markdown don't work even in presentation. Did not notice that.

**Comment by hakimel** [comment]
If I read your edit correctly, there is no issue with vertical slides in PDFs so I'll close this.

**Comment by aspergerish** [comment]
Hi, I think there are issues both in presentation and in PDFs when I posted the issue. I am unsure if anything has changed since then.

**Comment by hakimel** [comment]
It most likely has not changed since then – searched through issues and I believe #929 is the issue you are encountering.
