### ISSUE TITLE
Individual slide vertical centering broken with nested sections

### ISSUE THREAD

**Issue by jakerella** [hakimel/reveal.js#1055]
Hi! I wanted to have some slides vertically centered and others not, so I set the `center:false` option and then added the `center` class to sections that I wanted it on (`<section class='center'>`). However, when I have nested sections (for vertical navigation) the vertical centering does not work. All slide content in the "column" are about halfway off the top of the screen.

My structure:

``` html
<div class='slides'>
  <section>
    <section class='center'>
      <h2>Some title</h2>
      <p>This will NOT be centered, and will be partially off the top of the screen</p>
    </section>
    <section>
      <h2>Some other slide</h2>
    </section>
  </section>
</div>
```

Note that if I add the class of `center` to the containing `<section>` for the vertical column then all centering within that column works, however, the slides/sections that _do not_ have the `center` class within that column are no longer top-aligned. The work around is for me to not use the vertical navigation, but I like that!!

The `top` value for the current slide is being miscalculated when the `center` class is applied and there are nested sections, but I'm not sure where that happens or what the correct fix would be. If I get some time I'll try to look into it.

**Comment by demoneaux** [comment]
Can't seem to replicate this now, closing for now.

**Comment by jakerella** [comment]
It's been a while, I'll ping here if I can replicate again.
