### ISSUE TITLE
changing background color behind inserted video

### ISSUE THREAD

**Issue by jrherr** [hakimel/reveal.js#1056]
This may be adding to this [thread](https://github.com/hakimel/reveal.js/issues/751), but I was attempting to insert a video as a background, but when I do there is still a white border.  I was hoping for all black at the ends of the video.  

Here is my code:

```
<!-- Slide -->
<section data-background-color="#000000" data-background-size="contain" data-transition="fade">
<video class="stretch" data-autoplay src="img/test_video.mp4"></video>
</section>
```

Screenshot:
![screen shot 2014-11-17 at 4 38 37 pm](https://cloud.githubusercontent.com/assets/2516381/5078326/d5212c50-6e79-11e4-99c9-7f45d46ee204.png)

Does anyone have any input on the best way to do this without changing the css for all the slides?

Thanks!

**Comment by yosefw** [comment]
+1

**Comment by AlexandreBonneau** [comment]
+1

**Comment by bnjmnt4n** [comment]
This can probably be done with:
```html
<section data-background-video="http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4"
         data-background-color="#000">
</section>
```
