### ISSUE TITLE
Server Side Speaker Notes 404 Error

### ISSUE THREAD

**Issue by seongbong** [hakimel/reveal.js#1057]
(Please understand do not write English well)

I want to view notes and handling slides on phone device,
so set initailze code to use for socket.io/socket.io.js & plugin/notes-server/client.js
and then ran node plugin/notes-server

but, 
first, can't found socket.io.js file,
so... i found this file in /node_modules/socket.io/node_modules/socket.io-client/dist directory, and copied & pasted, and then this trouble was solved.

I was able to see the message ("View slide notes at ~~~ ") on console tab,
but, that url's response is HTTP 404 Error
i could see another error message after "view slide notes at ~~ " log,
it is "GET ~~ /socket.io/1/notes/ ~~" 404 not found

I don't know how to do for what I want - view notes & handling slides on my phone device

**Comment by demoneaux** [comment]
This should be working fine currently.
