### ISSUE TITLE
Error when using 'bower install'

### ISSUE THREAD

**Issue by hypery2k** [hakimel/reveal.js#1058]
When installing from nodes.org via `bower install` I'm getting this error:

```
/usr/bin/env: node: File or Directory not found
npm ERR! weird error 127
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
```
Doing a `sudo apt-get install nodejs-legacy` fixes it

**Comment by hakimel** [comment]
I have no idea what this means. Is it due to reveal.js using an outdated version of node? That was updated a short while ago as part of 3.0.

**Comment by hakimel** [comment]
Gonna close this since there's been no indication of it being an issue for anyone else. Also all reveal.js dependencies have update since this.
