### ISSUE TITLE
Support for synchronized audio (for narration)

### ISSUE THREAD

**Issue by fghaas** [hakimel/reveal.js#1065]
Here is something I've been thinking about for a while, so I thought I'd write it up here to see what others think. I'm not sure if and how this is feasible, so it would be great if others could chip in with additional insight.

I think it would be great if reveal supported playing an audio track on load, and then provided some way of synchronizing slides with the audio. That way, the presentation creator could narrate their presentation, and viewers could skip back and forth and would automatically be at the correct spot in the narration. Something like

```html
<section data-audio="3:14"> <!-- using an hh:mm:ss format -->
```

or

```html
<section data-audio="194"> <!-- using just seconds, perhaps less user-friendly -->
```

Apparently (though I am admittedly no expert here), seeking in audio media is supported through [`HTMLMediaElement.currentTime`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement).

This would also require that reveal could set auto-advance timing on a per-slide basis, rather than only globally as it presently does.

A presenter could either explicitly record the audio offline, or perhaps even record live audio while they are presenting. In the latter case, it would be fantastic if there was a way to automatically record the times when slide transitions were made in the live presentation. Perhaps most of the scaffolding for that already exists in the multiplex functionality?

**Comment by lordsutch** [comment]
I've rigged up something that may do what you want, although it is geared more to fragments within slides than slides themselves. It uses a "data-timepoints" attribute on the audio tag to decide when to advance.

JavaScript file: http://amgov.cnlawrence.com/narration.js
Demo: http://amgov.cnlawrence.com/05-publicopinion.html (and others on that website).

Hope this helps.

**Comment by fghaas** [comment]
@lordsutch, thanks for the heads-up!

**Comment by demoneaux** [comment]
Closing this as there’s already a plugin for this.
