### ISSUE TITLE
Announce presence of nested slides, notes and fragments

### ISSUE THREAD

**Issue by mpnkhan** [hakimel/reveal.js#1068]
Currently do not have a clue that the features like nested slides, notes and fragments are available in certain slides. When such slides are encountered a Hint Help text should be automatically spoken. 

Tried t build like a plugin https://github.com/mpnkhan/reveal.js/blob/a4bfa201d0682d40e50c8cabf72ba007047441d1/plugin.js  
It worked but  it would be good if this includes in code reveal.JS. Also not sure how these HintText could be used for  Internalization.

**Comment by demoneaux** [comment]
Currently, vertical slides are indicated by a change in colour of the down button in the controls. Feel free to create a plugin for hinting.
