### ISSUE TITLE
Keyboard issues when using Reveal with DPS (ios webview)

### ISSUE THREAD

**Issue by baj84** [hakimel/reveal.js#1069]
Hi,

I'm using Reveal for an presentation that is viewed in Adobe Folio on an iPad. 

Though when you try to type into a free text input the IOS keyboard doesn't focus on inputs or scroll to the input. 

I think it's because Reveal is preventing IOS from taking control of the scrollTo and/or focus events. It works fine in Safari on the iPad.

Any help on this would be really appreciated.

**Comment by demoneaux** [comment]
I’m not too sure about this. I don’t have an iPad, so I can’t test. Feel free to ping back with more details/fixes.
