### ISSUE TITLE
Section in README.md describing PDF export is Mac OSX specific

### ISSUE THREAD

**Issue by KurtPfeifle** [hakimel/reveal.js#1073]
Only a very minor issue... but the description about PDF export in README.md is too Mac OSX centric.

It seems to *assume* that everybody is using a Mac, because it mentions...

>     2. Open the in-browser print dialog (CMD+P).

There is no [CMD] key on non-Apple computers. For [WIN] the keyboard shortcut is probably [CTRL+P], but I cannot verify right now. Dunno if every Linux system would work with that too...

**Comment by Delapouite** [comment]
Yes, it's `CTRL+P` on Windows and Linux

**Comment by hakimel** [comment]
fixed in #1523
