### ISSUE TITLE
external markdown demo does not work

### ISSUE THREAD

**Issue by wighawag** [hakimel/reveal.js#1077]
Hi, 
It seems using markdown as an external file does not work properly.
Only the first slide is shown. I tried with the example.html demo

**Comment by juhoffma** [comment]
Same for me. Seems external markdown is broken in the current dev branch, as it seems the data-markdown is not interpreted

**Comment by juhoffma** [comment]
Correction it seems that

```
data-separator="^---"
data-vertical="^--"
data-notes="^Notes:"
```

are not interpreted

**Comment by juhoffma** [comment]
Looking at the code of markdown.js I found that the attributes were renamed to

```
data-separator="^---"
data-separator-vertical="^--"
data-separator-notes="^Notes:"
```

works for me now. I think it makes sense to update the docs. Let me know if you are interested in a PR

**Comment by hakimel** [comment]
Thanks for figuring that out @juhoffma. This should have been mentioned in the 3.0 release notes. I've updated the release notes to cover the renamed attributes. Also added it as a step in the migration 2.0 > 3.0 migration instructions: https://github.com/hakimel/reveal.js/wiki/Migrating-to-reveal.js-3.0.0

**Comment by IEfucker** [comment]
still not working with "data-separator-notes"

**Comment by juhoffma** [comment]
@IEfucker I do not really understand what you are trying to say

**Comment by demoneaux** [comment]
Closing this as it has since been fixed.
