### ISSUE TITLE
?print-pdf removes also links

### ISSUE THREAD

**Issue by Bysmyyr** [hakimel/reveal.js#1078]
I am just user of slides done with reveal.js

I like more read pdf-style slides. There is one problem: ?print-pdf option removes also links which are important.

**Comment by hakimel** [comment]
Links appear to be working when I export a PDF from the demo presentation at lab.hakim.se/reveal-js using the current stable version of Chrome.

Here's the output: http://cl.ly/1i0Q3k0r162F/reveal-2.6.2.pdf

**Comment by davidaparicio** [comment]
I have the same issue (no links in PDF export) on MacOS
- Chromium Version 80.0.3960.0 (Developer Build) (64-bit)
- Firefox Version 73.0 (64-bit)
on Reveal.js presentations, and [the official website](https://revealjs.com/?print-pdf#/)
