### ISSUE TITLE
AboutVerticalSection

### ISSUE THREAD

**Issue by tennsai3** [hakimel/reveal.js#1081]
Hello.
I use Reveal.js 2.6.2.

I want use these function
1:Do not reset vertical section position,when start(first)position and loop.
2:When use up/down slide vertical section, other vertical section sync moved.
   and do not reset position when move to other section.

When i change(erase) these script ↓

```
    // Resets all vertical slides so that only the first is visible
    resetVerticalSlides();false

    // Reset all slides upon navigate to home
    // Issue: #285 

 * Resets all vertical slides so that only the first
 * is visible.
```

working Not-Reset-verticalsection,when start(first) position and loop.

Reveal.js 1.4.0 had vertical sync moved.
but Vertical sync moved, they call bug.
What should i do?

**Comment by demoneaux** [comment]
See https://github.com/hakimel/reveal.js/issues/1519#issuecomment-298313406. We probably will not implement this in Reveal core, although it should be reasonably easy to do so yourself.
