### ISSUE TITLE
Integrating Mermaid diagrams into Markdown slides

### ISSUE THREAD

**Issue by velvia** [hakimel/reveal.js#1082]
Hey guys,

Any thoughts on integrating Mermaid (https://github.com/knsv/mermaid) into Markdown slides?

Basically let's say I have a giant Markdown doc used for slides, with separators etc.   How would I be able to add a Mermaid graph, like this:

```
<div class="mermaid">
graph LR;
    A[Hard edge]-->|Link text|B(Round edge);
    B-->C{Decision};
    C-->|One|D[Result one];
    C-->|Two|E[Result two];
</div>
```

without having reveal.js interpret and translate the stuff between the div's, and just pass the stuff in between straight to mermaid?

**Comment by heycalmdown** [comment]
+1

**Comment by fehmer** [comment]
+1

**Comment by oantoshchenko** [comment]
+1

**Comment by lrestifo** [comment]
+1

**Comment by bfritscher** [comment]
The mermaid doc has some examples on how to write a marked renderer http://knsv.github.io/mermaid/usage.html#example-of-marked-renderer therefore it should be possible to write markdown code blocks which get transformed to mermaid div, which then can get picked up by the mermaid code. Having the right code trigger in the right sequence is the main issue.

**Comment by velvia** [comment]
Would it be possible to integrate Mermaid directly into Marked?  I mean
have something like this
```mermaid-graph
A --> B(blah)
```

directly render into HTML using Marked.

On Sun, Apr 12, 2015 at 8:24 AM, Boris Fritscher <notifications@github.com>
wrote:

> The mermaid doc has some examples on how to write a marked renderer
> http://knsv.github.io/mermaid/usage.html#example-of-marked-renderer
> therefore it should be possible to write markdown code blocks which get
> transformed to mermaid div, which then can get picked up by the mermaid
> code. Having the right code trigger in the right sequence is the main issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hakimel/reveal.js/issues/1082#issuecomment-92079523>.
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by fehmer** [comment]
Hi,

i started implementing this feature. The graph is rendered but there seem to be a problem with the reveal.css file. If some of you guys want to have a look at it you can checkout my code from fehmer/reveal.js branch mermaid, https://github.com/fehmer/reveal.js/tree/mermaid

**Comment by maxmeyer** [comment]
@fehmer Is this knsv/mermaid#157 an issue for you as well?

**Comment by maxmeyer** [comment]
BTW: I started to integrate `mermaid` into [`middleman-presentation`](https://github.com/fedux-org/middleman-presentation) &ndash; a ruby gem which wraps `reveal.js` + some more additions.

**Comment by ludwick** [comment]
I went in a bit different direction to solve this issue. You can find my code [here](https://github.com/ludwick/reveal.js-mermaid-plugin). Note: pretty rough as I built this for a presentation I was preparing for (plus I am not very knowledgeable with javascript & css at this point).

**Comment by velvia** [comment]
Hm, what about integrating mermaid into marked.js?  Then multiple places
can take advantage of it.  (I suppose you would run into the same issue).

On Thu, Apr 23, 2015 at 12:07 PM, Rachael Ludwick <notifications@github.com>
wrote:

> I went in a bit different direction to solve this issue. You can find my
> code here <https://github.com/ludwick/reveal.js-mermaid-plugin>. Note:
> pretty rough as I built this for a presentation I was preparing for (plus I
> am not very knowledgeable with javascript & css at this point).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hakimel/reveal.js/issues/1082#issuecomment-95687719>.
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by maxmeyer** [comment]
@ludwick 

Thanks a lot. I will look into your solution soon. 

@velvia 

> Hm, what about integrating mermaid into marked.js? 

I don't think this is a good way. `mermaid` has nothing to do with markdown parsing, so why should it - a diagram/graph parser - be part of a markdown parser? @chjj Any thoughts on that?

I really like the idea to have it - mermaid - separated and that it looks for HTML-elements which are flagged with `class="mermaid"`.

In my (ruby-) implementation I re-use markdown code blocks to generate the HTML `mermaid` "needs":

    ~~~ mermaid-graph
    [...]
    ~~~

becomes

```html
<div class="mermaid">
[...]
</div>
```

I use a [custom code block parser](https://github.com/fedux-org/middleman-presentation/blob/feature/mermaid/middleman-presentation-core/lib/middleman-presentation-core/syntax_highlighter.rb) for `kramdown` to make this possible. Since this is a ruby gem I'm not sure how this could be done with `marked.js`. Maybe @chjj can help with some hints.

@velvia 

If building a custom code block parser is possible with `marked.js`, you could then build a plugin for `reveal.js`/`marked.js` to integrate it into your presentation.

**Comment by fehmer** [comment]
hi @maxmeyer ,
I used the guide posted by @bfritscher to define a [custom code block parser](https://github.com/fehmer/reveal.js/commit/6f828a0355175a5514eba40fa4a44be76884fdda#diff-7bb64d29f19e738b6dfb4b72976507c4R21) as you suggested. I haven't have time to look into my remaining css problem yet, but the html is generated correctly i think.

**Comment by maxmeyer** [comment]
@fehmer Great! I wrote an [article](https://www.fedux.org/articles/2015/05/08/embedded-css-in-svg-image.html) some time ago about the design issue I still have.

I would love to see mermaid have an API like reveal.js, something like

```
Mermaid.initialize({
  cloneCssStyles: true | false
})
```

Unfortunately it doesn't have such an interface yet.

**Comment by velvia** [comment]
@fehmer I tried your changes.  They kind of work, but they mess up the main reveal CSS styling, and the generated diagrams text does not show up (probably a CSS thing again).

@maxmeyer I'll try the marked.js changes if I have time.  Not sure this will get past the CSS issues though.  I do believe the issue is that Mermaid has its own CSS styles which conflict, and maybe it needs that API as you said.

**Comment by maxmeyer** [comment]
@velvia I wrote an [article](https://www.fedux.org/articles/2015/05/08/embedded-css-in-svg-image.html) which describes the design issue.

**Comment by velvia** [comment]
Yes, this is definitely the problem.... but what is the solution?  How can
we have the .svg's not embed CSS?

On Sun, May 10, 2015 at 10:57 PM, maxmeyer <notifications@github.com> wrote:

> @velvia <https://github.com/velvia> I wrote an article
> <https://www.fedux.org/articles/2015/05/08/embedded-css-in-svg-image.html>
> which describes the design issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hakimel/reveal.js/issues/1082#issuecomment-100777012>.
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by maxmeyer** [comment]
I think this needs to be solved by mermaid.

**Comment by maxmeyer** [comment]
@velvia 
See  knsv/mermaid#157 for a more complete "bug" description.

**Comment by velvia** [comment]
@maxmeyer @fehmer have you guys tried the fix in mermaid 0.5.0/0.5.1?   It seems the API has changed, and somehow the `<div class="mermaid">....` is not getting rendered to SVG for me.   Basically the only change I made to the initialize code in `markdown.js` is this:

```javascript
				// call mermaid if present
				if(typeof mermaid !== 'undefined' ) {
					mermaid.initialize({mermaid: { cloneCssStyles: false }}, ".mermaid");
					// mermaid.init();
				}
```

**Comment by maxmeyer** [comment]
@velvia I tried to integrate it back in 2015, but that failed. After that I didn't work on that code. :-( Unfortunately I had other things todo and forgot about it I must admit.

**Comment by velvia** [comment]
I figured out that there is some kind of bug on mermaid end I think.  Will follow up with them.  Basically when cloneCssStyles is set to true, there’s something wrong with SVG output.  When cloneCssStyles is set to false, then no svg is generated.  Will debug further with a non-minimized mermaid.js

**Comment by demoneaux** [comment]
This doesn't seem to have to do with Reveal, and is more related to the Mermaid parser. On a side note, the next release of Reveal will allow customisations to the Markdown rendering engine, so you can pass your own renderer to integrate Mermaid into marked if possible (as mentioned in the first few comments).
