### ISSUE TITLE
LESS highlight.js syntax not supported

### ISSUE THREAD

**Issue by julienmartin** [hakimel/reveal.js#1084]
LESS syntax seems to be not supported. Is it possible to add it ?

highlight.js supports it since v8.3 (2014-10-09).

**Comment by Delapouite** [comment]
Highlight.js is currently hardcoded in 8.2 right into the equivalent plugin : 

https://github.com/hakimel/reveal.js/blob/dev/plugin/highlight/highlight.js

This should be extracted as an external dependency.

**Comment by hakimel** [comment]
highlight.js has been updated to 8.6 which includes LESS support.
