### ISSUE TITLE
Background transition wrong when leaving overview mode

### ISSUE THREAD

**Issue by RasmusWL** [hakimel/reveal.js#1087]
When leaving the `overview` mode, the transition is almost always wrong -- it displays the transition needed for entering `overview` mode.

If you for example press `ESC` twice in a row, this will happen. They _only_ way I have gotten the correct transition, is to navigate with keys and press enter.

**Comment by hakimel** [comment]
Thanks for reporting. This transition is being removed entirely in reveal.js 3.0.0 so it will no longer be an issue.
