### ISSUE TITLE
Background not included in overview mode

### ISSUE THREAD

**Issue by RasmusWL** [hakimel/reveal.js#1088]
If you use custom background a lot in your presentation, overview mode will not do you much good. It will always display the background of the currently selected slide. If you mouse over other slides, the background will in fact change.

I would propose to show the background of each slide in the overview, so you can actually see what the slide did look like.

ps. Thanks for the good work :)

**Comment by hakimel** [comment]
This one has been bothering me since backgrounds were first introduced. It's been fixed now in the dev branch and will make its way out with the next release.

**Comment by RasmusWL** [comment]
awesome! Thanks
