### ISSUE TITLE
shuffle slides

### ISSUE THREAD

**Issue by benjamingr** [hakimel/reveal.js#1089]
Hey,

Are there any plans to support shuffling slide order or randomizing slide order?

If there are not - would you entertain a PR?

**Comment by hakimel** [comment]
Thanks for the suggestion but doesn't feel like this is a common enough use case to merit adding to the framework. A small script ahead of reveal.js initializing should be able to do this.

**Comment by demoneaux** [comment]
Closed in #1506.

**Comment by benjamingr** [comment]
Thanks!
