### ISSUE TITLE
Speakernotes + shrinking fragment crash Chromium on Linux

### ISSUE THREAD

**Issue by da-kid** [hakimel/reveal.js#1092]
Hey
I just tried out the [demo](http://lab.hakim.se/reveal-js/#/20/1) together with the speaker notes, iterating through it.
All was working well, until I reached the shrinking fragment.
As long as I leave the speaker notes closed, everything works fine, but letting it shrinks causes chromium to fix. There is no error message in the terminal.

I am using `Chromium 39.0.2171.95`.

**Comment by hakimel** [comment]
That's really strange. Unfortunately not something that I think we can do anything about in reveal.js, short of removing that fragment style. The browser shouldn't crash because of a transform being applied.

**Comment by DreaminginCodeZH** [comment]
Also confirmed this issue, on Arch Linux, Google Chrome 39.0.2171.95 (64-bit) and Intel graphics.

The previous release, 2.6.2, does not have this issue.

And slide transitions are gone in speaker view in the latest version, while still being usable in 2.6.2. The fragment transitions stays alive though.
