### ISSUE TITLE
Simplify usage of markdown

### ISSUE THREAD

**Issue by vitaut** [hakimel/reveal.js#1094]
Currently creating a Markdown slide requires much more work compared to an HTML slide. Compare
```
<section data-markdown>
    <script type="text/template">
    ...
    </script>
</section>
```
to
```
<section>
...
</section>
```
It would be nice if Reveal.js had an option to treat all slides as markdown and insert the necessary `<script>` element and `data-markdown` attribute automatically. Something like:

```
// Add the ``data-markdown`` attribute to ``<section>`` elements
// and wrap their contents in ``<script type="text/template">``.
var sections = document.getElementsByTagName('section');
for (var i = 0; i < sections.length; i++) {
  var section = sections[i];
  section.setAttribute('data-markdown', '');
  var script = document.createElement('script');
  script.type = 'text/template';
  script.innerHTML = section.innerHTML;
  while (section.firstChild) {
    section.removeChild(section.firstChild);
  }
  section.appendChild(script);
}
```

**Comment by hakimel** [comment]
Thanks for the suggestion but unfortunately that's not an option. The script wrapping it there to avoid having the browser parse the contents as HTML, which happens before JS has a chance to rewrite.

If you want to create a 100% Markdown presentation, external Markdown is a better option: https://github.com/hakimel/reveal.js#external-markdown
