### ISSUE TITLE
Incorrect rendering of code blocks

### ISSUE THREAD

**Issue by vitaut** [hakimel/reveal.js#1095]
Consider the following code:

    <section data-markdown>
    <script type="text/template">
    ``` c++
    void C::test() {
      int var;
    }
    ```
    </script>
    </section>

It is rendered as follows:

![screenshot from 2015-01-08 17 25 11](https://cloud.githubusercontent.com/assets/576385/5674197/6c527aca-975b-11e4-8e2f-79948fddb4b5.png)

with corresponding HTML:

```
<pre><code class="c++ coffeescript"><span class="reserved">void</span> <span class="attribute">C</span>::test() {
  int <span class="reserved">var</span>;
}</code></pre>
```

Note that syntax highlighting doesn't work and the `class` attribute contains `coffeescript` which is incorrect.

**Comment by vitaut** [comment]
The bug seems to affect all code blocks, not only markdown. Here's another example that reproduces the problem:

```
    <pre><code class="c++">
    void C::test() {
      int var;
    }
    </code></pre>
```

Again it gets `coffeescript` class and is rendered incorrectly.

**Comment by hakimel** [comment]
Hey – The class you'll need to use for C++ highlighting is "cpp", not "c++".

**Comment by vitaut** [comment]
Thanks for clarification, but what is the reason for that? According to the [documentation of Highlight.js](http://highlightjs.readthedocs.org/en/latest/css-classes-reference.html#c-cpp-c-h-c-h), “cpp”, “c”, “h”, “c++”, “h++" are all valid classed for the C++ code. Does Reveal.js use some old (or modified) version of Highlight.js and is it documented anywhere which version it uses?

**Comment by hakimel** [comment]
I'm surprised to see that's supported – figured plus signs in a class are invalid since it conflicts with CSS operators?

I tested your example and this actually works for me in stable Chrome / OS X:
```html
<pre><code class="c++">
void C::test() {
  int var;
}
</code></pre>
```

The parsed result is:
```html
<pre><code class="c++ hljs ">
<span class="hljs-keyword">void</span> C::test() {
  <span class="hljs-keyword">int</span> var;
}
</code></pre>
```

**Comment by hakimel** [comment]
Actually, it's probably because we're testing different versions. I'm using the dev version of reveal.js which has a more recent version of highlight.js. Try copying the highlight.js plugin from dev into your presentation: https://github.com/hakimel/reveal.js/blob/dev/plugin/highlight/highlight.js

**Comment by vitaut** [comment]
It works when I update `highlight.js` and `zenburn.css` from the dev branch. I also see that the script shows the version of Highlight.js which is quite useful. Thanks!

**Comment by lilijreey** [comment]
<pre >
<code style="opacity:0.8;" class="cpp">
#include <limits>
#include <iostream>
int main()
{
  cout << "largest float == " << std::numeric_limits<float>::max() << '\n';
  cout << "char is signed == " << std::numeric_limits<char>::is_signed << '\n';
}
</code>
</pre

render error

#include <limits>
#include <iostream>
int main()
{
  cout << "largest float == " << std::numeric_limits<float>::max() << '\n';
  cout << "char is signed == " << std::numeric_limits<char>::is_signed << '\n';
}
</char></float></iostream></limits> 

the last line will auto added

**Comment by pingswept** [comment]
It's obvious in hindsight, but note that "C++" is not valid, while "c++" is. Barely relevant, but maybe it will help someone like me in the future.

**Comment by vlazzarini** [comment]
I'm also finding a problem with markdown rendering of code (it happens in <code> blocks as well). 
Here is the code
```
<section data-markdown>
``` c++
#include <plugin.h>
struct MyPlug : csnd::Plugin<1,1> { };
```
</section>
```

the problem is that <plugin.h> disappears (it is not rendered). In <code> blocks it is, but bizarrely a </plugin.h> gets added at the end of the rendered code!
