### ISSUE TITLE
allow scrolling or auto shrinking font sizes when text area is longer

### ISSUE THREAD

**Issue by huashan** [hakimel/reveal.js#1096]
Is there anyway to scroll within a slide or shrink font sizes when the text within the slide is lengthy and go beyond the bottom of the screen?

**Comment by xuhdev** [comment]
This is useful IMO as powerpoint also does this.

**Comment by demoneaux** [comment]
I don't think this is suitable for Reveal core, perhaps someone could make a plugin for this.
