### ISSUE TITLE
VexFlow plugin

### ISSUE THREAD

**Issue by drewpotter** [hakimel/reveal.js#1098]
Hi,

I am using Reveal.js in an educational App which I am developing.

I am using the MathJax plugin which is great. I was wondering if it were possible to add support for VexFlow; A JavaScript library for rendering music notation.

I was hoping this would not be too difficult to create a Reveal.js plugin for.

The source repository is at: https://github.com/0xfe/vexflow

Any suggestions would be appreciated. Also here is the main website for VexFlow:
http://www.vexflow.com/

**Comment by hakimel** [comment]
Hey. I'm sure it's possible to make a plugin for this but unfortunately not something I can help with. I don't know how VexFlow works – but this is usually a matter of monitoring reveal.js for slide change events and calling the third party library to "do its thing" when the relevant slide is made visible.
