### ISSUE TITLE
Strange behavior of escaped HTML in <pre> tags

### ISSUE THREAD

**Issue by fhemberger** [hakimel/reveal.js#1100]
I just updated the slides of a security talk I held last year from reveal.js 2.6.1 to 3.0 and noticed a strange behavior when it comes to embedding HTML:

Create a slide with the following code:
```
<section>
    <!-- This triggers focus loss -->
    <pre class="fragment">&lt;body oninput=alert(1)&gt;&lt;input autofocus&gt;</pre>
    <!-- Those three XSS vectors are triggered, although the HTML is properly escaped -->
    <pre class="fragment">&lt;video poster=javascript:alert(1)//&gt;&lt;/video&gt;</pre>
    <pre class="fragment">&lt;!--&lt;img src="--&gt;&lt;img src=x onerror=alert(1)//"&gt;</pre>
    <pre class="fragment">&lt;img[a][b]src=x[d]onerror[c]=[e]"alert(1)"&gt;</pre>
</section>
```

This only happens when reveal.js kicks in, having those snippets on a website without is is harmless. If I replace `&lt;` with `&lt;&#x200b;` (zero width space), everything is fine. Might just be an interesting edge case.

**Comment by hakimel** [comment]
I pasted this into a fresh copy of 3.0 but neither of those are triggering in Chrome or Firefox on OS X. Can you test and see if you can reproduce this in a clean copy of reveal.js master? If you can, let me know and I'll reopen this.

**Comment by fhemberger** [comment]
Yes, still works on a freshly downloaded copy of master in Chrome 39 (OS X). I replaced the slides in the html file with this single slide.

**Comment by hakimel** [comment]
Weird. We're both using the same browser and OS but seeing different thing then. I uploaded this to http://lab.hakim.se/reveal-js-xss – does it fire alerts for you there as well?

**Comment by hakimel** [comment]
Ah, seeing it too now. Didn't realize it only triggered when actually stepping through the fragments.

**Comment by hakimel** [comment]
Fixed. We were accidentally calling out the `innerHTML` of fragments for screen readers, it has been changed to `textContent`.

**Comment by fhemberger** [comment]
Yay, thanks! :+1:
