### ISSUE TITLE
Load MathJax securely or insecurely depending on context

### ISSUE THREAD

**Issue by neuralyzer** [hakimel/reveal.js#1103]
MathJax can be loaded using this line
```
  options.mathjax = options.mathjax || '//cdn.mathjax.org/mathjax/latest/MathJax.js';
```
instead  [this one](https://github.com/hakimel/reveal.js/blob/master/plugin/math/math.js#L10).

(see also [MathJax: secure-access-to-the-cdn](http://docs.mathjax.org/en/latest/start.html#secure-access-to-the-cdn)) This loads the https version of the loading site if it is https and the http version if it is not. It might be nice to integrate this since the revealjs library can then be more conveniently used in other projects. For example, the dokuwiki revealjs plugin works better with the suggested patch applied.

**Comment by hakimel** [comment]
Thanks for the feedback. I've gone ahead and changed the default to use https. Didn't go relative since that wouldn't work in file://.
