### ISSUE TITLE
feature request: keyboard shortcut + API call to skip forward/back over fragments

### ISSUE THREAD

**Issue by jason-s** [hakimel/reveal.js#1105]
The left and right arrow keys move forward and back in the presentation through each fragment at a time. If there are a lot of fragments, it is clumsy to go to the previous or next slide.

Could you add a feature to move forward and back, skipping over fragments? (e.g. shift-left arrow and shift-right arrow)

**Comment by niccnacc** [comment]
I'd love to see that too.
https://github.com/shower/shower let's you present forwards in fragments and then locks the fragmets automatically upon showing the last one.
I guess a really clumpsy hack would be to use the "shown" callback of the last fragment and forbid the fragmentation somehow.
But imo this should be a general setting. I guess some people prefer permanent fragmentation and if the presentation is with question session it is really really bad to have it this way.

**Comment by kellyk** [comment]
I created a pull request for this issue (though I wasn't sure how to link them):
https://github.com/hakimel/reveal.js/pull/1173

**Comment by dsmf** [comment]
Would be awesome to have this feature. I just used RevealJS in order to prepare two presentations at work. Really love it except the navigation when there are fragments...

**Comment by Lomacar** [comment]
The pull request was made 7 years ago. Why wasn't it merged?

**Comment by BTTF2001** [comment]
> The pull request was made 7 years ago. Why wasn't it merged?

Sorry I'm new and didn't realise pls except my apologies

**Comment by Lomacar** [comment]
The API has methods for `.next()`, `.right()`, `.down()` etc. And it has `.nextFragment()`. These all do the exact same thing right now, which seems useless. I guess the direction ones just simulate the key press but `.next()` and `.previous()` should jump slides and ignore fragments!

**Comment by hakimel** [comment]
This has been added in 90bbe8be4f12ec56723a335d36f9be984ef7ed03

If you hold alt/option while pressing any navigation keyboard shortcut you'll skip all fragments. This works for the arrow keys as well as prev/next navigation via the space key.

To skip fragments in API navigations you'll need to include the "skipFragments" flag, for example: `Reveal.right({ skipFragments: true })`.

Also, if you hold shift while pressing an arrow key you'll jump to the last slide in the given direction.
