### ISSUE TITLE
plugin zoom.js not working: scrolling / scaling not working

### ISSUE THREAD

**Issue by wimalopaan** [hakimel/reveal.js#1109]
Long slides that are longer / larger than the screen size should be scrollable / scalable via the zoom-js/zoom.js plugin.

But this feature isn't working.

Any hints?

**Comment by hakimel** [comment]
Panning when zoomed in with the zoom.js plugin is disabled since it doesn't work together with other reveal.js styling. No plans for trying to make it compatible.

**Comment by wimalopaan** [comment]
Ok, but how can one show a slide larger than the screen. 
Or what is the purpose of the zoom plugin? And shortcuts?

**Comment by hakimel** [comment]
That's not something that reveal.js supports. Content needs to fit within the slide area.

The zoom plugin is for zooming in on a portion of a slide. For example, if you have a code sample on a slide you can alt+click it to bring it up as large as possible.
