### ISSUE TITLE
Forum / discussion board?

### ISSUE THREAD

**Issue by dandv** [hakimel/reveal.js#111]
Reveal.js is awesome, and I'd like to ask some questions that more experienced users could hopefully answer. Is there a forum or some other place to do this?

**Comment by markhutch** [comment]
I'm loving reveal.js - have used it for several conference presentations now.

However, I'd really like to be able to have links to other slides (I know this is already available!) but ... I'd like to have a "return" link to get back to wherever I was previously.

Some slides would be linked to from several different locations so a hard-coded link to "#previous_slide" wouldn't be possible.

Each section that might be linked-TO would have an id attribute and obviously every slide that had to be returned to would also have an id attribute.

Is there a way of doing this in HTML+JavaScript without cookies or jQuery/Angular etc?
