### ISSUE TITLE
Code background and color should be defined by Highlight theme

### ISSUE THREAD

**Issue by borisschapira** [hakimel/reveal.js#1114]
https://github.com/hakimel/reveal.js/blob/master/css/theme/template/theme.scss#L181

these lines are incompatible with several hljs themes like mono-blue ou github...

Is there a reason for these lines ? Could we remove them ?

**Comment by aslakhellesoy** [comment]
I'm bitten by this as well - the highlight theme's background and foreground colours are overridden by theme.scss.

**Comment by borisschapira** [comment]
@hakimel, any explanation ? I would gladly make a Pull Request but I imagine you've made it that way for a reason.

**Comment by shmerl** [comment]
Looks like it's the same bug as I stumbled upon in #1290.

**Comment by demoneaux** [comment]
Closing this as a duplicate of #1290 which has been fixed.
