### ISSUE TITLE
Insert diagrams or graphs generated by JS libs

### ISSUE THREAD

**Issue by kartoch** [hakimel/reveal.js#1117]
I want to insert diagrams generated by JointJS (http://www.jointjs.com/), graphs generated by sigmajs (http://sigmajs.org/). How can i include them in reveals.js while keeping size ratio when printing or displaying my presentation full screen ?

More generally, what is the best way to insert drawing libraries in reveal.js ?

**Comment by kartoch** [comment]
Seems related to issue #1082

**Comment by drvinceknight** [comment]
I am using mpld3 which creates d3, currently I'm adding those in using an iframe but this doesn't necessarily scale nicely. Would love for there to be a fix for this...

**Comment by demoneaux** [comment]
Inserting a diagram should work pretty fine with Reveal. After inserting, try running `Reveal.layout()` to allow Reveal to reconfigure the display to account for the new content.
