### ISSUE TITLE
head.min.js

### ISSUE THREAD

**Issue by anantshri** [hakimel/reveal.js#1118]
Hi Folks, as #783 we were suppose to remove / ignore all min.js file however head.min.js still exist.
however corresponding head.js doesn't exist.

There appears to be some confusion either in my understanding or the fix is not complete.

**Comment by frankcash** [comment]
http://cdnjs.cloudflare.com/ajax/libs/headjs/1.0.3/head.js

**Comment by hakimel** [comment]
That PR was for removing the minified files that reveal.js generates since those were getting recompiled and committed at every change. That library file is simply static so it can stay.
