### ISSUE TITLE
Feature Request : Large Speker notes section and small slide preview

### ISSUE THREAD

**Issue by anantshri** [hakimel/reveal.js#1121]
Can we keep the current slide and next slide on side section and use the main section for speaker notes. this will allows people to keep large content in speakers notes and avoid scrolling in that.

Or if no plans of doing that in code can someone point what customizations could be used to achieve it.
Appologies in advance if its already there, google search didn't revealed much about such feature.

**Comment by hakimel** [comment]
Nope, this isn't something that's supported. You'll need to change the CSS in this file: https://github.com/hakimel/reveal.js/blob/master/plugin/notes/notes.html
