### ISSUE TITLE
Adding a copyright and logo to all slides

### ISSUE THREAD

**Issue by KajKandler** [hakimel/reveal.js#1122]
I'm looking for ways to add a copyright and some logo to all slides. How would I go about that? Add it to the index.html or to the theme CSS?

**Comment by rparree** [comment]
I have just pushed a an example (as a reply to  another question). But it
does include a "footer" option. Perhaps it is helpful to you as well (added
a footer outside the `div.reveal` and use some css)

https://github.com/edc4it/revealjs-assemble

Raphaël Parrée
EDC4IT Europe BV
(m) +33 673 75 34 62
@rparree <https://twitter.com/intent/user?screen_name=rparree> | LinkedIn
<http://fr.linkedin.com/in/rparree>


On Tue, Feb 3, 2015 at 3:59 AM, Kaj Kandler <notifications@github.com>
wrote:

> I'm looking for ways to add a copyright and some logo to all slides. How
> would I go about that? Add it to the index.html or to the theme CSS?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hakimel/reveal.js/issues/1122>.
>

-- 
EDC4IT Europe BV is a company registered in the Netherlands. Registered 
number: 58704663. Registered office: Leeghwaterstraat 25, 2811 DT Reeuwijk. 
| This communication is for use by the intended recipient and contains 
information that may be privileged, confidential or copyrighted under 
applicable law. If you are not the intended recipient, you are hereby 
formally notified that any use, copying or distribution of this e-mail, in 
whole or in part, is strictly prohibited. Please notify the sender by 
return e-mail and delete this e-mail from your system. Unless explicitly 
and conspicuously designated as " E-Contract Intended", this e-mail does 
not constitute a contract offer, a contract amendment, or an acceptance of 
a contract offer. This e-mail does not constitute a consent to the use of 
sender's contact information for direct marketing purposes or for transfers 
of data to third parties. | info@edc4it.com.

**Comment by graffen** [comment]
I just add mine to the theme CSS: 

  body:after {
  content: url(../../images/logo.png);
  position: fixed;
  bottom: 3.5em;
  left: 3.5em;
  box-shadow: 5px 5px 10px #000; }

**Comment by fghaas** [comment]
I don't modify the original theme CSS, but habitually include this in my presentations:

```html
<!-- reveal.js CSS theme and local overrides -->
<link rel="stylesheet" href="reveal.js/css/reveal.css"/>
<link rel="stylesheet" href="reveal.js/css/theme/black.css" id="theme"/>
<link rel="stylesheet" href="css/reveal-override.css"/>
```

And then you could include what @graffen and @rparree have suggested, in your `reveal-override.css`.

@hakimel, can you close this? It's neither a bug nor a feature request.

**Comment by handsomeyang** [comment]
Check out my example https://github.com/handsomeyang/reveal.js

**Comment by hpurmann** [comment]
My solution:
```css
body {
    background-image: url(../img/image.svg);
    background-size: 20%;
    background-repeat: no-repeat;
    background-position: 3% 96%;
}
```

**Comment by psbell-meta** [comment]
Mentioned workarounds above don't seem to be working, has the code changed too much?  Or can someone give a more detailed explanation for how to implement?

**Comment by JamesIves** [comment]
I was looking for something similar to this, except I wanted it to be interactive. i solved this by adding an additional element to my `index.html` file immediately following the opening body tag.

```html
<div class="watermark">
   <a href="url_here" rel="noopener noreferrer">
     <img
       src="logo_src_here.png"
     />
   </a>
</div>
```

I then used absolute positioning to align it at the bottom left of the screen. Using % values may be a better option, but what I have here worked well for my use case.

```css
.watermark {
  position: absolute;
  left: 16px;
  bottom: 16px;
  z-index: 10;
}

.watermark img {
  width: 24px;
  height: 24px;
}
```

**Comment by r0ckarong** [comment]
Just to comment on this for those that come looking for the solution in 2024 and after. You need to modify this in your CSS file. The default puts the logo at  the top right corner.

```
.reveal-viewport {
  background-image: url(../_images/hilscher-solarized_light.png);
  background-size: 12%;
  background-repeat: no-repeat;
  background-position: 97% 3%;
}
```
