### ISSUE TITLE
Limit download of files

### ISSUE THREAD

**Issue by oxhey** [hakimel/reveal.js#1123]
I have a presentation with 10 slides. Each slide has an audio file with narration. The problem im finding is that when the presentation is loaded , everything is downloaded at once , causing spikes on my server. 

Is there a way to say , only download whats needed for this slide when your on it.

**Comment by hakimel** [comment]
Yeah there is, check out the "lazy loading" section of the readme: https://github.com/hakimel/reveal.js#lazy-loading

**Comment by oxhey** [comment]
Thanks , found that it was in the dev branch . Only problem i can see is that if there is a image in the paticular slide , it dosent align it propperly. It will load it with a big gap at the top , then if you go to the next slide and go back to the slide with the image , it jumps to the correct position.

**Comment by hakimel** [comment]
Good point, that's a bug and I've opened a new issue for it #1127

For now you should be able to work around it by specifying a height for your image.

**Comment by oxhey** [comment]
A way around the issue is to set lazy loading view distance to 2 or higher
