### ISSUE TITLE
Please update readme about step to include new theme in Grunt build file

### ISSUE THREAD

**Issue by gintsgints** [hakimel/reveal.js#1134]
Theme README says copy theme file and do 

````
grunt css-themes
````

But this will not work until you not add sass file to Gruntfile.js. Please mention this in theme readme.
Also option could be make grunt file compile all scss files in theme/source.

**Comment by hakimel** [comment]
This was recently fixed in the dev branch, all theme files in that folder are now automatically compiled 3b45b618b8f2f3c757a4c4645a381791ece71da8
