### ISSUE TITLE
Progress bar inside '.slides' container

### ISSUE THREAD

**Issue by adrianpuescu** [hakimel/reveal.js#1136]
Even if it's just a secondary UI component, sometimes it might be useful to be able to position the progress bar inside the '.slides' container (at the bottom).
A simple example: when you have a max-width set for the slides and also set up a border for each slide. As it is now, the progress bar would be a little contrasting with the general layout of the presentation.

![revealjs-progressbar-issue](https://cloud.githubusercontent.com/assets/3225561/6226513/bb2ae6ac-b69e-11e4-9606-a274bdec8244.png)

Also, another possible reason could be the fact that it would be easier to click on it if positioned at the bottom of the '.slides' container than at the bottom of the page.

Anyway, congratulations! You really did an amazing job with reveal.js.

**Comment by hakimel** [comment]
Thanks for the suggestion but I want to limit the slide container to only containing slide elements. There's other elements, such as the autoplay controls, that are also positioned relative to the `.reveal` container. I wouldn't want all of that to move one level further in.
