### ISSUE TITLE
fragmentshown and fragmenthidden firing multiple times

### ISSUE THREAD

**Issue by iandevlin** [hakimel/reveal.js#1139]
I don't know if this is by design or not, but I have 8 fragments on a page, and everytime one of them is hidden or shown, the appropriate event gets fired for all of them, although `e.fragment` does contain the correct fragment.

Calling `e.stopImmediatePropagation();` stops this from happening, but surely it should only fire the event once?

**Comment by hakimel** [comment]
That's not how it's intended – they should only fire once per fragment step. I just tested on the [demo presentation](http://lab.hakim.se/reveal-js/#/) by listening to fragmentshown/fragmenthidden via the browser JS console and they're only firing once there. Is it possible that you're attaching your event listeners multiple times?

**Comment by iandevlin** [comment]
Ah man, I am such a fool, I hadn't even noticed that it was sitting in an .each(). Sorry and thanks.
