### ISSUE TITLE
print-pdf hash support

### ISSUE THREAD

**Issue by willsf1862** [hakimel/reveal.js#1140]
Minor item that is mostly ergonomic...

function isPrintingPDF() {
        return ( /print-pdf/gi ).test( window.location.search );
}
?print-pdf#/proposal

Could we allow the print-pdf marker to be in the hash as well? Perhaps...

function isPrintingPDF() {
        var expr = (/print-pdf/gi)
        return expr.test(window.location.search) || expr.test(window.location.hash);
}
#/proposal?print-pdf

**Comment by hakimel** [comment]
Thanks for the suggestion but I don't think we need to support that. It's feels more straight forward to always expect the print-pdf param to be part of the query string, rather than looking for it in different parts of the URL.

**Comment by willsf1862** [comment]
Not a problem. Just to clarify though - for single page apps (e.g. using angular) the param ends up in the search query instead of the hash query which is less natural for adding the param (i.e. via $.param() instead of splicing the url) and it's also little visually inconsistent. Technically, there are two query strings in a url, although the hash one is never sent server side. Anyway and either way, this is an AWESOME PROJECT and I'm sure you have larger items to attend to than this one. Thank you!

Existing:
https://www.example.com:9443/?print-pdf=1/#/proposal/1234567890?company=60040

Additional:
https://www.example.com:9443/#/proposal/1234567890?company=60040&print-pdf=1
