### ISSUE TITLE
math plugin loads MathJax over HTTP only

### ISSUE THREAD

**Issue by Rufflewind** [hakimel/reveal.js#1146]
It seems that the [math plugin](https://github.com/hakimel/reveal.js/blob/master/plugin/math/math.js) loads MathJax over HTTP only, which means the presentation would break when loaded over HTTPS.

Ideally, it should load over HTTPS or HTTP depending on whether the webpage itself was loaded over HTTPS or not, or stick to HTTPS entirely (simplest approach).

(Note that using `//cdn.mathjax.org` would not work when loaded over `file://`.)

**Comment by Delapouite** [comment]
This could be done by appending the value of `window.location.protocol`

**Comment by Rufflewind** [comment]
> This could be done by appending the value of `window.location.protocol`

That would still break with `file://`.  Best approach would probably be something like:

```js
(window.location.protocol === 'http:' ? '' : 'https:') +
'//cdn.mathjax.org/mathjax/latest/MathJax.js'
```

**Comment by hakimel** [comment]
This was fixed a few weeks ago by always loading via HTTPS #1103

Only available in the dev branch so far.
