### ISSUE TITLE
Powerpoint to reveal

### ISSUE THREAD

**Issue by oxhey** [hakimel/reveal.js#1148]
Is there a script that can convert ppt files to reveal presentations besides having to use slides.com?

**Comment by hakimel** [comment]
Nope, not that I am aware.

**Comment by ge0ffrey** [comment]
Or [the other way around: from reveal.js to powerpoint](http://stackoverflow.com/questions/32179373/export-a-reveal-js-presentation-to-libreoffice-odp-or-powerpoint-ppt-pptx)?
