### ISSUE TITLE
"roll-in" fragment style crashes speaker view in Chrome

### ISSUE THREAD

**Issue by Crell** [hakimel/reveal.js#1150]
I've had this happen with 2 different decks multiple times now.

Using my local apache webserver on Linux (rather than grunt) as usual, I have a presentation that has a lot of speaker notes.  I load it up in a browser, hit S for speaker notes, and start presenting.  After not too many slides, something hiccups and both the speaker notes and main slides show the Chrome "dead computer" icon and say the tab crashed.  If I hit reload it works again for a couple of slides, then fails the same way.

I'm not sure what the issue is but it renders the 3.0.0 release unusable.  For reference, here's a deck that is experiencing this problem (see the ssp15 tag for a fixed point):

https://github.com/Crell/slides-d8-for-devs

**Comment by jpeterson** [comment]
:+1: 

Same issue for me... lots of notes, crashes after a few slides. This is happening for me on all 3 of the following: grunt serve, local apache, gh-pages

**Comment by hakimel** [comment]
Thanks for reporting. I cloned your presentation and turns out it's crashing because of the `roll-in` fragment style. As soon as that is removed, it no longer crashes.

Will let you know once it's been fixed.

**Comment by hakimel** [comment]
This is a strange one. Reducing the `rotateX` of the `roll-in` style from 90deg to 60deg stops Chrome from crashing when opening the speaker view. That's completely arbitrary so it'd be great if someone else can confirm by testing another presentation with the latest reveal.css from dev.

**Comment by joaopsilva** [comment]
It still crashes Chrome for me using version 41.0.2272.101, using the latest reveal.css with `rotateX(60deg).`

**Comment by hakimel** [comment]
Got it -- thanks for testing.

I don't have any other ideas so I may remove the roll-in style altogether to avoid the crash.

**Comment by reagle** [comment]
Even if that's a short term action for reveal, shouldn't a bug report be filed with Chromium?

**Comment by hakimel** [comment]
The `roll-in` fragment style has been removed. If anyone finds a way to reintroduce it without crashing Chrome we'll add it back in, if not I think this is an OK sacrifice to avoid crashes.

@reagle I wouldn't really know how to describe this – would need to be boiled down to a reduced test case for it to be debuggable by Chromium developers.

**Comment by reagle** [comment]
The roll-in was really nice for images, hopefully it'll reappear some day.
