### ISSUE TITLE
[Bug] Zooming with [alt]+clicking on navigation elements leads to unexpected behaviour

### ISSUE THREAD

**Issue by KurtPfeifle** [hakimel/reveal.js#1151]
Go to this link (I used Chrome 40.0.2214.115 (64-bit) on an OSX Mavericks system to test it):

* **[http://lab.hakim.se/reveal-js/#/4](http://lab.hakim.se/reveal-js/#/4)**

You'll read:

> *Hold down alt and click on any element to zoom in on it using [zoom.js](http://lab.hakim.se/zoom-js).*     
> *Alt + click anywhere to zoom back out.*

Either the wording of this should change, or the behavior of this feature deserves a bug investigation   ;-)

1. Either modify the first sentence of the above:    
    _"Hold down alt and click on any element (**with the exception of the navigation arrows in the lower left corner of the slide!**) to zoom in on it using [zoom.js](http://lab.hakim.se/zoom-js)."_
1. Or fix the bug which is exposed when alt-clicking near the navigation elements.

**Comment by sunnylinmy** [comment]
I agree with you..

**Comment by hakimel** [comment]
Fixed by 60457d21b437b66f6bab41ed0ae99391b3946376

**Comment by sunnylinmy** [comment]
Excuse me, is there any way to zoom the whole page with the region surrounded by mouse click instead of only contents like h1 h2 p img....Thank you!
