### ISSUE TITLE
Need way to iterate through all slides

### ISSUE THREAD

**Issue by awood** [hakimel/reveal.js#1154]
I was inspired by https://github.com/klamping/deck.narrator.js to add narration to my presentation where each slide would seek to a start point and play for a specific duration.  When the presentation is loaded, my callback walks through all the slides keeping a running total of the duration times and setting the start point for each slide accordingly.  But since the slides exist on an x and y axis and the y axis slides are children of the x axis slides, it's not trivial to walk the entire presentation.

What I think Reveal is missing though is an easy way to just iterate through every slide.  I am not a Javascript expert so maybe I am missing someting?  But a function like Reveal.slides() that returns an array of the elements for each slide or an iterator that can be called would be really nice.  I think this functionality already exists in the navigate functions, it just needs to be available without actually causing the presentation to move forward.

Here is my code as an example

``` javascript
// Inspired by https://github.com/klamping/deck.narrator.js
// Each slide with narration must have a data-narration-time
// set on it with the narration time in seconds

function toArray(o) {
  return Array.prototype.slice.call(o);
}

// Function to stop the player at a certain time
function checkTime() {
  if (player.currentTime >= segmentEnd) {
    player.pause();
  }
}

// The end time of a slide in seconds
var segmentEnd;

var player = document.getElementById("player");
player.addEventListener('timeupdate', checkTime, false);

Reveal.addEventListener("ready", function(event) {
  var position = 0;

  /* Reveal doesn't have any way that I can find to just iterate through all
   * the slides.  The slides are on an X and Y axis and in the DOM the slides
   * on the Y axis are elements of the ones of the X axis, so it is not trivial
   * to find each one.  Luckily, I am using markdown and each slide has a data-markdown
   * attribute that I can rely on.  I don't know how you would do it otherwise */
  var slides = toArray(document.querySelectorAll("section[data-markdown]"));

  for (var i = 0; i < slides.length; i++) {
    var slide = slides[i];
    var duration;

    duration = parseInt(slide.dataset.narrationTime) || 0;
    slide.dataset.narrationTime = duration;

    slide.dataset.seekTime = position;
    position += duration;
  }

  var seekTime = parseInt(event.currentSlide.dataset.seekTime);
  try {
    player.currentTime = seekTime;
    console(player.currentTime);
  } catch(e) {
    // The audio is not ready yet
    player.addEventListener('canplay', function(ev) {
      player.currentTime = seekTime;
      this.removeEventListener('canplay', arguments.callee, false);
    });
  }

  segmentEnd = parseInt(event.currentSlide.dataset.narrationTime) || seekTime;

  var onChange = function(changeEvent) {
    var slide = changeEvent.currentSlide;
    var duration = parseInt(slide.dataset.narrationTime);
    var seekTime = parseInt(slide.dataset.seekTime);

    if (player) {
      player.currentTime = seekTime;
      segmentEnd = duration + seekTime;
      if (duration > 0) {
        player.play();
      }
    }
  };

  Reveal.addEventListener("slidechanged", onChange);
  onChange(event);
})
```

**Comment by rajgoel** [comment]
You might want to checkout the `audio-slideshow` plugin (Pull-request #944) with which you can add audio files for each slide and fragment (instead of having one large audio file for the entire presentation). The `slideshow-recorder` plugin that you will also find there, allows you to easily create these audio files. A demo can be found [here](http://courses.telematique.eu/audio-slideshow).

**Comment by demoneaux** [comment]
There is an API for `Reveal.getSlides()`. Alternatively you can use `document.querySelectorAll('.slides > section')` for horizontal slides or `document.querySelectorAll('.slides > section > section')` for vertical slides.
