### ISSUE TITLE
Markdown issues when render a HTML containing a script tag

### ISSUE THREAD

**Issue by akiran** [hakimel/reveal.js#1157]
Reopening https://github.com/hakimel/reveal.js/issues/797
This issue was closed without resolving the bug.

Today, I faced the same issue.

**Comment by fabienvauchelles** [comment]
+1

**Comment by fabienvauchelles** [comment]
doesn't work when contain a full html page (with 'html' tag)

**Comment by bfritscher** [comment]
I had the same problem and after trying some solution ended up hacking in some substitution to make it work.

see pull request https://github.com/hakimel/reveal.js/pull/1200

Iif anyone has a better idea?

**Comment by hakimel** [comment]
The fix from @bfritscher has been merged.
