### ISSUE TITLE
Question : Will the new attributes of slides.com integrated with Reveaj.js

### ISSUE THREAD

**Issue by cmoulliard** [hakimel/reveal.js#1159]
Hi @hakimel,

I have discovered with a lot of interested the web site and project ("slides.com" / Revelajs editor) and also new data-xxx attributes like (data-placeholder-tag, data-placeholder-text, data-bloc-id, data-bloc-type, data-has-custom-html, data-natural-xxxx)

Question : Will these attributes be integrated with the OpenSource Revealjs project ?

Remark : The attributes `data-background-image`, `data-background-position` and `data-background-color` part of revealjs (2.6 & 3.0) are not documented within the README.md page

Great job.

Charles

**Comment by hakimel** [comment]
Those attributes won't be added to reveal.js. They are specific to the Slides editor and wouldn't be useful to non-Slides users. (Side note: we just added a new ZIP export option to Slides which might make your transition to reveal.js easier)

Good catch regarding the background attributes, will add those to the readme.
