### ISSUE TITLE
API for reveal.js-plugins

### ISSUE THREAD

**Issue by maxmeyer** [hakimel/reveal.js#1161]
Hello,

as discussed in #1124 this is an issue to discuss an api for external reveal.js-plugins. Please also see the [plugin guidlines](https://github.com/hakimel/reveal.js/wiki/Plugin-Guidelines) for more information about that topic.

Reason to support plugins:

Unfortunately not every piece of code is suitable to pull it into `reveal.js`-core. In most cases it is suitable only for a few use cases, so most reveal.js users will not use it.

Things to think about:
- There needs to be an easy way to activate plugins 
  
  Maybe the `dependencies`-`array in the`Reveal.initialize({` is suitable for this
- Download external dependencies
  
  Maybe one could use bower + a `grunt`-task for that.
- Hooks
  
  Maybe there's some need for hooks plugins can use.

Feel free to add more things as comment to this issue.

**Comment by maxmeyer** [comment]
@hakimel 
Done :smile:

**Comment by demoneaux** [comment]
Currently, many plugins define themselves following the style `RevealPluginName`, following the original core plugins. Personally, that seems fine to me, although defining everything on the Reveal namespace would also be much more structured (eg. `Reveal.abc`). For passing in arguments or configuration though, I feel that plugins should standardise on using the Reveal configuration (through `Reveal.getConfig().pluginName`). Any opinions? /cc @hakimel

**Comment by Martinomagnifico** [comment]
Configuration of plugins is indeed done inside the Reveal config object. This was added in May 2020. Closing the issue.
