### ISSUE TITLE
Enable SmartyPants option of Marked when rendering Markdown

### ISSUE THREAD

**Issue by callahad** [hakimel/reveal.js#1163]
`marked.setOptions({smartypants: true});` should automatically change straight quotes like "" into nice quotes like &ldquo;&rdquo;.

I'd suggest this default to on, since Marked is smart and avoids applying these transformations to code blocks, but I'd be happy with it being more easily configurable, too.

Unfortunately, the version of Marked that's bundled with Reveal has a bug, but updating to the latest Marked release and setting the above option appears to work seamlessly.

**Comment by hakimel** [comment]
I'm open to adding an option to the markdown plugin for this. Do you want to give it a shot? It would probably make sense to group markdown plugin options inside one object like:

```javascript
Reveal.initialize({
  markdown: {
    smartypants: true
  }
})
```

Which the markdown plugin then consumes via `Reveal.getConfig().markdown.smartypants`.

**Comment by legends2k** [comment]
It would be good to have @hakimel suggestion, but till then putting this in `Reveal.initialize` under `index.html` works:

    { src: 'plugin/markdown/marked.js', async: false, callback: function() { marked.setOptions({smartypants: true}); } },

**Comment by hakimel** [comment]
The proposed config option in the comments above was added by @demoneaux in #1765
