### ISSUE TITLE
Support filtering to a subset of slides (e.g. vertical/one-dimensional only)

### ISSUE THREAD

**Issue by devurandom** [hakimel/reveal.js#1168]
It would be great if reveal.js would support filtering of the deck to a subset of slides. E.g. only show the vertical or one-dimensional slides.

While this makes no sense in the regular screen mode, it becomes very useful when generating PDFs: Currently I have to manually specify the slides I need in the printer settings. For this I even need to print twice, as Firefox has no print-preview. I could avoid this (which becomes cumbersome, if there are a lot of horizontal slides in a large deck), if reveal.js would support subset-filtering automatically.

**Comment by hakimel** [comment]
This isn't something I think should be built into the framework. Would make more sense to have a custom script outside of reveal.js hide slides according to your rules and context.
