### ISSUE TITLE
Fragment roll in and presentation mode

### ISSUE THREAD

**Issue by maxime1992** [hakimel/reveal.js#1169]
In a section if you want to display blocks after blocks you use fragment and roll-in classes. 

It works well in normal mode but as soon as i start the presentation mode (by clicking on 's') if there's a part to display with fragment and roll-in the page just crashes and chrome display an error.

I'm using chrome version 41.0.2272.76 and Ubuntu 14.10 (64-bit).

**Comment by hakimel** [comment]
Thanks for reporting, tracking this issue in #1150
