### ISSUE TITLE
Fragment autoslide not working for section containing <audio> element

### ISSUE THREAD

**Issue by bailz** [hakimel/reveal.js#1170]
It appears there is an issue with fragments containing data-autoslide and audio elements.

This example works

```
<section data-autoslide="2000"> 
<ul>
    <li class="fragment" data-autoslide="2000">1</li>
    <li class="fragment" data-autoslide="2000">2</li>
    <li class="fragment" data-autoslide="2000">3</li>
</ul>
</section>

```

This example does not work

```
<section data-autoslide="2000"> 
<audio data-autoplay src="testfile.mp3"></audio>
<ul>
    <li class="fragment" data-autoslide="2000">1</li>
    <li class="fragment" data-autoslide="2000">2</li>
    <li class="fragment" data-autoslide="2000">3</li>
</ul>
</section>
```

Any help would be greatful
Thank you

**Comment by hakimel** [comment]
This has been fixed. If reveal.js finds "data-autoplay"-enabled media on a slide it automatically sets the auto-slide duration to match the length of the media. This logic has now been disabled when there are fragments in the slide.
