### ISSUE TITLE
Link preview iframe scrolling with mouse wheel not working.

### ISSUE THREAD

**Issue by danfraticiu** [hakimel/reveal.js#1172]
## Overview:

mouse wheel and/or trackpad scrolling in a link preview not working.

System: OSX 10.10.2
Browser: Chrome 41.0.2272.89 and Safari 8.0.3
## Reproduce:
1. open http://nfr.ro/revealjs_previewlink_issue
2. click the link 
3. try to scroll using the mouse wheel, a magic mouse or a trackpad

Additional info:
- this behaviour is not present in Firefox and on IE10 running in a virtual machine.
- the problem dissapears after the window is resized (reappears after refresh)

**Comment by demoneaux** [comment]
Can't seem to repro on latest Chrome/Safari. Closing for now. Feel free to re-open if you have more info.
