### ISSUE TITLE
inline markdown for entire presentation

### ISSUE THREAD

**Issue by anantshri** [hakimel/reveal.js#1174]
at times it makes sense not to have a seperate external markdown file rather all the markdown could just be copy pasted inside the html file with proper section attribute.

However at this point we do not support it. I suppose inline markdown is for per slide basis.
any plans on changing that behaviour.

-Anant

**Comment by lifuzu** [comment]
+1

**Comment by anantshri** [comment]
I take this back. I just now tried this again. the error was in my code.
we do support full markdown in a single section.
@hakimel please correct me if i am wrong here.

Here is what i am using and its working just fine.
```
    	<div class='reveal'>
    		<div class='slides'>
        <section data-markdown data-separator="^\n---\n$" data-separator-vertical="^\n--\n$">
          <script type="text/template">
          <!-- Markdown Here --> 
          </script>
        </section>
    </div>
  </div>
```
