### ISSUE TITLE
Get reveal to update

### ISSUE THREAD

**Issue by oxhey** [hakimel/reveal.js#1177]
Im building an editor for reveal (i no there some already). I have made it so that I can add slides.

Whats happening is that reveal isn't updating the controls in the bottom right to show that there are more slides until you click left to reveal the new slide, making it confusing to use the editor.

Is there a way to make it so that reveal updates every time a new slide is added.

My code for adding a slide is : 

```
function slide2()
  {
     var sec = document.createElement("section");
     sec.innerHTML = '<h3>Title</h3><p>content</p>';
     document.getElementById('slides').appendChild(sec);
     slideAdded();
  }
```

**Comment by hakimel** [comment]
You'll need to call `Reveal.sync()` after adding or removing a slide.

**Comment by oxhey** [comment]
Thanks . That kind of works. The controls update , but the slides load ontop of each other

**Comment by hakimel** [comment]
Hm, give this a try instead of sync `Reveal.slide( Reveal.getIndices().h, Reveal.getIndices().v )`

**Comment by oxhey** [comment]
heres the link to the editor - http://oxhey.wc.lt/Editor/#/

**Comment by oxhey** [comment]
Awesome!! . That fixed it . Cant wait to finalize the design of the editor .

**Comment by oxhey** [comment]
Would i use getPreviousSlide or previousFragment() to navigate 1 slide to the left if a slide has been deleted . (This assumes there will always be at least one slide )
