### ISSUE TITLE
Navigating after delete

### ISSUE THREAD

**Issue by oxhey** [hakimel/reveal.js#1178]
sorry to make another post .

Would i use getPreviousSlide or previousFragment() to navigate 1 slide to the left if a slide has been deleted . (This assumes there will always be at least one slide )

**Comment by hakimel** [comment]
Hey – this issue tracker isn't intended for personal support requests/how-to's so please only open new issues for bugs and feature requests. 

You'll need to use the API (https://github.com/hakimel/reveal.js#api) to achieve this but which methods you use depends on the context, like which slide you're on when a slide is deleted.

**Comment by oxhey** [comment]
sorry
