### ISSUE TITLE
Setting section "id" other than digits disables slide change on hashChange

### ISSUE THREAD

**Issue by harpreetkhalsagtbit** [hakimel/reveal.js#1183]
I have tried different **id's** to `section` - _ang-1_ or _ang1_ or _ang_1_ but on changing hash value of the URL slide does not change.

**Comment by aspiers** [comment]
If I understand this bug report, I found something similar but it turned out that I had `id` set to the same value both for a `<section>` in my `index.html` *and* a sub-`<section>` in my separate markdown file.  When I fixed the duplicate ids, the problem vanished.

**Comment by demoneaux** [comment]
Yep, duplicate IDs will probably cause some issues with slide navigation. Closing for now.
