### ISSUE TITLE
customizing speaker notes

### ISSUE THREAD

**Issue by FND** [hakimel/reveal.js#1189]
as far as I can tell, there is no way to inject custom CSS into the speaker notes window, short of forking the plugin

it would be useful to have a configuration parameter for additional CSS URIs

**Comment by hakimel** [comment]
If you want to change he way the notes look or work I think forking is the right approach.

**Comment by DanielRuf** [comment]
Why not provide an option for setting `notesFilePath` of `openNotes`?
Currently this is unused.

**Comment by DanielRuf** [comment]
In general, it should work:

```
					currentSlide = document.createElement( 'iframe' );
					currentSlide.setAttribute( 'width', 1280 );
					currentSlide.setAttribute( 'height', 1024 );
					currentSlide.setAttribute( 'src', currentURL );
					document.querySelector( '#current-slide' ).appendChild( currentSlide );
					currentSlide.onload = function () {
						var body = currentSlide.contentWindow.document.querySelector('body');
						body.style.fontSize = '12px';
						body.style.zoom = '0.25';
					};
```

**Comment by DanielRuf** [comment]
Can we reopen this and provide some PR(s)?
