### ISSUE TITLE
data-background-iframe doesn't work

### ISSUE THREAD

**Issue by reagle** [hakimel/reveal.js#1190]
I see in the documentation there's an option for [data-background-iframe](https://github.com/hakimel/reveal.js#slide-backgrounds). However, there's no example in the [demo](http://lab.hakim.se/reveal-js/) and when [I use it in my slides](http://reagle.org/joseph/talks/2014/exemplar.html#/iframe-background), it doesn't work there either. Chrome 41.0.2272.118-1.

**Comment by reagle** [comment]
Does work in Firefox 37.0.1+build1-0ubuntu0.14.04.1

**Comment by hakimel** [comment]
That iframe embed isn't working because the target page explicitly disallows embedding through an X-Frame-Options header. If you open the developer tools when viewing your presentation you'll see the following error:

```
Refused to display 'https://slides.com/' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.
```

**Comment by reagle** [comment]
Thanks @hakimel, please don't use 'https://slides.com/' as your [example](https://github.com/hakimel/reveal.js#slide-backgrounds) then.

**Comment by hakimel** [comment]
Didn't realize I was, will update that. I used it as an example before our
upgrade to rails 4 (which defaults to disabling embeds).

**Comment by yberol** [comment]
@hakimel is there a simple solution to this problem. I am using `iframe` to call a non-https page inside my reveal presentation and get a blank page with

> was loaded over HTTPS, but requested an insecure resource ... This request has been blocked; the content must be served over HTTPS.

in developer tools. There is a proposed solution [here](http://stackoverflow.com/questions/7699615/cross-domain-xmlhttprequest-using-background-pages/7699773#7699773) but I was wondering whether there was simple solution in reveal for this.

**Comment by hakimel** [comment]
@yberol Sorry but there's no workaround for that as far as I know.

**Comment by reagle** [comment]
If @hakimel isn't using <https://slides.com/> anymore I think we can close this issue even though it's probably worth noting in the documentation. However, even though I opened it I don't see the close button.

**Comment by hakimel** [comment]
@reagle This actually closed already, which why you're not seeing the close button :)

**Comment by reagle** [comment]
Duh! Sorry!

**Comment by aluminum1** [comment]
I just had the same problem. The not-working-in-iframe `https://slides.com`link is still contained in the documentation `README.md`, latest version.
