### ISSUE TITLE
Multiplexing setup

### ISSUE THREAD

**Issue by ArthurMaroulier** [hakimel/reveal.js#1195]
Hello, I succeeded in setting up multiplexing with your socket.io server (revealjs.jit.su:80) but I didn't succeed in setting it up with a local socket.io server.
Please, can you help me in setting it up? The Socket.io server (https://github.com/hakimel/reveal.js#socketio-server) section in the doc is confusing to me.

An other thing is for server side notes. I succeeded in setting it up but when I open the notes window on an other device, the client doesn't window update (on an other device) when I change the slide in the notes window. But with multiplexing and server side notes it works.

Thank you for your help.

(I'm on MacOS and Debian for server side, with google chrome)

**Comment by lukaspetr** [comment]
I have to say that for me this section is also a bit confusing...

**Comment by ArthurMaroulier** [comment]
Finally I succeed, I'll submit an update of the multiplexing doc section.

**Comment by lukaspetr** [comment]
Great, I would be very happy to see it! Looking forward.

**Comment by ArthurMaroulier** [comment]
I've finally found some time to update the doc for self hosted socket.io server and master / clients configuration. And made a pull request.
https://github.com/hakimel/reveal.js/pull/1218
