### ISSUE TITLE
Reset animated gifs each time slide becomes active

### ISSUE THREAD

**Issue by thomasballinger** [hakimel/reveal.js#1198]
I just tried a hack to get gifs in the background of slides to reload each time I viewed a slide - would there be interest in making this a feature?

To do this we had to
* remove the data-loaded attribute from the slide background
* add a query string as described in [this SO post](http://stackoverflow.com/a/10730240/398212)

**Comment by hakimel** [comment]
I recently added support for this, so far it's only available in the dev branch and it doesn't work in Firefox. You can see it in action by navigating to the following slide http://lab.hakim.se/reveal-js/#/10/4

**Comment by Huxpro** [comment]
@hakimel It seems like this functionality never works in modern browsers? I tried safari/chrome on Macbook/Phones and both failed, and please reopen this issues 😢
