### ISSUE TITLE
Live demo with Beige theme not showing background tile or image with Chrome 42.0.2311.90-1 0

### ISSUE THREAD

**Issue by reagle** [hakimel/reveal.js#1203]
Weird issue.

1. Go to [live demo](http://lab.hakim.se/reveal-js/)
2. When you get to [themes](http://lab.hakim.se/reveal-js/#/themes) select beige and continue.
3. Image [backgrounds](http://lab.hakim.se/reveal-js/#/10/1) and [tiles](http://lab.hakim.se/reveal-js/#/10/2) do not show.

**Comment by hakimel** [comment]
The background actually shows up but it's a low opacity image so hard to see against light backgrounds. I think that's OK since this is demo content designed for the dark default theme.

**Comment by reagle** [comment]
Oh, okay, thanks.
