### ISSUE TITLE
Unable to Hide Address Bar on Mobile Safari

### ISSUE THREAD

**Issue by sumitrshah** [hakimel/reveal.js#1210]
I'm unable to get the address bar to hide in landscape mode on mobile Safari.  

When the mobile user first rotates to landscape mode, the address bar disappears.  However, as soon as the user starts touching through the slides, the address bar pops back in and never slides back out.  Any ideas what the issue might be?  It only seems to be a problem for my slide deck, as some example presentations from slides.com don't have this issue.

hideAddressBar has been set to _true_ in the initialize function.

And the <head> section of my HTML file has the following <meta> links:

<meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
<meta name="msapplication-tap-highlight" content="no" />

**Comment by cavie78** [comment]
I'm having the same issue...

**Comment by cavie78** [comment]
Any news about this?

**Comment by spacepluk** [comment]
This doesn't work on Android either.

**Comment by demoneaux** [comment]
Sadly, the code for hiding the address bar no longer works reliably on modern mobile browsers. If anyone has a reliable method, please feel free to reopen this issue.
