### ISSUE TITLE
Simplify fragments for lists

### ISSUE THREAD

**Issue by kjetilk** [hakimel/reveal.js#1211]
It seems like if I have a list, I would have to go
```
<ul>
  <li class="fragment">Foo</li>
  <li class="fragment">Bar</li>
</ul>
```

To get the common behaviour of one item per forward action. It would be nice if this could be simplied to something like 

```
<ul class="fragments">
  <li>Foo</li>
  <li>Bar</li>
</ul>
```

I suppose you could do this for any block level element, so you could do 
```
<div class="fragments">
  <p>Foo</p>
  <p>Bar</p>
</div>
```

But the interesting special case is for definition lists where the dt and dd should be presented together.

**Comment by demoneaux** [comment]
I think this is rather complicated, and won’t be suitable for reveal.js, as there are many different elements, both block and inline with different semantics. Feel free to implement a plugin for this.

**Comment by crawben20** [comment]
I second this issue - it is far more annoying when using Markdown, as you have to label every single list item with `<!-- .element: class="fragment" -->`. That gets irritating quickly.

**Comment by maiermic** [comment]
You can use this script

```js
Reveal.addEventListener("ready", function addFragmentToLists() {
  for (const listItem of document.querySelectorAll(".fragmented-lists li")) {
    listItem.classList.add("fragment");
  }
});
```

which adds the class `fragment` to all list items that are descendants of an element with class `fragmented-lists`, e.g.

```md
<!-- .slide: class="fragmented-lists" -->

## Fragmented List
- foo
- bar

---

## Regular List
- foo
- bar
```

**Comment by slambert** [comment]
Had to tweak the script a bit to get it to work on my VSCode Reveal plugin version:

```javascript
<script>
setTimeout(() => {
  const elements = document.querySelectorAll(".fragmented-lists li");
  for (const listItem of elements) {
    listItem.classList.add("fragment");
  }
}, 1000);
</script> 
```
