### ISSUE TITLE
Preload for offline use

### ISSUE THREAD

**Issue by kjetilk** [hakimel/reveal.js#1212]
There might be times of panic when you are about to present, and have relied on a network being present, and there is none, at least not in the room where the presentation was going to be. 

Then, it would be really nice if the whole presentation could be preloaded, so you have a Plan B in case it happens. 

It seems it could be done after #703 is done by adding manifest support.

**Comment by leadingcode** [comment]
I use caching presentations
Here is an example, presentation name all.html
Use file, in root presentation folder with this name:
cache-manifest.appcache
```
# v1.0

CACHE MANIFEST
presentation/reduksin/all.html
presentation/reduksin/imsges/
presentation/reduksin/css/
presentation/reduksin/fonts/
presentation/reduksin/js/
presentation/reduksin/lib/
presentation/reduksin/plugins/

NETWORK:
# search.php
# login.php
# /api

FALLBACK:
```

Then in header all.html you need declare manifest="cache-manifest.appcache"
```
<!doctype html>
<html lang="en" manifest="cache-manifest.appcache">
	<head>
		<meta charset="utf-8">
```
And in .htaccess you need declare this line AddType text/cache-manifest .manifest
```
##
# @copyright	i.creative@yandex.ru
##
AddDefaultCharset UTF-8

# Cache manifest
AddType text/cache-manifest .manifest
```

**Comment by tomByrer** [comment]
> It seems it could be done after #703 is done by adding manifest support.

No, two different issues.  In fact, using applicationCache should be done first IMHO, because that could eliminate issues with loading presentation the second+ times.

**Comment by kjetilk** [comment]
OK, cool! :-)

**Comment by demoneaux** [comment]
This can probably be done with ServiceWorkers, but I’m not sure if they should be included in the core repository. @hakimel what do you think?

**Comment by hakimel** [comment]
I think this is outside the scope of reveal.js. To run a reveal.js presentation offline you should store it locally on your computer. All framework assets are already included in the repo so as long as you keep local copies of your images as well it should all work offline.

**Comment by fruitloop** [comment]
remember to download the necessary fonts as well
