### ISSUE TITLE
Turning outslide on and off within fragments

### ISSUE THREAD

**Issue by GuidoS** [hakimel/reveal.js#1216]
Hi,

I can't seem to find enough documentation about auto-slide and fragments. I would like to have sections autoslide, but not the slide itself. I could not seem to turn autoslide off once the section was setup with data-autoslide.

thoughts?

**Comment by GuidoS** [comment]
Is there a chance that the following code could be honored?
```
data-fragment-autoslide="3000" 
```

**Comment by GuidoS** [comment]
BTW, this was originally asked for in #335 ;)

**Comment by demoneaux** [comment]
As mentioned [here](https://github.com/hakimel/reveal.js#auto-sliding), fragments support the `data-autoslide` attribute to indicate the length of time before auto-sliding.
