### ISSUE TITLE
when there is a long code snippet, the contents get cut off in the print-pdf version

### ISSUE THREAD

**Issue by davidhan527** [hakimel/reveal.js#1217]
operating system - yosemite 
browser - Chrome latest - Version 42.0.2311.135 (64-bit)

http://davidhan527.github.io/gh_testing/#/11/3

* the second highlight.js code snippet on this page is long and scrollable. The web version of the slides support viewing long code snippets by scrolling but the pdf version does not show the entire snippet.

**Comment by demoneaux** [comment]
This can’t be helped as each slide has a set width/height, so all text that overflows has to be cut off. You might want to split it into a different slide.
