### ISSUE TITLE
Highlight doesn't work with markdown-only

### ISSUE THREAD

**Issue by gre** [hakimel/reveal.js#1225]
It seems highlight doesn't work if using only markdown slides because of this:

`condition: function() { return !!document.querySelector( 'pre code' ); },`

in the default highlight plugin condition.

I've removed it and everything works as expected

**Comment by hseeberger** [comment]
Same here.

**Comment by Huxpro** [comment]
same problem

**Comment by ggarnier** [comment]
I have the same problem. Here is a snippet to simulate this:

		<section data-markdown>
			<script type="text/template">
				## Highlight with markdown

		```
		def sum(a, b)
		  a + b
		end
		```

			</script>
		</section>

		<section>
			<h2>Highlight without markdown</h2>
			<pre><code data-trim contenteditable>
		def sum(a, b)
		  a + b
		end
			</code></pre>
		</section>

In this example, both slides get code highlight. But if I remove the second slide, the first one isn't highlighted anymore.

**Comment by gre** [comment]
if you want to fix it, just remove the `condition` of highlight plugin:

```
{ src: 'plugin/highlight/highlight.js', async: true, callback: function() { hljs.initHighlightingOnLoad(); } },
```

I'll submit a PR to make this a default

**Comment by faxm0dem** [comment]
:+1: thanks WFM
