### ISSUE TITLE
Is there a way to change/force zoom-js scale factor?

### ISSUE THREAD

**Issue by theradioboy** [hakimel/reveal.js#1231]
When I alt-click on a slide, the magnification factor is sometimes too small to be of any use, and sometimes it works with something in the range +10%/+20%. Is there a way to force a scale factor, either globally or per-slide? Thanks.

**Comment by hakimel** [comment]
That's not configurable, the scale factor is based on the size of the element you click. It tries to zoom as far as it can while keeping the whole element visible.
