### ISSUE TITLE
reduce empty space at the top

### ISSUE THREAD

**Issue by fommil** [hakimel/reveal.js#1237]
I'd really like to be able to decrease the amount of padding at the top of all my level 2 slides. It doesn't appear to be possible to customise this with CSS because the offset is a negative number calculated dynamically.

e.g. in http://fommil.github.io/scalax14/#/5/1 I would like to reclaim at least 200 pixels at the top.

Is there a way to do this?

**Comment by fommil** [comment]
to clarify, the `top` parameter is being calculated to be `-350px` but I'd really rather it was closer to `-500px`.

**Comment by fommil** [comment]
closing in preference of http://stackoverflow.com/questions/30422299 I'll reopen if this is a genuine feature request.

**Comment by JJ** [comment]
Where are you setting that parameter?
