### ISSUE TITLE
Documentation for help (?) key?

### ISSUE THREAD

**Issue by matbury** [hakimel/reveal.js#1241]
Hi,
Great project. Thanks for developing this! :)

I'm looking for some docs and examples of the help (?) key feature. At the moment, the screen fades but nothing else happens. Is there something we need to do to enable/link to a help menu/page?

Thanks in advance.

**Comment by matbury** [comment]
Ah, just worked it out: Users have to press Shift + ? to get it to work, and "F1 Help" key doesn't work.

Would it be possible/reasonable to make those work by default instead of hard-coding it on each slide show in JS?

Thanks again :)

**Comment by aspiers** [comment]
Puzzled by your second comment - I'm wondering how it would be possible to press `?` on any standard English-based keyboard *without* pressing Shift?

**Comment by demoneaux** [comment]
Yep, you have to use `Shift` + `?` to get the `?` symbol on a English keyboard. Alternatively, you can use the new `Reveal.toggleHelp()` method in v3.5.
