### ISSUE TITLE
Displacement animations

### ISSUE THREAD

**Issue by piranna** [hakimel/reveal.js#1243]
Add support for fade-in and fade-out animations that change the position of an element: intro from out of screen, spin-out, bounce...

**Comment by demoneaux** [comment]
This isn't a very good fit for the Reveal.js core library which aims to have a set of essential utilities. Feel free to create your own set of animations and share them [here](https://github.com/hakimel/reveal.js/wiki/Plugins,-Tools-and-Hardware).
