### ISSUE TITLE
Shadows don't fit snugly around code/pre

### ISSUE THREAD

**Issue by estan** [hakimel/reveal.js#1246]
I get

![nosnug](https://cloud.githubusercontent.com/assets/86675/7929521/53b5ecb6-08ff-11e5-8a57-8634f83ac0e7.png)

whenever I use `<code><pre>...</pre></code>`. Note how the frame with the shadow does not fit snugly around the code. This happens with both the white and black themes (haven't tried others), and both in Chromium and Firefox.

EDIT: I am using `data-trim`, so that's not the issue.

**Comment by hakimel** [comment]
Can you include a link to that presentation or the source code for the slide? This doesn't appear to be a problem in the example presentation at http://lab.hakim.se/reveal-js/#/13

**Comment by estan** [comment]
Ah you're right. I don't get the problem with the demo either.

I don't have the presentation running at an URL, but here's a zip of it: http://dose.se/~estan/reveal.js.zip

It started as a clone of reveal.js master. The only thing I've changed is `index.html` and added an `images/` directory.

**Comment by estan** [comment]
Bah I'm so stupid. I had whitespace between the `code` and `pre` elements. That was it. Closing this one.
