### ISSUE TITLE
Overview Mode is broken when width is 100%

### ISSUE THREAD

**Issue by waywaaard** [hakimel/reveal.js#1247]
When setting the ```width: "100%"``` the overview mode is not usable anymore. It does not shrink the individual slides.

You can try this on the official reveal-js demo when executing following snippet:

```javascript
Reveal.configure({width: "100%"});
```

**Comment by yarray** [comment]
+1

**Comment by Jmuccigr** [comment]
Biting me too, but I think the problem is  present for any percentage value.

**Comment by Jmuccigr** [comment]
Any activity on this one? Really a pain.

**Comment by hackhowtofaq** [comment]
Same problem here...

**Comment by hakimel** [comment]
Just fixed this in the dev branch. Will be released with 3.3.0.
