### ISSUE TITLE
No transitions fire with internal links

### ISSUE THREAD

**Issue by kariannking** [hakimel/reveal.js#1248]
I can't seem to find a way to make the slides transition normally if I use the internal link method to skip slides. When I skip one or more slides with an internal link, it simply "jumps" to the specified section in the link. I can't find in the documentation if this is working as intended or a bug. If it is working as intended is it possible to include a way to toggle transitions on with internal links?

example:
`<section class="slide" id="slide01">`
`<a href="#/slide03">Go to Slide 3</a> /*No transition*/`
`<a href="#/slide02">Next</a> /*default transition works*/`
`</section>`
`<section class="slide" id="slide02"></section>`
`<section class="slide" id="slide03"></section>`

**Comment by nopio** [comment]
Were you able to find a solution for this?

**Comment by kariannking** [comment]
I was not. I even tried to apply a <i>data-transition="fade-in fade-out"</i> to every section and still didn't have any luck.

**Comment by nopio** [comment]
We actually found a way to handle this, but it required a nasty hack in the styles:
.reveal .slides > section {
   display: block !important;
}

This ensures that the past and future slides are always visible. That said, we didn't have a chance to investigate why it's not like that by default and if this does not break something else.

**Comment by TranceGeniK** [comment]
Same issue here. And the !important hack didn't solve this issue for me, as my slides are dynamically created and updated, they overlap after the update and sync and I can't put 1second time for the transition to finish before I get to the next slide. Any ideas ?

**Comment by designcomputer** [comment]
It appears that an issue, which was reported 9 years ago, is still unresolved. To demonstrate the problem, consider a basic example where the first two links on Slide 1 transition smoothly but the following transitions just cut.

The page can be tired here: [](https://ic5.designcomputer.com/reveal/)

```
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Building Directory</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/reveal.js/5.0.5/reset.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/reveal.js/5.0.5/reveal.min.css">
    <style>
        body a {
            color: blue;
            text-decoration: none;
        }
        body a:hover,
        body a:active {
            color: red;
        }
        h2 {
            font-size: 30px;
            font-family: Arial, Helvetica, sans-serif;
        }
    </style>
</head>

<body>
    <div class="reveal">
        <div class="slides">
            <section>
                <h2>Slide 1</h2><br><br>
                <a href="#/1">Go to Slide 2</a><br><br>
                <a href="#/2">Go to Slide 3</a><br><br>
                <a href="#/3">Go to Slide 4</a><br><br>
                <a href="#/4">Go to Slide 5</a><br><br>
                <a href="#/5">Go to Slide 6</a><br><br>
                <a href="#/6">Go to Slide 7</a><br><br>
            </section>
            <section>
                <h2>Slide 2</h2><br>
                <a href="#/0">Back to the first</a>
            </section>
            <section>
                <h2>Slide 3</h2><br>
                <a href="#/0">Back to the first</a>
            </section>
            <section>
                <h2>Slide 4</h2><br>
                <a href="#/0">Back to the first</a>
            </section>
            <section>
                <h2>Slide 5</h2><br>
                <a href="#/0">Back to the first</a>
            </section>
            <section>
                <h2>Slide 6</h2><br>
                <a href="#/0">Back to the first</a>
            </section>
            <section>
                <h2>Slide 7</h2><br>
                <a href="#/0">Back to the first</a>
            </section>
        </div>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/reveal.js/5.0.5/reveal.js"></script>
    <script>
        Reveal.initialize({
            width: "100%",
            height: "100%",
            margin: 0,
            minScale: 1,
            maxScale: 1,
            hash: true,
            transition: 'slide', // none/fade/slide/convex/concave/zoom
        });
    </script>
</body>

</html>
```

**Comment by Martinomagnifico** [comment]
Thus is a side-effect of the fact that sections further away are set to `display:none`, and that is done for performance reasons. You can set this viewDistance to a larger number, for example the total amount of slides, in the config: `{viewDistance: 100}`. See this issue: https://github.com/hakimel/reveal.js/issues/260#issuecomment-26919687

**Comment by designcomputer** [comment]
Thanks @Martinomagnifico, I'll give that a try tomorrow.

**Comment by designcomputer** [comment]
Thanks again @Martinomagnifico, Setting `{viewDistance: 10} ` did the trick. 
The docs make it sound as though this setting is more about caching media like images and video.

**Comment by Martinomagnifico** [comment]
Hi @designcomputer, I guess this issue can be closed then?
