### ISSUE TITLE
Export PDF does not display background

### ISSUE THREAD

**Issue by arnaldorusso** [hakimel/reveal.js#1253]
Hi, 

I have this problem for a while.... so I have pulled the repo again (to update my old or bugged old files). 
The same problem I have already becomes to me. Even running a server, or directly opening the index.html, when I open the print dialog, it shows the pages without background and all text left aligned. It seems to not preserve .css information.

What I'm doing wrong?

Just as a note, the slides work very well on the browser.

**Comment by hypery2k** [comment]
In reveal.js (Line 1504) edit this line
```
if( dom.wrapper && !isPrintingPDF() ) {
```
change it to 
```
if( dom.wrapper ) {
```

Then it should work

@hakimel Is the second condition really needed?

**Comment by cfjedimaster** [comment]
I'm having this too, and the mod above did not help.

**Comment by cfjedimaster** [comment]
FYI, I had another issue, and removing this mod helped.

**Comment by felixzapata** [comment]
Hi, I have the same problem with the last version.

**Comment by felixzapata** [comment]
nevermind, you have to check now when you open the dialog to print, the option to show background images.
