### ISSUE TITLE
Do slidechanged event triggers before slides change?

### ISSUE THREAD

**Issue by matbury** [hakimel/reveal.js#1254]
Hi,

Many thanks for the great project :)

I've set up a listener for the slidechanged event using the Reveal.JS API.

I'm (over)writing the current browser URL in a cookie each time the slidechanged event is triggered and when the slideshow opens, and there is a URL stored in the cookie, it automatically goes to that slide, i.e. an automatic resume feature.

However, the URL that gets stored is the second to last one, not the current one. I'm guessing that the slidechanged event triggers before the URL changes. Is that true? Is that supposed to happen?

Is there another way to implement a resume feature?

Thanks in advance :)

**Comment by FeliciousX** [comment]
Hey @matbury , if you're trying to implement a resume feature, you can actually use the [presentation state](https://github.com/hakimel/reveal.js#presentation-state) API .

Store it in a variable and then resume it by setting the state.

Hope that helps :smile:

**Comment by FranceBaril** [comment]
Hi, I have what I believe is a related issue. I transform XML content to Reveal.js. Sometimes, the content is too large to fit the slides, so on slidechanged, I run a resize function that shrinks content until the scroll height is smaller or equal the height of the slide area. 

This works perfectly fine 99% of the time. However, sometimes, it seems that the content isn't loaded before the slidechanged is triggered. My resize function gets the scroll height from the slide I'm leaving, instead of getting the height from the new slide. 

The behaviour is always on the same slides, and so far it seems to only affect slides that are accessed with the down arrow. If I move forward and back, these same slides do get resized. I'm pretty sure therefore that the issue is linked to navigation with that specific arrow.

Note: I'm using 3.2.0.

**Comment by matbury** [comment]
Hi @FeliciousX, I'm storing the slide number in a cookie so that the next time the user opens the presentation, it automatically goes to where they left off. At the moment, it's 1 slide behind so it's not a big deal.

**Comment by matbury** [comment]
Hi @FranceBaril, I've tried putting a delay in the JS like this:

```
// slidechanged event triggers too soon, so Wait for 1 second before pausing audio
pauseSlide = function() {
    pauseTimer = window.setTimeout(pauseAudioPlayer, 1000);
};
```

and the events trigger as expected, so I suspect the event is triggered before the slide change functions are completed.

I hope this helps! :)

**Comment by FranceBaril** [comment]
Is there an other event that is only triggered after a slide is fully
loaded?

On Wed, Dec 30, 2015 at 7:28 PM, Matt Bury <notifications@github.com> wrote:

> Hi @FranceBaril <https://github.com/FranceBaril>, I've tried putting a
> delay in the JS like this:
>
> // slidechanged event triggers too soon, so Wait for 1 second before pausing audio
> pauseSlide = function() {
>     pauseTimer = window.setTimeout(pauseAudioPlayer, 1000);
> };
>
> and the events trigger as expected, so I suspect the event is triggered
> before the slide change functions are completed.
>
> I hope this helps! :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hakimel/reveal.js/issues/1254#issuecomment-168099691>.
>



-- 
France Baril
Architecte documentaire / Documentation architect
france.baril@architextus.com

**Comment by matbury** [comment]
The entire slide show (web page) is already fully loaded. RevealJS shows each section of the web page, one at a time and transitions between them. Do you mean an "on transition complete" event? I haven't seen one documented.

**Comment by FranceBaril** [comment]
Yep, since the event is called slidechanged with a 'd', I assumed it was
for after the slide is shown, therefore after @class=present is set.

On Wed, Dec 30, 2015 at 9:49 PM, Matt Bury <notifications@github.com> wrote:

> The entire slide show (web page) is already fully loaded. RevealJS shows
> each section of the web page, one at a time and transitions between them.
> Do you mean an "on transition complete" event? I haven't seen one
> documented.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hakimel/reveal.js/issues/1254#issuecomment-168112944>.
>



-- 
France Baril
Architecte documentaire / Documentation architect
france.baril@architextus.com

**Comment by FranceBaril** [comment]
Is this considered a bug, or is it how slidechanged is expected to work? I'm wondering if I need to code a workaround or if I can expect the next release to fix this issue.

Thanks?

**Comment by nix1** [comment]
I experienced a similar issue with having some old state in `slidechanged` handler. As a workaround, any delay (`setTimeout(..., 0)`) was enough to get the correct data.

**Comment by matbury** [comment]
Should we ask for a transitionComplete event?

**Comment by FranceBaril** [comment]
Matt Bury, yes! The content for my slides is added automatically from a
database. I added javascript to resize content to fit the window when
slides are displayed. Resize only works if the content is actually loaded.
This event is of great importance to me!

On Mon, Feb 29, 2016 at 10:40 AM, Matt Bury <notifications@github.com>
wrote:

> Should we ask for a transitionComplete event?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hakimel/reveal.js/issues/1254#issuecomment-190260666>.
>



-- 
France Baril
Architecte documentaire / Documentation architect
france.baril@architextus.com

**Comment by FranceBaril** [comment]
I ran into other problems related to this issue. And adding delays everywhere is starting to slow things down. I took a quick look at the reveal.js source and I moved the code that dispatches the slidechanged event to the end of function slide(h, v, f, o){} near line 2213. The code I moved is: 

` // Dispatch an event if the slide changed
		var slideChanged = ( indexh !== indexhBefore || indexv !== indexvBefore );
		if( slideChanged ) {
			dispatchEvent( 'slidechanged', {
				'indexh': indexh,
				'indexv': indexv,
				'previousSlide': previousSlide,
				'currentSlide': currentSlide,
				'origin': o
			} );
		}
		else {
			// Ensure that the previous slide is never the same as the current
			previousSlide = null;
		}`

It resolved my issues and so far I have no undesired side effect. May I request a change in future releases? Was there a reason the event was triggered so early?

**Comment by Martinomagnifico** [comment]
The `slidetransitionend` event was added in version 4.0.0.
