### ISSUE TITLE
How to upgrade

### ISSUE THREAD

**Issue by matthewp** [hakimel/reveal.js#1255]
I searched and couldn't find an answer to this, but how do you upgrade a project that uses an older version of reveal.js?

**Comment by matthewp** [comment]
Ah, found it.  Sorry https://github.com/hakimel/reveal.js/wiki/Migrating-to-reveal.js-3.0.0

**Comment by matthewp** [comment]
Well that still doesn't explain what you need to do to upgrade your project.

**Comment by demoneaux** [comment]
The format for Reveal.js slides has stayed mostly the same, so probably just updating the code files should be fine.
