### ISSUE TITLE
Per slide vertical centering

### ISSUE THREAD

**Issue by hadim** [hakimel/reveal.js#1262]
Most of my slide are not vertically centered (I use `center: false,` option). How can I ask reveal.js to vertically center only one slide (by JS or CSS).

Thank you

**Comment by tpgmartin** [comment]
Hey @hadim this should be possible by adding the class "center" to any slide you want vertically centred.

**Comment by hadim** [comment]
Thank you +1

**Comment by jdehaan** [comment]
+1 Good idea!

**Comment by denispeyrusaubes** [comment]
How can you add the "center" class to a slide in your markdown code ?

---
## Title

`To be vertically centered`

**Comment by demoneaux** [comment]
You can see [this example from the readme](https://github.com/hakimel/reveal.js#slide-attributes):

```html
<section data-markdown>
    <script type="text/template">
    <!-- .slide: class="center" -->
        Markdown content
    </script>
</section>
```

Or just add the class directly as well:

```html
<section data-markdown class="center">
    <script type="text/template">
        Markdown content
    </script>
</section>
```

**Comment by denispeyrusaubes** [comment]
Thank for the response... 
but I need to apply this style to some specific slides, and my slides are divided in chapters I specific md files.
One slide is delimited by ```---``` from the other
so I don't understand how to proceed in my case.

My index.html links all chapters using:

```html
<section>
				<section data-markdown="/myfolder/mychapter.md" data-separator="^\n---\n" data-vertical="^\n\n">
					Markdown body of a slide here ...
				</section>
			</section>
```

**Comment by demoneaux** [comment]
You can try placing the `<!-- .slide: class="center" -->` after each `---` for each slide.

**Comment by denispeyrusaubes** [comment]
Strange, I've placed this code immediately after ```---```, and the generated html contains

```html
<section data-markdown="" data-markdown-parsed="true" class="center present" style="top: 0px; display: block;"><!-- -->
<h2 id="le-jeu-de-test">Le jeu de test</h2>
<p>test</p>
</section>
```

But my text isn't vertically centered...

**Comment by demoneaux** [comment]
The slide should be vertically centred, not too sure how to help you with that anymore.

**Comment by denispeyrusaubes** [comment]
is ```center``` a standard css style ? 
I can't find a specific css rule defined in provided css files...

**Comment by demoneaux** [comment]
The `center` class is used in JS to indicate that the slide should be vertically centred. See https://github.com/hakimel/reveal.js/blob/713702a0ab81d1756a30e6c14ae49afd42135541/js/reveal.js#L1650-L1659.

**Comment by denispeyrusaubes** [comment]
ok, thank you very much for your help !

**Comment by demoneaux** [comment]
There isn't a built in way to do that, you'll have to manually figure out the CSS and styles to make it work. The Reveal.js `center` will only center the whole slide.
