### ISSUE TITLE
Presentation size in percentage not working

### ISSUE THREAD

**Issue by rootion** [hakimel/reveal.js#1263]
I want to follow the steps indicated in #857, but I don't manage to set up the size at 100% both height and width with the following code. It should be working according to the documentation, but it's not.

```
    // The "normal" size of the presentation, aspect ratio will be preserved
    // when the presentation is scaled to fit different resolutions. Can be
    // specified using percentage units.
    width: 100%,
    height: 100%
```

What exactly is wrong here?

**Comment by hakimel** [comment]
You'll need to wrap the units in quotation marks

**Comment by qmarcos** [comment]
Unfortunately, this doesn't work properly.

Looking into the code, the implementation is not right:

**file reveal.js** 
```js
dom.viewport.style.setProperty( '--slide-width', config.width + 'px' );
dom.viewport.style.setProperty( '--slide-height', config.height + 'px' );
```

If you pass to width or height a value like '100%' you get a value for those variables of '100%px'. 
I think something like this could solve the issue to accept units that are not px based:

```js
dom.viewport.style.setProperty( '--slide-width', isNaN(config.width) ? config.width :  config.width + 'px' );
dom.viewport.style.setProperty( '--slide-height', isNaN(config.height) ? config.height :  config.height + 'px' );
```

**Comment by scritrolf** [comment]
I can only agree, I just stumbled upon this when trying to get full size slides and found 
<code>style="--slide-width: 100%px; --slide-height: 100%px; --slide-scale: 1;</code>
when debugging :)
