### ISSUE TITLE
data-transition="none" isn't none.

### ISSUE THREAD

**Issue by socketwench** [hakimel/reveal.js#1265]
The `none` slide transition no longer is none. Given you have the following slides: 

```
                <section>
                    <section data-transition="none">
                        <h1>Stuff</h1>
                    </section>
                    <section data-transition="none">
                        <h1>Stuff</h1>
                    </section>
                    <section data-transition="none">
                        <h1>Stuff</h1>
                    </section>
                    <section data-transition="none">
                        <h1>Stuff</h1>
                    </section>
                </section>
```

Even given the data-transition being `none` the text will appear to "pulse" as it fades out and then fades back in again. Typically, I've used this pattern with images, progressively revealing the image content on consecutive slides with a new image in each slide. (Example: http://socketwench.github.io/exampleModuleAintCore/#/6/8)

The behavior was not present in earlier versions of Reveal.js.

**Comment by tpgmartin** [comment]
I'm not sure if it's intentional but you've nested your slides within a containing `section` tag so there'll be arranged vertically. I've found that you'll get the desired transition behaviour if you remove the outermost `section` tags - so move between slides with left/right cursor keys. 

Also, you shouldn't have to declare the `data-transition` attribute on every slide just set `transition` in your configuration options. However, you can override this global behaviour by setting the `data-transition` attribute on a slide by slide bassi.

**Comment by socketwench** [comment]
That's really only a workaround. None *does* seem to be none between left and right slide transitions. This is a change on behavior from earlier versions of Reveal, though. I shouldn't need to throw out all multi-level slides just because of this regression...

**Comment by demoneaux** [comment]
This bug should be fixed in reveal.js v3.2.0.

**Comment by socketwench** [comment]
Confirmed, fixed in 3.2.0. Thanks!

**Comment by Huxpro** [comment]
@socketwench Have you ever wrote following code?

```
<section data-transition="slide-in none-out">
  <h1>Stuff</h1>
</section>
<!--  or <section data-transition="none-in none-out">  -->
<section data-transition="none">
  <h1>Stuff</h1>
</section>
<section data-transition="none-in slide-out">
  <h1>Stuff</h1>
</section>
```
This approach provide even better transitions and controll between every slide.
But sadly It won't work yet.

**Comment by AsafAgranat** [comment]
@Huxpro, until it is fixed, you can add the following to the reveal.scss meantime:
```
section {
	&[data-transition*="none-out"] {
		&.present, &.past {
			transition-duration: 0s !important;
		}
	}
	&[data-transition*="none-in"] {
		&.future, &.present {
			transition-duration: 0s !important;
		}
	}
}
```
