### ISSUE TITLE
Colour coding of code not working without specific elements in the page

### ISSUE THREAD

**Issue by judgej** [hakimel/reveal.js#1266]
This had me stumped for hours, and a really obscure bug. I had a slide show with PHP code samples, all in markdown sections. Without warning at one point of writing this presentation, all the colours of the code fragments disappeared. In the source, all code was in `<pre>` and `<code>` elements, but not parts of the code was wrapped in tags to colour-code it. There were no JS errors.

I traced it down to this. I can make the colours come back by placing these elements anywhere in the page:

    <pre><code></code></pre>

It can be absolutely anywhere in the HTML page, inside or outside the slides section.

To prevent it affecting the display, you can do this:

    <pre style="display:none;"><code></code></pre>

So what is up with that? Why should the JS for colour-coding code samples no kick in without that particular sequence of nested elements in the original source of the page?

I'm using FF on Windows 7. You can see this effect by taking the sample page and removing all slides but the "Markdown support" page.

**Comment by judgej** [comment]
I was specifically using `\`\`\`php` to open the PHP code sample sections, which is a nice undocumented feature, but the same happens whether the "php" suffix is added or not. I believe `~~~php` works the same.

**Comment by jakubholynet** [comment]
I have experienced the same problem, loading my presentation from an external file. And I have a better workaround, modifying `Reveal.initialize dependencies` slightly:
```js
// BEFORE: { src: 'plugin/highlight/highlight.js', async: true, condition: function() {  !!document.querySelector( 'pre code' ); }, callback: function() { hljs.initHighlightingOnLoad(); } },
/* AFTER */ { src: 'plugin/highlight/highlight.js', async: true, condition: function() { return true; }, callback: function() { hljs.initHighlightingOnLoad(); } },
```

Just for reference, this is the key part of my `index.html`:
```html
<div class="reveal">
  <!-- Any section element inside of this container is displayed as a slide -->
  <div class="slides">

    <section data-markdown="talk-fp-in-js-ova201506.md"
         data-separator="^---$"
         data-separator-vertical="^\n\n"
         data-separator-notes="^Note:"
         data-charset="utf-8">
    </section>
  </div>
</div>
```

**Comment by judgej** [comment]
Indeed, a more elegant fix. I just threw in what worked for me in the rush I had to get the presentation together, but only posted it here to try to offer some clues as to what might *actually* be happening. If it is dependent libraries loaded on-the-fly in the wrong order against some conditions, then that makes sense.

**Comment by faxm0dem** [comment]
had to find out the workaround the hard way :+1:

**Comment by hakimel** [comment]
That condition for loading highlight.js was dropped in the 3.2.0 release. From now on it's always loaded, even if there is no `<pre><code>` block on the page.

See #1225

**Comment by faxm0dem** [comment]
WFM thanks! :+1:
