### ISSUE TITLE
SCSS: Two Dashes and the &-Operator are not compiling - "invalid propery name"

### ISSUE THREAD

**Issue by heroheman** [hakimel/reveal.js#1269]
hi,
i am working right now on some extensions in the for a simple grid in reveal.js. 
But it seems i can compile this (see attached image, 1376, 1377) with node-sass (this never occured to me, so i think its something with reveal)
![82kfv](https://cloud.githubusercontent.com/assets/407485/8181571/57570962-1427-11e5-87c9-4174fb367dd8.png)
I already updated node-sass in the package json from 0.9 - 3.2 - but it doesnt fix the problem. 

Any idea?

**Comment by demoneaux** [comment]
This doesn’t seem to have anything to do with reveal.js. Possibly your Sass has errors?
