### ISSUE TITLE
data-state not being applied as slide classname

### ISSUE THREAD

**Issue by jasonkarns** [hakimel/reveal.js#1272]
I have a section/slide with `data-state="title"` but the slide is not getting the `title` classname when active. That's how this is supposed to work, right?

**Comment by tpgmartin** [comment]
The name passed to `data-state` is added as a class to the html tag when that slide is viewed, i.e. the slide with class `present`. So the dom should look something like: <html lang="en" class="title" hola_ext_inject="disabled"> etc.

**Comment by demoneaux** [comment]
Yep, it will be applied to the HTML element. See [here](https://github.com/hakimel/reveal.js#slide-states).
