### ISSUE TITLE
Speaker notes for fragments

### ISSUE THREAD

**Issue by spassvogel** [hakimel/reveal.js#1275]
Right now it appears that the notes plugin takes the first '< aside>' element on a section to contain the notes.

What I would actually like is to be able to nest the notes inside a fragment, such that the note only appears when that fragment is active (and disappears when the next fragment becomes active).

**Comment by apmccartney** [comment]
Seconded

**Comment by fzzzt** [comment]
👍

**Comment by demoneaux** [comment]
Fixed in #1636.
