### ISSUE TITLE
Multiplex no longer works with example given in README due to socket.io version discrepancy with revealjs.jit.su

### ISSUE THREAD

**Issue by fghaas** [hakimel/reveal.js#1276]
The README currently gives this example for a multiplex configuration:

```javascript
Reveal.initialize({
	// other options...

	multiplex: {
		// Example values. To generate your own, see the socket.io server instructions.
		secret: '13652805320794272084', // Obtained from the socket.io server. Gives this (the master) control of the presentation
		id: '1ea875674b17ca76', // Obtained from socket.io server
		url: 'revealjs.jit.su:80' // Location of socket.io server
	},

	// Don't forget to add the dependencies
	dependencies: [
		{ src: '//cdnjs.cloudflare.com/ajax/libs/socket.io/0.9.16/socket.io.min.js', async: true },
		{ src: 'plugin/multiplex/master.js', async: true },

		// and if you want speaker notes
		{ src: 'plugin/notes-server/client.js', async: true }

		// other dependencies...
	]
});
```

Evidently, the socket.io server at revealjs.jit.su has been upgraded to a 1.x version, with which the 0.9.16 client library is incompatible, resulting in an HTTP 400 (Bad Request) error.

Updating the client socket.io library to 1.3.5 makes the problem go away; thus the correct socket.io source URL appears to be `//cdn.socket.io/socket.io-1.3.5.js`.

**Comment by Delapouite** [comment]
Thanks @fghass for finding this version incompatibility. Do you mind providing a PR to fix this URL?

**Comment by fghaas** [comment]
Yes the PR is trivial, but I've noticed that if I use the updated socket.io client in conjunction with the notes plugin, then instead of the next slide I only ever see the current slide in the speaker console. This applies **only** to the master presentation, i.e. the one where the socket.io secret is non-null, and the speaker console does work as expected on slaves. Is this a new problem, or has this existed before?

**Comment by jereme-leandev** [comment]
Hi why not update the socket.io in the package.json? I can see that it's still using 0.9.16

**Comment by fghaas** [comment]
@jereme-leandev please feel free to do that. I'm not sure if @hakimel has any intention to merge this PR though; it's been sitting in the queue for more than a month...

**Comment by hakimel** [comment]
Thanks for digging into this. The PR you submitted was merged and reveal.js now uses a more recent version of socket.io.

However I needed to make some changes to how multiplexing works as part of the dependency update so it's no longer compatible with the version at revealjs.jit.su. I'll file a new issue for asking the person who operates that server to update it once these changes have had some time to be tested and are merged into master.

**Comment by fghaas** [comment]
@hakimel Thanks! So to clarify, does this mean that a presentation using current master will not work with multiplexing via revealjs.jit.su?

**Comment by hakimel** [comment]
Neither master or dev currently work. Also just saw that the server is moving: https://github.com/hakimel/reveal.js/pull/1357/files

I'm starting to wonder if it might just be easier to switch the examples in the readme to run the server locally.
