### ISSUE TITLE
Integrating Reveal JS with Polymer 1.0. Is it possible ?

### ISSUE THREAD

**Issue by joao-parana** [hakimel/reveal.js#1277]
Is it possible integrate Reveal JS with Polymer 1.0 ?

My sugestion is build idiomatic HTML for Slides Presentation (something like this):

    <rjs-slides>
      <rjs-slide type="markdown">
        # First Slide
        . . . 
      </rjs-slide>
      . . .
    </rjs-slides>

where rjs mean Reveal JS

**Comment by Delapouite** [comment]
Beside a more semantic naming, what would be the benefits over the current nested `<section>` HTML tags?

**Comment by demoneaux** [comment]
Not too sure if it's possible (I don't really use Polymer), but it probably won't be landing in this core repository. However, if you do want to experiment with implementing it feel free to do so.
