### ISSUE TITLE
</t> are sometimes added at the end of code statements

### ISSUE THREAD

**Issue by wget** [hakimel/reveal.js#1278]
Like specified in [my tweet](https://twitter.com/wget42/status/610439533411344384), sometimes when I add code statements, `</t>` tags appears at the end of the code block.

![chi3hunvaaavcbj](https://cloud.githubusercontent.com/assets/2997662/8301522/bacd91fc-198e-11e5-985c-e61346c9a97c.png)

I think the problem might be due to the `highlight.js` library reveal.js is using.

To get the code of the presentation, you can get [a snippet here](http://wget.be/reveal).

**Comment by hakimel** [comment]
You'll need to escape the `< >` symbols with HTML entities. If not the browser will try to "fix" the broken markup in the page (an opening `<t>` without a closing tag). This happens before our JS kicks in so we can't script around it.

This:
```
public class FailableValueWrapper<t>
```
Would be changed to:
```
public class FailableValueWrapper&lt;t&gt;
```
