### ISSUE TITLE
Support a background opacity data attribute

### ISSUE THREAD

**Issue by cfjedimaster** [hakimel/reveal.js#1279]
I'd like to use a full screen background, but change the opacity via a data attribute.

**Comment by waywaaard** [comment]
You can use a special class that will be added to the slide when displayed. See https://github.com/hakimel/reveal.js#slide-states

**Comment by cfjedimaster** [comment]
Oh, I know I can hack it now. :) Just looking for something simple. :)

**Comment by demoneaux** [comment]
I think using a state class is the best way to do that.

**Comment by cfjedimaster** [comment]
Would you mind me asking for a specific example of this? I've tried this:

    <section data-background="http://www.hindscc.edu/Assets/images/careertech-hinds-computer-programmer-code.jpg" data-state="dimbg">
	<h1>Programming</h1>
    </section>

(And yes, I know it's bad to use a remote img like this, I'm just testing.) When I inspect w/ Chome dev tools, I do not see "dimbg" being applied to my current page.

**Comment by cfjedimaster** [comment]
I found it in the <html> tag. Ok, didn't expect it up there. :) Would be nice though if there was a reference that let you know where elements exist DOM wise, so for example, "what class applies to the current background"

**Comment by C-Duv** [comment]
Using this technique I get a merged background when the slide with `data-state` is shown.

Given the following CSS and HTML:
```CSS
html.dim-background .slide-background {
    opacity: 0.4 !important;
}
```

```HTML
<body>
    <div class="reveal">
        <div class="slides">
            <section>
                <section data-background-image="./images/bg-slide-1.jpg">1</section>
            </section>
            <section>
                <section>2</section>
            </section>
            <section>
                <section data-background-image="./images/bg-slide-2.jpg" data-state="dim-background">3</section>
            </section>
        </div>
    </div>
</body>
```

When slide "3" is displayed, both `bg-slide-1.jpg` and `bg-slide-3.jpg` are displayed "merged".
Is it a bug or do I miss something?

**Comment by jdepriest** [comment]
@C-Duv. I'm having the same issue. A workaround I found (not a fix) is to set data-background-transition="slide" for the slide(s) in question. The weird ghosting/merge seems to happen with the "fade" background transition.
