### ISSUE TITLE
Problem with links in PDF export

### ISSUE THREAD

**Issue by ggarnier** [hakimel/reveal.js#1283]
When I export a presentation to PDF, every link is shown as `text (URL)`. For example, I have this link in a slide:

    <a href="http://blog.guilhermegarnier.com">my blog</a>

In PDF, it becomes this:

    my blog (http://blog.guilhermegarnier.com)

I'm using reveal.js 3.1.0

**Comment by scor** [comment]
I also have problems with links in the PDF export, though it appears to be more like a browser issue. For example going to http://lab.hakim.se/reveal-js/?print-pdf#/ and scrolling to one of the first links (slides.com or zoom.js), you will see that you cannot click on the links in your browser (chrome 45.0.2454.101). I suspect this is why the links are not working in the PDF export either.

**Comment by ggarnier** [comment]
I just tried again in the latest Chome version (46.0.2490.80), and it worked!

**Comment by 7Moses** [comment]
Chrome Version 61.0.3163.100 (Official Build)
My Links are working fine in Chrome, the print to PDF is working great, I print to Evernote and tested on all the other options. My Links in the PDF are not working, any further guidance welcome,  

p.s. [This is how I am doing the Link](http://example.net/)

**Comment by elouet** [comment]
I'm seeing this also, links are not passed on the PDF file, which disapointing. Using Chrome  72.0.3626.119.

On the browser page links are also not working if you add the print-pdf item. I find it very difficult to debug this because for some reason you can't "inspect element" to check the CSS on the link.

**Comment by elouet** [comment]
I found that this only happens where printing 2 slides per page !
