### ISSUE TITLE
Ability to align to edge of screen

### ISSUE THREAD

**Issue by cfjedimaster** [hakimel/reveal.js#1284]
I know this is *possible*, but it would be nice if it were *easier* to align text/etc to the edges of the current slide. I have an image I'm using a background and I want to place a credit link on the bottom left hand corner of the screen. I've tried even using absolute positioning, like so:

				<section data-background="img/analytics.jpg">
					<h1>Analytics</h1>
					<p style="font-style:italic;align:bottom;position:absolute;left:0">
						<a href="https://flic.kr/p/d9KiHk">Image Credit: Today's latte, Google Analytics.</a>
					</p>
				</section>

And it still doesn't go to the left of the current screen. I'm sure it is my fault, but again, it seems like this could be easier.

**Comment by demoneaux** [comment]
Couldn’t this be done with `text-align: left`?
