### ISSUE TITLE
zomm - set "z" as a shortcut for zooming to the center of slide

### ISSUE THREAD

**Issue by arnaldorusso** [hakimel/reveal.js#1285]
Hi there,

First of all, thank you so much for sharing this fantastic tool for awesome presentations.

Iwas wondering on how change the zoom shortcut while presenting.
Is it possible to include a zoom in the center of slide (or in the figure, if it is present) just pressing the "z" key?

Cheers,
Arnaldo.

**Comment by hakimel** [comment]
Hey, this isn't something that reveal.js supports so you'd need to write custom code to achieve it.
