### ISSUE TITLE
Overview Transitions: are they available?

### ISSUE THREAD

**Issue by hityr5yr** [hakimel/reveal.js#1286]
I wandered why there is no transition on activating overview and I intended to suggest it as a feature. But then I saw that except for desktop and mobile Safari it is supposed to be available (looking into overviewTransitions and activateOverview). I checked it with Google Chrome and Firefox. So is it a bug or something that is not envisaged or I am just missing something?

Thank you.

Peter

**Comment by hakimel** [comment]
Those transitions were intentionally removed because they had too many issues.
