### ISSUE TITLE
highlight.js background color is overriden

### ISSUE THREAD

**Issue by shmerl** [hakimel/reveal.js#1290]
In current themes in reveal.js you can't control the background color of the code block. I.e. switching the theme for highlight.js doesn't change the background color. It can be enabled by commenting out explicit coloring in the theme styles. Example for night.css:

    .reveal pre code {
      display: block;
      padding: 5px;
      overflow: auto;
      max-height: 400px;
      word-wrap: normal;
    /*  background: #3F3F3F;
      color: #DCDCDC; */ }

Is it intended or it's some omission? Leaving background color up to the highlight.js theme gives it more flexibility.

**Comment by Delapouite** [comment]
I agree, these values should not be forced. Either by letting highlight.js do the job or at least offers vars to tweak the colors : https://github.com/hakimel/reveal.js/pull/1135/files

**Comment by hakimel** [comment]
Those styles have been removed.
