### ISSUE TITLE
Using reveal.js as a dashboard with Twitter's Bootstrap and Google Charts

### ISSUE THREAD

**Issue by Khrysller** [hakimel/reveal.js#1293]
Hi. I am new to this and after reading and seeing some examples I am not sure if I can do what I am trying to do. I am building a dashboard and reveal.js looks great for the navigation part, but for the content, i am not sure yet.

I will be using Twitter's Bootstrap + Google Charts and reveal.js to auto slide between pages and stop after the user start moving the mouse.

For example, inside a bootstrap panel I will the showing this google chart: https://jsfiddle.net/2368v4w4/

I have it all done, using clickable links to navigate,

Can someone tells me if this is possible? Thanks

**Comment by waywaaard** [comment]
It is working, however do you need to reoverwrite some of the bootstrap css rules.

**Comment by demoneaux** [comment]
Not too sure whether it can be done, reveal.js is more for presentations. Feel free to try though :)
