### ISSUE TITLE
Hosting reveal.js slideshow from an aws s3 bucket

### ISSUE THREAD

**Issue by JohnGriffiths** [hakimel/reveal.js#1296]
Dear Hakimel,

I would like to host reveal.js slideshows from an amazon S3 bucket. However when I try uploading the files and navigating to the links (as well as adding a reveal.js folder to the bucket), the pages still do not render as expected. 

Could you please if possible spell out the process of hosting a reveal.js slideshow from an s3 bucket?

Thanks very much,

j

**Comment by anantshri** [comment]
Hi @JohnGriffiths if you have a publically hosted version it would be easy for folks to help you out here.

-Anant

**Comment by demoneaux** [comment]
I'm not too sure as I personally don't use S3, but uploading the static files should be enough.
