### ISSUE TITLE
If I only use markdown, highlight.js won't work

### ISSUE THREAD

**Issue by zhongdian121** [hakimel/reveal.js#1297]
If there are no <pre><code></code></pre> block, highlight won't load. Maybe here you could make a improvement.

**Comment by hakimel** [comment]
You'll need to use backticks to delimit code blocks rather than pre or code tags. Here's a working example: http://lab.hakim.se/reveal-js/#/6

Source:
```html
<section data-markdown>
	<script type="text/template">
		## Markdown support

		Write content using inline or external Markdown.
		Instructions and more info available in the [readme](https://github.com/hakimel/reveal.js#markdown).

		```
		<section data-markdown>
		  ## Markdown support

		  Write content using inline or external Markdown.
		  Instructions and more info available in the [readme](https://github.com/hakimel/reveal.js#markdown).
		</section>
		```
	</script>
</section>
```

**Comment by JohannesHoppe** [comment]
This is because of
```js
//index.html
{ src: 'plugin/highlight/highlight.js', async: true, condition: function() { return !!document.querySelector( 'pre code' ); }, callback: function() { hljs.initHighlightingOnLoad(); } },
```

Pure Code blocks in data-markdown are not satisfying this condition.
Change it to:

```js
//index.html
{ src: 'plugin/highlight/highlight.js', async: true, callback: function() { hljs.initHighlightingOnLoad(); } },
```
