### ISSUE TITLE
Project structure

### ISSUE THREAD

**Issue by janniklorenz** [hakimel/reveal.js#1298]
I think the current structure of the reveal.js framework is a bit against the nodejs philosophy of modules. Some features as markdown slides simply should not be in the core of reveal.js, which is responsible for managing the slides.

So I would suggest to move all functionality, which isn’t part of the core out, and build modules, which provide HTML and LESS for the slides, which will only affect the HTML of the current module.

Her is a very basic implementation of this idea (https://github.com/LarveSpeer/LarveSpeer), which has not yet the full API for the modules.
The presentation content is located in a separated folder, which contains a config.js file, to link all slide paths.

**Comment by demoneaux** [comment]
@hakimel any opinions on the current project structure?

**Comment by demoneaux** [comment]
I feel that the current structure is fine, with only the core code and a few plugins. Closing for now.
