### ISSUE TITLE
Dynamically show/hide slides

### ISSUE THREAD

**Issue by mattkholland** [hakimel/reveal.js#1301]
Hello – 

Wondering if there is a way to dynamically show/hide slides with a certain class? For example, my deck might have 5 blue slides and 5 red slides. Is there a way that I can ONLY display the red or blue slides? 

Thanks very much

**Comment by hakimel** [comment]
You'll need to use JS to add/remove the slides from the DOM. After adding or removing slides you can call `Reveal.sync()` to refresh the navigation etc.

**Comment by Frazer** [comment]
if I add slides dynamically, and dont run Reveal.sync()  the visible arrow navigation wont be darkened if slides appear to the right, and pushing 'o' for slideOverview will be focussed on the wrong slide if there are slides added to the left, but other than that, it seems to work fine.


 when I call Reveal.sync()  after each update - all the navigation works perfectly, but I see a ghosting effect of slides being overlaid on top of each other.

![screen shot 2017-02-05 at 21 19 49](https://cloud.githubusercontent.com/assets/374464/22629604/3d0dded2-ebe9-11e6-87fa-759b58484f07.png)
