### ISSUE TITLE
Presentation size not working

### ISSUE THREAD

**Issue by hohwille** [hakimel/reveal.js#1306]
https://github.com/hakimel/reveal.js#presentation-size

I tried with width and height set to 100 or to 2000 with no difference at all.
My slides do not fit on the screen if resolution is below 1280x1024.

**Comment by Arnaud-D** [comment]
Same here... I can't change it, and need to stick to the initial configuration.

**Comment by hakimel** [comment]
You can test this to see how it works on the demo presentation. For example:

http://lab.hakim.se/reveal-js/?width=500
http://lab.hakim.se/reveal-js/?width=1500&height=1500

Regardless of the specified width/height the presentation should always scale to fit the display (the above links do). The width and height config values represent the original resolution before any scaling is applied. Scaling can be controlled via the `minScale` and `maxScale` configuration options.

If you've got a presentation that's not scaling down correctly please include a link to it and I'll check out what might be wrong.
