### ISSUE TITLE
markdown plugin conflicts with math plugin

### ISSUE THREAD

**Issue by zoof** [hakimel/reveal.js#1307]
I've been wrestling with figuring out why my markdown tables were not showing up in my slides.  I finally discovered that the problem was the math plugin which I have been using.  Once I commented out the lines that enabled the math plugin, my table shows fine.

**Comment by zoof** [comment]
It seems that I enabled the math plugin incorrectly.  Nevertheless, I'm finding that the math sometimes renders correctly and sometimes not:

    <section data-markdown data-separator="^\n---\n$" data-separator-vertical="^\n--\n$">
        <script type="text/template">
    * $J$ xyz
    $\{\mu_w(j),\mu_\xi(j),\pi_j\}_{j=1}^J$
    * $\xi\sim N(\mu_\xi(j),\sigma_\xi)$
        </script>
    </section>

**Comment by rajgoel** [comment]
It looks like your problem is the same as this: #702 for which there is a fix in the recent dev-branch #1205.

**Comment by zoof** [comment]
So if I

**Comment by zoof** [comment]
So if I `git pull`, I should have the development version?

**Comment by zoof** [comment]
Nevermind -- I downloaded the dev zip file. Unfortunately, the fix does not work for the sample markdown I've included above.

**Comment by waywaaard** [comment]
This is a markdown specific error. It seems that some tex ist treated as markdown tags.

**Comment by gothma** [comment]
LaTeX formula has to be wrapped in backticks: ``` `$\sum_{m} \sum_{d}$` ``` If this is not the case formula displaying will only work *sometimes*.

@zoof: Does it work for you now?

**Comment by demoneaux** [comment]
Closing this for now since it seems that @gothma is right. Feel free to reopen if you encounter other issues.
