### ISSUE TITLE
Make section height consistent between slides

### ISSUE THREAD

**Issue by vitaut** [hakimel/reveal.js#1312]
Currently only the section width is the same between slides while the height varies depending on the content, for example:
![screenshot from 2015-07-23 11 28 56](https://cloud.githubusercontent.com/assets/576385/8858778/39fa0c6a-312e-11e5-85d1-5df52a7e2be1.png)

Is it possible to fix section height so that the title appeared at the same vertical position when changing slides and only the content was aligned vertically? Here's an example from Beamer that does exactly this:

![1280px-a_modified_latex_beamer_example](https://cloud.githubusercontent.com/assets/576385/8858910/1568bb02-312f-11e5-8722-64e40d5ce4db.jpg)

**Comment by rofrol** [comment]
My solution https://github.com/hakimel/reveal.js/issues/180#issuecomment-173543708

**Comment by vitaut** [comment]
Thanks, @rofrol, I'll check it out.

**Comment by vitaut** [comment]
@rofrol, This somewhat helps but because the content of each slide is center-justified the result remains pretty much the same:
![screenshot from 2016-01-24 13 55 53](https://cloud.githubusercontent.com/assets/576385/12539217/3bf4d864-c2a2-11e5-9001-69113ba0382f.png)
and it has interferes with navigation, for example when switching to the next slide the content of the previous one briefly aligns to the top before disappearing.

**Comment by rofrol** [comment]
Just add styles for h2 also. Check this example https://rawgit.com/rofrol/reveal.js/master/index.html.

Does it work for you?

**Comment by vitaut** [comment]
Thanks, this mostly works although the problem with navigation is still there (the title realigns awkwardly before disappearing when you switch slides).

**Comment by rofrol** [comment]
strange. can you record some demo with sharex?

**Comment by vitaut** [comment]
No idea what sharex is, but I've created this screencast showing the issue: https://youtu.be/VB96r44ow9I . Notice the content of the slide jumping to the top during transitions.

**Comment by rofrol** [comment]
Try again the same url https://rawgit.com/rofrol/reveal.js/fixed_header/index.html

**Comment by vitaut** [comment]
Looks good, thanks!
