### ISSUE TITLE
Code formatting broken by otherwise legit code fragment.

### ISSUE THREAD

**Issue by sam-falvo** [hakimel/reveal.js#1313]
The following example does not properly format in reveal.js.  The only thing which formats correctly is "IO0", but after that, it's all free-flowed text again.

What it should look like:

testing

```
    IO0  ----o 1   7 o---- IO4
    IO1  ----o 2   8 o---- IO5
    IO2  ----o 3   9 o---- IO6
    IO3  ----o 4  10 o---- IO7
    GND  ----o 5  11 o---- GND
    3.3V ----o 6  12 o---- 3.3V
```

How I format it:

```
    testing

            IO0  ----o 1   7 o---- IO4
            IO1  ----o 2   8 o---- IO5
            IO2  ----o 3   9 o---- IO6
            IO3  ----o 4  10 o---- IO7
            GND  ----o 5  11 o---- GND
            3.3V ----o 6  12 o---- 3.3V
```

What I see:

testing
        IO0
  ----o 1   7 o---- IO4 IO1  ----o 2   8 o---- IO5 IO2  ----o 3   9 o---- IO6 IO3  ----o 4  10 o---- IO7 GND  ----o 5  11 o---- GND 3.3V ----o 6  12 o---- 3.3V

**Comment by demoneaux** [comment]
Hi @sam-falvo! I'm not too sure what's wrong with the formatting, this seems to be more of a marked issue than Reveal. Perhaps if you could create a reduced test case showing the problem, it might be easier to solve. Feel free to re-open with more information.

**Comment by sam-falvo** [comment]
The entire test case is less than 20 lines, and is in the bug report.  I do not understand your request for more information.  You could literally cut and paste the example provided.

**Comment by sam-falvo** [comment]
Never mind.  I'm disappointed that it took this long for someone to respond at all, much less pretty much just blow me off in the process.  I've decided to stop using reveal.js and am going back to PDF slide decks.

**Comment by demoneaux** [comment]
Hi @sam-falvo! Really sorry for the long response. I recently started contributing to the Reveal project, and wanted to help with the issues. I'm not too sure how you are formatting the Markdown code, which is why I asked for more information.

Are you doing something like:

```html
<section data-markdown>
testing

    IO0  ----o 1   7 o---- IO4
    IO1  ----o 2   8 o---- IO5
    IO2  ----o 3   9 o---- IO6
    IO3  ----o 4  10 o---- IO7
    GND  ----o 5  11 o---- GND
    3.3V ----o 6  12 o---- 3.3V
```

What does your "how I format it" mean? Is the whole chunk in a code block?
