### ISSUE TITLE
fragment auto-slide does not work as advertised

### ISSUE THREAD

**Issue by kklepper** [hakimel/reveal.js#1316]
I included this snippet from the readme into my version from May 21st:

    <section data-autoslide="2000">
        <p>After 2 seconds the first fragment will be shown.</p>
        <p class="fragment" data-autoslide="10000">After 10 seconds the next fragment will be shown.</p>
        <p class="fragment">Now, the fragment is displayed for 2 seconds before the next slide is shown.</p>
    </section>

Well, it slides all of them with 2000 milliseconds nevertheless. 

I put in 

    Reveal.configure({
      autoSlide: 5000
    });

and the animation knob was not shown.

So I refreshed to the latest version, and lo, everything worked as stated. But now, the text is moved to the left for half a screen on all slides, so half of the text is cut off to the left. 

Now what? Did I miss something?

**Comment by hakimel** [comment]
Can you upload the presentation somewhere and share a link? If everything is shifted half a screen to the left there's bound to be some error on the page.

**Comment by kklepper** [comment]
See http://voxx.biz/1504/

**Comment by hakimel** [comment]
When updating to the latest reveal.js it looks like you only updated the JavaScript file. You'll also need to update to the latest CSS styles, this is the file that's out of date: http://voxx.biz/styles/reveal.min.css.
