### ISSUE TITLE
Sections with id's not in all lower case break history functionality

### ISSUE THREAD

**Issue by gruber76** [hakimel/reveal.js#1319]
If a section has an id with one or more capital letters, the user cannot use the back button to return to that slide.

**Comment by gruber76** [comment]
I'm not sure if the "toLowerCase" call in `writeURL` was necessary for some functionality, but taking it out appears to fix this issue (and has the side effect of prettier URLs.)

**Comment by hakimel** [comment]
Fixed by @gruber76 in #1320
