### ISSUE TITLE
Multiple instances of Reveal

### ISSUE THREAD

**Issue by jeremiahmmv2** [hakimel/reveal.js#1321]
Is there a way of creating multiple Reveal instances on the same page?

Ideally, it would work like this:

```javascript
var firstInstance = new Reveal();
firstInstance.initialize({
  selector: '#reveal-1'
});

var secondInstance = new Reveal();
secondInstance.initialize({
  selector: '#reveal-2'
});
```

Is there any equivalent way of creating instances?

**Comment by hakimel** [comment]
Nope, that's not something we support.
