### ISSUE TITLE
Dynamically changing data-background

### ISSUE THREAD

**Issue by mandeeps708** [hakimel/reveal.js#1322]
Suppose I have a slide with multiple `<li>` items (with `fragment` class). Now what I want is when I navigate through the fragments on the same slide, the background should change after every fragment.
Is there any way out to achieve this?
Thank you.

**Comment by sprankhub** [comment]
You can give each `li` element another class name and then do something like this:

    Reveal.addEventListener('fragmentshown', function(e) {
        if (e.fragment.className.indexOf('another-background') > -1) {
            Reveal.getCurrentSlide().dataset.backgroundColor = '#fff';
            Reveal.sync();
        }
    }, false);
