### ISSUE TITLE
I have some trouble exporting to PDF

### ISSUE THREAD

**Issue by hanzichi** [hakimel/reveal.js#1323]
Dear friend, I have great interest in your perfect framework, I'd like to introduce it to my teammates, but now I have some trouble exporting to PDF. I have made a easy page, click [here](http://hanzichi.github.io/reveal/template.html#/), it's ok, but when I want it to export to PDF, I follow your advice and set the url to <http://hanzichi.github.io/reveal/template.html?print-pdf#/>, you see it not works quite well, I don't know why, and this is really important to me, I hope you can help me, with great thanks!

**Comment by waywaaard** [comment]
You have to open the print preview before you can see the final print version. Just open your presentation and add ```?print-pdf``` and then open the print dialog with ```Ctrl+P```.

![image](https://cloud.githubusercontent.com/assets/1634468/9149433/0d996ebc-3daa-11e5-85fb-ca9a8d6dfd8a.png)

**Comment by hanzichi** [comment]
Awesome ! It really works ! You really help me a lot ! Thanks a lot !
