### ISSUE TITLE
Allow display property of visible slide to be configured

### ISSUE THREAD

**Issue by mojavelinux** [hakimel/reveal.js#1324]
The flexbox model is a very useful way to layout slide content. However, at the moment, it's not possible to use the flexbox model for slides because reveal.js is explicitly setting the display CSS property on the current slide to "block". (See https://github.com/hakimel/reveal.js/blob/master/js/reveal.js#L2724).

Please allow the display property of the current slide to be configured so that other slide layouts can be used. In particular, allow the value to be "flex".

I propose the name `display` for this setting.

``` javascript
Reveal.initialize({
  display: 'flex',
  // ...
});
```

An alternative is to detect the original display value using `getComputedStyle` and reuse that value when setting the display CSS property to reveal the current slide.

**Comment by hakimel** [comment]
See #1325
