### ISSUE TITLE
Highlight/animate controls to show next slide

### ISSUE THREAD

**Issue by cavie78** [hakimel/reveal.js#1332]
To make it easier for users to know which slide to view next I'd like to highlight or use animation on the control which points to the next slide (be that right or down). My presentation runs left to right but occasionally has 'further information' slides which go down. While the user is free to navigate how they please, I'd like to make it more obvious which path they need to follow to see all slides in the deck.

**Comment by demoneaux** [comment]
Currently there are slight changes to the controls to indicate that there are slides at the bottom/side. If you want your own indicators, feel free to implement them in a plugin.

**Comment by cavie78** [comment]
"Currently there are slight changes to the controls to indicate that there are slides at the bottom/side."

No there aren't

"If you want your own indicators, feel free to implement them in a plugin."

Ace. Presumably you are going to close all enhancement requests with the same response? "do it yourself"

**Comment by demoneaux** [comment]
> "Currently there are slight changes to the controls to indicate that there are slides at the bottom/side."  
No there aren't

If you take a look at http://lab.hakim.se/reveal-js/, as you scroll through the slides, the controls light up when there are vertical slides.

> "If you want your own indicators, feel free to implement them in a plugin."  
Ace. Presumably you are going to close all enhancement requests with the same response? "do it yourself"

Currently there are over 150 open issues in reveal.js, most of which are feature requests
 It would be difficult to implement all features requested while we only have limited time to maintain this open source project. Thus I think looking for plugins/creating your own plugin for a specific feature which is outside the core usage is fine.
