### ISSUE TITLE
Feature request: Possibilty to mark last slide

### ISSUE THREAD

**Issue by sjoerd222888** [hakimel/reveal.js#1341]
I have some extra backup slides in my presentation that I add in the end. I have a slide that is the last slide in the presentation (if I do not use the backup slide) and I would like to mark it as the last slide such that the progress bar at the bottom is just filled when that slide is reached. The progress bar should remain filled when going through backup slides.

I think backup slides are a common scenario where you prepare some extra slides in case there is time left or for some special question from the audience.

**Comment by demoneaux** [comment]
@hakimel What do you think? IMO this use case shouldn’t be happening a lot, so I would be fine not implementing this. Additionally, a different progress bar can also be implemented simply using the `slidechanged` event.

**Comment by hakimel** [comment]
@demoneaux I agree this is not something we need to add to the framework. If the progress bar not filling entirely is distracting, you can turn it off using `progress: false` in your reveal.js config.

**Comment by zenzike** [comment]
I happen to also think that this would be a useful feature: backup slides are common in live presentations. The progress bar is useful to help the audience know what to expect in terms of material in the talk, so having it present is good even when there are backup slides that should not count towards progress.

**Comment by zenzike** [comment]
For what it's worth, this can be achieved by making the backup slides part of the stack class. For instance:

    <section id="appendix" class="stack"> ... </section>
