### ISSUE TITLE
Feature request: WebGL embedded ie Blend4Web

### ISSUE THREAD

**Issue by drewpotter** [hakimel/reveal.js#1343]
Hey, thanks for making such a cool library!

I was wondering, would it be possible to embed WebGL or Blend4Web https://www.blend4web.com/en/ interactions inside a slide? That would be really awesome.

Thanks,

Drew

**Comment by drewpotter** [comment]
Ok. So you can simply use an iframe to do this :-)

**Comment by demoneaux** [comment]
I think this issue can be closed as iframes can be used and it shouldn't require anything from Reveal.js’ side.

**Comment by hakimel** [comment]
Thanks @demoneaux
