### ISSUE TITLE
Error when running #grunt serve# on OS X

### ISSUE THREAD

**Issue by rkrug** [hakimel/reveal.js#1344]
Hi

I am on OS X Yosemite and I am using homebrew.

I used the following to install the local web server:

    brew install node
    brew install libsass
    npm install -g grunt-cli  
    cd ~/.emacs.d/
    git clone https://github.com/hakimel/reveal.js.git
    cd reveal.js
    npm install

When I now run

    09:52:46 (master) ~/.emacs.d/reveal.js$ grunt serve
    Loading "sass.js" tasks...ERROR
    >> Error: `libsass` bindings not found. Try reinstalling `node-sass`?
    
    Running "connect:server" (connect) task
    Started connect web server on http://0.0.0.0:8000
    
    Running "watch" task 
    Waiting...

Even 
    npm install -g node-sass

does not solve the error message. Nevertheless, I can see the presentation on ```localhost:8000```

Any suggestions, or can I just ignore this error?

Thanks,

Rainer

**Comment by verdurin** [comment]
@rkrug : while I can't help with your actual problem, I can't even get past the `npm install` part, without lots of errors and the build failing. Could you let me know which versions you're using?

**Comment by jgkite** [comment]
@verdurin I had the same problem (assuming we were seeing the same failures). #1351 fixes the issue for me.

**Comment by demoneaux** [comment]
Closed as #1351 was fixed.
