### ISSUE TITLE
Feature request : zoom gesture on tablet

### ISSUE THREAD

**Issue by Desiderius77** [hakimel/reveal.js#1350]
I have tried reveal.js on a tablet.

It works perfectly and swipe is very easy to change slide.

but when I tried to zoom with the traditional gesture with two fingers it did not work !

It would be a great feature to add for mobile phone or tablet

**Comment by hakimel** [comment]
Pinch-to-zoom support was added in 10e44aabfcaba104ab52bdc11f2f6963155cdea4
