### ISSUE TITLE
Use fragment to manipulate class

### ISSUE THREAD

**Issue by arximboldi** [hakimel/reveal.js#1355]
Hi!

I would like to use fragments to manipulate the class of an element. This way, I can simply make an animation by using CSS instead of resorting to D3 and other stuff I don't understand.

- Is there anything like this supported in the library or a plugin?
- Is there any workaround, even it it's an ugly hack?

Thanks a lot!

JP

**Comment by demoneaux** [comment]
Fragments will have the class `.visible`, and the class `.current-fragment` when they are the active fragment. You can also use the `fragmentshown` and `fragmenthidden` event.
