### ISSUE TITLE
How to slide upwards?

### ISSUE THREAD

**Issue by mschroen** [hakimel/reveal.js#1364]
It is possible to slide downwards into the second dimension of slides, which is a very cool feature. But is it possible to slide upwards, too? I.e, to give one of the sub-`<section>`-elements a "main level" flag?

I need it together with the parallax background, having the main slide level in the vertical center of the background, and beeing able to view the upper and lower part of the image through sliding.

Please see this question on stackoverflow for details, which is unanswered for almost 2 weeks now: http://stackoverflow.com/questions/32619528/how-to-slide-upwards-with-reveal-js

**Comment by dvenkatsagar** [comment]
I checked stackoverflow question.
It is possible to do it in javascript(check the API and slidechanged event section of reveal).
It goes something like this(partial solution):  
```javascript
Reveal.addEventListener( 'slidechanged', function( event ) {
    // event.previousSlide, event.currentSlide, event.indexh, event.indexv
    if (event.indexh == 0 && event.indexv==0){
}
} );
```
