### ISSUE TITLE
Attributes get `=""` added

### ISSUE THREAD

**Issue by mhartington** [hakimel/reveal.js#1367]
With the following code block

```
<pre><code data-trim class="html">
<div button></div>
</code></pre
```
The rendered output shows

```
<div button=""></div>
```

The extra `=` and `""` should not be added.

**Comment by Delapouite** [comment]
I guess this is more an issue for highlight.js.

**Comment by demoneaux** [comment]
This is because your code block is not escaped. The browser interprets the `button` attribute as `""`, then highlight.js highlights the whole code. To prevent this, escape all HTML code properly.
