### ISSUE TITLE
Feature request/plugin : Integrating chartjs and revealjs

### ISSUE THREAD

**Issue by dvenkatsagar** [hakimel/reveal.js#1370]
@hakimel 
I have been trying to integrate chartjs with revealjs as a plugin. But I am having problem to bring the canvas tag to be displayed in the reveal slide. It always shows its width and height as 0 and even though I try to change it in the css or javascript, it gets overridden. I need help to figure out how to increase the canvas size so that it could display the charts.

P.S i have forked the project and created a feature branch for it. I will transfer it to a separate repository after this thing works out. 

Update:

Ok, I was able find a work around for that issue... What I did was insert a iframe instead and then write the canvas tag in that iframe and get the result. But I still am trying to figure out how to directly embed the chart canvas in the \<section\> rather than using the iframe method.

**Comment by dvenkatsagar** [comment]
Update 2:
Well i was able to make a plugin with the iframe as the bases. 
Just check this out : 
https://github.com/dvenkatsagar/reveal-chart

Tested it on firefox and chrome but not on IE

**Comment by demoneaux** [comment]
Thanks for creating the plugin! Closing this for now.
