### ISSUE TITLE
Markdown tables work with inline markdown, but doesn't work with external markdown

### ISSUE THREAD

**Issue by bamos** [hakimel/reveal.js#1372]
# Inline

```HTML
            <div class="slides">
                <section data-markdown>
                    <script type="text/template">
|h1|h2|
|--|--|
|a|b|
                    </script>
                </section>
            </div>
```

![image](https://cloud.githubusercontent.com/assets/707462/10116975/5e65adf2-6414-11e5-99a9-523453faccd1.png)

# External

```HTML
            <div class="slides">
                <section data-markdown="content.md"
                         data-separator="---"
                         data-separator-vertical="--"
                         data-separator-notes="^Note:"
                         data-charset="iso-8859-15">
                </section>
            </div>
```

![image](https://cloud.githubusercontent.com/assets/707462/10116972/42096f2c-6414-11e5-9a96-66f8e8071bca.png)

**Comment by bamos** [comment]
Sorry, this may be a non-issue. Tables with external markdown is now working for me and I'm not sure what I changed.

**Comment by britter** [comment]
I'm seeing the same problem. Tables in external markdown don't work for me.

**Comment by britter** [comment]
Found the problem. I had the `data-separator="---"`. This caused problems with the table header row. Changing it to `data-separator="^---$"` did the trick for me.
