### ISSUE TITLE
Keyboard shortcut documentation

### ISSUE THREAD

**Issue by jere19** [hakimel/reveal.js#1373]
Hello,
I'm trying to modify the keyboard shortcuts to match my (cheap) remote/pointer.
I found the correct syntax on the wiki but it's currently missing informations:
- keycode are the javascript ones (took me a while to figure it)
- what are the shortcuts target names beside the few examples on the current wiki page? (I found 'prev' and 'next' but what is it for pause or fullscreen?)

**Comment by Delapouite** [comment]
Does this section of the code answer your problem?
https://github.com/hakimel/reveal.js/blob/master/js/reveal.js#L3807

**Comment by jere19** [comment]
Unfortunately not. The base problem might be my lack of knowledge of javascript, but i think it might be worth a better explanation for newbs like me.

Currently in my Reveal.initialize i have this:
```javascript
keyboard: {
	75: Reveal.toggleFullscreen() {},
	38: 'prev',
	40: 'next'
},
```
I tried also with `'toggleFullscreen'` without more success in binding 'k' to fullscreen mode.

I couldn't find where the aliases  `'next'` and `'prev'` were defined  (for `navigateNext()` and `navigatePrev()` i assume given the part of the code you pointed me to).

**Comment by demoneaux** [comment]
Please take a look at the docs at https://github.com/hakimel/reveal.js#keyboard-bindings. You can pass a function `Reveal.toggleFullscreen`. Alternatively paying in a string will call the function on `Reveal`, so you can pass in the string `'toggleFullscreen'` as well.
