### ISSUE TITLE
Accessing the dependency variables

### ISSUE THREAD

**Issue by dvenkatsagar** [hakimel/reveal.js#1378]
Ok, I have been fiddling around with the dependencies of Revealjs.
The problem that I'm facing is that, when I load a dependency or plugin and I want to access the variables of it,  It shows undefined in the console when loading the page.

I am loading the dependency/plugin synchronously but still doesnt work. 

The only work around that I found is to set a Timeout function and wait for it to load.

Here the sample code:
```javascript
Reveal.initialize({
  dependencies : [
    {src: 'plugin.js'} // The plugin to load which contains a global variable X;
  ]
});

console.log(window.X); // gives undefined;
setTimeout(function(){
  console.log(window.X); // Now works
},1000);
```

I trying to find out if there are any other solutions that are better than this. 
Appreciate the help.
Thank you

**Comment by demoneaux** [comment]
This is because it is loaded separately in the event loop. I think if you shift the remainder of code to the next `script` element it should be Able to work.

```js
<script>
Reveal.initialize({ ...});
</script>
<script src="abc.js"></script>
