### ISSUE TITLE
Setting keyboard: false does not disable the s key

### ISSUE THREAD

**Issue by TimeTravelersHackedMe** [hakimel/reveal.js#1379]
I am using the keyboard for another JS library but RevealJS fails to disable the s key when the keyboard: false setting is used. Any reason why?

**Comment by rohithpr** [comment]
Hi, I'm new to this project. I thought of taking up this issue. I've found the function 'onDocumentKeyDown' but it doesn't seem to be responsible for the 's' key. Could an admin please point me in the right direction?

**Comment by eirism** [comment]
I belive it is the notes plugin which prevents this, https://github.com/hakimel/reveal.js/blob/master/plugin/notes/notes.js#L109. It does always add an keyDown eventlistener, regardless of the keyboard config flag.

**Comment by rohithpr** [comment]
Thank you! I'll fix it.
