### ISSUE TITLE
Problem with vertical alignment in a table row with rowspan

### ISSUE THREAD

**Issue by curioustolearn** [hakimel/reveal.js#138]
The following html code produces the expected output in a barebones html file. However, when I use it my html presentation file (which is using reveal.js). 'Player 1' does not align vertically in the center.

```
    <table>
        <thead>
            <tr>
                <th></th>
                <th></th>
                <th colspan="3" align="center">Player 2</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td rowspan="3" align="center" valign="middle">Player 1</td>
                <td></td>
                <td>U</td>
                <td>U</td>
                <td>U</td>
            </tr>
            <tr>
                <td></td>
                <td>U</td>
                <td>U</td>
                <td>U</td>
            </tr>
            <tr>
                <td></td>
                <td>U</td>
                <td>U</td>
                <td>U</td>
            </tr>               
        </tbody>
    </table>
```

**Comment by wirepatch** [comment]
I disagree this being a very  limited use case. Effectively using `<td>` fields spanning multiple rows does not seem to work at all. Consider the following sample:

```html
<table>
  <tr>
    <td>Row 1</td>
    <td rowspan="2">
      <ul>
        <li>Test 1</li>
        <li>Test 2</li>
      </ul>
    </td>
  </tr>
  <tr>
    <td>Row 2</td>
  </tr>
</table>
```
This perfectly valid HTML [renders as expected](https://cloud.mi.hdm-stuttgart.de/owncloud/index.php/s/6IeVEAOx0WcpY9t) unless becoming part of a reveal.js presentation. The latter exhibits the `<ul>` being aligned solely to the first row no matter how many `<li>` entries are being added, see [rendered version](https://cloud.mi.hdm-stuttgart.de/owncloud/index.php/s/3SUAh720ib4DsJT).

**Comment by peteruhnak** [comment]
I just ran into this same issue.

It seems that the problem is setting `vertical-align: baseline` for all elements ( https://github.com/hakimel/reveal.js/blob/master/css/reveal.scss#L32 )

see comparison https://jsfiddle.net/6zeapfut/
