### ISSUE TITLE
Using slide seperator in code tags

### ISSUE THREAD

**Issue by Bmandk** [hakimel/reveal.js#1380]
What I'm essentially trying to do is make a small guide of how to use Markdown for Reveal.js, using Reveal.js. The problem is that when I'm trying to show the user how to make a new slide in a code tag, it won't escape the seperator.

**Comment by demoneaux** [comment]
You can use a `<textarea data-template>` instead, as mentioned here: https://github.com/hakimel/reveal.js#markdown
