### ISSUE TITLE
bower.json corrupt ?

### ISSUE THREAD

**Issue by wzr1337** [hakimel/reveal.js#1384]
Hi,

I get the following output on 

    $ bower install reveal.js#3.1.0

    bower reveal.js#3.1.0       not-cached git://github.com/hakimel/reveal.js.git#3.1.0
    bower reveal.js#3.1.0          resolve git://github.com/hakimel/reveal.js.git#3.1.0
    bower reveal.js#3.1.0         download https://github.com/hakimel/reveal.js/archive/3.1.0.tar.gz
    bower reveal.js#3.1.0         progress received 1.2MB of 1.5MB downloaded, 77%
    bower reveal.js#3.1.0         progress received 1.4MB of 1.5MB downloaded, 94%
    bower reveal.js#3.1.0          extract archive.tar.gz
    bower reveal.js#3.1.0     invalid-meta reveal.js is missing "main" entry in bower.json
    bower reveal.js#3.1.0     invalid-meta reveal.js is missing "ignore" entry in bower.json
    bower reveal.js#3.1.0         resolved git://github.com/hakimel/reveal.js.git#3.1.0
    bower reveal.js#3.1.0          install reveal.js#3.1.0

**Comment by eirism** [comment]
From what I can see the bower.json were added after the 3.1.0 release. Thus bower is downloading a version that is missing bower.json, and warns you that it can't find such a file.

**Comment by hakimel** [comment]
That's right – the bower.json manifest was just added. I just released 3.2.0 and bower install should work from this release.
