### ISSUE TITLE
table of contents

### ISSUE THREAD

**Issue by ducin** [hakimel/reveal.js#1389]
First of all, @hakimel, many thanks for your work. I do use slides.com a lot!

I can see that the readme.md file has lots of valuable content, but it is a little difficult to look through (due to its size and complexity). My suggestion is to introduce the **table of contents** just like the ones I did [here](https://github.com/json-schema-faker/json-schema-faker) and [here](https://github.com/swagger-api/swagger-codegen#table-of-contents).

But before I do that I'd like to know whether you're interested in having such thing. It's only aim is to improve readibility of the readme.

**Comment by demoneaux** [comment]
@hakimel what do you think about this? I can send in a PR for this if you’re fine :)

**Comment by hakimel** [comment]
I agree the readme is getting a bit unwieldy. I'm all for adding a TOC.

**Comment by ducin** [comment]
I'm happy to create such table of contents. But I need you to accept it soon (otherwise it'll get outdated and might become useless at some point). Been waiting few moths for this reply :P. Hm?

**Comment by demoneaux** [comment]
@ducin Feel free to send in a PR. We’ll try to merge it ASAP :)

**Comment by demoneaux** [comment]
Closed by #1545.
