### ISSUE TITLE
README does not provide full list of transitions

### ISSUE THREAD

**Issue by adunning** [hakimel/reveal.js#1390]
There are references to page and cube transitions later in the document, but the only transition styles listed as configuration options are `none/fade/slide/convex/concave/zoom`.

**Comment by hakimel** [comment]
The page and cube transitions used to be in the readme but have since been deprecated due to how inflexible they were. They're still in the CSS for backwards compatibility though.

**Comment by adunning** [comment]
Thanks; I hadn't realized this. There is still one reference to the removed transitions: is this intentional?

**Comment by hakimel** [comment]
That was unintentional – just removed it in 35462a424c4899747aa2079101372c66ac14d211.

**Comment by adunning** [comment]
Great; thank you!
