### ISSUE TITLE
Several lists are not left aligned if code block is between them

### ISSUE THREAD

**Issue by knl** [hakimel/reveal.js#1396]
Hi all,

I'm running into this problem that lists on a slide are not left aligned. This happens is two lists are interrupted with a code block or an image. I can't find anything in the CSS files that would imply this behaviour, and I tried white and simple themes.

<img width="1538" alt="a slide" src="https://cloud.githubusercontent.com/assets/361496/10461921/01d8c8aa-71dc-11e5-9bef-5ee650367f49.png">

**Comment by demoneaux** [comment]
By default, Reveal.js centres all slides. This can be disabled using `Reveal.configure({ 'center': false })`.
