### ISSUE TITLE
latex instead of mathjax

### ISSUE THREAD

**Issue by DJJ88** [hakimel/reveal.js#1397]
Hello I was wondering if it was possible to use latex instead of mathjax?
Compared to latex mathjax is super fast but I guess some people would be ready to trade speed for latex flexibility. For example I'm thinking about packaged like tikz that cannot be used direclty.

**Comment by waywaaard** [comment]
By using LaTeX you mean prerendering the LaTeX on the serverside or during development?

And what kind of "LaTeX" do you compare with MathJax as MathJax implements LaTeX in JavaScript and renders on the client side.

**Comment by DJJ88** [comment]
We won't need any server for this purpose. As far as I understood we can use MathJax locally as well. So instead of using MathJax, latex would be used instead. 
Let's say that you want to use [tikz] (http://pgf.sourceforge.net/) or some other package that have not been implemented by MathJax yet. I refer you to this issue on [MathJax] (https://github.com/mathjax/MathJax/issues/41)

**Comment by Sgiath** [comment]
And what about [KaTeX](https://github.com/Khan/KaTeX)? This seems to be the best solution for this ;)

**Comment by waywaaard** [comment]
Well you would need to write a custom build step that crawls through the slides and render and replaces the LaTeX snippets in there. Then you would need to place the graphics somewhere etc.

KaTeX aswell as MathJax allow calling them server side but I think that is not what @DJJ88 wants to do. KaTeX still supports only a subset of MathJax. I am using it without any reveal.js math plugin only using the KaTeX.contrib loader.

**Comment by demoneaux** [comment]
Where’s also a KaTeX plugin for Reveal.js at https://github.com/j13z/reveal.js-math-katex-plugin.
