### ISSUE TITLE
The remote plugin can not work

### ISSUE THREAD

**Issue by lilijreey** [hakimel/reveal.js#1404]
Hi, i add the {src 'plugin/remotes/remotes/js, async:true}, in dependencies
then grunt serve.
the node server run on my PC 192.168.1.1, open chromium visit slide,
then i use a android phone visit the 192.168.1.1 want to control the PC slide, but just show slide can not control.
Please help me thanks :)

**Comment by hakimel** [comment]
Hey, sorry but the site that was powering this plugin was taken down bu the original author. I've removed the remotes plugin from reveal.js now since it's no longer working.
