### ISSUE TITLE
Enhancement: add MarkDeep support?

### ISSUE THREAD

**Issue by krimple** [hakimel/reveal.js#1406]
This would absolutely make the markdown support sing - implementing MarkDeep diagrams.
Diagrams in ascii art -> images - joy!
See http://casual-effects.com/markdeep/

**Comment by anttivs** [comment]
Came here just to submit exactly this same feature request. The diagram support would be just made for slides.

**Comment by 3lnc** [comment]
+1
simple svg should be great

**Comment by pplux** [comment]
+1 I've tried to include markdeep in reveal.js, it basically works but images are too small, and the default theme is black and all lines are traced in black.

**Comment by demoneaux** [comment]
This will probably not land in the core Reveal.js repository, as it is too specialised. However, feel free to [create a plugin](https://github.com/hakimel/reveal.js/wiki/Plugins,-Tools-and-Hardware) for MarkDeep.

**Comment by aetherical** [comment]
I have a hack'd version which I used for a conference in January;  I'll look at cleaning it up to be a plugin.  However, if anyone's interested, they could build off, in the meantime, look at the gh-pages branch of https://github.com/aetherical/galloping_cuckoos
