### ISSUE TITLE
Material Design Lite break default transitions

### ISSUE THREAD

**Issue by chrjangit** [hakimel/reveal.js#1407]
I would like to use components from Google's frontend "Material Design Lite", but when I add these lines to the head of the reveal.js presentation, the transitions are always like "none":

    <link rel="stylesheet" href="https://storage.googleapis.com/code.getmdl.io/1.0.5/material.indigo-pink.min.css">
    <script src="https://storage.googleapis.com/code.getmdl.io/1.0.5/material.min.js"></script>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

When I delete the three lines, transitions "default" start to work again.

Is there anything I can do to get the nice default-transition also with "Material Design Lite"?

**Comment by Delapouite** [comment]
You encounter this issue because of this snippet in the material designe CSS :

```css
*[hidden] {
    display: none!important
}
```

Try to override it in your own stylesheet.

**Comment by beweisj** [comment]
for reference: 
```CSS
*[hidden] {
    display: initial !important;
}
```
after loading the material css and before reveal.css works for me.
