### ISSUE TITLE
White theme not change background color when fullscreen

### ISSUE THREAD

**Issue by Asoul** [hakimel/reveal.js#1408]
As title, I choose white.css as theme. It's not change background to white in fullscreen mode.

**Comment by jpletner** [comment]
Hello Asoul,

I had that same issue. It turned out to be a chrome bug. mplabs solution from issue 668 of adding html { background-color: inherit; } to the CSS file solved the problem for me: https://github.com/hakimel/reveal.js/issues/668

Good luck,

Jenny

**Comment by Asoul** [comment]
It works! Thanks a lot :)
