### ISSUE TITLE
Forcing slides in order

### ISSUE THREAD

**Issue by carmdq** [hakimel/reveal.js#1409]
Hi. Is it possible to force a certain order in the slides so the user can't go through them in any order when moving manually? That might imply 'locking' the controls so the arrows become active in the order the slides should play. Hope it makes any sense. Thanks.

**Comment by spidergears** [comment]
When moving manually the whole idea to give the user control over the order. I don't think that a good idea.

**Comment by demoneaux** [comment]
I think @spidergears is right, it doesn't make sense to lock users out of what they want to do.

**Comment by carmdq** [comment]
Actually, it does to me, since I wanted to use it to tell a story sequentially. The idea was to move through the slides while keeping a coherent flow for the story to make any sense.
