### ISSUE TITLE
Hash navigation should'nt be overwritten

### ISSUE THREAD

**Issue by teawithfruit** [hakimel/reveal.js#1417]
Hello,

Thank you for this great pice of code.

In an upcoming project I want to use hash driven navigation to switch between content. Reveal presentations should be one kind of content. Every kind of content should be reachable with a deeplink. At this point I got a problem with reveal.js.
If I open a presenation with one of this hashtag deeplinks, reveal is going to overwrite the url towards the hash.

How or is it possible, that reveal appends the url instead of overwriting it?

Thanks.

**Comment by ramezrafla** [comment]
// Push each slide change to the browser history
    history: false,

Did you read the docs?

**Comment by teawithfruit** [comment]
Yes. But if I do that, the deeplink to the presentation is completly hidden.
I want something like "http://www.website.com/#/thePresentation/1". But at this time reveal.js is changing the links to this "http://www.website.com/#/1".

**Comment by demoneaux** [comment]
This is currently not possible with Reveal, as it will try to search for an element with ID `thePresentation/1`. Instead of providing a deep linking structure, maybe you could use query parameters like `#/1?presentation`, which Reveal should not remove.

**Comment by mathiasmadsen** [comment]
The suggestion by @bnjmnt4n does not seem to work :/
