### ISSUE TITLE
Can't control presentation from speaker notes via notes-server plugin

### ISSUE THREAD

**Issue by thmzlt** [hakimel/reveal.js#1425]
When I launch a presentation (either client or server mode), and press the `S` key, I get the speaker notes view popup and I can control the presentation from there using the arrow keys.

When I open the speaker notes view from the "View slide notes at" console link, and I try to move between slides, the slide in the presentation does not update to match the slide in the speaker notes. This stops me from being able to control the presentation from speaker notes on a separate device.

Is this expected behavior or it should work and I'm doing something wrong?

**Comment by hakimel** [comment]
The server side speaker notes plugin wasn't built to sync both ways but I just added that. Changes inside of the speaker view will now reflect in the main presentation view. Only in the dev branch so far.

**Comment by thmzlt** [comment]
Thanks!

**Comment by harrycheng8** [comment]
#2831

**Comment by harrycheng8** [comment]
@harrycheng8
