### ISSUE TITLE
HighChart - reveal.js

### ISSUE THREAD

**Issue by ilpepe** [hakimel/reveal.js#1427]
Hi,
I truely like the software.

however i need to use different graphs.
I've gotten highchart to work (initiate the plot using the addEventListener).

However for now the plot starts drawing during slide transition. I haven't find out yet how to wait for a moment.

However i'm unable to read data from an external csv for that same plot...

Any help?

<code>
			Reveal.addEventListener( 'slidechanged', function( event ) {

				$(function () {
    			$('#graph1').highcharts({
        		chart: {
            	type: 'bar'
        		},
        		title: {
            	text: 'Fruit Consumption'
        		},
        		xAxis: {
            	categories: ['Apples', 'Bananas', 'Oranges']
        		},
        		yAxis: {
            	title: {
                text: 'Fruit eaten'
            	}
        		},
        		series: [{
            	name: 'Jane',
            	data: [1, 0, 4]
        		}, {
            	name: 'John',
            	data: [5, 7, 3]
        		}]
    			});
				});

				
					$.get('dataset.csv', function(csv) { $('#container').highcharts({
					chart: { type: 'column' }, data: { csv: csv }, title: { text: 'Fruit
					Consumption' }, yAxis: { title: { text: 'Units' } } }); });
			

			});
<\code>

**Comment by demoneaux** [comment]
For now there aren’t any events indicating when transitions end. You can use `setTimeout` to start drawing your charts after the transition ends though.
