### ISSUE TITLE
Update Highlight.JS to latest Version

### ISSUE THREAD

**Issue by ivanoats** [hakimel/reveal.js#1433]
There are a lot more languages now, time for an update to highlight.js please?

**Comment by Delapouite** [comment]
highlight.js has been updated to 8.9.1 recently : https://github.com/hakimel/reveal.js/commit/50f9896362e373375d05eb3278ccab983849d3d9

which is the last version according to : https://github.com/isagalaev/highlight.js/releases

**Comment by elazar** [comment]
[9.1.0](https://github.com/isagalaev/highlight.js/releases/tag/9.1.0) is the latest version as of today. I can say that it adds support for the PHP `::class` feature added in its 5.5.0 version.

**Comment by bnjmnt4n** [comment]
Closed as highlight.js has been updated to 9.11.0 in Reveal 3.6.0.
