### ISSUE TITLE
Update export PDF section to include Decktape

### ISSUE THREAD

**Issue by rmpestano** [hakimel/reveal.js#1435]
Hi guys,

I think we could include [Decktape](https://github.com/astefanutti/decktape) into **Export PDF** section as an alternative to export presentation as PDF. I have used it and got really impressed with the results.

 [Here](https://astefanutti.github.io/decktape/examples/fowd-nyc-2014.pdf) is a revealjs presentation exported to PDF by decktape.

WDYT?

**Comment by demoneaux** [comment]
Decktape has already been added to the bottom of the [exporting PDFs section](https://github.com/hakimel/reveal.js#pdf-export).
