### ISSUE TITLE
Add text at the button of the slide using Markdown

### ISSUE THREAD

**Issue by SudeepParajuli** [hakimel/reveal.js#1439]
I want to add the contact address at the button of the first slide but I could not figure out how to add it using markdown .

**Comment by demoneaux** [comment]
I’m not too sure what you’re referring to. Could you give more details/examples?

**Comment by demoneaux** [comment]
Closing for now due to lack of details. In the future feel free to ask such questions on [StackOverflow](http://stackoverflow.com/questions/tagged/reveal.js).

**Comment by SudeepParajuli** [comment]
I have found the solution . You could close the issue .


*----------------------------------------------*
*Sudeep Parajuli*
DevOps Engineer | YoungInnovations Pvt Ltd.
+977-9801089446 | sudeep.parajuli@hotmail.com
VMware Cloud Associate ( VCA )
