### ISSUE TITLE
Feature request: current position in presentation through a miniature map in the corner

### ISSUE THREAD

**Issue by ibeerepoot** [hakimel/reveal.js#1444]
I'd love to know the position of the current slide in the overall presentation by looking at some sort of miniature map in the left-bottom corner of the screen for example. Think of the miniature maps you have in games, so you know where you are. It would just be a simple grid with small rectangles that represent the slides. You can already see this when you press Escape, but I'd like to see it while I'm in slide view too. You could even have different colours for slides you've visited.

I hope someone can make this happen! Love the framework by the way :)

**Comment by demoneaux** [comment]
Reveal.js already has a progress bar at the bottom to show the overall slide progress. If you’d like a mini map of the slides, that sounds like a great idea for a plugin! Feel free to create one and add it to the wiki.
