### ISSUE TITLE
conditional slide overview

### ISSUE THREAD

**Issue by while0pass** [hakimel/reveal.js#1446]
When speaker view is activated it would be good to only show slide overview to the speaker, not the audience.

**Comment by demoneaux** [comment]
@hakimel opinions? This seems fine to me :)

**Comment by denehyg** [comment]
An alternative approach would be to use the [reveal.js-menu](https://github.com/denehyg/reveal.js-menu) plugin. Opening the menu from the speaker view does not show the menu to the audience.

**Comment by hakimel** [comment]
Makes sense to me – I've made the change in 8e3a7f03d189391f88f56b8ac7c96db709d7cba7 and ef137fd01f228c50027c356084a2e69e938e2511

**Comment by hjwp** [comment]
*(very briefly, thank you *so* much for this project, it is exactly what I needed)*

minor feature detail / addition/ suggestion here:  when presenter is in overview mode, flicking through slides, you probably only actually want to show the audience the slide they've jumped to once they've selected it?  maybe that's just me?
