### ISSUE TITLE
Make overview mode scrollable by dragging the mouse

### ISSUE THREAD

**Issue by hadim** [hakimel/reveal.js#1447]
It would be nice to be abe to scroll (horizontally and vertically) the slides when the overview mode is enable by dragging the mouse on the screen. It's very convenient during a talk !

I tried to use this lib http://www.cssscript.com/small-javascript-library-to-scroll-content-with-mouse-drag-dragscroll/ but it does not work :-(

Any idea ?

**Comment by demoneaux** [comment]
@hakimel what do you think? Personally I don’t think it’s very necessary.

**Comment by hakimel** [comment]
Thanks for the idea but this isn't something I think we should add. The overview mode is sluggish and at the brink of being overly complex already so it wouldn't be a good idea trying to add something like this on top.

**Comment by jmuheim** [comment]
I would love to see this feature still.

Especially when having spectators watching the presentation using Multiplex, I think it's very ugly if their presentations all follow me while I'm trying to find a "far away" slide in overview mode, browsing through all the slides in between.

Being able to simply scroll in the overview would help to avoid this.
