### ISSUE TITLE
Lazy load svg

### ISSUE THREAD

**Issue by hadim** [hakimel/reveal.js#1453]
Would it be possible to have lazy loading for svg as well ?

It has been done for iframe for example here : https://github.com/hakimel/reveal.js/commit/54ca9edeed077c4f7e564d0fa26c086af28a02ee

(svg elements are the main media I use)

**Comment by hadim** [comment]
I tried to replace

```javascript
toArray( slide.querySelectorAll( 'img[data-src], video[data-src], audio[data-src]' ) ).forEach( function( element ) {
```

by

```javascript
toArray( slide.querySelectorAll( 'img[data-src], video[data-src], audio[data-src], svg[data-src]' ) ).forEach( function( element ) {
```

But svg elements don't load anymore ... and I got no errors in the console.

Any idea ?

**Comment by demoneaux** [comment]
`<svg>` elements do not have the `src` attribute. If you’re trying to load an external SVG, you can use `<img>`.
