### ISSUE TITLE
Controls not showing on IE9

### ISSUE THREAD

**Issue by Calcyfer** [hakimel/reveal.js#1454]
On IE9, controls aren't visible at the moment.
Below is a snapshot of the reveal.js demo site as of 4 Dec 2015.

I've looked at the DOM and CSS rules, but can't find a reason as to why they won't render properly.

![revealjs-ie9](https://cloud.githubusercontent.com/assets/1166874/11591208/50d9b9b8-9a96-11e5-9b40-d544caf1e669.png)

**Comment by redballoon** [comment]
Seems they are using diff border colors to make the arrows which probably doesn't work in IE9

**Comment by Calcyfer** [comment]
Thanks for pointing that out.
I might give that a shot, or I'll just wait for january and tell the client IE9 isn't being supported by Microsoft anymore, telling them to upgrade. :)

**Comment by demoneaux** [comment]
Based on https://github.com/hakimel/reveal.js/wiki/Browser-Support, only transitions are officially supported in IE9, so I’ll be closing this.
