### ISSUE TITLE
Embeded youtube video as background?

### ISSUE THREAD

**Issue by reagle** [hakimel/reveal.js#1455]
I know you can embed video files using the {data-background-video} but what about an actual YouTube video? Trying a background-iframe isn't working for me...

**Comment by Calcyfer** [comment]
You could just add the iframe outside the .reveal div and use a custom css to hide the default background.
Example : 
```
<iframe height="100%" width="100%" 
src="https://youtube.com/embed/ID?autoplay=1&controls=0&showinfo=0&autohide=1">
</iframe>
```

**Comment by demoneaux** [comment]
@reagle currently there is no such way to do so that is built into reveal.js. I will mark this as a duplicate of #1465.
