### ISSUE TITLE
Parallax background not working in overview mode

### ISSUE THREAD

**Issue by ztiruam** [hakimel/reveal.js#1457]
In the current version (3.2.0) the background parallax image only shows in the first slide when in overview mode. It used to show up in the entire background earlier.

Standard example:
http://lab.hakim.se/reveal-js/?parallaxBackgroundImage=https%3A%2F%2Fs3.amazonaws.com%2Fhakim-static%2Freveal-js%2Freveal-parallax-1.jpg&parallaxBackgroundSize=2100px%20900px#/

What can I do to get this very nice feature it working again?

**Comment by imagejan** [comment]
The commit that changed this behavior is https://github.com/hakimel/reveal.js/commit/b71705c.

As the commit message suggests, this was made to allow the overview slides to be shown with their own background each (if they have one). If you find a solution that works well for both static and parallax backgrounds, I guess you are welcome to submit a pull request to fix this.

**Comment by ztiruam** [comment]
Ok, I understand the reason. Thanks.
