### ISSUE TITLE
Markdown fails with pseudo-HTML-looking code blocks

### ISSUE THREAD

**Issue by rsgranne** [hakimel/reveal.js#146]
I inserted this into a reveal.js presentation:

```
<section data-markdown>
`/etc/cups/cupsd.conf`

Contains config blocks  
specifying which computers can access printers

    <Location /printers>  
    Order Deny, Allow  
    Deny from All  
    BrowseAllow from 127.0.0.1  
    BrowseAllow from 192.168.1.0/24  
    BrowseAllow from @LOCAL  
    Allow from 127.0.0.1  
    Allow from 192.168.1.0/24  
    Allow from @LOCAL
    </Location>

</section>
```

Everything looked fine except for two lines: `<Location /printers>` & `</Location>`.

When I viewed the slideshow in Chrome 22.0.1229.64 beta, Firefox 15.01, & Safari 6.0.1, using Mac OS X 10.8.2, I instead see this:

```
<location printers="">
[snip]
</location>
```

(Note that the last line has substituted lowercase "l" for the capital "L".)

I was expecting to see `<Location /printers>` & `</Location>`. I tested that what I expected is correct for Markdown by copying everything between `<section data-markdown>` & `</section>` & pasting it into Markdown Dingus, at http://daringfireball.net/projects/markdown/dingus, & there I saw what I expected to see. In addition, according to Gruber's Mardown Syntax page:

> Within a code block, ampersands (&) and angle brackets (< and >) are automatically converted into HTML entities. This makes it very easy to include example HTML source code using Markdown — just paste it and indent it, and Markdown will handle the hassle of encoding the ampersands and angle brackets. … Regular Markdown syntax is not processed within code blocks.

I had 158 slides in this presentation, all done with Markdown, & all worked fine, with this exception. Interestingly, & perhaps helpfully, I had this on other slides, & it worked; in other words, it display correctly.

```
Edit `/etc/gdm/gdm.schemas`,  
find `<key>security/DisallowTCP</key>`  
& change value from `true`  
to `false`
```

In that case, I saw `<key>security/DisallowTCP</key>` display correctly, with both `<key>` & `</key>`.

This also worked:

```
Edit `/etc/fonts/local/conf`

Add line pointing to font directory:

`<dir>/font/directory</dir>`
```

There, `<dir>/font/directory</dir>` also displayed correctly, with both `<dir>` & `</dir>`.

So it appears that the Markdown processor is trying to convert `<Location /printers>` into HTML, which it shouldn't do, as this is within a code block.

**Comment by jjatria** [comment]
I think this might still be unresolved. I'm getting some odd behaviour if the code in the slide contains itself a `<script>` tag:

```html
<section data-markdown>
  <script type='text/template'>
    ## Code in a slide

    ```
    <div>
    </div>
    ```

        <script>
        </script>

    ```
    <script>
    </script>
    ```
  </script>
</section>
``` 

If the tag is something other than `<script>`, then it works as expected. If the tag is `<script>`, using ` ``` ` to delimit the block breaks the slide entirely, but indenting it shows the _start_ of the `<script>` block, all the way (but not including) the closing tag.

Or am I doing something wrong?

I ran into this while trying to have a slide that had an example of a Reveal.js slide.

**Comment by demoneaux** [comment]
This is because the `</script>` tag causes the browser to close the initial template script (`<script type='text/template'>). For now, you can try replacing that with `__SCRIPT_END__` to allow your Markdown code to be parsed properly.

**Comment by jjatria** [comment]
> For now, you can try replacing that with `__SCRIPT_END__`

Thanks. Does this mean that this is something that should eventually get fixed?
