### ISSUE TITLE
Some TeX equations can't be parsed

### ISSUE THREAD

**Issue by ruiafonsopereira** [hakimel/reveal.js#1471]
I'm inserting some TeX equations such as
```latex
\underline{abc}
```
and
```latex
\underbrace{abc}
```

And it's returned the following error
```KaTeX parse error: Expected 'EOF', got '\underline' at position 10: \underline̲{abc}```. Since the equation is correct, why is this error being returned? Is there any package missing? Am I somehow misspelling the equation? Thanks in advance.

Link to presentation: https://slides.com/ruiafonsopereira/bug-report/
I'm using Google Chrome on Windows 10

**Comment by process91** [comment]
[KaTeX doesn't support underline](https://github.com/Khan/KaTeX/wiki/Function-Support-in-KaTeX), Mathjax does so if you need this you may want to consider switching.

**Comment by ruiafonsopereira** [comment]
I algo forgot to mention that I was using www.slides.com
But yeah, thanks for the reference @process91
