### ISSUE TITLE
Vertical slides, slide numbers and progress bar

### ISSUE THREAD

**Issue by WG-** [hakimel/reveal.js#1475]
Reveal.js supports vertical slides, which gives a second dimensions to the slides. Now I want to use vertical slides as backup slides. Backup slides can be slides which are used as an intermezzo or to elaborate a certain topic presented in the main horizontal slide. 

As a result in a normal presentation these backup slides are not used. However I could decide during the presentation to show one of the backup (vertical) slides. Currently vertical slides are also counted as slides in the progress bar and the slide numbers. This gives the audience a false view of the progress of the current presentation. 

Now what I want is the following:
- Can I make sure that the progress bar and the total slide numbers will only takes horizontal slides into account in displaying the progress?
- Can I change the numbering of the vertical slides, that is to say. Slide 3.1 (the top vertical slide) will get the slide number 3. And slide 3.2 (the slide below the top vertical slide) gets the number 3.1?

**Comment by zionsg** [comment]
Hi, this is what I have done for my own slides. You can view a sample of the slide number at http://slides.intzone.com/2015-10-16-ZendFramework.

I have 8 horizontal slides.
Slide 1 with no vertical slides will be `1.1/8`.
Slide 6 with 3 vertical slides will show `6.2/8` when the 2nd vertical slide is shown.

```
<script>
Reveal.initialize({
    // other settings
    slideNumber: "c.v/t"
});

// Code to reflect actual slide number instead of using flattened slide number - does NOT work on speaker notes
var horzSlideCnt = document.querySelectorAll( '.reveal .slides>section' ).length;

// Update slide number for 1st slide where slidechanged event has not been triggered
Reveal.addEventListener('ready', function (event) {
    Reveal.configure({
        slideNumber: "c.1/" + horzSlideCnt
    });
});

// Update slide number to reflect actual horizontal/vertical slide numbers (indexh/indexv are zero-based)
Reveal.addEventListener('slidechanged', function (event) {
    var slideNumberField = document.querySelector('.reveal .slide-number'),
        slideNumber = (event.indexh + 1) + "." + (event.indexv + 1) + '/' + horzSlideCnt,
        interval;

    // Unable to set innerHTML straightaway without use of setInterval() as element may be re-created after event
    interval = window.setInterval(
        function () {
            slideNumberField.innerHTML = slideNumber;
            clearInterval(interval);
        },
        10
    );
});
</script>
```

**Comment by demoneaux** [comment]
@WG-

> Can I make sure that the progress bar and the total slide numbers will only takes horizontal slides into account in displaying the progress?

This is currently not possible, as the progress bar takes into account both horizontal and vertical sides.

> Can I change the numbering of the vertical slides, that is to say. Slide 3.1 (the top vertical slide) will get the slide number 3. And slide 3.2 (the slide below the top vertical slide) gets the number 3.1?

There isn’t a built-in way to do that, but you can follow @zionsg’s method of modifying the contents of the `.slide-number` element when the “slidechanged” event fires.
