### ISSUE TITLE
Ads on reveal.js homepage

### ISSUE THREAD

**Issue by sworisbreathing** [hakimel/reveal.js#1477]
I'm not sure how it happened, but I see an ad on the title slide at http://lab.hakim.se/reveal-js/#/
![image](https://cloud.githubusercontent.com/assets/1486524/12227242/737b7aec-b87d-11e5-916b-e65320d38f88.png)

Looking in the source code, I don't see any references to carbon.js so I'm not sure whether @hakimel added it specifically or if it's being injected from something else. Either way it was pretty confusing to see a code sample on the title slide which was unrelated to the project.

**Comment by hakimel** [comment]
I added that – it's there in the source of the page if you search for "carbon".
