### ISSUE TITLE
Data-Transition Slide in and Out

### ISSUE THREAD

**Issue by DeastinY** [hakimel/reveal.js#1480]
Hey @hakimel !
First of all thanks a lot for the great work !

I have a bunch of slides, where nothing but the images changes:

```
<section data-transition="none">
...
</section>
```

Then I want a slide transition into the next section:

```
<section data-transition="slide-in">
```

But the first section still leaves with "none" transition.
I've tried all different cominations with _data-transition="none slide-out"_ etc, but nothing seems to work. Is what I'm trying even possible ?

Kind Regards, DeastinY :)

**Comment by NAlexPear** [comment]
`none slide-out` is working for me. Don't forget, too, that you can do `<section>` overrides for individual slides. Have you tried applying `none slide-out` to just the last slide? And do you have a link to your site where that doesn't work?

**Comment by demoneaux** [comment]
Closing, as `none-in slide-out` should be able to work.
