### ISSUE TITLE
Hard Shadows when exporting from Chrome

### ISSUE THREAD

**Issue by DeastinY** [hakimel/reveal.js#1481]
Hi all,
I use the ?print-pdf method to print my slides, but when exporting I don't get anything soft shadows in the resulting pdf, but black boxes with a hard border.

![screenshot from 2016-01-13 10-43-30](https://cloud.githubusercontent.com/assets/5399476/12290535/9ee7d9e4-b9e2-11e5-9a64-7850322635b3.png)

Is there any known workaround other than disabling shadows ? I'm using a slightly modified version of the "White" template.

**Comment by demoneaux** [comment]
Hi @DeastinY have you looked at the [PDF exporting](https://github.com/hakimel/reveal.js#pdf-export) section of the readme? Please try to follow that and see if your slides are printed correctly.

**Comment by demoneaux** [comment]
Closing for now. Feel free to reopen if you encounter any issues.
