### ISSUE TITLE
slide selectors in the config or global settings

### ISSUE THREAD

**Issue by pikilon** [hakimel/reveal.js#1482]
We need to change the selectors for slide without cloning the reveal.js (in order to update it later without any harm).

The problem is this one 
```javascript
	var SLIDES_SELECTOR = '.slides section',
		HORIZONTAL_SLIDES_SELECTOR = '.slides>section',
		VERTICAL_SLIDES_SELECTOR = '.slides>section.present>section',
		HOME_SLIDE_SELECTOR = '.slides>section:first-of-type',
```
This variables are unnacesible because are runned in IFFe there is no way to alter it without touching the original one.

As a temporary solution I added this code just before initialize options to get a global variable if exists
```javascript
	/**
	* Change the selectors if the variable (Object) "revealSelectors" is set
	*/
	if( typeof revealSelectors === 'object' ) {
			for (var k in revealSelectors) eval(k+"='"+revealSelectors[k]+"';");
	}
	/**
	 * Starts up the presentation if the client is capable.
	 */
	function initialize( options ) {
//[...]
```

So I put before the script link 
```html
		<script>
		 var revealSelectors = {
		 		SLIDES_SELECTOR : '.slides section',
				HORIZONTAL_SLIDES_SELECTOR : '.slides>section',
				VERTICAL_SLIDES_SELECTOR : '.slides>section.present>section',
				HOME_SLIDE_SELECTOR : '.slides>section:first-of-type',
		 };
		</script>
		<script src="../../js/my_reveal.js"></script>
		<script>Reveal.initialize();</script>
```

I guess there is a better way of doing this through amd, but don't know much about it.

**Comment by demoneaux** [comment]
Just changing the selectors like that isn’t going to completely work, as there are other references to the current slides format within the code. For now, I think your use case is too obscure to implement such a setting, so I’m going to close this. Feel free to modify your own copy of reveal.js.
