### ISSUE TITLE
Stop auto-scaling

### ISSUE THREAD

**Issue by phillord** [hakimel/reveal.js#1487]
It would be nice to have an option to prevent the auto-scaling functionality.

I sometimes put large amounts of code on my slides which will not (sanely) fit on a screen. I use Ctrl-+ and Ctrl-- to zoom in and out, and just scroll up and down to show the bit I am interested in at the time, which works well within slidy, but not reveal.

**Comment by hakimel** [comment]
You can disabled scaling by setting both the `maxScale` and `minScale` config options to 1. For example: http://lab.hakim.se/reveal-js/?minScale=1&maxScale=1

More info about presentation size and scaling here: https://github.com/hakimel/reveal.js#presentation-size

**Comment by phillord** [comment]
Thank you.
