### ISSUE TITLE
GeoGebra iframe not loading

### ISSUE THREAD

**Issue by nimonian** [hakimel/reveal.js#1488]
I have GeoGebra applets embedded in RevealJS slides using iframes. When the slide is loaded, the iframe does not load and hence the applet appears as a blank white rectangle. Refreshing the page then loads the applet. I have tried a few things (using data-src="" instead of src="" for example) but I cannot cause the iframe to load when the slide is loaded. I use Reveal for teaching so it would be very nice if embedding geogebra could happen without hitting F5 every time. Does anyone have a work around for embedding geogebra into slides?

**Comment by demoneaux** [comment]
What's the exact code snippet that you used?

**Comment by demoneaux** [comment]
Closing this until I get more details. Feel free to ask questions like this on [StackOverflow](http://stackoverflow.com/questions/tagged/reveal.js).
