### ISSUE TITLE
Speaker Notes: Display time in current locale

### ISSUE THREAD

**Issue by fd0** [hakimel/reveal.js#1489]
Hi,

first of all: thanks for this great presentation tool!

I'd like to be able to display the time in the speaker's panel in my proper local format (13:48 instead of 1:48 PM), is that possible? It seems the clock's locale [is hardcoded here](https://github.com/hakimel/reveal.js/blob/master/plugin/notes/notes.html#L342):
```javascript
clockEl.innerHTML = now.toLocaleTimeString( 'en-US', { hour12: true, hour: '2-digit', minute:'2-digit' } );
```

Is there a way to configure this without patching the `notes.html` file?

**Comment by demoneaux** [comment]
There doesn’t appear to be a simple way to configure that without manually editing the HTML file, so for now I think that would be the recommended way.
