### ISSUE TITLE
css `zoom` is not zooming iframe in Chrome

### ISSUE THREAD

**Issue by Huxpro** [hakimel/reveal.js#1490]
well, css `zoom` is not working for iframe, but `translate: scale()` works well.

Is there any way to only use `translate: scale()` (like Safari) and stop using `zoom`?

**Comment by Huxpro** [comment]
Just found [Releases 3.2.0](https://github.com/hakimel/reveal.js/releases/tag/3.2.0) has deprecated the using of `zoom`, close it.

**Comment by turnerguo** [comment]
It just deprecated `zoom` for scale down, but not for scale up.
I think this should be reopened as a new feature to add new config property to enable just `transform: scale()`, because in sometime we need include some interactions in slide, `zoom` will break the position.
