### ISSUE TITLE
slidechanged event does not fire on reload of page with hash URL

### ISSUE THREAD

**Issue by JamesDunne** [hakimel/reveal.js#1491]
I'm relying on the `slidechanged` event to initialize some interactive code on each slide but the `slidechanged` event does not fire when reloading the presentation page with the current slide URL in the hash. It fires when changing between slides but not on initial slide load.

**Comment by demoneaux** [comment]
This makes sense as a reload does not cause the slide to change, it loads the page again with a specific slide. You should probably use `React.addEventListener('ready', fn)` to initialize your code based on the current slide.
