### ISSUE TITLE
Get Slidenumber from event.previousSlide

### ISSUE THREAD

**Issue by cgrossbaier** [hakimel/reveal.js#1496]
I have the following code.

`Reveal.addEventListener('slidechanged', function (event) {
            // event.previousSlide
        });`

I am not able to retrieve the horizontal index from the previousSlide. Can anyone help me?

Thanks!

**Comment by demoneaux** [comment]
Currently this is not in the Reveal.js API, although it can still be retrieved.

```js
var prevSlide = { horizontal: null, vertical: null };
Reveal.addEventListener('ready', function(e) {
  prevSlide.horizontal = e.indexh;
  prevSlide.vertical = e.indexv;
});

Reveal.addEventListener('slidechanged', function (e) {
  // use previous slide information
  // …
  // update previous slide information
  prevSlide.horizontal = e.indexh;
  prevSlide.vertical = e.indexv;
});
```
