### ISSUE TITLE
VirusTotal reports "suspected of Malware.JS.Obfuscated"

### ISSUE THREAD

**Issue by Birgos** [hakimel/reveal.js#1497]
Could anyone please clarify why malware alarm for highlight.js occurred?
Is it a false positive?

Please take a look at:
https://www.virustotal.com/en/file/05434a19213e9704b76e239d8db0cf64b734293aebb46d8a1f636ae246b614bf/analysis/ (Downloaded from https://github.com/hakimel/reveal.js/archive/3.2.0.zip)
or the file after cloning the project from github:
https://www.virustotal.com/en/file/aecbf507a17493291e26497c6c2731b28ead5a798d3f6509a8c7cf19d8dfb8dc/analysis/

**Comment by demoneaux** [comment]
This is probably a false positive, also it was only detected by one AV vendor. It's probably an issue on their side and should be reported to them.
