### ISSUE TITLE
Bug: Glitches when using Chromium in Full-Screen with Notes Display

### ISSUE THREAD

**Issue by fd0** [hakimel/reveal.js#1501]
Hi,

first of all: Thanks for this great software!

Unfortunately (during a recent talk) I discovered strange glitches being displayed on the projector when the presentation window is in full-screen mode. This behavior confused my audience. Leaving full-screen mode fixes the issue, I did not observe any glitches in non-full-screen mode.

I'm using Chromium 48 on Linux with i3 as the window manager, with two screens configured side by side. On the left screen I have the presenter notes window, on the right screen is the projector.

After the talk, I've managed to capture the glitches in a video, you can find it here: https://fd0.me/tmp/revealjs-glitches.mov
You can see that I'm stepping through some slides on the left (control) window, everything is fine until I switch the right (presenter) window to full-screen (00:00:19).

At 00:00:23 to 00:00:25 you can see that the slide "jumps" to the side for a few moments, afterwards the text on the slide jumps a bit to the right. At 00:00:39 to 00:00:41 it seem to fade in and out the previous slide, as the word "fragmented" vanishes and appears again (but only in the "presentation" window). 00:00:51 to 00:00:54 shows a glitch that displays a previous slide.

Is there anything I can do to debug this issue? It is really nasty (because the audience is sometimes shown the previous slide and the current slide back and forth) and I'd like to help getting resolved. I'm easily able to reproduce it.

As you can see in the video I used the official reveal.js presentation, but for the presentation I gave the topmost commit was 822a9c937c902807e376713760e1f07845951d5a.

**Comment by boschkundendienst** [comment]
First of all, your video is no longer available, at least from Germany.

I would try to make sure that you disable all browser extensions. They often insert javascript code into pages that might cause such issues, but this is just an idea.

**Comment by fd0** [comment]
Thanks for the comment, I've completely forgotten about this issue and I don't use Reveal.js any more. Therefore, I'm closing this issue. Thanks anyway! :)
