### ISSUE TITLE
Custom google font adding

### ISSUE THREAD

**Issue by ekremkaraca** [hakimel/reveal.js#1504]
Hey guys,

Thanks for the wonderful project. I'd like to add custom Google font to one of theme I'm using now. I don't know how to add it either adding directly to css file (like `bower_components/reveal.js/css/theme/sky.css`, every bower update it is probably reverted back to original one) or overriding them using custom css file (I'm unsure whether it works or not). Can you suggest me how to do it?

**Comment by h4xr** [comment]
It's preferable to create a custom stylesheet and override the fonts there

**Comment by demoneaux** [comment]
@h4xr is right, you should override the fonts in a separate stylesheet, so I think this issue can be closed as it isn't really related to Reveal.js.

**Comment by hakimel** [comment]
Yep – @demoneaux and @h4xr are right that you should add your new font in a custom stylesheet. Could create a new theme too.
