### ISSUE TITLE
Slide overview broken in pre-release Firefox builds

### ISSUE THREAD

**Issue by callahad** [hakimel/reveal.js#1508]
I'll look into this later, but the slide overview is currently broken in Firefox Developer Edition and Nightly, but works fine in Stable.

<img width="1254" alt="screen shot 2016-02-17 at 11 04 12" src="https://cloud.githubusercontent.com/assets/24193/13117679/9ad12ffa-d566-11e5-9801-a47b578069c1.png">

Hovering elements with the Inspector shows outlines of things where they should be, but for some reason they're not actually being composited in the right place.

**Comment by callahad** [comment]
Tracking in Bugzilla: [Bug 1253042](https://bugzilla.mozilla.org/show_bug.cgi?id=1253042)

**Comment by demoneaux** [comment]
Should be closed with #1649.
