### ISSUE TITLE
Using Reveal.js to build a website as framework or plugin

### ISSUE THREAD

**Issue by ElizabethC1688** [hakimel/reveal.js#1510]
HI @hakimel . 

Thank you for this amazing framework. I understand that you built it as a html5 presentation framework  to create slides. Which I've been using as my sole source when building my presentations. 

But I think it could be more and I love it so much that I want to build my website using it. 

A few questions:
1. Can this be done? 
2. What would the downsides be? 
3. Security (since it is no longer internal use but provided to the public, would my site be secure)?
4. Is it possible to not use reveal.js as a framework but as a plugin?
5. Would you recommend someone using reveal.js to build a full fledged site and what should I be kept in mind?

Your feedback would be greatly appreciated.

Thank you in advance.

**Comment by MattAgile** [comment]
I think I am trying to do the similar thing here: http://stackoverflow.com/questions/35511988/reveal-js-as-an-external-dependency

**Comment by demoneaux** [comment]
I'm not too sure what you mean when you want to use Reveal as a website. If you want your website to look like a presentation, then it should work alright. There shouldn't be any security issues, it should just work like other Reveal. presentations.

**Comment by ts-xie** [comment]
Hi, I too am trying to use Reveal.js as a dependency. For example, I want to host different slides on my site, eg. `mysite.com/slides/slideA`. Is there an official support for packaging?

**Comment by silvia-ma** [comment]
@ts-xie did you find a solution about this? I'm trying to use reveal.js as a website too.
