### ISSUE TITLE
Hyperlinks cannot be clicked in Firefox Desktop

### ISSUE THREAD

**Issue by reinhart1010** [hakimel/reveal.js#1511]
While using Firefox 46 (Windows Desktop), the links of the slides on reveal.js cannot be clicked. When using developer tools > Pick an element from the page > Hovering on a link, the link is treated as the <div class="slides"> and the link is not clickable.
On the attachment, the black arrow is the place where I hover the link (since the system Print Screen does not show the cursor position)
This issue is only available at the desktop Firefox. Firefox for Android and iOS does not have any issues.
This issue applies for both Firefox windows with and without multiprocess/e10s.
![error](https://cloud.githubusercontent.com/assets/17312341/13139718/7f935be6-d660-11e5-9957-4304181132d8.png)

**Comment by xFlatlinex** [comment]
Same here, using Firefox 45.0a2 on Ubuntu, so it looks like devs at Firefox broke something on the latest update for the Developer Edition.

**Comment by demoneaux** [comment]
Are you all using the `rollingLinks` option?

**Comment by demoneaux** [comment]
This doesn't seem to be an issue anymore, closing.
