### ISSUE TITLE
blank page after install third party plugin

### ISSUE THREAD

**Issue by ordinaryegi** [hakimel/reveal.js#1513]
Hi @hakimel 
i'm adding third party plugin to my presentation, i'm following from guidelines plugin installation, but unfortunately after install third party plugin, my slide become blank, when i deleted the third party plugin line source my slide appear again, it's something wrong or i making some wrong configuration

regards

**Comment by denizdogan** [comment]
Have you checked if there's an error logged in the console? In Chrome or Firefox, press F12 to open the developer tools and see if there are any errors. Also, what third party plugin is it?

**Comment by ordinaryegi** [comment]
After upgrade to latest reveal.js, it solved, all plugin run normally,
thanks
Pada tanggal 24 Feb 2016 21.50, "Deniz Dogan" <notifications@github.com>
menulis:

**Comment by demoneaux** [comment]
I think this issue can be closed.
