### ISSUE TITLE
Chrome displays black background in fullscreen mode

### ISSUE THREAD

**Issue by jamestwebber** [hakimel/reveal.js#1516]
It looks like other people have had this issue but I didn't see it in the tracker so I thought I'd mention it. When I try to go into fullscreen mode in Chrome, it displays the background as black (instead of white which it should be). This behavior doesn't happen in Safari&mdash;I think it's a specific issue with Chrome.

[This SO post](http://stackoverflow.com/questions/16163089/background-element-goes-black-when-entering-fullscreen-with-html5) has a fix: instead of `var element = document.body;` in [line 1977 of reveal.js](https://github.com/hakimel/reveal.js/blob/master/js/reveal.js#L1977), Chrome works correctly with `var element = document.documentElement;`

It also works correctly in Safari for what it's worth&mdash;I don't know if this is worth modifying though. Depends if this is considered bug in Chrome and should be fixed soon? In any case it is a very simple PR.

**Comment by demoneaux** [comment]
This should have been fixed in reveal.js 3.2.0. What version are you using?

**Comment by jamestwebber** [comment]
Is the fix somewhere else in the code? I just pulled from master and it still seems to be acting that way, unless I make the change I mentioned in the previous post.

**Comment by demoneaux** [comment]
Not too sure about that. It was mentioned in the change log of v3.2.0, so I thought it would be fixed. /cc @hakimel should have more ideas.

**Comment by demoneaux** [comment]
Apparently it’s a CSS fix: 5e763bc67d140d1a41056c2e63f0fbe80c5d03ab

**Comment by jamestwebber** [comment]
Ah, I figured out what my problem was. Had the change pulled from master but was still using an old version of the CSS file. Recompiling fixed it. Cased closed.

**Comment by joehoeller** [comment]
So what was the fix? Can you post the code snippet at least?
