### ISSUE TITLE
Overriding 'routes'

### ISSUE THREAD

**Issue by markedup** [hakimel/reveal.js#1519]
I need to lock users out of navigating left or right when in sub-slides (i.e. `Reveal.getIndices().v > 0`). It's not a good experience for the structure of the presentations I'm building with **Reveal**.

I've tried something basic, like attempting to remove the `enabled` CSS class from the left and right arrows on slide change, but this has no effect and the `enabled` classes remain in place.

I've found the `availableRoutes` function in the source, but this doesn't look easy to override/update without hacking this library function directly.

I couldn't find anything in the documentation about customising route conditions—can anyone help, please?

**Comment by demoneaux** [comment]
There aren't any built in features that allow you to limit navigation of slides like that. However, you can probably do something similar by listening to `onslidechanged` and switching the slide yourself. If you do create such a plugin, do add it to the [list](https://github.com/hakimel/reveal.js/wiki/Plugins,-Tools-and-Hardware) to share it with others.
