### ISSUE TITLE
Default `data-separator` attribute value doesn't seem to work

### ISSUE THREAD

**Issue by reosablo** [hakimel/reveal.js#1524]
Thanks for providing a great package!!

I found the default value of the `data-separator` attribute in [/plugin/markdown/markdown.js](https://github.com/hakimel/reveal.js/blob/dev/plugin/markdown/markdown.js) and tried to write a markdown that matches the separator.

```js
var DEFAULT_SLIDE_SEPARATOR = '^\r?\n---\r?\n$',
```

But the default expression doesn't match the bellow markdown expression.

```markdown
foo

---

bar
```

The `DEFAULT_SLIDE_SEPARATOR` variable is used as a `new RegExp` parameter, but it's incorrect as an regular expression source.

The bellow lines should be fixed.

```javascript
	var DEFAULT_SLIDE_SEPARATOR = '^\r?\n---\r?\n$',
		DEFAULT_NOTES_SEPARATOR = 'note:',
		DEFAULT_ELEMENT_ATTRIBUTES_SEPARATOR = '\\\.element\\\s*?(.+?)$',
		DEFAULT_SLIDE_ATTRIBUTES_SEPARATOR = '\\\.slide:\\\s*?(\\\S.+?)$';
```

All the numbers of back slashes should be 2.

```javascript
	var DEFAULT_SLIDE_SEPARATOR = '^\\r?\\n---\\r?\\n$',
		DEFAULT_NOTES_SEPARATOR = 'note:',
		DEFAULT_ELEMENT_ATTRIBUTES_SEPARATOR = '\\.element\\s*?(.+?)$',
		DEFAULT_SLIDE_ATTRIBUTES_SEPARATOR = '\\.slide:\\s*?(\\S.+?)$';
```

The last 2 changes affects nothing because `'\s'` is regarded as `'s'` in JavaScript string literal.

If you fix the expression, it might be a breaking change those who doesn't declare the `data-separator` attribute. Please fix it if you think it's a good idea.

**Comment by demoneaux** [comment]
Closing as this has been fixed.

**Comment by reosablo** [comment]
Will it fix in future releases...?
Thanks anyway!
