### ISSUE TITLE
Default index.html should be a blank template

### ISSUE THREAD

**Issue by bharadwaj-raju** [hakimel/reveal.js#1526]
The default `index.html` at the repository should be made into a blank template, and the existing should be moved to something like `demo.html`.

This helps when creating new presentations - the user doesn't *need* to delete the intro/demo to this framework from the file to get to a workable blank presentation.

**Comment by demoneaux** [comment]
Maybe we could add a `blank.html` file with just a blank template, as `index.html` is used to power `gh-pages`. @hakimel what do you think?

**Comment by bharadwaj-raju** [comment]
An [example template](https://gist.github.com/bharadwaj-raju/e42721abcbd1f928ad7f).

**Comment by hakimel** [comment]
This is a good idea. I'd like to slim down the template a little to make sure it has only the essentials. Will need to test that out a little bit more.

**Comment by hakimel** [comment]
The index.html file is now an empty template. This is the content and plugins I settled on: https://github.com/hakimel/reveal.js/blob/dev/index.html

Hopefully I didn't miss any documentation that needs updating.
