### ISSUE TITLE
Demo Error

### ISSUE THREAD

**Issue by DonRichards** [hakimel/reveal.js#1531]
README.md
A framework for easily creating beautiful presentations using HTML. Check out the live demo.

```text
Forbidden

You don't have permission to access /reveal-js/ on this server.

Apache/2.2.31 (Amazon) Server at lab.hakim.se Port 80
```

**Comment by demoneaux** [comment]
See https://github.com/hakimel/reveal.js/issues/1530#issuecomment-197401128.

**Comment by DonRichards** [comment]
Thanks!
