### ISSUE TITLE
add figure/figcaption styling

### ISSUE THREAD

**Issue by TzviyaSiegman** [hakimel/reveal.js#1541]
I tried adding:
`.reveal figure {
    page-break-inside: avoid;
    display: block;
}
.reveal figcaption {
  font-size: 75%;
}`

to a figure with `class="stretch"`, but the caption falls off the bottom of the screen.

**Comment by deki** [comment]
have you found a workaround?

**Comment by bnjmnt4n** [comment]
You should try applying `.stretch` to the image instead of the figure, which should work fine.
