### ISSUE TITLE
Recursive addition of elements when using custom data-state function and D3

### ISSUE THREAD

**Issue by mheieis** [hakimel/reveal.js#1543]
I seem to have run into a problem when using reveal.js+D3 and custom user functions / slide.
What happens is at the first run through of the slides, everything displays. However, when the slide in question (slide 2 - stripchart) is revisited, a second chart is displayed on the slide. This continues, I presume, for as many times as the slide is visited (see attached screen shot).

I can't see anything obvious that would be causing this.

Any thoughts or advice would be greatly appreciated. And thank-you for a great package. 
Kind regards.
[Uploading files.zip…]()

**Comment by demoneaux** [comment]
Not too sure what's happening, as your upload didn't seem to work. Next time, try putting it in a gist instead, which would be more friendly to people looking at your code. Closing this for now, feel free to re-open with more information.
