### ISSUE TITLE
`data-background-iframe` with URL should support proxy settings

### ISSUE THREAD

**Issue by ghost** [hakimel/reveal.js#1548]
When the presentation runs behind a [corporate] HTTP proxy, using a public URL with `data-background-iframe` does not show the website.

_Ideally_ it would just use my browser's proxy settings (currently that doesn't seem to be working).

Or, if that's not possible, some syntax to include HTTP proxy options in the URL itself, or an additional attribute `data-background-iframe-proxy` (or something like it) where I can configure the proxy.

Example:

``` html
<!-- does not work behind proxy -->
<section data-background-iframe="https://www.google.com">

<!-- set a proxy using additional attribute -->
<section data-background-iframe="https://www.google.com"
         data-background-iframe-proxy="http://my.local.proxy:5678">
```

**Comment by demoneaux** [comment]
I don’t see why this shouldn't use your browser's proxy settings by default as it is simply a normal iframe which is placed in the background. Perhaps you should check your settings again? Creating custom proxy settings is probably not required for most people using reveal.js.

**Comment by estraph** [comment]
That's what I though, too. I dug in a bit deeper, and it seems like the proxy is *not* the issue - it just often is an issue in my environment, so I prematurely came to that conclusion.

What's _actually _happening is because the page I'm linking to is using SSL (HTTPS), it's not displaying in an iframe. Is there a good workaround for this?

**Comment by demoneaux** [comment]
Being served via HTTPS shouldn't affect it from being embedded, you should check if the page is allowed to be embedded (via `X-FRAME-OPTIONS`).
