### ISSUE TITLE
Edge is accidentally using 'zoom'

### ISSUE THREAD

**Issue by RopoMen** [hakimel/reveal.js#1549]
Hi,

I noticed that in Windows 10 + Edge reveal.js is using 'zoom' property instead of 'transform: scale()'.

Edge UserAgent: 

*Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) 
Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586*

That will match in to RegExp intented for Chrome it is found [here](https://github.com/hakimel/reveal.js/blob/master/js/reveal.js#L1592)
```js
/chrome/i.test( navigator.userAgent )
```

This is causing issue with Edge scaling at least in our project. When `zoom` property value is under `0.846` whole background image disappears, but if we use `transform: scale(_some_value_)` it works perfectly.

**Comment by demoneaux** [comment]
Closed by #1550.
