### ISSUE TITLE
[Bug] Ordered list width problem

### ISSUE THREAD

**Issue by vanquang9387** [hakimel/reveal.js#1567]
HTML:

``` html
            <div class="slides">
                <section>
                    <h2>Nội dung</h2>
                    <ol>
                        <li>Cron và crontab là gì?</li>
                        <li>Crontab format</li>
                        <li>Một số ví dụ</li>
                    </ol>
                </section>
            </div>
```

Displayed:
Line break at 1st item
![ol](https://cloud.githubusercontent.com/assets/7125810/14635456/a1d73220-0650-11e6-961f-8780a4f2be0d.PNG)

Browser
Chrome version 49 (64bit)

OS
Windows 10 Pro

**Comment by datavectors** [comment]
Seems to work without wrap here ...

![slides](https://cloud.githubusercontent.com/assets/4958509/14636928/38e4c68a-0626-11e6-93ff-a8a73806f48a.png)

Chromium Version 49.0.2623.108 Ubuntu 14.04 32bits

**Comment by demoneaux** [comment]
I can't seem to reproduce this on Firefox/Chrome, closing for now.
