### ISSUE TITLE
Sections containing an img after a fragments section breaks next()

### ISSUE THREAD

**Issue by mcameron** [hakimel/reveal.js#1573]
As far as I can tell the "Bar" slide in the following page will not be shown.

```
<section style="fragments">
Foo
</section
<section>
<img src="images/baz.png">
</section>
<section style="fragments">
Bar
</section>
```

It gets weirder for me in that next after the image section returns to a mid point way before the Foo section.

**Comment by demoneaux** [comment]
Hmm, I think there's probably an issue with your code. `<section style="fragments">` is not valid and might cause some issues.
