### ISSUE TITLE
Keyboard shortcut help doesn't honour rebindings

### ISSUE THREAD

**Issue by aspiers** [hakimel/reveal.js#1579]
If I rebind keys via `Reveal.initialize({ ... keyboard: ... })`, the rebindings are not reflected in the keyboard shortcut help table shown when I view the slides and press `?`.

**Comment by demoneaux** [comment]
You can try using [`Reveal.registerKeyboardShortcut('key', 'description')`](https://github.com/hakimel/reveal.js/blob/713702a0ab81d1756a30e6c14ae49afd42135541/js/reveal.js#L4737) to change the table.
