### ISSUE TITLE
change theme with a query string 

### ISSUE THREAD

**Issue by rockonedege** [hakimel/reveal.js#1581]
I usually use black/color background to protect/please eyes on the screen. However,  when there's a need to print it out for reading. white theme is preferred to save inks.

the only way I know is to manually change the theme in the index.html. Is it possible to support theme change with something like ?theme=white.

**Comment by demoneaux** [comment]
You can do this yourself by loading a stylesheet based on the query string. For example, [the demo](https://github.com/hakimel/reveal.js/blob/c2997c605d969ae46180f0a714802511bb89dbc7/demo.html#L165-176) does something like that.
