### ISSUE TITLE
Fails to read attributes in external markdown files

### ISSUE THREAD

**Issue by artasbartas** [hakimel/reveal.js#1583]
I was trying to set background image to my slides in external markdown file, but reveal.js fails to parse them. As per documentation, using the HTML comment tag fails:

```
<!-- .slide: data-background="https://example.com/image.png" -->
```

I also tried curly brackets, which fails as well:

```
{.slide: data-background="https://example.com/image.png"}
```

Ditto for element attributes. The funny thing is that when I try to render the same md file with the [reveal-md](https://github.com/webpro/reveal-md) library, the slides are properly styled. 

Looking at #947 and #1242, I see that the problem persisted for a while now. Any plans to address it in the foreseeable future?

**Comment by artasbartas** [comment]
Found the solution to this one, you need to specify the separators for slide and element attributes in the html file. Simple enough, yet your external markdown example in the README omits that.

**Comment by demoneaux** [comment]
The docs now [does have that note](https://github.com/hakimel/reveal.js#external-markdown), so I'm closing this issue.
