### ISSUE TITLE
Hide specific arrow controls on specific slides.

### ISSUE THREAD

**Issue by duikb00t** [hakimel/reveal.js#1593]
Hello,

I was wondering is there is a way to limit the navigation? I would like to disable for some sections specific controls. What is a good approach of doing this?

Thanks!

**Comment by demoneaux** [comment]
You can use the [slide state attribute](https://github.com/hakimel/reveal.js#slide-states) to customise the current class for specific slides, and hide the navigation via `.[state] .reveal .controls { display: none; }`.
