### ISSUE TITLE
Nest different types of HTML tags with fragments

### ISSUE THREAD

**Issue by FSMaxB** [hakimel/reveal.js#1596]
I would like something like this to work:

``` html
<section>
    <p class="fragment"><del class="fragment">text</del></p>
</section>
```
1. Fade in `text`
2. Strikethrough ~~`text`~~

**Comment by malcalevak** [comment]
I feel like this is something you could do with an absolutely positioned pair of fragments and current-visible on the first fragment

**Comment by demoneaux** [comment]
The strikethrough effect can't be part of a `<del>` fragment, as it is shown by default on all `<del>` element. You might need to create a separate fragment, with `text-decoration: line-through`.
