### ISSUE TITLE
data-background url check doesn't work with get parameters

### ISSUE THREAD

**Issue by timopar** [hakimel/reveal.js#1603]
If I use data-background attribute with relative image path that contains cache buster the url won't be auto wrapped. data-background attribute will be converted to data-background-image attribute if it contains correct protocol or ends with image extension so this kind path won work /path/to/image?123

`if( /^(http|file|\/\/)/gi.test( data.background ) || /\.(svg|png|jpg|jpeg|gif|bmp)$/gi.test( data.background ) ) {
   slide.setAttribute( 'data-background-image', data.background );
}`

**Comment by hakimel** [comment]
Fixed in #1768
