### ISSUE TITLE
Default theme text is too small

### ISSUE THREAD

**Issue by nedbat** [hakimel/reveal.js#1605]
I love reveal.js, and I love that people are able to make sharp presentations easily and quickly.

But the default theme has text that is too small for most presentation venues, and enormous margins that show lots of empty space instead of the presenter's message.

Would you be open to changing the default theme to be a more reasonable default?

**Comment by proofit404** [comment]
Especially for code blocks. It looks perfect on laptop but too small for TV or projectors.

**Comment by hakimel** [comment]
Sure, I made a few changes;
- Increased default font size
- Reduced default page margin from 10% to 4%
- Increase default max scale from 1.5x to 2x

Here's the before and after in a gif:
![reveal-js-default-size](https://cloud.githubusercontent.com/assets/629429/15959510/6585e57c-2efb-11e6-8f18-017756da2275.gif)

Note that if you include the zoom.js plugin, you can alt+click on an element to zoom in on it. This is particularly useful for elements like code blocks. Can try it out at http://lab.hakim.se/reveal-js/#/13

**Comment by naholyr** [comment]
Note about alt+click: on most Linux window managers it will not be propagated to the page, as it's caught by window manager itself to move window. You can still press ctrl+alt+click or shift+alt+click to try it.
