### ISSUE TITLE
Using reveal.js as courseware

### ISSUE THREAD

**Issue by egrosclaude** [hakimel/reveal.js#1610]
As a teacher, I use reveal.js much as a courseware tool. I slightly edited^H^H^H^H deteriorated the 'notes' plugin to wipe out the next slide frame and leave the right third or so of the screen for the notes. I heavily populate the sections' asides, give my classroom presentations in the 'classic mode'. Later, at home or while mobile, my students use the 'notes' reading with the text material. I even have convinced some students to record their voice to the notes for me to publish, so we end up with a blind-accesible, deaf-accessible, all-terrain, courseware material, where I can insert exercises, quizzes, or any activities, not to mention videos or whatever. For a teacher like me, reveal.js has the best of every communicational world, excelling PDF, Powerpoint or videos in one go. Would I add Thank You, I wouldn't find a font with a large enough body size.

Now, I wish I had a means to make my dumbed-down notes the default mode for my students to read. I know I can publish the URL to my presentations with the '?notes' query appended, but the first window will open in 'classic mode' and keep lurking behind, in sync with the reading. Can it be made to disappear and be brought back with a keypress? --the presenter, that's me, would be its only user.

**Comment by linquize** [comment]
Cool! There are some CS professors / tutors using `reveal.js` in classrooms to present lecture notes.

**Comment by anayrat** [comment]
:+1:

**Comment by egrosclaude** [comment]
Anybody interested, please see
https://github.com/Sonaryr/reveal.js-coursemod
