### ISSUE TITLE
Markdown Example missing Script elements.

### ISSUE THREAD

**Issue by eddiewebb** [hakimel/reveal.js#1614]
Slide 6 in demo omits the required <script template tags.

**Comment by eddiewebb** [comment]
Submitted PR #1615 to resolve this.  I think I followed all guidance in contributing.md

**Comment by demoneaux** [comment]
The `<script>` template tags are not required for all usage of Markdown, only if HTML tags are still used within the Markdown, to prevent browsers from parsing it as HTML before Markdown gets parsed.
