### ISSUE TITLE
Speaker view navigation bug with hidden controls

### ISSUE THREAD

**Issue by Timothep** [hakimel/reveal.js#1616]
I just cloned a fresh repo and added a few slides to the default deck. 

```
<div class="slides">
    <section>Slide 1</section>
    <section>Slide 2</section>
    <section>Slide 3</section>
    <section>Slide 4</section>
    <section>Slide 5</section>
    <section>Slide 6</section>
    <section>Slide 7</section>
    <section>Slide 8</section>
    <section>Slide 9</section>
    <section>Slide 10</section>
</div>
```

Then I added the following code at the end of the index.html page to hide the controls:

`<script>
    Reveal.initialize({
        controls: false
    });
</script>
</body>`

Is this the correct way to hide the "arrow controls"?

I then start the app and open the speaker view:

* The "upcoming slide" is slide 3 (instead of 2)
* I navigate to the next slide, slide 2 is displayed, and the "upcoming slide" is slide 4
* I navigate to the next slide, slide 3 is displayed, and the "upcoming slide" is slide 5

![slidebump](https://cloud.githubusercontent.com/assets/594373/15910959/cf7cf5c6-2dcd-11e6-9faa-e77d78006b04.gif)

If I remove the script above, everything works fine again.

**Comment by hakimel** [comment]
Hey! That's the right config value, but the `initialize` method should only be called once and it looks like you're calling it twice. If you want to change an option after initializing, you can use `Reveal.configure({ controls: false })`.

**Comment by hakimel** [comment]
6bfa48a667fe91bb1de1b680769aeb7260af3a49 adds a check that will prevent repeated initialization
