### ISSUE TITLE
Markdown not working 

### ISSUE THREAD

**Issue by iplus26** [hakimel/reveal.js#1617]
Hi, guys, markdown example is not working and I've got no error. 

Here is my `index.html` file: 

```html
<html>
<head>
	<meta charset="utf-8" />
    <title>NOT WORKING</title>
    <link rel="stylesheet" href="css/reveal.css">
    <link rel="stylesheet" href="css/theme/ivan-white.css">
    <script src="bower_components/headjs/dist/1.0.0/head.min.js"></script>
</head>
<body>
    <div class="reveal">
        <div class="slides">
            <section data-markdown>
    <script type="text/template">
        ## Page title

        A paragraph with some text and a [link](http://hakim.se).
    </script>
</section>
        </div>
    </div>
    <script src="js/reveal.js"></script>
    <script>
        Reveal.initialize({
            dependencies: [
                {
                  src: 'node_modules/marked/lib/marked.js', 
                  condition: function() { 
                    return !!document.querySelector( '[data-markdown]' ); 
                  }
                }
            ]
        });
    </script>
</body>
</html>
```

Did I do something wrong?

**Comment by demoneaux** [comment]
Apart from including `marked.js`, you need to include `markdown.js` as well. See the [readme](https://github.com/hakimel/reveal.js#dependencies).

**Comment by iplus26** [comment]
Still not working after I imported the `markdown.js`

**Comment by Oluwasetemi** [comment]
@iplus26 for this pattern:
for the example of the markdown you want show in the slide (embedded or load from another file)
```html
<section data-markdown>
        <script type="text/template">
          ## Hello I'm using markdown.

        </script>
</section>
```
and  `script` should look like this 
```html
<script src="../lib/js/head.min.js"></script>
  <script src="../js/reveal.js"></script>
  <script src="../plugin/markdown/marked.js"></script>
  <script src="../plugin/markdown/markdown.js"></script>
```
and finally your `Reveal.initialize({})` should contain *dependencies* that points to markdown

```js
{
          src: '/plugin/markdown/marked.js',
          condition: function () {
            return document.querySelector('[data-markdown]');
          }
        },
        {
          src: '/plugin/markdown/markdown.js',
          condition: function () {
            return document.querySelector('[data-markdown]');
          }
        },
```
I hope it works now! Keep coding and enjoy reveal.js

**Comment by iplus26** [comment]
@Oluwasetemi Thanks for answering this but still not working. From my point of view, it is **external** markdown file that needs a web server running, while I can render inline markdown without a server. Am I right?

**Comment by demoneaux** [comment]
I'm not too sure. Try adding a `<!doctype html>`, and making sure all of your files are in the right place. Check the devtools console to see fit any 404 errors.

**Comment by iplus26** [comment]
@demoneaux No, there're not any error or warning in console, and `marked.js` and `markdown.js` is imported since I can use them in console. I want to do it without a server, which I believe is possible. And I will dive into its source code and find out what's wrong when I'm free. Anyway, thanks for your great job

**Comment by demoneaux** [comment]
Working on it offline should be fine, I'm not too sure what's the issue
either. I'll try to debug when I'm free after next week.

**Comment by Oluwasetemi** [comment]
@iplus26 let me try the external markdown file. I will give you a feedback.

**Comment by Oluwasetemi** [comment]
@iplus26 After a digging through the issues i found this #929. 
carefully checked the data attributes.
```html
<!-- Use external markdown resource, separate slides by three newlines; vertical slides by two newlines -->
      <section data-markdown="example.md" data-separator="^\n\n\n" data-separator-vertical="^\n\n"></section>
```
also check the dependencies very well. use chrome developer tool to test.
