### ISSUE TITLE
is there a way to trigger keyboards key (example: ESC, up arrow, left arrow) function on reveal that is inside an iframe? 

### ISSUE THREAD

**Issue by thomasjoyce** [hakimel/reveal.js#1619]
hi,

  I got an iframe display on my site that show the reveal.js slides.

I notice the keyboard feature does not work unless i click on the iframe content inside itself to activate the keyboard feature or click on one of the "controls" button first to activate the keyboard keys to work.

```
<aside class="controls" style="display: block;">
<div class="navigate-left enabled"></div>
<div class="navigate-right enabled"></div>
<div class="navigate-up enabled"></div>
<div class="navigate-down enabled"></div>
</aside>
```

Is there a way to trigger the keyboards keys without clicking the iframe content? 

Thanks for your help. :- )

**Comment by demoneaux** [comment]
This is expected behaviour, as iframes are treated as separate from the main content. If you would like to do that, you can bind to the `keypress` event on your page and [send `postMessage` calls to the Reveal.js iframe](https://github.com/hakimel/reveal.js#postmessage-api).
