### ISSUE TITLE
Firefox + white.css: Backgroundcolor switches to Black in Fullscreen

### ISSUE THREAD

**Issue by emasch** [hakimel/reveal.js#1624]
Hi,
I use Version 3.3.0 (from bower.json) fo reveal.js. I've also seen those Tickets: #668, #1408 and #1516, but they doesn't fix the problem for white.css for Firefox on Mac OS. 

If I toggle fullscreen via 'f', the background-color switches from white to black. I have to add the following css to change the color back:
        
        html:-webkit-full-screen-ancestor {
            background-color: #fff;
        }

        html:-moz-full-screen-ancestor {
            background-color: #fff;
        }

In the reveal.css the color is `inherit`, which means it usees the browser default, which is black in firefox 47.0 on Mac OS 10.11.

**Comment by hakimel** [comment]
Fixed by a12a17b2d7053fad006ae9914309e8fb56c44329
