### ISSUE TITLE
Could not able to use animation in 3.3.0 version

### ISSUE THREAD

**Issue by sumankundu** [hakimel/reveal.js#1625]
Hello,

I tried different package to have js based animation. Triend Two.js, TweenJS, vis.js but nothing worked. I found https://teresalight.com/labs/presentation-createjs/ but the same code does not work for version 3.3.0. I can see the animation with 2.6.2. 

Is this a bug or I am missing something.

**Comment by demoneaux** [comment]
Not too sure what's happening, but Reveal shouldn't affect animations from other libraries, so I'm closing this for now. If possible, could you reproduce this issue with a JSBin for easier debugging?
