### ISSUE TITLE
Interaction with SVG

### ISSUE THREAD

**Issue by ranr01** [hakimel/reveal.js#1626]
Hey, 

Thanks for developing this great tool. I've used it for the first and it was a very nice experience.

Sometimes, especially in scientific presentations, it is desired that different element of a figure (let's say svg) will appear/disappear at different times. 

It would be very nice if this capability could be integrated into reveal.js directly.
Something like [RevealJS SVG fragment presenter](https://gist.github.com/bollwyvl/fe1d2806449487cdf88a) but with support for different fragment effects, multiple fragment for each element and consistent scaling and style (i.e. behaves like img).

I'm not a JS programer and my HTML/CSS knowledge is extremely limited so I can not help with this.
I'll be happy to help in testing though.

Keep up the good work. 
Cheers!

**Comment by jasoncmcg** [comment]
That would be excellent. Here is an approach that you might want to consider until something like that happens.

In your SVG, create a group around your elements and place the `fragment` class on them. Then, paste the SVG to use it inline. This will allow you to use the mouse-over CSS styling.

Here is how to style SVG with CSS:
[MDN](https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/SVG_and_CSS)
[Longer article](https://tympanus.net/codrops/2015/07/16/styling-svg-use-content-css/)

Here is some example SVG to test with:

```
<svg
   xmlns:dc="http://purl.org/dc/elements/1.1/"
   xmlns:cc="http://creativecommons.org/ns#"
   xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
   xmlns:svg="http://www.w3.org/2000/svg"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
   xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
   width="100%"
   viewBox="0 0 210 297"
   version="1.1"
   id="svg8"
   inkscape:version="0.92.1 r15371"
   sodipodi:docname="drawing.svg">
  <defs
     id="defs2" />
  <sodipodi:namedview
     id="base"
     pagecolor="#ffffff"
     bordercolor="#666666"
     borderopacity="1.0"
     inkscape:pageopacity="0.0"
     inkscape:pageshadow="2"
     inkscape:zoom="0.35"
     inkscape:cx="-232.85714"
     inkscape:cy="560"
     inkscape:document-units="mm"
     inkscape:current-layer="layer1"
     showgrid="false"
     inkscape:window-width="1920"
     inkscape:window-height="1012"
     inkscape:window-x="1912"
     inkscape:window-y="-8"
     inkscape:window-maximized="1" />
  <metadata
     id="metadata5">
    <rdf:RDF>
      <cc:Work
         rdf:about="">
        <dc:format>image/svg+xml</dc:format>
        <dc:type
           rdf:resource="http://purl.org/dc/dcmitype/StillImage" />
        <dc:title></dc:title>
      </cc:Work>
    </rdf:RDF>
  </metadata>
  <g
     inkscape:label="Layer 1"
     inkscape:groupmode="layer"
     id="layer1">
    <g class="fragment"
       id="g8446">
      <text
         transform="matrix(1.8826141,0.42906948,-0.11508336,0.50494748,0,0)"
         id="text8419"
         y="101.34892"
         x="19.983477"
         style="font-style:normal;font-weight:normal;font-size:20.43525314px;line-height:125%;font-family:sans-serif;letter-spacing:0px;word-spacing:0px;fill:#000000;fill-opacity:1;stroke:none;stroke-width:0.5108813px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1"
         xml:space="preserve"><tspan
           style="stroke-width:0.5108813px"
           y="101.34892"
           x="19.983477"
           id="tspan8417"
           sodipodi:role="line">testing</tspan></text>
    </g>
    <g class="fragment"
       id="g8442">
      <rect
         transform="rotate(11.28635)"
         y="60.349972"
         x="29.8608"
         height="32.505951"
         width="148.92261"
         id="rect8421"
         style="fill:none;fill-opacity:1;stroke:#000000;stroke-width:1.86500001;stroke-miterlimit:4;stroke-dasharray:none;stroke-dashoffset:0" />
    </g>
    <g class="fragment"
       id="g8439">
      <rect
         transform="rotate(-28.894848)"
         y="128.72079"
         x="-35.31881"
         height="32.505951"
         width="148.92261"
         id="rect8421-2"
         style="fill:none;fill-opacity:1;stroke:#000000;stroke-width:1.86500001;stroke-miterlimit:4;stroke-dasharray:none;stroke-dashoffset:0" />
    </g>
  </g>
</svg>
```

**Comment by ranr01** [comment]
I was not working on a presentation for a while so this comment is somewhat delayed :-)

Thanks for the info, it works quite well. A small improvement would be to not having to paste the SVG code manually into the HTML. This makes the editing of the figures very cumbersome.
My solution to that is the following:

1. Add fragments etc. in  SVG file.
2. Include the SVG as an `object` like this:
 `<object type="image/svg+xml" data="your_svg_file.svg">
   </object>` 
3. Add the following JS script to the presentation HTML file after the `Reveal.initialize({...})` function (Adapted from [here](https://stackoverflow.com/questions/35783441/include-svg-files-with-html-and-still-be-able-to-apply-styles-to-them)):
```
Reveal.addEventListener( 'ready', function( event ) {
    document.querySelectorAll("object").forEach(function(e) {
         if (e.contentDocument) 
             e.parentElement.replaceChild(e.contentDocument.documentElement.cloneNode(true),
                                                             e);
    });
});
```

The script will find all the `object` elements in the HTML and will replace them with inline SVG elements so that Reveal.js can present them just like any other element.

The script can probably be more robust (i.e. handle lazy loading or select just specific objects etc.) but my JS knowledge is very minimal and I was happy just to make it work :-)...

**Comment by Waateur** [comment]
I did the exact same thing. And I had a problem with the inlining function being applied before the svg object was loaded ( In chrome 62 and FF 57 ). 
The solution was to do 
```
{src: 'js/inline.js', async :true }
```

**Comment by ranr01** [comment]
I actually have a slightly better way of doing this now (see here: [reveal-inline-svg](https://github.com/ranr01/reveal-inline-svg) )
The main idea is the same but there is no need to insert the fragments into the SVG directly.
Instead you specify the fragments and other properties of different SVG elements as `<param>` elements inside the`<object>` element. 
The JS then applies these properties when in-lining the SVG instead of the `<object>` elements.

**Comment by bnjmnt4n** [comment]
These seem like great ways of integrating SVG and fragments into Reveal. If you're interested, you can even add your plugin into the [plugins page](https://github.com/hakimel/reveal.js/wiki/Plugins,-Tools-and-Hardware).

**Comment by iraklic** [comment]
I need a simple thing, for animation to start (I have svg with animation) when I get to that page. fragment does not affect the animation start (at least I couldn't make these work). Should be simple but I cannot make it work. Help is appreciated.

**Comment by Hexanders** [comment]
I know it is already closed, but I just stumbled upon it and my solution might help someone. 
I start my SVG animation through the Reveal.on event Trigger like this:
 
```
<script> 
function reloadSvgAnimation(SVGname) {
		     var object = document.getElementById(SVGname);
		     var data = object.getAttribute('data');
		     object.setAttribute('data', ''); // Clear the data attribute
		     object.setAttribute('data', data); // Reset it to trigger reload
}

 Reveal.on('fragmentshown', function(event) {
		     if (event.fragment.id === 'fragment_ID') {
			 reloadSvgAnimation('svgID');
		     }
});
 </script>
```

**Comment by akirakyle** [comment]
I was having trouble with the load order of stuff in the proposed js code snippet, so here's my submission in case it helps anyone else who happens to find themselves here. I adapted [this web component](https://dev.to/dannyengelman/load-file-web-component-add-external-content-to-the-dom-1nd) to the js here which adds the appropriate fragment classes (or anything else)
```js
customElements.define("load-file", class extends HTMLElement {
  async connectedCallback() {
    let params = this.querySelectorAll("param");
    let shadowRoot = this.attachShadow({mode:"open"});
    shadowRoot.innerHTML = await (await fetch(this.getAttribute("src"))).text();
      
    params.forEach(function(p) {
        var svg_elem = shadowRoot.querySelector("#".concat(p.getAttribute("id")));
        for (const attr of p.attributes) {
            svg_elem.setAttribute(attr.name, attr.value);
        }
    });
    this.replaceWith(...shadowRoot.childNodes);
  }
})
```
