### ISSUE TITLE
embedded html in markdown sections

### ISSUE THREAD

**Issue by onqtam** [hakimel/reveal.js#1631]
currently if I want to use markdown I have to make the whole slide (section) as markdown with the `data-markdown` attribute.

But when markdown is not enough (like setting the color of a word with `<div style="color:#ff0000"> word </div>`) there is nothing to be done except for dropping markdown for the current slide entirely.

I've used [strapdown.js](http://strapdownjs.com/) (not for presentations) which is for rendering github flavored markdown into the browser which uses `<xmp>` tags - everything in them is treated as markdown. But what's more is that I can embed html within that tag and everything still works - so I can use html for more control over tables or colors or whatever. I can also have multiple such tags in the html document.

It would be awesome to be able to embed html in the `<section>` tags of reveal.js when using markdown. It would be even cooler if a section can have sub-sections which are either markdown or not.

**Comment by demoneaux** [comment]
As mentioned [here](https://github.com/hakimel/reveal.js#markdown), you can wrap your Markdown code in script tags to prevent browsers from parsing them before the Markdown output is rendered:

```html
<section data-markdown>
    <script type="text/template">
        ## Page title

        <div>
            A paragraph with some text and a [link](http://hakim.se).
        </div>
    </script>
</section>
```
