### ISSUE TITLE
Speakernote event

### ISSUE THREAD

**Issue by Taxman972** [hakimel/reveal.js#1645]
Hi,

When clicking on a div on the speakernote the event isn't sent to the main windows.

Do I miss something or it's a bug ?
![reveal](https://cloud.githubusercontent.com/assets/14277043/17173952/2fb4240e-53fe-11e6-9dc5-fbcf5ced68f4.jpg)

**Comment by demoneaux** [comment]
Not all events which occur in the speaker notes page will be bubbled up to the presentation. If you do want such behavior, you will have to write your own `postMessage` event handlers and send events to the parent presentation.
