### ISSUE TITLE
slide-number should not be displayed when printing

### ISSUE THREAD

**Issue by Leftium** [hakimel/reveal.js#1647]
This is one of the controls that should be hidden when printing: it renders as the exact same value on every page (the current slide that was being viewed when printing was initiated.)

Easily fixed by adding `.reveal .slide-number` to the [list of classes hidden in paper.css](https://github.com/hakimel/reveal.js/blob/de2ab07334766e6df2e3e69cd58a820e40d6349e/css/print/paper.css#L33).

**Comment by christinakayastha** [comment]
@Leftium created a PR for this issue, does that look good?

**Comment by Leftium** [comment]
@christinakayastha css/print/pdf.css should not be modified. The pages on a PDF *do* change and are useful.

**Comment by christinakayastha** [comment]
Oh gochha, Done

**Comment by hakimel** [comment]
Merged your PR, so the number is now hidden when printing to paper.
