### ISSUE TITLE
External markdown rendering of HTML headers is broken following marked.js plugin update.

### ISSUE THREAD

**Issue by gitpitch** [hakimel/reveal.js#1653]
It  looks like the rendering of HTML headers using external Markdown is broken following an update of the **plugin/markdown/marked.js** dependency from v0.3.3 to v0.3.5 in the **dev** branch.

Markdown formatted headers are being rendered by Reveal.js as plain text and the **#** header syntax itself is visible in the output as plain text instead of solely being used to apply style to the accompanying text. For example, the following Markdown:

```
#Hello
##Hello

Let's try *this* and **see** what happens.

- One
- Two
```

Renders as follows:

![bad-headers](https://cloud.githubusercontent.com/assets/19169584/17390817/b4338bb0-5a3a-11e6-96f5-92a4071df94f.png)

The text italics and bold along with lists in the Markdown are rendered correctly. The headers are not.

As noted this problem has been found in the dev branch and based on testing here it looks like the problem was introduced when the marked.js dependency was upgraded from 0.3.3 to 0.3.5. Also worth noting, this problem also seems to occur when tested against the marked.js 0.3.4 release.

Problem verifiable across Firefox, Safari and Chrome. Tested on OSX. This problem is not reproducible when testing inline Markdown using a  `data-markdown` section. It appears to exhibit only when using external Markdown.

**Comment by hakimel** [comment]
Hey, looks like there's an error in that example. There should be an empty
space between hash and heading: "# hello" rather than "#hello".

**Comment by gitpitch** [comment]
You're right, the space is the issue. Turns out marked.js has become less permissive. Prior to 0.3.4 a header hash without the space would still render correctly. I wasn't aware the space was mandatory. Even GitHub doesn't enforce the space when rendering, a header hash within a README without the space will render just fine too. Thanks @hakimal. Closing issue.
