### ISSUE TITLE
Allow plugins to contribute sections to the input URL

### ISSUE THREAD

**Issue by hyphz** [hakimel/reveal.js#1654]
I don't think there's currently any way for a plugin to read input from the part of the URL after the #, because Rjs itself will always redirect to the given slide number or remove the input if it is not a slide-id.

This would be a very useful feature for plugins that have their own state that would be useful to save in a bookmark. (I was personally thinking about a plugin that would allow separate presentations to share the same rjs configuration, so the presentation name would appear after the # as well and would be loaded from a separate file to the configuring .html file.)

**Comment by demoneaux** [comment]
Yeah, currently Reveal.js does not allow overriding the `#` query hash, but it is possible for plugins to use query parameters instead, such as `?option=1&next=2`.
