### ISSUE TITLE
Some MD tags not recognized when using npm or python local webservers

### ISSUE THREAD

**Issue by tim-c-smith** [hakimel/reveal.js#1657]
This is a rather strange issue. I'm finding markdown issues only with local servers.  

I'm using reveal.js as a github.io webpage framework. I have external md files. Everything is working as expected, but continually having to push content to GitHub to see it is a pain. 

To avoid this, I want to serve content from my local machine. Since I have external MD files, I need to use an http server (the filesystem alone will not work). 

I tried both python http.server and npm http-server, but find that - though the content works perfectly on GitHub.io, on my local machine some tags are not recognized.  Specifically vertical slide delimiters

For example, within an example index html file I have the following section:            

`<section data markdown="slides_md/example.md" data-separator="^\n\n\n" data-separator-vertical="^\n\n"></section>. 
`

And the external example.md file looks like this:

```
 # Gitro
Introduction to Git


## External 1.1

Content 1.1

Note: This will only appear in the speaker notes window.


## External 1.2

Content 1.2



## External 2

Content 2.1



## External 3.1

Content 3.1


## External 3.2

Content 3.2

```

Using github io, the slides are displayed correctly, but on  my local servers (either python http-server or npm http-server), I only see one slide  (see attached pics below). 

Here is the proper slides (displayed from github io)

![2](https://cloud.githubusercontent.com/assets/1692306/17481447/b6c879be-5d53-11e6-975e-6c3e974ccc8a.PNG)
![3](https://cloud.githubusercontent.com/assets/1692306/17481450/b8f6e4f0-5d53-11e6-8fb0-869f0425098a.PNG)

Here's the slides when accessed through a local http sever

![1](https://cloud.githubusercontent.com/assets/1692306/17481459/c3d7c830-5d53-11e6-9b5c-16e16460c3bd.PNG)

**Comment by tim-c-smith** [comment]
Issue is with CR and LF. 

If I commit and push, CR-LF's (windows) are translated into LF's only. When I serve the local repo content this (obviously) doesn't have the CR's removed. 

Therefore, by using:

```
				         data-separator="^\n>>>>>\n"
				         data-separator-vertical="^\nvvvvv\n"
```

The tags will not be interpreted correctly. 

To fix this problem, add the CR's to the tag definition (to whatever char string you prefer):
```
				         data-separator="^\r\n>>>>>\r\n"
				         data-separator-vertical="^\r\nvvvvv\r\n"
```

**Comment by demoneaux** [comment]
Yep, CRLF issues cause a lot of problems everywhere. Glad you found it!
