### ISSUE TITLE
Interactive code snippets with the klipse plugin

### ISSUE THREAD

**Issue by viebel** [hakimel/reveal.js#1670]
I'd like to build slides with interactive code snippets, with the [klipse plugin](https://github.com/viebel/klipse).

For that purpose, I need to include (safe) `script` and `link` tags as specified [here](https://github.com/viebel/klipse).

Please provide a solution

**Comment by demoneaux** [comment]
There doesn't seem to be much of an issue. Just include your scripts and styles in your presentation, provide the code snippets via `<pre><code>`, and the klipse plugin should be able to work fine.

**Comment by viebel** [comment]
Oh. Sorry I forgot to mention the context: I want to use the klipse plugin in reveal onlide editor http://lab.hakim.se/reveal-js/#/ https://slides.com/

As far as I know, <script> tags are not allowed there...

**Comment by demoneaux** [comment]
Yep, AFAIK script tags are not supported on slides.com. Unfortunately, I can't really help you out there, as this repo is for the open source Reveal.js library. Maybe you could try to contact their support to ask.

**Comment by viebel** [comment]
Thanks @demoneaux I sent a message to their support team.
Maybe you can help with this issue https://github.com/hakimel/reveal.js/issues/1735 ?
It is related to a CSS conflict between reveal and CodeMirror (used inside KLIPSE)
