### ISSUE TITLE
iframes are not preloaded according to viewDistance

### ISSUE THREAD

**Issue by mispy** [hakimel/reveal.js#1672]
Adding iframe[data-src] to the selector here makes it behave as expected: https://github.com/hakimel/reveal.js/blob/bac187f3a0f7e8f92d33ca0258fe2e96553d2930/js/reveal.js#L2887

Is this omission intentional? If so, it should probably be documented in the README. :)

**Comment by kp77** [comment]
Are there any plans for fixing this one?

**Comment by gbrowdy** [comment]
simply adding `iframe[data-src]` to the selector array in the line of code referenced above causes iframe lazy loading to work for me.  I'll send a PR for this.

**Comment by hakimel** [comment]
This is intentional. I've added a note to the readme to explain the rationale: https://github.com/hakimel/reveal.js/tree/dev#lazy-loading-iframes
