### ISSUE TITLE
Unable to full install

### ISSUE THREAD

**Issue by chadmorrow** [hakimel/reveal.js#1673]
On windows 10, clone repository, open folder in command prompt, git command, node.js command prompt, git bash, and npm install. Process fails at installing node-sass. Not sure how to fix. Anyone else run into this?

>3174 silly runTopLevelLifecycles Finishing
3175 silly install printInstalled
3176 verbose stack Error: node-sass@3.3.3 postinstall: `node scripts/build.js`
3176 verbose stack Exit status 1
3176 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:245:16)
3176 verbose stack     at emitTwo (events.js:106:13)
3176 verbose stack     at EventEmitter.emit (events.js:191:7)
3176 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
3176 verbose stack     at emitTwo (events.js:106:13)
3176 verbose stack     at ChildProcess.emit (events.js:191:7)
3176 verbose stack     at maybeClose (internal/child_process.js:850:16)
3176 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
3177 verbose pkgid node-sass@3.3.3
3178 verbose cwd C:\Users\Chad\Documents\GitHub\reveal.js
3179 error Windows_NT 10.0.10586
3180 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save-dev" "node-sass"
3181 error node v6.2.0
3182 error npm  v3.8.9
3183 error code ELIFECYCLE
3184 error node-sass@3.3.3 postinstall: `node scripts/build.js`
3184 error Exit status 1
3185 error Failed at the node-sass@3.3.3 postinstall script 'node scripts/build.js'.
3185 error Make sure you have the latest version of node.js and npm installed.
3185 error If you do, this is most likely a problem with the node-sass package,
3185 error not with npm itself.
3185 error Tell the author that this fails on your system:
3185 error     node scripts/build.js
3185 error You can get information on how to open an issue for this project with:
3185 error     npm bugs node-sass
3185 error Or if that isn't available, you can get their info via:
3185 error     npm owner ls node-sass
3185 error There is likely additional logging output above.
3186 verbose exit [ 1, true ]

**Comment by JanJordan** [comment]
same with me. 
my log points to other errors coming from python, installed an old 2.7 python, added pythonpath, more errors connected to python.
still no cigar.

maybe a specific node/npm version ist needed? 

sorry no time right now to investigate further

**Comment by EstelleDoreau** [comment]
hello, same as me, but I do not know if I can be useful
npm start doesn't work (or not well)

my solution : 
so use 
`grunt serve` and we can see : `Error: Cannot find module 'abbrev'`
so, use 
`npm i abbrev `
then 
`grunt serve` and it works (for me) 

(on windows 10)

**Comment by chadmorrow** [comment]
Tried this again today and it works now. Some other commit must have resolved this.
