### ISSUE TITLE
Change Onclick with JS

### ISSUE THREAD

**Issue by alkanadi** [hakimel/reveal.js#1674]
I tried doing this:
`(document.getElementById("img1").src = "img1.jpg").onclick=alert("Hello");`

As soon as the slide is loaded, the onclick event is fired. How can I add an onclick event to a fragment?

The end goal that I am trying to achieve is to shuffle the fragments. Each fragment has its own function associated to it. For example, if the user clicks on the cat image, it plays the cat sound. I can make it work if it were possible to add onclick.

So if I can't add onclick to a fragment with JS, how can I shuffle the fragments? Thanks

**Comment by demoneaux** [comment]
Your code is currently calling the alert as soon as the line is encountered. In order to properly attach a click listener, you need to wrap the `alert` call in a function:

```js
(document.getElementById("img1").src = "img1.jpg").onclick = function(e) {
  alert("Hello");
};
```
