### ISSUE TITLE
Shortcut to display a link with the link URL?

### ISSUE THREAD

**Issue by xuhdev** [hakimel/reveal.js#1683]
It is common in presentations where we want the URL to be shown as well as clickable. Is there any shortcut to do it?

**Comment by demoneaux** [comment]
If you use Markdown to render your presentations](https://github.com/hakimel/reveal.js#markdown), the Markdown parser will automatically add URLs as links.

**Comment by xuhdev** [comment]
What I'm talking about is when HTML is in use...

**Comment by demoneaux** [comment]
Nope. you'll have to add `<a>` tags yourself, or develop a plugin to help you do that easily.

**Comment by xuhdev** [comment]
Plugin added: https://www.topbug.net/revealjs-explicit-link/

**Comment by lanmaster53** [comment]
> If you use [Markdown to render your presentations](https://github.com/hakimel/reveal.js#markdown), the Markdown parser will automatically add URLs as links.

I have the opposite problem. How do I prevent this from happening in code blocks?
