### ISSUE TITLE
markdown script

### ISSUE THREAD

**Issue by fxbois** [hakimel/reveal.js#1693]
Hi,
I am the author of https://github.com/fxbois/web-mode an emacs major mode for editing web templates.
A user asked me to deal with the markdown parts that can be embedded in reveal.js templates.
I was wondering why don't use a syntax like : `<script type="text/markdown">` or `<script type="application/markdown">` to declare those parts ? 
Using specific script types is a common approach for template languages (e.g. `<script type="text/x-jquery-tmpl">`, `<script type="text/ng-template">`, `<script type="text/x-dust-template">`)

**Comment by Blightwidow** [comment]
Actually, if you take a look at the parsing of the Markdown, the type is irrelevant.

[The markdown script](https://github.com/hakimel/reveal.js/blob/master/plugin/markdown/markdown.js) scraps all the script elements embedded into a data-makdown section. You can change the content of the type attribute or even remove it without changing the result.

**Comment by demoneaux** [comment]
Yep, as mentioned, you can include a script in a section with the `data-markdown` attribute, which will be used as the content for the slide to be parsed as Markdown.

**Comment by fxbois** [comment]
@demoneaux do you have an example of this kind of syntax ?

**Comment by demoneaux** [comment]
See the readme for an example: https://github.com/hakimel/reveal.js#markdown.
