### ISSUE TITLE
PR: Fragment in Highlight.js Code is on Gist

### ISSUE THREAD

**Issue by nielsnuebel** [hakimel/reveal.js#1696]
Hi,

i wrote a little script with regex and string.replace and now it's possible to use fragment in highlight.js.

add 

```
<pre class="stretch">
    <code class="hljs xml" data-trim fragment>
    <mark class="fragment">
        <files>
            <mark class="fragment"><file>index.php</file></mark>
            <mark class="fragment"><file>templateDetails.xml</file></mark>
        </files>
    </mark>
    </code>
</pre>
```

add this script to dependencies in Reveal.initialize add the bottom.
https://gist.github.com/nielsnuebel/fecc7a7a9bf556f79d801c502a3a3932

**Comment by nielsnuebel** [comment]
Here is a Demo http://joomladaytemplate.niels-nuebel.de/fragment.html#/fragment

**Comment by demoneaux** [comment]
Perhaps you could release this as a [plugin](https://github.com/hakimel/reveal.js/wiki/Plugins,-Tools-and-Hardware). On a side note, I have a somewhat similar plugin, which only allows people to highlight specific lines of code when a fragment is shown (https://github.com/demoneaux/reveal-code-focus).
