### ISSUE TITLE
feature request: countdown timer option in speaker notes

### ISSUE THREAD

**Issue by bdarcus** [hakimel/reveal.js#1697]
Am suggesting having an option to allow the presenter to set the presentation time length, and then to have the timer countdown to that number.

**Comment by Sonaryr** [comment]
What would be the use case for this? There is already a timer in the speaker view that shows how long you are busy.

**Comment by bdarcus** [comment]
This is admittedly not that important, but it's just sometimes cognitively
easier to see how much time you have left than than to calculate it on the
fly.

Cases I'm thinking about are conference sessions where, say, you have
multiple speakers who each have a strict 15 or 20 minutes.

**Comment by demoneaux** [comment]
@hakimel what do you think about this?

**Comment by demoneaux** [comment]
This has been implemented in #1564.
