### ISSUE TITLE
Cannot read property 'classList' of null

### ISSUE THREAD

**Issue by oeway** [hakimel/reveal.js#1698]
Hi,

I am using reveal.js, and it's super cool.

I feature I want to have is to let the user decide when to load the reveal.js and reveal.css.
With https://github.com/ocombe/ocLazyLoad , I can load almost all other libraries, but when comes to reveal.js, I got the following error:

```
angular.js:13424 TypeError: Cannot read property 'classList' of null
    at a (reveal.js:476)
    at n (reveal.js:417)
    at e (reveal.js:366)
    at r (reveal.js:405)
    at Object.e [as initialize] (reveal.js:302)
```

The js and css used is:

"//cdnjs.cloudflare.com/ajax/libs/reveal.js/3.3.0/js/reveal.min.js",
"//cdnjs.cloudflare.com/ajax/libs/reveal.js/3.3.0/css/reveal.min.css"

It seems this error also related to #90 , but that would means it won't work for my case, is there any work around? I mean, load reveal.js whenever needed.

Thanks.

**Comment by oeway** [comment]
I fixed the error by execute Reveal.initialize after dom ready, but still it still doesn't work, I see nothing on the screen. 

I try to embed the reveal slides in to a md-content tag(https://material.angularjs.org/latest/api/directive/mdContent) in angular material. What could be the problem? Thanks in advance.

**Comment by demoneaux** [comment]
Hi! I'm not too sure exactly what this issue is about, but reveal doesn't work very well with being embedded into a page. A lot of the code requires it to be the only content available. Closing this for now, feel free to reopen with an example presentation.
