### ISSUE TITLE
Wide format slides (16:9 aspect ratio)

### ISSUE THREAD

**Issue by kaushalmodi** [hakimel/reveal.js#1699]
Hello,

I am preparing a set of slides for wide-screen (16:9 aspect ratio) viewing.

So I am setting the title slide and default slide background images to wide-format ratio images.

While the slides are viewed fine on (1) wide screen monitor (2) browser window in non-full-screen mode (when F11 is not yet pressed on Chrome browser), the slides get truncated if,
- viewed on a 4:3 ratio monitor
- viewed in full-screen mode (after pressing F11 on Chrome browser), regardless of the monitor ratio

The left and right sides of the slides (slide background) get truncated. 

Is there a way to ensure that none of the sides get truncated? Possibly fill with black or white or the slide background color instead of truncating any side?

**Comment by RubenOlsen** [comment]
Could you please provide us with an example deck?

**Comment by demoneaux** [comment]
You should be able to pass in `width` and `height` of your slides to allow Reveal to maintain the aspect ratio. If possible, please provide an example deck so we can see the issue.
