### ISSUE TITLE
Export reveal.js presentation to .odp or .ppt presentation

### ISSUE THREAD

**Issue by alesarrett** [hakimel/reveal.js#1702]
One issue dealing with the use of reveal.js is collaboration: when sharing a reveal.js presentations with colleagues for reuse, it's difficult to provide a simple way to share content to people who are usually using .ppt or .odp files.
A workaround is to export the presentation into pdf, open it e.g. in Libreoffice and create an .odp files.This is described in this Stackoverflow discussion: http://stackoverflow.com/questions/32179373/export-a-reveal-js-presentation-to-libreoffice-odp-or-powerpoint-ppt-pptx
Anyway the output is not totally satisfying for errors in formatting various things.
Is there a way to directly export a reveal.js presentation into .odp or .ppt files in the same way as it's possible to export into .pdf files?

**Comment by demoneaux** [comment]
Currently there isn't such a way, as Reveal.js presentations are just webpages, and they would be difficult to convert to specific proprietary `.ppt`/`.odp` slides. PDF printing is currently the easiest way to export presentations.

**Comment by ijstokes** [comment]
FWIW this would be a great feature and I think is definitely an achievable thing with a focused team of JS/CSS/HTML experts.  I'd expect a reasonable converter could be created with 3-6 person-weeks of work.

**Comment by davidfetter** [comment]
@ijstokes do you have or have access to such expertise?

**Comment by codypiersall** [comment]
You can take a revealjs source markdown file and output a powerpoint presentation using [pandoc](https://pandoc.org/) like this:

```bash
pandoc --from markdown --to pptx slides.md -o slides.pptx
```

I believe a template presentation can be given as well for styling.

**Comment by tojoirinah** [comment]
Is any way to do reverse ? export ppt / odp to html ?

**Comment by wenchaomartin** [comment]
@davidfetter codypiersall
  i just download https://jyywiki.cn/OS/2022/slides/2.slides and save as html
 
  i use the command as you said  but the ppt of converted is not pretty style
  
  the style of ppt is messy

**Comment by allefeld** [comment]
The best way is to write the presentation in Markdown and then process it with [Pandoc](https://pandoc.org/MANUAL.html) into both reveal.js and PowerPoint, as well as other formats.

Pandoc can also convert from PowerPoint to Markdown, but the result is normally not usable without a lot of touching up.

You should also look at [Quarto](https://quarto.org/) (successor of R Markdown) which improves the usability of Pandoc a lot, including processing from VS Code, R Studio and other editors, simpler customization through YAML front matter options, and last but not least computationally generated content.
