### ISSUE TITLE
Interative Slides (Realtime Editing)

### ISSUE THREAD

**Issue by jieverson** [hakimel/reveal.js#1704]
I was looking for a slide tool that could easily support iterative slides, where I could actually change the code in real time.

Some Examples what I'm talking about:
- Realtime CSS Edit (even ctrl+z works)
  https://www.w3.org/Talks/2016/font-level-up/#ampersand-demo
- Iterative components
  http://leaverou.github.io/csss/#css-controls-demo
  https://www.w3.org/Talks/2016/font-level-up/#fractions
- Realtime Javascript Console
  Couldn't find any example, but I'm suggesting a built-in javascript console, so you could stylish and highlight it, different from browser's console.

I fell like this could be easily implemented (if it's not already) in reveal.js as plugings. Like it is for syntax highlight using [highlight.js](https://highlightjs.org/).

**Comment by jocelynlecomte** [comment]
You should definitely check the [plugins](https://github.com/hakimel/reveal.js/wiki/Plugins,-Tools-and-Hardware)

**Comment by demoneaux** [comment]
Yep, as mentioned, you should look at the [plugins page](https://github.com/hakimel/reveal.js/wiki/Plugins,-Tools-and-Hardware). In fact, a quick look through gave me [this](https://github.com/soluml/reveal-css-snippet), which you can probably use to provide a real-time editable CSS snippet.
