### ISSUE TITLE
Is it possible to pass arguments when dependencies are defined?

### ISSUE THREAD

**Issue by garajo** [hakimel/reveal.js#1705]
I saw in the Wiki, there are no predefined structures for plugins, https://github.com/hakimel/reveal.js/wiki/Plugin-Guidelines#plugin-structure

But, I'm curious to why dependencies do not have a property for arguments, like this

```
dependencies: [
    { src: '../../plugin/background/background.js' , args: {'foo':'bar'}},
]
```

I looked for the plugin instance to "decorate" it, but I could not find it. Is there recommended way to pass variables to the plugin constructor or instance? Thanks

**Comment by Sonaryr** [comment]
you can always add your args to the config of reveal.js and in your plugin you can do `Reveal..getConfig();` to get to global reveal config.

**Comment by demoneaux** [comment]
Yep, agreed with @Sonaryr. Using the reveal config would be a great solution. I've got a couple of thoughts on this, and will fill up #1161 with some ideas. For now, closing this for #1161.
