### ISSUE TITLE
Speaker notes don't seem to work when used with multi-level slides

### ISSUE THREAD

**Issue by jerdog** [hakimel/reveal.js#1713]
I am trying to get notes to work and can't seem to get them to appear anywhere really. Right now I am trying to get them as part of a multi-level bit of my slides and no matter where I put the `<aside>` tag they won't display in the Speaker notes window

REF: https://github.com/hakimel/reveal.js#speaker-notes

``` html
<section>
    <section data-markdown>
    ### Slide title
    </section>
    <section data-markdown>
    slide
    </section>
    <section data-markdown>
    slide
    </section>
    <section data-markdown>
    slide
    </section>
    <aside class="notes">
    - Notes to tell me stuff
    </aside>
</section>
```

**Comment by CMeza99** [comment]
I had a where the speaker notes were not rendering as expected, but I am using external files. Maybe my workaround may help you. I had to add a extra line in between sections. To make sure I have it, I used a HTML comment tag.

slide.md:
```markdown
# Header 1

<section>
## Header 2

First part of multi-slide.
<aside class="notes">
Speaker note
</aside>
</section>
<!-- -->
<section>
## Header 2

Second part of multi-slide.
<aside class="notes">
Speaker note
</aside>
</section>
<!-- -->
```

**Comment by demoneaux** [comment]
@jerdog: the speaker notes have to be placed within an individual slide. Currently, you are placing them within the outermost wrapper which is used for creating vertical slides, hence they are unable to render properly.

It should look something like this:
```html
<section>
    <section data-markdown>
    ### Slide title
    </section>
    <section data-markdown>
    slide
    </section>

    <section data-markdown>
      slide
      <aside class="notes">...</aside>
    </section>

    <section data-markdown>
      slide
      <aside class="notes">
      - Notes to tell me stuff
      </aside>
    </section>
</section>
```

**Comment by jerdog** [comment]
Thanks guys!
