### ISSUE TITLE
Quotation marks converted to italics?

### ISSUE THREAD

**Issue by garretwilson** [hakimel/reveal.js#1720]
Things I put inside `<q>` should be shown surrounded by questions marks—yet reveal.js is removing the quotation marks and instead showing the content in italics.

Why is reveal messing around with basic styling? These are fundamental, semantic issues that shouldn't be changed. See also #1675. (In summary: reveal.js is removing italics that are needed, and putting italics there when they are not needed, and removing ultra-important quotation marks.)

**Comment by Blightwidow** [comment]
Apparently, each theme deactivate quotes in `<q>` blocks:
`.reveal blockquote {
  quotes: none; }`

You could make a workaround by creating your own theme and loading it in your _index.html_ file. I have no idea why it's deactivated by default though and agree this should not be.

**Comment by garretwilson** [comment]
Thanks for investigating this, and for suggesting a workaround. But I'm unclear; is someone going to fix it?

**Comment by Blightwidow** [comment]
That I cannot answer as I was just passing by. Maybe I'll submit a pull request later but the absence of quotes seems intended, I would like to know why it's like that.

**Comment by garretwilson** [comment]
@hakimel , can you comment on why Reveal is removing my quotation marks and how I can disable this? Thank you.

**Comment by bnjmntn** [comment]
The styles are set [here](https://github.com/hakimel/reveal.js/blob/43eada79901830702bd40dce857831aef8e76759/css/theme/template/theme.scss#L137-L160), as they are the basic default styling for Reveal. If you don't like the default styling, you can create your own theme, by [modifying the `quotes` property](https://css-tricks.com/almanac/properties/q/quotes/) and changing the `font-style`.

**Comment by garretwilson** [comment]
But @bnjmntn , one of the great things about `<q>` is that it is semantic; if you don't explicitly set it, it allows the _browser_ to decide which quotes to use. This way quotes may automatically appear as “” for English and «» for French.

Removing the quotes short-circuits this process. How do I tell the browser to take over again? It looks like a value of [`initial`](https://developer.mozilla.org/en-US/docs/Web/CSS/initial) might work, but that doesn't seem to be supported by Internet Explorer.

You see, it's not just an issue of adding back an explicit value --- by default the user agent determines the value, and that's what I want.

**Comment by hakimel** [comment]
Localization seems like a good argument for leaving the default quotation marks. I've changed it so that the themes don't reset the `quotes` CSS property anymore in dc17129082dc112fd45515adfc233c685723d547.

Quotes are still italicized though. That's a style choice for the theme that you can override if you want to.
