### ISSUE TITLE
Update node version in package.json

### ISSUE THREAD

**Issue by kolis** [hakimel/reveal.js#1729]
Reveal.js does not install with the `yarn` package manager and node engine v6. I'm getting this error:
`error reveal.js@3.3.0: The engine "node" is incompatible with this module. Expected version "~4.1.1".`

I can install it using npm, and it seems to work, so I guess it is only the entry in `package.json` that needs updating.

**Comment by kolis** [comment]
```
$ node --version
v6.8.1
```

**Comment by msegado** [comment]
I also ran into this.
(@kolis, as a temporary workaround, yarn has a `--ignore-engines` flag you can use)

**Comment by hakimel** [comment]
Updated in #1743

**Comment by mrsum** [comment]
Hm... Still have troubles with reveal 3.3.0 and node v6.9.1

**Comment by pirelenito** [comment]
Was this release? I just got this issue while trying to install it with `yarn add reveal.js`.

Btw, thanks for this awesome project! Really, it is awesome! ❤️

**Comment by hakimel** [comment]
Just released this as part 3.4.0 🚀
