### ISSUE TITLE
YAML frontmatter in Markdown files

### ISSUE THREAD

**Issue by paddelkraft** [hakimel/reveal.js#1730]
I generally use reveal-md and RevealGhPages that both use reveal as its core.
I have added functionality in the Markdown plugin to set markdown options and Reveal options from YAML frontmatter inside the MD file jekyll style.   like this. 

```

---
title: Foobar
separator: <!--s-->
verticalSeparator: <!--v-->
theme: css/theme/solarized.css
revealOptions:
    transition: 'fade'

---
Foo

Note: test note

<!--s-->

# Bar

<!--v-->

Sub Bar 
```

Is this functionality something the reveal community would be interested in merging in?

if so i would be happy to submit a pull request.

**Comment by demoneaux** [comment]
Personally I feel that this feature is rather extravagant, and not really necessary, as it adds unnecessary bloat to the Markdown plugin, as the YAML front matter has to be parsed. @hakimel any opinions?

**Comment by paddelkraft** [comment]
maybe it is only the way i use reveal. i want the content to be in an .md file and like to be able to change the behaviour of reveal without going into the HTML. Im used to having yaml front matter in .md files from using static site generators.
Anyway the feature is added to Reveal-md outside of the plugin but i figured it would be cleaner to add it in the plugin and have it added at the source so one could use the same .md files with all flavours of reveal.

**Comment by demoneaux** [comment]
Since it is already available in a plugin, we’re probably not going to shift it into the core Reveal.js code, as that would add additional code and maintenance. Closing this for now.
