### ISSUE TITLE
does Reveal really need to be a Global Static variable?

### ISSUE THREAD

**Issue by robertop87** [hakimel/reveal.js#1731]
Reveal as a Global Static variable is really a big limitation to get more than one presentations in the same page.

is there a really stronger reason to keep it as Global Static??

**Comment by demoneaux** [comment]
Currently, there are no plans to allow for multiple instances of Reveal in 1 page, hence Reveal is a "global static" variable. There would be a lot of code refactoring to do to allow that, but since the primary use case of Reveal is just for simple presentations, I don't think it is worth it.
