### ISSUE TITLE
Feature request: Multiple Reveal instances

### ISSUE THREAD

**Issue by robertop87** [hakimel/reveal.js#1732]
It would be great can to get more than one single Reveal instances, and of course avoid the Global variable.

Expected result:
I can:

```

var leftSlider = new Reveal();
leftSlider.initialize();
...
var rightSlider = new Reveal();
rightSlider.initialize();
```

**Comment by alphatwit** [comment]
+1

**Comment by demoneaux** [comment]
Currently, it is not possible to have multiple instances of Reveal on 1 page. I don't think this will be on the roadmap for any future release. If you do want to have multiple presentations in the same page, your best bet currently is to embed multiple presentations is `<iframe>`s.

**Comment by xanisu** [comment]
+1 that would be an awesome improvement.

**Comment by joe733** [comment]
For future visitors: If you're looking for multiple presentation, it's implemented. Docs: https://revealjs.com/initialization/#multiple-presentations
