### ISSUE TITLE
SVG Animation with vivus

### ISSUE THREAD

**Issue by Barnados** [hakimel/reveal.js#1733]
Hi.

I wanted to animate the SVG Object with the plugin **vivus**.
https://github.com/maxwellito/vivus
 
AFAIK, i think it's possible to ask for the currentSlide and then trigger the Animation. I'm not really sure and don't gasp the whole project. Help would be appreciated.

**Comment by robertop87** [comment]
@Barnados This is a question for StackOverflow, please move it there.
http://stackoverflow.com/tags/reveal.js
