### ISSUE TITLE
codemirror integration?

### ISSUE THREAD

**Issue by titaniumbones** [hakimel/reveal.js#1735]
I would like to be able to include editable/runnable code in my slides.  Is there a working codemirror or ace implementation that would allow this? A bug was filed with codemirror in August (https://github.com/codemirror/CodeMirror/issues/4189) and closed as a "won't fix" -- I guess the author thought the issue was on the reval side. 

I don't know much about CSS scoping, so I'm not sure how hard it would be to fix the conflict -- how hard would it be to develop this feature and where would I have to start? 

Thank you for a great framework that I use on a daily basis. I'd love to be able to use it in classes in which I need to show running code.

**Comment by viebel** [comment]
Any update on this issue?

**Comment by titaniumbones** [comment]
Not from me. I would love to have a solution but have not had time to look into it.

**Comment by titaniumbones** [comment]
following up on #1760, the embedded codemirror instance displays poorly in the demo slideshow. I think there are some conflicts with reveal code, though I am not sure where they are exactly and an initial search only finds about 20 instances of `!important` which I had hoped would prove to be the origin of the problem.  

Can't attach an html file but in the dmeo try adding 
```html
                                        <pre><code class="language-klipse-eval-js">[1,2,3].map(function(x){ return x + 1;})
                                        </code></pre>
```
in a slide and 
```html
                <link rel="stylesheet" type="text/css" href="https://storage.googleapis.com/app.klipse.tech/css/codemirror.css">

                <script>
                  window.klipse_settings = {
                  selector_eval_js: '.language-klipse-eval-js', // css selector for the html elements you want to klipsify
                  };
                </script>
                <script src="https://storage.googleapis.com/app.klipse.tech/plugin_prod/js/klipse_plugin.min.js"></script>
```
at the end of the `body` tag, and I think you'll see what I mean. Tested on linux w/ chrome & firefox.

**Comment by viebel** [comment]
@hakimel could you help on this issue?

**Comment by titaniumbones** [comment]
@viebel could we start by building a repo or otherwise sharing a configuration that includes a minimal reveal slideshow with the klipse scripts linked in? then maybe we could start identifying individual issues (I think there are multiple problems maybe) and tackling them one at a time.

**Comment by titaniumbones** [comment]
also have you tried klipse in deck.js or other presentation prameworks? Would be good to know how much of the incompatibility is specific to reveal.

**Comment by titaniumbones** [comment]
I've just confirmed (I hthnk!), that klipse runs slmost perfectly in an iframe with a `srcdoc` attribute that looks like this:
```html
<iframe height="500px" width="100%" srcdoc='
<pre><code class="language-klipse-eval-js">[1,2,3].map(function(x){ return x + 1;})
  </code></pre>

  <link rel="stylesheet" type="text/css" href="https://storage.googleapis.com/app.klipse.tech/css/codemirror.css">

  <script>
    window.klipse_settings = {
    selector_eval_js: ".language-klipse-eval-js" // css selector for the html elements you want to klipsify
    };
  </script>
  <script src="https://storage.googleapis.com/app.klipse.tech/plugin_prod/js/klipse_plugin.min.js"></script>'>
</iframe>
```

So, if one wrote a plugin that transforms the appropriate `<pre><code src=...>` tags into iframes, I think it might work fine. You'd want to add at least a little cs as the default font sizes were pretty tiny on my laptop.  What do you think?

**Comment by viebel** [comment]
@titaniumbones that's fantastic. I made a [template of reveal slides with klipse](http://viebel.github.io/klipse/examples/reveal.html) based on your idea with interactive code snippets in javascript, clojure, ruby and python.

Have a look [here](http://viebel.github.io/klipse/examples/reveal.html).

**Comment by viebel** [comment]
And now - following your suggestion again - I have written a plugin that converts dom elements with `klipse-snippet` tag into iframes.

Here is a [demo](http://viebel.github.io/klipse/examples/reveal_with_klipse.html)

**Comment by titaniumbones** [comment]
This looks amazing, and so simple!  

I think we should figure out what further features it would be nice to have, implement them, and then set up a repo so we can distribute this as a separate plugin.  (where by "we" I probably mostly mean "you" since you are clearly much faster than me).  Here's my list -- should I be submitting these on your klipse demo site or is here good?:

- Allow user to set some CSS properties on load through a variable.  This will allow theming of CodeMirror, and also maybe control of the overall font sizing. One option I was thinking would be to look for a "codemirror.css" file in the current theme and load that in the iframe, what do you think?
- allow side-by-side code/evaluation windows -- seems like that might make better use of space in a wide screen.  I guess this could just be done with the above, so maybe this is still the same issue.  
- allow inclusion of other scripts in a particular code block, maybe with say "data-dependencies" attribute that adds script tags for jquery or angular or whatever.  This would be a nice way to set up an environment for learning object-oriented programming or whatever.  
- document this fully so that it's straightforward for users of other tools to build in support.  

Really psyched to have this working.  Neat to see your kids coding course. Do you like teaching with clojure? I don't use it at all but really wish I had started programming with a lisp dialogue so love the idea of it as a first language.

**Comment by titaniumbones** [comment]
Oh, and also, include the klipse sourccode in the plugin so that the klipse/codemirror code can be included in "packaged" presentations for use offline. I often distribute such offline-compatible presentations to students.
