### ISSUE TITLE
Finger Spread zoom??

### ISSUE THREAD

**Issue by kapelskic** [hakimel/reveal.js#175]
I am working on a project where we have basically a pdf of 4 pages we are putting into reveal to make it more interactive.  However, some of the content on the pages is really small and we want to be able to enlarge them with a finger spread on iPad.  Is there a way to do this?  I noticed you can double tap on the screen to have a slide zoom, which is okay, but it falls short of what we need.

I look forward to hearing from you guys!

**Comment by mispy** [comment]
Disabling overview no longer seems to work for this on Android Chrome. I've tried various permutations of the viewport tag and removing the reveal.js touch handlers also without any success. Troublesome!

**Comment by mispy** [comment]
Ah: it is the use of "touch-action: none" on .reveal that is the issue. Works if you override that!

**Comment by Twaanzin** [comment]
I'm currently working on a project and just can't get the pinch-zoom to work. I tried the "overview: false" option and with that I changed "touch-action: none" to both "auto" and "pinch-zoom". Both won't seem to work on my iphone SE. Not sure how it reacts on Android. On my latest test double tap worked on iOS but not on Android, and pinch to zoom on none.

If one of the options would work on both iOS and Android (preferably pinch-zoom) that would be great. Thanks in advance for all the well appreciated help:D

**Comment by tanmaym88** [comment]
I too can't get the pinhc-zoom to work on Chrome (Android).
The touch-action is set to pinch-zoom in reveal.css

Any help would be appreciated! 
Thanks

**Comment by peter-kehl** [comment]
The following `initial-scale=0.3, maximum-scale=10.0` makes zoom/scaling possible on mobile with reveal.js' c1c41452 (master as of mid Sep 2022, possibly with current release 4.3.1, too):

```
<meta name="viewport" content="width=device-width, initial-scale=0.3, minimum-scale=0.1,
		maximum-scale=10.0, user-scalable=yes">
...
<script>
Reveal.initialize({
// Standard config, keeping touch: true (as is default)
// ...
// Probably not very relevant:
				width: "100%",
				margin: 0,
```

However (in both current Firefox on Android cellphone, and Chrome on Android):
- `minimum-scale` seems ignored - the minimum (content size) we can scale to/zoom out to is the same as the initial. Please advise.
- You **can** scroll (the content) on mobile. However, it's almost impossible with one finger (as Reveal.js picks it up for the next/previous slide). Instead, use two fingers even for scrolling (both vertically and horizontally).
- Unfortunately, the bottom left menu (from `RevealMenu` plugin), the bottom progress bar and the bottom right previous/next slide arrows go out of view as you zoom in. This happens on a mobile, but not on desktop. Please advise.
