### ISSUE TITLE
iframe

### ISSUE THREAD

**Issue by lionpeloux** [hakimel/reveal.js#1763]
Hello,

I'm one the last commit on `dev` (at the time of this post).
It appears some iframe failed to load. Here is the console error from my browser :

```
17:27:21,551 Load denied by X-Frame-Options: https://fr.pinterest.com/lionpeloux/shading-device/ does not permit cross-origin framing. 1 (source inconnue)
```

It works fine with the example I found in the help files. 

```html
<section data-background-iframe="https://slides.com/news/make-better-presentations/embed?style=hidden&autoSlide=4000">
</section>
```

But not with my custom url.

```html
<section data-background-iframe="https://fr.pinterest.com/lionpeloux/shading-device/">
</section>
```

Any ideas how to sort that out ?
Tks,
Lionel

**Comment by demoneaux** [comment]
This is not related to Reveal.js. The site you are embedding appears to have set the `X-FRAME-OPTIONS` header to disallow embedding in iframes.
