### ISSUE TITLE
Feature Request: Ability to play thousands (infinite) of slides from JSON without bogging down

### ISSUE THREAD

**Issue by jtkeyva** [hakimel/reveal.js#1773]
300 slides is ok, but the more slides you have, the longer the delay between slides is. If you have a thousand slides, things get very sluggish.

Would be great if it worked kind of like an infinite scroller and maintained it's snappy response time between slides.

Thanks

**Comment by demoneaux** [comment]
There isn't such a way for now. Perhaps you could build a plugin and share it: https://github.com/hakimel/reveal.js/wiki/Plugins,-Tools-and-Hardware. Something similar might be this external HTML plugin: https://github.com/janschoepke/reveal_external
