### ISSUE TITLE
Mobile responsive with Reveal.js

### ISSUE THREAD

**Issue by sbsatter** [hakimel/reveal.js#1783]
I don't know if this is the perfect place to ask such a noob question, but I was wondering how to make my site (based on bootstrap and reveal.js) mobile responsive.
My slides have a lot of images on some of them. And such images are arranged in columns (3 in each row). But in mobile displays, each of them take up each row. 
Expected behavior: Each image show one below another, and the slide should stretch to cover all its contents.
Actual Behavior: The slide does extend to include them, however, as I scroll, it goes to the next slide. Like I cannot scroll within this slide.
![sym](https://cloud.githubusercontent.com/assets/8899816/21572130/29b9b9ba-cf00-11e6-983c-8437d214b80f.png)
![sym1](https://cloud.githubusercontent.com/assets/8899816/21572131/29baa1b8-cf00-11e6-9c7b-71455ce13031.png)

**Comment by demoneaux** [comment]
This is not really a Reveal.js issue, and I don't have experience with Bootstrap. Perhaps asking on StackOverflow with more info would be better. IMO, the Bootstrap code you are using for the columns might be responsive, so the grid changes from columns to rows on smaller viewports.
