### ISSUE TITLE
Play/Pause Controls

### ISSUE THREAD

**Issue by jessejamesrichard** [hakimel/reveal.js#1785]
I'm a little confused about how the play and pause button images are being inserted into class playback? I want to remove them and/or replace them, but I dunno how they're being rendered.

**Comment by hakimel** [comment]
I assume you're referring to the auto-slide controls in the bottom left? Those are painted on a <canvas> element so the only way to change them is to edit this part of the reveal.js source: https://github.com/hakimel/reveal.js/blob/master/js/reveal.js#L4745-L4759

**Comment by MartinStettner** [comment]
The controls are drawn using a canvas element which has the CSS class "playback". So if you just want to hide the playback controls you can add a CSS rule

    .playback { display: none; }

**Comment by elnisi** [comment]
```
Reveal.initialize({ 
     autoSlideStoppable: false 
});
```
