### ISSUE TITLE
CSS conflicts with CodeMirror

### ISSUE THREAD

**Issue by viebel** [hakimel/reveal.js#1788]
When including a codemirror editor inside a reveal page, there is a css conflict and the codemirror editor looks very bad and is not very usable (you cannot navigate the code properly).

Look at this page that reproduces the issue: http://viebel.github.io/klipse/misc/reveal-codemirror.html.

I have also opened and issue on [CodeMirror repo](https://github.com/codemirror/CodeMirror/issues/4189)

I have tried to put codemirror editor inside a web component but it didn't help a lot. Here is a [demo](http://viebel.github.io/klipse/misc/codemirror-reveal-webcomponent.html).

Please help or at least provide a workaround: I really need a way to integrate those 2 amazing projects.

**Comment by demoneaux** [comment]
The reveal.js styles are for the whole document and are bound to modify some of CodeMirror's styling. Unfortunately, I don't have time to look into it, but feel free to send a PR or more information about which styles are conflicting so we can look into modifying that.

**Comment by kno10** [comment]
The problem is the CSS `transform` used by reveal.js to fit slides to the browser window size.

Codemirror appears to rely on `getClientRects` for drawing cursors and interpreting clicks, and this method reportedly does not take CSS transforms into account. The problem supposedly disappears if you set minScale:1, maxScale:1

<https://github.com/codemirror/dev/issues/324>

**Comment by kno10** [comment]
Possible work-around:
```js
Reveal.on('resize', (event) => {
 let scale="scale("+(1/event.scale)+")";
 document.getElementsByClassName('CodeMirror').forEach((x)=>{
   x.CodeMirror.display.cursorDiv.style.transform=scale;
   x.CodeMirror.display.cursorDiv.style.transformOrigin="0 0 0";
   x.CodeMirror.display.selectionDiv.style.transform=scale;
   x.CodeMirror.display.selectionDiv.style.transformOrigin="0 0 0";
})});
```
