### ISSUE TITLE
Include slide number in speaker notes view

### ISSUE THREAD

**Issue by malcomio** [hakimel/reveal.js#1791]
It would be very useful to display the current slide number and the total number of slides in the speaker notes view, along with the time

**Comment by kilinkis** [comment]
I fully agree with @malcomio

**Comment by malcomio** [comment]
I was able to achieve this by editing the conditions at https://github.com/malcomio/reveal.js/blob/master/js/reveal.js#L911

```
dom.slideNumber.style.display = config.slideNumber && !isPrintingPDF() && isSpeakerNotes() ? 'block' : 'none';
```

it's a bit hacky, but it works for my purposes, because I won't ever want to include the slide number in the presentation view

ideally there would also be a config option to determine which view the number appears on

**Comment by malcomio** [comment]
I've attempted to address this with a configurable option in #1833
