### ISSUE TITLE
Specify order in which fragments are displayed (improved)

### ISSUE THREAD

**Issue by AlexandreDecan** [hakimel/reveal.js#1793]
Hello,

I really appreciate reveal.js. There's one thing that bothered me for a while: while it is possible to specify in which fragments should be displayed, using data-fragment-index, the fragments that are not annotated with this attribute are always displayed after the ones that are annotated with the attribute. 

Say you have 10 fragments, and you want to invert the order between the 5th and the 6th, then you need to put a ``data-fragment-index`` in at least the first 6th fragments (1, 2, 3, 4, 6, 5). I prefer a solution in which you just have to specify that the 5th fragment has index 6, and the 6th fragment has index 5. 

The code below allows you to do that, using the ``data-index`` attribute. The code mainly computes a new value of ``data-fragment-index`` based on the specified ``data-index``. 

Notice that this code relies on Jquery, but it should be quite easy to remove this dependency (I'm not fluent in JS, so I didn't try ^^). 

```Javascript
// Automatic fragment numbering
var fragmentNumbering = function ( event ) {
  var fragments = $(event.currentSlide).find('.fragment');
  var order = new Array(fragments.length);
  
  $(fragments).filter('[data-index]').each( function () { 
    var index = parseInt($(this).attr('data-index')) - 1;
    if (index < 0 || index >= order.length) {
      alert('Invalid data-index: ' + index);
      return;
    }
    if (typeof order[index] == 'undefined') {
      order[index] = [ $(this) ];
    } else {
      order[index].push($(this));
    }
  });
  
  var index = 0;
  $(fragments).not('[data-index]').each( function () {
    while(typeof order[index] != 'undefined') {
      index = index + 1;
    }
    order[index] = [ $(this) ];
  });
  
  $(order).each( function (index) {
    $(this).each( function () { 
      $(this).attr('data-fragment-index', index);
    })
  });
};
Reveal.addEventListener('ready', fragmentNumbering);
Reveal.addEventListener('slidechanged', fragmentNumbering);
```

Here's an html sample:
```html
<section>
	<h2>Fragments order</h2>
	<p class="left">
		Control fragment order by using <span class="warning">data-index</span>, a variation around <span class="warning">data-fragment-index</span> that takes existing unindexed fragments into account.
	</p>
	<p>Example: 
		<span class="fragment" data-index=2>2</span>
		<span class="fragment">1</span>
		<span class="fragment" data-index=4>4</span>
		<span class="fragment">3</span>
		<span class="fragment" data-index=4>4</span>
		<span class="fragment">5</span>
	</p>
</section>
```

**Comment by AlexandreDecan** [comment]
I close it as it is not an issue, just some trick I wanted to share.

**Comment by apotonick** [comment]
Thank you, this is fantastic and an excellent trick I now use in all presentations! :heart:

**Comment by AlexandreDecan** [comment]
You're welcome ;)

**Comment by Hexanders** [comment]
Thank you, this is a very nice solution.
Could it be that this destroys the id tag of the element?
I am relying on the svg animation which is set at the aperning of the svg object. 
With your approach the animation does not restart because I no longer have access to the id tag.
Do you have a solution? I am too inexperienced to solve this myself.

**Comment by AlexandreDecan** [comment]
I'm sorry I don't know.
