### ISSUE TITLE
Lower case #+begin_notes blocks aren't rendered as notes

### ISSUE THREAD

**Issue by deerpig** [hakimel/reveal.js#1806]
When inserting speaker notes:

This works:
#+BEGIN_NOTES
#+END_NOTES

This doesn't export as notes:
#+begin_notes
#+end_notes

I use lower case for #+begin_source, #+begin_quote etc without any problem, mostly because it's easier on my eyes.  Is anyone else having this problem?

**Comment by demoneaux** [comment]
This seems to be the wrong place for this issue. Try opening an issue here: https://github.com/yjwen/org-reveal
