### ISSUE TITLE
Improve doc for external markdown on Windows

### ISSUE THREAD

**Issue by saidelike** [hakimel/reveal.js#1808]
Regarding https://github.com/hakimel/reveal.js/#external-markdown

Might be worth having a note that for windows it would need to be \r\n (instead of \n) to have it working right away?

                <section data-markdown="slides.md"  
                         data-separator="^\r\n\r\n\r\n"  
                         data-separator-vertical="^\r\n\r\n"  
                         data-separator-notes="^Note:"  
                         data-charset="iso-8859-15">
                </section>

**Comment by TiemenSch** [comment]
I was experiencing this exact problem. Thanks so much for handing me the workaround right away!
