### ISSUE TITLE
window focus is lost after returning from fullscreen in safari and vivaldi

### ISSUE THREAD

**Issue by Frazer** [hakimel/reveal.js#1817]
In safari and vivaldi keyboard control doesn't work after returning from full screen.
A mouse click in the screen will make it work again, but window.focus() will not.

In your demo vivaldi escape can not exit full screen as it changes to slideOverview mode. I've reported that to vivaldi.  I don't use esc for overview, so esc exits full screen for me, but I have still lost keyboard control of the screen after that.

Oh, I found a kind-of-solution:

    function enterFullscreen() {

        var element = document.documentElement;

        // Check which implementation is available
        var requestMethod = element.requestFullscreen ||
             element.webkitRequestFullscreen ||
             element.webkitRequestFullScreen ||
             element.mozRequestFullScreen ||
             element.msRequestFullscreen;

         if( requestMethod ) {
             requestMethod.apply( element );
         }
	
         document.addEventListener('webkitfullscreenchange', regainFocusOnExitFullScreen, false);
         document.addEventListener('mozfullscreenchange', regainFocusOnExitFullScreen, false);
         document.addEventListener('fullscreenchange', regainFocusOnExitFullScreen, false);
         document.addEventListener('MSFullscreenChange', regainFocusOnExitFullScreen, false);
			
    }

    function regainFocusOnExitFullScreen(textabc){
         if(!(document.webkitIsFullScreen || document.mozFullScreen || document.msFullscreenElement)){
             document.querySelector('.navigate-left').focus();
             document.removeEventListener('webkitfullscreenchange', regainFocusOnExitFullScreen, false);
             document.removeEventListener('mozfullscreenchange', regainFocusOnExitFullScreen, false);
             document.removeEventListener('fullscreenchange', regainFocusOnExitFullScreen, false);
             document.removeEventListener('MSFullscreenChange', regainFocusOnExitFullScreen, false);
        }
     }

The  querySelector('.navigate-left')   is not guaranteed to work if the user doesn't have controls visible. I'm not sure what to use as a general case.

**Comment by Frazer** [comment]
I've asked for a general solution here: http://stackoverflow.com/questions/42059152/how-to-return-keyboard-focus-to-screen-in-safari-after-exiting-fullscreen

**Comment by Martinomagnifico** [comment]
Hi Frazer, this is no longer an issue in both Safari and Vivaldi. See any embedded Reveal presentation. Going out of fullscreen keeps the focus and users can keep interacting with it.
