### ISSUE TITLE
Code highlighting enters very slow loop on some C# templates

### ISSUE THREAD

**Issue by Siderite** [hakimel/reveal.js#1822]
Simple code:
```
<pre><code class="hljs">
    private static void ensureContainer()
    {
        if (_container != null) return;
        lock(_lock)
        {
            if (_container != null) return;
            _container = new Container();
            _container.Register&lt;IWorldDominator, WorldDominator&gt;();
            _container.Register&lt;ITanks, Tanks&gt;();
            ...
        }
    }
</code></pre>
```
It makes the page load for a long time in order to highlight the code. If I remove the Register lines, the problem disappears.

**Comment by demoneaux** [comment]
Not too sure what's causing this, will try to debug soon.

**Comment by BDav24** [comment]
Upgrading highlight.js to v9.12.0 seems to fix the problem.

**Comment by bnjmnt4n** [comment]
Closing as highlight has been updated to a more recent version and we can't duplicate this anymore.
