### ISSUE TITLE
 Lost reveal.js fragment IDs in address bar

### ISSUE THREAD

**Issue by reagle** [hakimel/reveal.js#1829]
This [1] may be because of the template pandoc uses, but, if so, I'd like to fix that as well.

> [changing fragment id] was nice because when I edited a slide in markdown, I could generate the slides, refresh, and---unless I change the title/header---see the changes without having to navigate to that slide again. Also, I could easily send a link to a single slide to someone else.
> 
> Now, the URL in the address bar stays the same regardless what slide I'm on (e.g., [2]).

[1] https://groups.google.com/forum/#!msg/pandoc-discuss/1EefbbV3g5k/m4yYtDf3CQAJ

**Comment by reagle** [comment]
Here is an example, as you browse the slides, the URL fragment ID doesn't change. What could this be?

<http://reagle.org/joseph/2017/cda/talks/080-social-know-how.html>

**Comment by demoneaux** [comment]
You'll need to enable the `history` option to let the fragment change.

**Comment by reagle** [comment]
Okay, thanks, I will investigate. (BTW: Sorry, I just saw this was discussed on the pandoc-list but I didn't get those email, but see them in the archive.)
