### ISSUE TITLE
Example socket.io server is down

### ISSUE THREAD

**Issue by saulirajala** [hakimel/reveal.js#1830]
Example socket.io server (https://reveal-js-multiplex-ccjbegmaii.now.sh/) gives you the following error message:
"502 | An error occured with your deployment."

Do you know why and can you do anything about it?

**Comment by kylerschin** [comment]
This is a server error, a developer will need to handle this.

**Comment by saulirajala** [comment]
Yes and I noticed, that you can (and actually should, if you plan to use multiplexing in real life) deploy your own socket.io with now.sh -service ([https://zeit.co/now](https://zeit.co/now)). There is free account available with some basic functionality, which are enough for running socket.io server. I wrote some instructions about this in my blog ([http://irajala.com/2017/02/deploying-socket-io-server/](http://irajala.com/2017/02/deploying-socket-io-server/)).

So I think we can close this issue, even though it might be a good idea to add some notice to README about deploying your own socket.io server using now.sh?

**Comment by hakimel** [comment]
Looks like the example server is back up again.

There's a package.json in the multiplex dir specifically for deploying with now. So deployment is as easy as running `now plugin/multiple`. I've added a note about this to the README in 5565d0861260c62f20f9ad5211aea697b4e8a0cc.

**Comment by harish1996** [comment]
> Looks like the example server is back up again.
> 
> There's a package.json in the multiplex dir specifically for deploying with now. So deployment is as easy as running `now plugin/multiple`. I've added a note about this to the README in [5565d08](https://github.com/hakimel/reveal.js/commit/5565d0861260c62f20f9ad5211aea697b4e8a0cc).

I followed the instructions to deploy a socket server. But `now plugin/multiplex` is now throwing an error saying that package.json file doesn't have "build" property under "scripts" property.

I think this is due to the fact that zeit has moved to now 2.0. I have very little knowledge about this. Is there are a way to fix this ?
