### ISSUE TITLE
Prezi "Path tool" equivalent 

### ISSUE THREAD

**Issue by fsdias** [hakimel/reveal.js#1838]
Is it possible to display slides along a big background image? For instance have an .svg image of a tree and display slides along its branches.

In Prezi this can be done using a "Path tool" and by creating and place frames/slides in different places of the background images. See this link:

https://prezi.com/support/article/creating/setting-your-prezis-path-adding-a-slide/

**Comment by demoneaux** [comment]
There isn't such an equivalent for now. Reveal's slides follows a structured approach as compared to Prezi's free flowing and flexible slides. If you're interested in something similar you can look at https://github.com/impress/impress.js.
