### ISSUE TITLE
Show only left/right control arrows

### ISSUE THREAD

**Issue by annasimoniaine** [hakimel/reveal.js#1839]
Is there an easy way to show only horizontal navigation arrows and not the up/down buttons? For a strictly horizontal presentation it might be confusing to show vertical controls that don't do anything.

**Comment by egrosclaude** [comment]
I second. Plus, they take too much real estate in mobile screens.

**Comment by annasimoniaine** [comment]
I ended up just adding the following css:

```
.reveal .controls .navigate-down, .reveal .controls .navigate-up {
    display: none;
}
```

**Comment by demoneaux** [comment]
For now CSS is a good way to do it.
