### ISSUE TITLE
Replicating a control in the slide

### ISSUE THREAD

**Issue by dandv** [hakimel/reveal.js#184]
User testing has shown that some people just don't quite notice the controls changing color to indicate there's more content in the vertical slides, so I've added a footer to those slides, saying "...more below". In the footer, I'd like to replicate the down arrow of the controls, with all its properties - styling, clickable, going to the next slide, whichever that slide is (so no hard-coded anchors).

Same for a "...back up" footer that would need the up arrow control.

Below is a screenshot of what I'm trying to accomplish. What is the best way of duplicating a control in a slide?

![screenshot](http://i.imgur.com/YchxD.png)

**Comment by samiahmed321** [comment]
hello friends  i need help in adding control buttons in presentation
