### ISSUE TITLE
MathJax dependency turns my presentation blank

### ISSUE THREAD

**Issue by ericbarnhill** [hakimel/reveal.js#1850]
When I add the suggested statement

{ src: 'plugin/math/math.js', async: true }

to the dependencies, my entire presentation turns blank from this statement alone.

This happens in both browsers I have available, Chromium and Firefox. Is there an additional step I have forgotten?

**Comment by ericbarnhill** [comment]
The answer to this bug, is that one's presentation has to have the filename index.html in order to use the math dependency. It is now working for me, but that was a lot of panic -- consider whether you might develop math.js to be used for an HTML file of any name.

**Comment by demoneaux** [comment]
There doesn't seem to be a reason why the filename should affect the rendering. This is probably a one off config error. Feel free to reopen if you encounter anything similar.
