### ISSUE TITLE
Add Prism as an alternative highlighter

### ISSUE THREAD

**Issue by astorije** [hakimel/reveal.js#1852]
[Prism](http://prismjs.com/) is another syntax highlight library that can be useful for languages that highlight.js doesn't support yet (for example [GraphQL](https://github.com/isagalaev/highlight.js/issues/1471)).

It would be really cool to provide a reveal.js-enhanced version of it in this repo similar to the [modified version of highlight.js](https://github.com/hakimel/reveal.js/blob/master/plugin/highlight/highlight.js).

**Comment by demoneaux** [comment]
This can probably be maintained as an external plugin as we want to keep the reveal.js core plugins small. Feel free to make a plugin and share it!
