### ISSUE TITLE
AsciiDoc support

### ISSUE THREAD

**Issue by manoelcampos** [hakimel/reveal.js#1861]
[Asciidoc](http://asciidoctor.org) is a very efficient and full-featured format to enable developers to write documentation, mainly when the presentation of code snippets is concerned. It enables developers to easily include blocks from source code files, preventing the documentation to become out-of-date when those files are updated. It completely makes unnecessary to use copy-and-paste to write documentation.

AsciiDoc support will enable developers to write their slides using a more powerful format than Markdown and may encourage other ones to start using reveal.js. Since AsciiDoc is already supported everywhere, it would be possible to host AsciiDoc slides in services such as GitHub pages yet.

**Comment by demoneaux** [comment]
Hi @manoelcampos! This is a perfect fit for a plugin, so as to allow the Reveal.js core library to remain lean. Feel free to add it here if you do make it: https://github.com/hakimel/reveal.js/wiki/Plugins,-Tools-and-Hardware
