### ISSUE TITLE
Printing: Every second page empty

### ISSUE THREAD

**Issue by Skyr** [hakimel/reveal.js#1862]
When printing (appending ?print-pdf, then using the browser's print function) with Chromium on Fedora 24 (56.0.2924.87), every second page is empty.
Tried it with demo.html.
Problem occurs on master, v3.4.1, v3.4.0.
v3.3.0 is unaffected.

**Comment by hakimel** [comment]
Thanks for reporting. This previously reported and fixed in #1804. Not sure why it started happening again but I've reopened the original issue and am closing this.

**Comment by Skyr** [comment]
Thanks for looking into it!
