### ISSUE TITLE
WARNING cdn.mathjax.org end-of-life IN 5 DAYS

### ISSUE THREAD

**Issue by Naereen** [hakimel/reveal.js#1880]
Apparently, the main branch still uses the official MathJax CDN. WARNING It closes **in 5 days**! :boom: !

See https://www.mathjax.org/cdn-shutting-down/ for more details on migrating to another service.

> Basically, a complete find-and-replace of `https://cdn.mathjax.org/mathjax/2.7-latest/` (as is used right now) to `https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/` could probably be enough.
> But I prefer to let you chose which CDN to use instead of filing a pull request, hence this issue.

**Comment by hakimel** [comment]
Thanks for reporting! A fix (#1866) for this was already merged into the dev branch. I've added that to master now as well and it will be included in the 3.5.0 release.
