### ISSUE TITLE
Speaker notes broken in 3.5.0 release (in Safari)

### ISSUE THREAD

**Issue by gcalmettes** [hakimel/reveal.js#1883]
The speaker notes interface appears blank in the new 3.5.0 release (see screen capture below).
Tested with the demo file or a personal slideshow that was working fine in 3.4

UPDATE: the problem is specific to Safari. The speaker notes work fine on Chrome
![Imgur](http://i.imgur.com/oVk60VU.png)

**Comment by mosabua** [comment]
uff .. thats a deal breaker for upgrading. Thanks for noticing before I make that step.

**Comment by hakimel** [comment]
I've tested the 3.5.0 speaker view in both Safari and Chrome but didn't run into any issues. The speaker view tends to be cached pretty hard, would you mind trying Safari again with a clear cache?

**Comment by gcalmettes** [comment]
Tried Safari with a clear cache (and also tried the "Safari Technology Preview" version), but the speaker notes still get stuck.
When I launch the javascript console, this is the error that cycles:
![Imgur](http://i.imgur.com/wznw8Wv.png)

**Comment by hakimel** [comment]
Thanks for the info. Looks like the main window is having issues posting updates to the notes window, although I'm not sure why.

**Comment by gcalmettes** [comment]
I'll try to see if I can isolate the problem, and post the updates here.

**Comment by phillord** [comment]
Also broken in Firefox, running under Ubuntu. This is tested on both my own slides and on http://lab.hakim.se/reveal-js/#/. The slides function with chromium.

**Comment by nIQnutn** [comment]
Same here with Firefox ESR 52.3.0 (64 bits) on Debian.

**Comment by nIQnutn** [comment]
now working on http://lab.hakim.se/reveal-js/#/
also tested on dev branch

**Comment by gcalmettes** [comment]
Working with Safari too now! Closing the issue.
