### ISSUE TITLE
Live reload not working

### ISSUE THREAD

**Issue by apieceofbart** [hakimel/reveal.js#1889]
I have forked the repo, installed dependencies and I am running with `npm start` . Everything works fine except the live reload option. `watch` tasks works fine but browser is not being refreshed. 
There's an error in console coming from `livereload.js` : `Failed to load resource: net::ERR_ADDRESS_INVALID`

I am on Windows 7 using chrome 57.

**Comment by apieceofbart** [comment]
Ok, this exactly this issue: https://github.com/livereload/livereload-js/issues/50
I think you can close this.

**Comment by apieceofbart** [comment]
if anyone is struggling with this the quick fix is to add this to `grunt-contrib-connect` config in options in Gruntfile:
`hostname: 'localhost`

**Comment by allenGKC** [comment]
If this hostname is set, on MacOS is still working？

**Comment by apieceofbart** [comment]
@allenGKC I cannot verify this but I'm pretty sure it would work.

**Comment by allenGKC** [comment]
@apieceofbart Thanks buddy, I have tried in MacOS，and it works well.

**Comment by bityob** [comment]
I had the same issue now, needed to add the `hostname` field, and comment `useAvailablePort` field.

`Gruntfile.js` connect before - 
```
connect: {
	server: {
		options: {
			port: port,
			base: root,
			livereload: true,
			open: true,
			useAvailablePort: true
		}
	}
},
```

`Gruntfile.js` connect after - 
```
connect: {
	server: {
		options: {
			hostname: 'localhost',
			port: port,
			base: root,
			livereload: true,
			open: true,
			//useAvailablePort: true
		}
	}
},
```

**Comment by blachawk** [comment]
Live reloading still does not work.  Changes do occur, but we have to manually refresh the browser to see them...

**Comment by blachawk** [comment]
There is a good chance that this is an issue with FireFox. Simply run the same project in a different browser or in incognito mode to see the difference.  You can research and see what settings in your FireFox browser is causing the issue.  More on that here.
