### ISSUE TITLE
Conditional slide configuration

### ISSUE THREAD

**Issue by seidgy** [hakimel/reveal.js#1892]
I'd like to know if there's a way of configuring a slide based on a condition. In my example I'm building a slide presentation and I'd like to setup a video background for a slide but if the user is accessing it in portrait orientation (mobile phones), I'd like to use a image as background instead.

**Comment by bnjmntn** [comment]
This is posible, but you'll probably have to do it yourself. For example, listen to the `ready` event, then check the conditions (mobile phones, etc.), then modify the DOM, and call `Reveal.layout()`.
