### ISSUE TITLE
Client does not follow master on URL open

### ISSUE THREAD

**Issue by OleMussmann** [hakimel/reveal.js#1896]
I would like to jump to specific slides on the master presentation with URLs on RFID tags. The master-client setup works well for slide changes. It does, however, not work for opening URLs. Once I manually change slides on the master, the client 'locks' on again, and follows. Is there any way to make the client follow on opening URLs?

**Comment by OleMussmann** [comment]
Fixed in [pull request 1917](https://github.com/hakimel/reveal.js/pull/1917).

**Comment by bnjmntn** [comment]
Closed by #1917.
