### ISSUE TITLE
incorrect rendering of C++ include statements in code blocks and markdown

### ISSUE THREAD

**Issue by vlazzarini** [hakimel/reveal.js#1899]
I am trying to put the following code in a reveal.js presentation:

``` c++
#include <plugin.h>
struct MyPlug : csnd::Plugin<1,1> { };
```

If I use pre and code, the rendering becomes 

``` c++
#include <plugin.h>
struct MyPlug : csnd::Plugin<1,1> { };
<\plugin.h>
```

if I use markdown, it becomes

``` c++
#include 
struct MyPlug : csnd::Plugin<1,1> { };
```

I could not find any one with the same issues, so I am wondering what the problem is, and whether it is possible to do this at all.

**Comment by vlazzarini** [comment]
As an update, I was able to solve the problem with markdown by adding the code inside textarea, but not with pre and code.

**Comment by demoneaux** [comment]
This is because the browser will treat the `<>` brackets as a HTML tags. To solve this, you'll have to either use `data-markdown` with a script or textarea with `type="text/template"` or encode the characters using `&lt;` and `&gt;`.
