### ISSUE TITLE
Features question

### ISSUE THREAD

**Issue by berserk82** [hakimel/reveal.js#1900]
Hello there.
My name is Ivano Arrighetta and I'm Italian.
I wonder if Reveal.js supports the following features:
slide masters (applying a single style to multiple slides)
formatting text
adding formulas
creating bulleted/numbered lists
text boxes (creating tables, inserting links)
inserting and transforming media elements (images, audio, video, charts - translate/rotate/scale)
export pdf/html
undo
redo
cut
copy
paste
save/export
new
close
open
delete
help link
quit
zoom

Thanks in advance for any help.

Bye, Ivano.

**Comment by bnjmntn** [comment]
Reveal.js presentations are made by editing HTML, using your text editor. Most of the features you seen to be more visual, so you might want to look at a visual editor, such as https://slides.com, which is built on Reveal.js.
