### ISSUE TITLE
How to set extertal markdown table style

### ISSUE THREAD

**Issue by databill** [hakimel/reveal.js#1901]
I have several table in external markdown file. The length of each line in one of the table is relative longer. In my mbp, I even can not see line 6 and it will be worse when I open it in a bigger monitor(4K). The font-size becomes bigger while less lines can be shown on the screen.

In the inline markdown file, I can add a customized style in section. When I try to add section style in the external markdown file, none can succeed. I even can not set class style for this table.

How to set the length and font-size for this table?

| Title | List | Notes |
| :--- | :---| :---|
| This is long line for one<br>Location1 | List 1 | |
| This is long line for two<br>Location2 | List 2 | |
| This is long line for three<br>Location2 | List 2 | |
| This is long line for four<br>Location2 | List 2 | |
| This is long line for five<br>Location2 | List 2 | |
| This is long line for six<br>Location2 | List 2 | |

**Comment by bnjmnt4n** [comment]
I'm not too sure what you're referring to, but if you do want to do extensive styling of certain slides, I would recommend adding a class/ID to the slide/table and styling it in CSS instead.

**Comment by swill** [comment]
@bnjmnt4n How do you add a class to a markdown table?

**Comment by databill** [comment]
hi @swill , I use in this way,

1. add a narrow class in the css file:
.narrow p
{
    margin: 5px 0;
}

.narrow li
{
    font-size: xx-large;
}

.narrow blockquote
{
    width: 90%;
    margin: 10px auto;
    padding: 10px;
}

.narrow td
{
    font-size: 26pt;
}

.narrow pre
{
    width: 500px;
}

2. use the "narrow" class in the markdown file

**Comment by swill** [comment]
Unfortunately that requires that I have predefined the class.  I have already done this in some cases, but I would prefer to be able to do something like this.

`<!-- .element: style="font-size:80%;" -->`

But there is no way to apply this to a table (or a code block for that matter).

For a code block, I often want to do something like this:

`<!-- .element: style="width:50%; float:right;" -->`

There does not seem to be a way to apply these details to either `table` or `code` elements which is really unfortunate.

**Comment by georgms** [comment]
> Unfortunately that requires that I have predefined the class. I have already done this in some cases, but I would prefer to be able to do something like this.
> 
> `<!-- .element: style="font-size:80%;" -->`
> 
> But there is no way to apply this to a table (or a code block for that matter).
> 
> For a code block, I often want to do something like this:
> 
> `<!-- .element: style="width:50%; float:right;" -->`
> 
> There does not seem to be a way to apply these details to either `table` or `code` elements which is really unfortunate.

Is there a solution for this?

**Comment by swill** [comment]
@georgms I have not found a solution to these issues.  I would welcome others input if they have solved the problem.

**Comment by nabilbendafi** [comment]
@swill @georgms Sorry to come late to the _party_
If using `Markdown` plugin, you can achieve what you want simply like this:
```
| Title | List | Notes |
| --- | --- | --- |
| This is long line for one Location1 | List 1 <!-- .element: style="font-size:50%;" --> | |
| This is long line for one Location2 | List 2 | |
<!-- .element.table: style="font-size:50%;" -->
```

So you can both apply size to whole table and override individual cell, if needed.
⚠️ Here `List 1` will be display as 50% of the 50% font applied to the table (so 25% of the slide font).

And of course this also applies to `code` blocks

~~~
```bash
echo "RevealJS THE HTML PRESENTATION FRAMEWORK"
```
<!-- .element.table: style="font-size:50%;" -->
~~~

No additional css involved.
