### ISSUE TITLE
General features

### ISSUE THREAD

**Issue by berserk82** [hakimel/reveal.js#1902]
Hello again. I wonder if this project does support the following features:
undo
redo
cut
copy
paste
save/export
new
close
open
zoom

Thanks in advance for either.

Bye, Ivano.

**Comment by jdittrich** [comment]
hello @berserk82. No, it does not since creating the slides is done with a normal text editor via writing HTML. In your text editor, you can have these features.

**Comment by demoneaux** [comment]
Yep, as mentioned by @jdittrich, you can create presentations only by editing HTML, using your text editor. Alternatively, if you want a more visual approach, you can use https://slides.com.
