### ISSUE TITLE
rendering of js-sequence-diagrams sometimes not correct.

### ISSUE THREAD

**Issue by sander76** [hakimel/reveal.js#1906]
I am using the following libary to generate sequence diagrams:
https://bramp.github.io/js-sequence-diagrams/
I implement it as follows:

```html
<section>
    <div id="chart-internet" class="diagram"></div>
</section>
```

inside the script tag after the Reveal.initialize() method I put:
```javascript
var _chart1 = Diagram.parse("A->B: Message"); // generates a svg sequence diagram.
_chart1.drawSVG('chart-internet'); // looks for a div with id "chart-internet" and puts the generated svg inside.
```

But now I run into sizing issues: Sometimes the diagram scales correctly. Sometimes it is just way too small. A refresh of the browser solves this, but it would be nice to not having to do this.

Anyone any ideas ?

Thanks !

**Comment by egrosclaude** [comment]
FWIW, I happen to use Snap.svg just like this library does, and I have exactly the same issue sometimes. Can't figure it out.

**Comment by bnjmntn** [comment]
I think you can try to fix this by calling `Reveal.layout()` after plotting your charts/diagrams.
