### ISSUE TITLE
Video.js and MediaElement playlist not working with Reveal.js

### ISSUE THREAD

**Issue by gabriellluz** [hakimel/reveal.js#1907]
I've tried many playlist scripts and none of them actually worked with Reveal.js. I've tried Video.js and MediaElement and even others. If I enable autoPlayMedia and if I use a video playlist on the third slide, when I play the first slide, the video gets played on the third slide but I can hear the sound on the first slide. Any way to improve my code? Or maybe there is a way to create a fully functional playlist that actually works with Reveal.js? Please help.
Below MediaElement.js code:

				`<video 
				class="mep-playlist" 
				data-showplaylist="true" 
				width="530" 
				height="300" 
				poster="poster.png" 
				
				
				<source src="http://gemusteste.novohamburgo.rs.gov.br/temp_videos/[SMS]aids_vt_30segundos.mp4"  type="video/mp4"  title="Track 1">
				
				<source src="http://gemusteste.novohamburgo.rs.gov.br/temp_videos/[SMS]COMBATE-A-TUBERCULOSE_30s.mp4"  type="video/mp4"  title="Track 2">
				
				<source src="http://gemusteste.novohamburgo.rs.gov.br/temp_videos/[SMS]Filme_Tarde_HD_30s.mp4"  type="video/mp4"  title="Track 3">
				
				<img src="no-video-playlist.png" title="No video playlist capabilities.">
				</video>

		<script>
			$(function () {

				// both video playlists(regular and slider)
				$('video.mep-playlist').mediaelementplayer({
					"features": ['playlistfeature', 'prevtrack', 'playpause', 'nexttrack', 'loop', 'shuffle', 'current', 'progress', 'duration', 'volume', 'playlist', 'fullscreen'],
					"shuffle": true,
					"playlist": true,
					"playlistfeature": true,
					"shuffle": true
				});

				// audio playlist
				$('audio.mep-playlist').mediaelementplayer({
					"features": ['playlistfeature', 'prevtrack', 'playpause', 'nexttrack', 'loop', 'shuffle', 'current', 'progress', 'duration', 'volume', 'playlist'],
					"audioVolume": "vertical", // just like video player
					"shuffle": false,
					"loop": false
				});

				// regular video
				$('video:not(.mep-playlist)').mediaelementplayer({
					"features": ['playpause', 'current', 'progress', 'duration', 'tracks', 'volume', 'fullscreen'],
				});

			});
		</script>`

**Comment by bnjmntn** [comment]
Personally, I'm not too familiar with Video.js and MediaElement. You might want to prevent autoplay on such libraries, then listen to Reveal's `onslidechange` event, and play/stop the video based on that.
