### ISSUE TITLE
Be able to create slide templates

### ISSUE THREAD

**Issue by CrazyTuna** [hakimel/reveal.js#1910]
I'd like to be able to create slide templates (with header and footer for example) and use it when needed.
Something like that

    <script type = "text/template" id="#template1">
        <section>
            <div class="header"><div>
            <div class="footer"><div>
            <div class="content">
                
            <div>
        </section>
    </script>

And use it like that:

    <section data-template-id="#template1">
        ...
    </section>

Anyway you're doing an awesome work with your framework  !!

**Comment by jcamp** [comment]
I use the framework with Smarty template language - works a treat and can integrate to DB for full templating really well.

**Comment by CrazyTuna** [comment]
thanks, I'll give it a try :-)

**Comment by bnjmntn** [comment]
This seems too specific for the Reveal.js core library, which we are trying to keep lean. As mentioned, perhaps you could try using an external tempting library or plugin.
