### ISSUE TITLE
External Markdown notes not hidden in PDF

### ISSUE THREAD

**Issue by codedge** [hakimel/reveal.js#1913]
When having each slide in an external `.md` file including speaker notes, these are printed in the PDF - although `showNotes` is set to false.

You can check this on http://dockerized-web-dev.codedge.de/?print-pdf or see it here:

<img width="1146" alt="markdown_notes" src="https://cloud.githubusercontent.com/assets/4409904/26730896/b6e48a74-47b2-11e7-963f-679e6ad38597.png">

There is not container around the notes so that they can be hidden with CSS. 

Any idea how hide them in PDF export?

**Comment by hakimel** [comment]
Hey! The correct default separator for speaker notes is `note:` not `notes:`. This is correct in most of your md but wrong in that particular slide.

**Comment by hakimel** [comment]
^ That commit makes it so that both `note:` and `notes:` will work in the future. Seems like his would be an easy mistake to make.

**Comment by codedge** [comment]
Thanks a lot, also for the improvement note/notes!
