### ISSUE TITLE
IE Rendering shows a blank page

### ISSUE THREAD

**Issue by jcamp** [hakimel/reveal.js#1918]
When rendering after an export from Slides.com, the offline-v2.css file has a style:

html.offline.decks .reveal {
    -webkit-transition: opacity 0.3s ease;
    transition: opacity 0.3s ease;
    **opacity: 0;**
}

The opacity gets set to 0 for some reason (only happens with IE) which renders a blank slide show.

![image](https://cloud.githubusercontent.com/assets/148007/26827234/383a9ede-4ab4-11e7-98e3-bc8eddb123bf.png)

Can override the stylesheet of course, but not sure why the opacity is being set to '0' ...?

Cheers
Jonathan

**Comment by hakimel** [comment]
Hi Jonathan. Those styles were used to wait with showing content until fonts finished loading. However we removed them from Slides a few weeks ago so no new export should include that initial 0 opacity. Can you try a new export and see if you still have the same issue?

Also please get in touch via support @ slides.com for any Slides-related questions in the future.

**Comment by jcamp** [comment]
Hi Hakim

Will do. Issue is that I have a hybrid between the slides export and our own with templating from a DB, so don't want to risk. Can I just export any slides and get the correct offline css ?

Cheers
Jonathan

**Comment by hakimel** [comment]
Yeah, exporting any presentation to ZIP and copying over the offline CSS from there should do the trick.
