### ISSUE TITLE
Suggest to add fragments could index

### ISSUE THREAD

**Issue by xxssww0258** [hakimel/reveal.js#1919]
My English is not good.
"Fragments" lack "index" parameter, I need to use the "index" of the fragments, similar to the effect of some of the subtitles, continuously Hidden display, fragments
thank you.
我在使用过程中需要做一些类似字幕的效果，但是缺少fragments的index我操作起来不好控制，
例如说我第一次只显示2个fragment ,到第三个的时候隐藏前2个出现5个fragment,每一次都是不同的个数，我需要不断的创建id判断dom是不是等于这个id的dom,
好心人翻译一下，谢谢

**Comment by bnjmntn** [comment]
Duplicate of [#228](https://github.com/hakimel/reveal.js/pull/228#issuecomment-10261098).
