### ISSUE TITLE
parallax backgrounds on slides.com?

### ISSUE THREAD

**Issue by morandd** [hakimel/reveal.js#1920]
Any plans to introduce this feature? (or I am not seeing it at the slides.com gui..)

**Comment by morandd** [comment]
Ah: just saw this

http://help.slides.com/forums/175819-general/suggestions/6993994-parallax-transitions

too bad; I hope this decision is not etched in stone. it's a cool gee-whiz feature, and one thing that definitely separates js slides from powerpoint.

**Comment by bnjmntn** [comment]
Slides.com is not part of the open source Reveal.js project, so if you want them to reconsider their decision, you should probably vote or ask them there instead of on Reveal's GitHub.
