### ISSUE TITLE
Esacpe URLs in code blocks 

### ISSUE THREAD

**Issue by lachnerd** [hakimel/reveal.js#1925]
Hi,

i don't know if this is a reveal js or markdown or something else question:

Is there a way to escape URLs e.g. i have a Code Block in my Markdown file like
`<pre><code class="bash">curl -fsSL https://download.docker.com/linux/ubuntu/gpg \ | sudo apt-key add -</code></pre><!-- .element: class="fragment" -->`

And i don't wan't that URL interpreted as URL otherwise i display as:
`<a href="https://download.docker.com/linux/ubuntu/gpg">https://download.docker.com/linux/ubuntu/gpg</a>`

Didn't find anything.

**Comment by bnjmnt4n** [comment]
You could change to using the ``` syntax for writing your code, as the markdown parser shouldn't modify stuff within the code block.
