### ISSUE TITLE
Feature: out-of-tree presentation

### ISSUE THREAD

**Issue by azrdev** [hakimel/reveal.js#1926]
I'm following the [pandoc documentation](http://pandoc.org/MANUAL.html#speaker-notes) to create a revealjs presentation from markdown source using pandoc. It requires to checkout the revealjs repo to a directory next to the `presentation.html` file, which includes the framework using 
~~~html                                                   
  <script src="reveal.js/lib/js/head.min.js"></script>
  <script src="reveal.js/js/reveal.js"></script>
~~~
etc

I like this approach, because it separates content from code.

However, this does not work together with the built-in webserver, which is required for speaker notes, since that one assumes the presentation is in `reveal.js/index.html`. I can ouput my presentation html to that file, which makes the presentation work, but all embedded media are not found, because they are referenced relative to the presentation directory, not the reveal.js one.

So, I'd like to be able to run the webserver *from my presentation directory* i.e. the one in which `presentation.html`, the assets and `reveal.js/` reside. I'm not familiar with npm, grunt and whatever else is used, so if this is already possible, please tell me how and where this is documented.

**Comment by skomanduri** [comment]
In your presentation directory do:
```
npm start --prefix reveal.js -- --root=..
```
This sets the npm "local" path to the `reveal.js` directory and the base path of the webserver to be its parent (which gets you back to the local directory).

--- 

If your presentation is not called `index.html` you can change `open: true` in your `Gruntfile.js` to
```
  open: 'http://localhost:8000/presentation.html'
```
