### ISSUE TITLE
No landscape option when printing

### ISSUE THREAD

**Issue by slhck** [hakimel/reveal.js#1927]
I'm trying to print these slides:

http://slhck.info/ffmpeg-encoding-course/#/1/print-pdf

(Source code here: https://github.com/slhck/ffmpeg-encoding-course)

The print CSS seems to be included. When I open the print dialog in Google Chrome (59.0.3071.109) on OS X, there is no landscape option (unlike shown in the README screenshot):

![image](https://user-images.githubusercontent.com/582444/27444037-536e2c98-5775-11e7-8fa8-eefc98baf2ed.png)

When I try to print with the system dialog, pressing the landscape button there screws up the formatting of the pages:

![image](https://user-images.githubusercontent.com/582444/27444068-7924fa2a-5775-11e7-9254-3de0ea634ea1.png)

**Comment by bnjmnt4n** [comment]
Hi, you'll need to use a querystring for the url: http://slhck.info/ffmpeg-encoding-course/?print-pdf should be able to work. Note that including the print CSS using `?print-pdf` will mess up the formatting on screen, but when printed it should work just fine.

**Comment by slhck** [comment]
True, I read "when print-pdf is included in the query string" as just having to include that string in the URL, but "query string" has a more specific meaning. Thanks!
