### ISSUE TITLE
Links with "previewLinks: false" don't open in a new tab

### ISSUE THREAD

**Issue by JonasT** [hakimel/reveal.js#1929]
Links with "previewLinks: false" don't open in a new tab. Since X-Frame-Options: deny is very common, this is an important feature to use links in presentations properly - and replacing an in-progress presentation with an opened link seems hardly like a good idea. Therefore, I propose that all links are written with target="_blank" and rel=noopener (for security reasons).

**Comment by bnjmnt4n** [comment]
This is probably something that should be decided by the creators of presentations themselves. Opening all links in a new tab is quite invasive and should probably not be a default option. Creators of presentations can add `target="_blank"` themselves, or create a plugin that does that for all links.

**Comment by JonasT** [comment]
And closing the presentation entirely isn't invasive either? A new tab won't destroy the state of drawn things on the slides and other worse things, while the current behavior possibly will. How is that the better standard choice?

**Comment by kospl** [comment]
I can't believe this was closed. So in your mind there is an average user that is like "yeah, let's go to this link and forget about my presentation". This is not even close to other presentation tools behaviour.

At least there should be an option to open all links in new tab - preferably turned on by default for all users.

Here is use case for you: currently presentations made with Reveal.js cannot open links if they are hosted and presented from iframe. Users got full screen grey overlay with "domain.com refused to connect." and no explanation on what do do next. From other hand same link opened in new tab is loading perfectly, think about that.

**Comment by rsp** [comment]
@kospl adding `<base target="_blank">` to the head of the page solves the problem but I agree that it should be the default (and that it isn't I found out the hard way).
