### ISSUE TITLE
Disabling request of socket.io.js

### ISSUE THREAD

**Issue by seglo** [hakimel/reveal.js#1937]
While developing my presentation with a simple webserver on my localhost I always get a request for `socket.io.js` from this URL: http://revealjs.jit.su/socket.io/socket.io.js .  It will stall after a few minutes, but I'm not sure why.  I think this may have something to do with the hosted multiplexing.  Is there a clean way to disable this?

**Comment by bnjmnt4n** [comment]
Seems like you have included the socket.io.js in your dependencies when you copy pasted the initial template from a Reveal demo or docs. If you are not using the multiplexing feature, feel free to remove that from your dependencies.
