### ISSUE TITLE
markdown fragment syntax ineffective when enable sanitize option of marked

### ISSUE THREAD

**Issue by annProg** [hakimel/reveal.js#1939]
marked sanitize mode will convert '&lt;!-- code --&gt; ' to '&amp;lt;-- code --&amp;gt;'

this is my temporary method to fix this. Maybe there is a better solution

code in plugin/markdown/markdown.js
```
section.innerHTML = marked( markdown ).replace(/&lt;!--(.*?)--&gt;/g, function(){var cmt = arguments[1].replace(/&quot;/g, '"'); return '<!--'+cmt+'-->';});
```

**Comment by bnjmnt4n** [comment]
Yup, when sanitizing all HTML like syntax will be replaced, hence the custom markdown syntax will not be supported.
