### ISSUE TITLE
Does not load if JS assets have trailing ?timestamp

### ISSUE THREAD

**Issue by puyo** [hakimel/reveal.js#1944]
Love reveal.js, thank you for it!

I use reveal.js with the Middleman static site generator, which adds hashes and timestamps on my JS paths, converting them from `/javascripts/slides/plugin/markdown/marked.js` into `/javascripts/slides/plugin/markdown/marked-c4596c44.js?1500625769`. Reveal.js has no errors but simply fails to boot up, presenting the slides background and an empty foreground.

I had to go into this line: https://github.com/hakimel/reveal.js/blob/master/js/reveal.js#L401

And change it from:

```js
head.ready( s.src.match( /([\w\d_\-]*)\.?js$|[^\\\/]*$/i )[0], function() {
```

to

```js
head.ready( s.src.match( /([\w\d_\-]*)\.?js|[^\\\/]*$/i )[0], function() {
```

in order to make reveal.js work in my situation. Frustratingly, I only notice this problem after it has been deployed to production.

Am I doing the right thing with this change? Are there any unforeseen consequences?

Is this something that reveal.js should do differently? Should it show a warning or error message in the console so it's easier to figure out what is happening?

**Comment by bnjmnt4n** [comment]
Yep, Reveal.js should be able to match and load JS files with query strings. Created #2077 to fix that.

**Comment by hakimel** [comment]
Good catch. The fix has been merged into dev
