### ISSUE TITLE
how to make different theme in some slides

### ISSUE THREAD

**Issue by chxp** [hakimel/reveal.js#1945]
I hardly find detailed  instruction to make several slides use different theme, for example, the title slide and the second content list slide. Title slide or content slide using a different theme (or different css style) is so often.

Most related question was asked on Stackoverflow (Not me), https://stackoverflow.com/questions/41776881/reveal-js-cant-change-theme , but is not clear to one who knows nothing about JS. 

So where the code snips refer from the Stackoverflow put in, and is there a way to set the theme in slides as simple as just adding  `<section theme="css/theme/white.css">` in the slide like https://github.com/hakimel/reveal.js/issues/39

**Comment by chxp** [comment]
I find a solution according to https://github.com/hakimel/reveal.js/issues/1745

1. setting all used theme of your as following

    <script>
      Reveal.initialize({
      ...
      });
    
      Reveal.addEventListener( 'changeToBlackTheme', function() {
      document.getElementById('theme').setAttribute('href', 'css/theme/black.css');
      }, false );
      Reveal.addEventListener( 'changeToWhiteTheme', function() {
      document.getElementById('theme').setAttribute('href', 'css/theme/white.css');
      }, false );
    </script>

2. Using data-state="changeToBlackTheme" in section to the black theme (like following).

    <section data-state="changeToBlackTheme">
      <p> Some thing... </p>
    </section>      
    
3. Using data-state="changeToDefaultTheme" in section to the white theme.

A problem: when reverse review the slide, the theme will disordered, any better idea?

**Comment by bnjmnt4n** [comment]
Since changing themes within the same presentation isn't common, we don't have any specialized tools for you to do so. You can try using `Reveal.addEventListener('slidechanged')`, then check `event.currentSlide.getAttribute('theme')` instead.
