### ISSUE TITLE
Set initial slide

### ISSUE THREAD

**Issue by shd101wyy** [hakimel/reveal.js#1949]
Hi,

First of all, thanks for offering us such an amazing library.
My question is that Is it possible to set the initial slide when calling `Reveal.initialized()`. (Not by calling `.slide` function)  
For example, I have 10 slides, but I want to start from the 2nd after initialization, is there a way to do so?  

Thank you :)

**Comment by rauschma** [comment]
You could do the following.

Step 1: enable `#` links for slides:

```
Reveal.initialize({
	history: true,
	···
});
```

Step 2: link to the relevant slide:

```
http://localhost:8080/my-slides.html#/2
```

**Comment by shd101wyy** [comment]
@rauschma Thank you very much! This is cool!!!
