### ISSUE TITLE
Building themes: no need to install grunt globally!

### ISSUE THREAD

**Issue by rauschma** [hakimel/reveal.js#1951]
The following command works well and uses the locally installed gulp.

```
npm run build -- css-themes
```

**Comment by bnjmnt4n** [comment]
Hey sorry for the late reply, but any idea where you read that it was required to install gulp? AFAIK we don't use gulp, and only use Grunt. If you were referring to Grunt (I get that it can be confusing sometimes), would appreciate a note on where we said it's required. Thanks!

**Comment by rauschma** [comment]
Yes, grunt. Fixed now, thanks.

[The readme](https://github.com/hakimel/reveal.js/blob/master/css/theme/README.md) tells you to run `grunt css-themes` (= execute a globally installed grunt).

**Comment by bnjmnt4n** [comment]
Ah, missed that file because it wasn't in the main readme :'). Will upload a docs patch soon. Thanks very much!
