### ISSUE TITLE
TypeError: secnode is null

### ISSUE THREAD

**Issue by lechten** [hakimel/reveal.js#1953]
The search plugin does not work for me. I see "TypeError: secnode is null". This seems to be fixed in the dev branch. What about master?

**Comment by lechten** [comment]
@hakimel Any comment? The critical part is the check ```secnode != null``` in [line 57 of search.js](https://github.com/hakimel/reveal.js/blob/dev/plugin/search/search.js#L57) of the dev branch, which is missing in [master](https://github.com/hakimel/reveal.js/blob/master/plugin/search/search.js#L57). (Also ```secnode``` is initialized differently in line 56.)

**Comment by hakimel** [comment]
Thanks for reporting. This was fixed as part of PR #1909 that included a few other changes as well. PRs are merged into dev before being released with the next reveal.js version and merged into master.

**Comment by bnjmnt4n** [comment]
Closing for now, should be fixed in Reveal 3.6.0.
