### ISSUE TITLE
Append markdown formatted text to a slide

### ISSUE THREAD

**Issue by phzs** [hakimel/reveal.js#1956]
I'm trying to update a single-slide reveal.js-presentation inside an Iframe dynamically using the post message API. As there is no api call for replacing a slides content documented, I'm creating my own EventListener in the Iframe listening for my custom message containing the new content (analog to how reveal.js is using an EventListener to parse API calls from a postMessage).

This works fine but if the new content contains markdown formatting, it won't get parsed.

**Is there a way to replace a slides content from outside the window/frame, so that markdown is parsed?**
Or is it possible to tell reveal to parse markdown after it was initialized?

(I tried to set the sections' data-markdown-parsed attribute to false but this had no effect. I also tried replacing the content via javascript using ids (without using the postMessage api) but it had the same outcome)

Note: In my project I'm using reveal.js 3.3.0.

**Comment by bnjmnt4n** [comment]
It's currently not possible to re-parse a slide which has already been parsed, but you can try to run `RevealMarkdown.convertSlides()` to convert a newly inserted slide with `data-markdown` enabled.
