### ISSUE TITLE
Background Audio Management

### ISSUE THREAD

**Issue by nvohra** [hakimel/reveal.js#1960]
I want the audio to be reproduced at the beginning of the presentation and paused or stopped at the end of the presentation. I know how to start playing at the beginning, but I can not pause or stop it on the last slide. how can I do it?
To start: 
`<audio data-autoplay src="music.mp3">`

**Comment by maxigaz** [comment]
I've just found [this answer](https://stackoverflow.com/a/35489808/3969218) on Stackoverflow. I copied the given code snippet under `<script>`, added an ID to the `<audio>` tag and changed the keycode value based on https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode, and it seems to work pretty well!

Here are my changes:

```html
<audio data-autoplay data-ignore loop id="mymusic" src="music.mp3">
<!-- I added "data-ignore" so that it continues playing even after I move to another slide and "loop" to, well, make it loop. -->
```

```javascript
var audio = document.getElementById("wiosna");
window.addEventListener("keyup", playPauseKb, false);
function playPauseKb(event) {//<-- added missing event parameter

	var x = event.keyCode;

	//debug
	//console.log(x);

	//x on the keyboard
	if (x === 88) {

		audio.play();

		//alert("playing");

	} else if (x === 90) { //y button keycode

		audio.pause();

		//alert("paused");

	}
}
```

By the way, I have limited Javascript knowledge, so if anyone knows a better answer, let me know.

**Comment by BouncyBird** [comment]
This really helped me, thank you!
