### ISSUE TITLE
`data-background-iframe` with video control support?

### ISSUE THREAD

**Issue by darinacosta** [hakimel/reveal.js#1964]
Hi,

I'm attempting to embed a Vimeo video that will take up 100% of the width and height of the screen. `data-background-iframe` accomplishes this, but doesn't allow the user to access the video controls. Will this be introduced as a feature in the future; or is there a workaround that you'd recommend? 

Thanks!

**Comment by bnjmnt4n** [comment]
The `data-background-iframe` is used in the background of the current slide, hence the controls won't be accessible. The best case for your scenario is to put the video in the foreground and customise the CSS or play with the [presentation size](https://github.com/hakimel/reveal.js#presentation-size).
