### ISSUE TITLE
Modify the Zoom Transition Focal Point

### ISSUE THREAD

**Issue by jaredvacanti** [hakimel/reveal.js#1968]
I would like to click on a spot on the slide and appear to zoom into that spot as the transition to the next section - similar to a prezi presentiation (https://prezi.com/). Now when I zoom, it appears from the center of the slide. 

Can I specify where to zoom from, so it looks like a section is being enlarged ?

**Comment by bnjmnt4n** [comment]
Hi! Currently the zoom transition is done mostly using CSS transitions, so you might want to look at the code for transitions: https://github.com/hakimel/reveal.js/blob/65bdccd5807b6dfecad6eb3ea38872436d291e81/css/reveal.scss#L682-L726 and the zoom transition: https://github.com/hakimel/reveal.js/blob/65bdccd5807b6dfecad6eb3ea38872436d291e81/css/reveal.scss#L797-L817 to modify the code to suit your slides.
