### ISSUE TITLE
Setting background iframe does not work from markdown script

### ISSUE THREAD

**Issue by glopesdev** [hakimel/reveal.js#1972]
Setting embedded youtube iframes using `data-background-iframe` inside a markdown script does not work. Adding the same iframe explicitly in HTML using the same attribute works with no problems.

The issue seems specific to youtube iframes, as I've tested other iframe references and they seem to work fine.

**Example HTML:**
```
<section data-background-iframe="https://www.youtube.com/VIDEO">
</section>
```

**Example Markdown:**
```
---
<!-- .element: data-background-iframe="https://www.youtube.com/VIDEO" -->
---
```

**Comment by glopesdev** [comment]
Inspecting the raw HTML generated by Reveal.js, it looks like raw HTML files have some extra complicated logic for dealing with background videos, using past and future state and some play logic.

Markdown slides decorated with the `data-background-iframe` do not get this treatment, which is probably one reason why this doesn't work.

**Comment by bnjmnt4n** [comment]
I believe you're using the wrong attribute: see https://github.com/hakimel/reveal.js#slide-attributes. Try using `<!-- .slide: data-background-iframe="..." -->`.
