### ISSUE TITLE
Update docs about interactive iframe backgrounds

### ISSUE THREAD

**Issue by oslego** [hakimel/reveal.js#1974]
The docs section on [iframe-backgrounds](https://github.com/hakimel/reveal.js#iframe-backgrounds) mentions there is a way to make a background iframe interactive by using the `data-background-interactive` attribute.

This doesn't work. I did not find any reference to `data-background-interactive` in the source code.

If this is deprecated behaviour, I'd like to submit a PR to fix the docs and remove the mention. 

Is this the case, or is it a bug that should be fixed?

**Comment by hakimel** [comment]
This isn't supposed to be deprecated, `data-background-interactive` was recently added and is intended to work as described in the docs.

You weren't able to find it in the JS source because it's a purely CSS-based feature: https://github.com/hakimel/reveal.js/blob/master/css/reveal.scss#L450-L453

**Comment by bnjmnt4n** [comment]
This seems to work, tested in Chrome and Firefox latest. Closing this issue for now.
