### ISSUE TITLE
[Feature Request] Use Up/Down button to make the slide transition.

### ISSUE THREAD

**Issue by WenjieZ** [hakimel/reveal.js#1982]
Currently, reveal.js uses Left/Right to move between first-level slides, and Up/Down to go up or down the levels. However, a lot of presentation pointers bind their buttons to Up/Down instead of Left/Right. This feature can be added into the setting, and it allows the use of these pointers with reveal.js.

**Comment by MichaelNeas** [comment]
Would you want to change left/right to then dictate going down/up levels?

**Comment by WenjieZ** [comment]
@MichaelNeas Yes, why not.

**Comment by MichaelNeas** [comment]
That just seems counter intuitive to me.

**Comment by WenjieZ** [comment]
@MichaelNeas When I said the "button", I didn't mean the one on the page. I meant the physical one on the keyboard. What I want is _when I press the `Down` button on the keyboard or on my Laser pointer, Slides executes the `Right` commond_.

**Comment by rugk** [comment]
It could be added as an option, e.g. named `reverseKeyboard`, but AFAIK you can already ad custom keybindings (see Readme), so you could emulate the behavior too, now.

**Comment by WenjieZ** [comment]
@rugk I also noticed that information in Readme. But it seems to me that the `Reveal.configure` type code is not allowed in the "Reveal.js online editor". My current workaround is to change the key mapping.

**Comment by bnjmnt4n** [comment]
Currently this is possible in Reveal by [overriding the keyboard bindings](https://github.com/hakimel/reveal.js#keyboard-bindings).
