### ISSUE TITLE
css example incorrect

### ISSUE THREAD

**Issue by QHose** [hakimel/reveal.js#1986]
hi,

in the readme it says you have to import `<link rel="stylesheet" href="css/reveal.css">`
should this not be `index.css`?

**Comment by MichaelNeas** [comment]
Where do you get index.css from?  You can make your own css file to add to reveal.css or make your own theme but that requires you to generate your own `index.css` file

It says import `<link rel="stylesheet" href="css/reveal.css">` to get the styles provided by reveal.js, without these styles your presentation won't have any of the stylistic features of the project

**Comment by QHose** [comment]
Thanks, I understand, but in NPM reveal, there is no reveal.css only index.css

**Comment by QHose** [comment]
![image](https://user-images.githubusercontent.com/12411165/30477704-5f4b404c-9a0e-11e7-9b87-47e1eadfe3de.png)

**Comment by bnjmnt4n** [comment]
Make sure you are using the right reveal package on npm: https://www.npmjs.com/package/reveal.js.
