### ISSUE TITLE
Content of slides moved or cut using Slides.com

### ISSUE THREAD

**Issue by argotan** [hakimel/reveal.js#1987]
I have some notions of html and css, but they are very basic, I use slides.com, to make presentations. I finish making my presentation, I follow the export instructions (having free account):

1. Download reveal.js from github
2. Copy the style code, which provides slides.com and substituting it for the link to the css file <link>, which brings by default the file "index.html".
3. I copy the code from "div class = "reveal" and replace it with the default "index.html" file.
4. Añador center: false, as indicated by the page, to the reveal configuration.

I follow these instructions, since the other file that adds the export option, indicates that it should not be used in conditions where there is no connection, as is my case.

When I open the file "index.html", in the browser, you see that the contents of the slides are shifted to the right, and part of it is off the screen.

How can I fix this?
attachment file index.html
[index.zip](https://github.com/hakimel/reveal.js/files/1303487/index.zip)

**Comment by MichaelNeas** [comment]
In your index.html there is a "style" attribute in your sections. Try to make the "left" property smaller.

`<div class="sl-block" data-block-type="text" style="height: auto; min-width: 30px; min-height: 30px; width: 1153px; left: 64px; top: 72px;">`

For example, try dropping left from 64px to 30px and see if that works 😃
