### ISSUE TITLE
Reveal.getState() not a function

### ISSUE THREAD

**Issue by QHose** [hakimel/reveal.js#1988]
hi,

I follow the docs, and would like to get the current slide number, but I get an error for `Reveal.getState()` `Reveal.getState() not a function`

**Comment by MichaelNeas** [comment]
Hey,
Can you `console.log(Reveal)` for me and see if getState() exists on your Reveal object.

**Comment by QHose** [comment]
hi, no that does not exist...
![image](https://user-images.githubusercontent.com/12411165/30477765-a8a0a70a-9a0e-11e7-83c6-932c8035d535.png)

PS: if you don't mind, it would help if you add a little readme to get the current slide number. I searched a lot and later on I saw its available everywhere you look, like in the html tag itself :)

**Comment by razeel** [comment]
at _menu.js_, _highlightCurrentSlide_ function:
instead of `var state = Reveal.getState();`, we need to use `var state = Reveal.getCurrentSlide().getAttribute('data-state');`

**Comment by QHose** [comment]
Thanks!

Verstuurd vanaf mijn iPhone

Op 18 sep. 2017 om 07:46 heeft Razeel Akbar <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


at menu.js, highlightCurrentSlide function:
instead of var state = Reveal.getState();, we need to use var state = Reveal.getCurrentSlide().getAttribute('data-state');

**Comment by bnjmnt4n** [comment]
I can't seem to reproduce this, `Reveal.getState` and `Reveal.setState` seem to both exist.
