### ISSUE TITLE
Local demo uses different control arrows than live demo

### ISSUE THREAD

**Issue by infotexture** [hakimel/reveal.js#1989]
The [live demo](http://lab.hakim.se/reveal-js/) now uses angle brackets `<` / `>` as control arrows for navigation, but the [local development environment](https://github.com/hakimel/reveal.js#full-setup) and [3.5.0 release package](https://github.com/hakimel/reveal.js/archive/3.5.0.zip) still use triangles ◀︎ / ▶︎ instead.

I would expect the local demo to render the same as the live demo.

Is this a bug, or is there a configuration option that needs to be passed to use the same control arrows in local demos?

**Comment by hakimel** [comment]
The live demo is the current in-development version; https://github.com/hakimel/reveal.js/tree/dev

The new controls are part of that and will make their way out with 3.6.0.

**Comment by infotexture** [comment]
Cool, looking forward to the new release.

**Comment by omkensey** [comment]
This is a bit of a simple question, so I didn't want to create a whole new issue for it -- but where in the code is the character used to draw the arrows?  I can't find it and it's driving me nuts.  I want to change it for some presentations.
