### ISSUE TITLE
http://lab.hakim.se/reveal-js/?print-pdf#/ example not working well

### ISSUE THREAD

**Issue by QHose** [hakimel/reveal.js#1992]
hey guys, 

I am evaluating the export to pdf option, if I run the example: http://lab.hakim.se/reveal-js/?print-pdf#/

the output is not good, I miss a lot of content, it looks like a mess... Whats going on here?

**Comment by bnjmnt4n** [comment]
This seems to work pretty well for me. Perhaps you could make sure you follow the instructions here when printing: https://github.com/hakimel/reveal.js#pdf-export. Feel free to provide more info if this still doesn't work for you.
