### ISSUE TITLE
Notes Server Error

### ISSUE THREAD

**Issue by fruitloop** [hakimel/reveal.js#1993]
Hi, 
I'm ran reveal.js for a few presentations.

Now I'll have to hold a presentation again but the notes-server won't work.
It just won't sync to the main presentation.

So I had a look at the JavaScript Console in Chrome on my main presentation window and it told me:
```
client.js:9 Uncaught ReferenceError: io is not defined
    at client.js:9
    at client.js:66
(anonymous) @ client.js:9
(anonymous) @ client.js:66```

Did I do something wrong?

**Comment by MadhavBahlMD** [comment]
show your script.

**Comment by fruitloop** [comment]
my bad, I forgot `npm install`
