### ISSUE TITLE
Problems with umlauts

### ISSUE THREAD

**Issue by b-v** [hakimel/reveal.js#1994]
Not sure if this is a problem of reveal.js, but when I convert an ipython notebook with the word 'Schrödinger' in a markdown cell and use `jupyter nbconvert test.ipynb --to slides --post serve`, the resulting HTML file displayed in Firefox (on a Mac) shows 'Schrö dinger' instead of 'Schrödinger'. There is an extra space inserted.

**Comment by bnjmnt4n** [comment]
I don't believe this is a reveal issue. Perhaps you should look at the generated HTML file to see if there was a space added unintentionally by the program.

**Comment by b-v** [comment]
Actually, there is not any space at that location in the generated HTML file and if I disable the 'reveals.js' it looks fine in the browser. 

So it may be better to reopen the issue?

**Comment by bnjmnt4n** [comment]
Could you provide a reproduction page?

**Comment by b-v** [comment]
I've attached an example `.html` file (gzipped). I tested it by opening the file from a folder where the folder `reveal.js` also resides. When I do so, the first word has an extra space, while the second one doesn't.
[not-working.html.gz](https://github.com/hakimel/reveal.js/files/1704969/not-working.html.gz)

**Comment by bnjmnt4n** [comment]
Hi, I've taken a look at your page. The two Schrodinger's are different, you can compare them by looking at 

```js
'Schrödinger'.length // 12
'Schrödinger'.length // 11
```

This is because the ö in the first string is made up of U+006F Latin Small Letter O and U+0308 Combining Diaeresis.

The ö in the second string is the U+00F6 Latin Small Letter O with Diaeresis.

Since the characters are different, it probably has to do with the font not supporting the combining mark properly resulting in a weird alignment issue.

**Comment by b-v** [comment]
Thanks for looking into it, so it is a font issue. It worked without reveal.js since then it would be using a font that would support it. 

Apparently the font Lato, as being used in the simple theme, had some issues in the past. However, I managed to resolve this problem by replacing `@import url(https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic);` with `@import url(https://fonts.googleapis.com/css?family=Lato&subset=latin,latin-ext:400,700,400italic,700italic);` in the file `reveals.js/css/theme/simple.css`, as indicated on the page https://fonts.google.com/specimen/Lato.
