### ISSUE TITLE
Transitions on an element within a slide (section)

### ISSUE THREAD

**Issue by nextrang** [hakimel/reveal.js#1998]
Hi,

In one slide (`<section>`), I want to keep the title/heading the same, but to transition between a list of divs.

For example, my slide's code would look like this:

```html
<section>
  <h2>Some title</h2>
  <ul>
    <li>
      <div id="div1">
        I am shown first.
      </div>
    </li>
    <li>
      <div id="div2">
        Then, #div1 is hidden (display: none;) and I am shown.
      </div>
    </li>
    <li>
      <div id="div3">
        Then, #div2 is hidden (display: none;) and I am shown.
      </div>
    </li>
  </ul>
</section>
```

* The title `Some title` is displayed while we are on this slide.
* Initially only `Some title` and the contents of `#div1` are displayed.
* Then `Some title` stays displayed, but `#div1` transitions out and eventually is not displayed anymore and `#div2` transitions in.
* Then while `Some title` stays displayed, but `#div2` transitions out and eventually is not displayed anymore and `#div3` transitions in.

Can Reveal do this?

**Comment by WenjieZ** [comment]
I think this can be realized by the "current-visible" fragment.

**Comment by behrangsa** [comment]
Have to recheck, but I think `current-visible` fragments always occupy space.

**Comment by WenjieZ** [comment]
Yes, it is. But you can overlay it with another element. The disadvantage is the PDF version will have troubles.

**Comment by WenjieZ** [comment]
I think in Keynote, they put them on different slides. You see it as element transition. But actually, it's slide transition.

**Comment by bnjmnt4n** [comment]
This is more complex, and can probably be done with your own custom fragment styles. By placing it display: none by default, you can then do something like display: block when the fragment is active, but with a transition (with delay) on some transform such as brightness or scale to achieve such an effect
