### ISSUE TITLE
Auto break long text into slides? 

### ISSUE THREAD

**Issue by filipgoc** [hakimel/reveal.js#1999]
Hi, 

Sorry in advance if this is trivial. 

Is there a flag to automatically break content (long outlines) into individual slides? 
(Right now the text/ images just disappears off the screen on the bottom.)

I'm using pandoc to convert markdown into revealjs.

Thanks!!

**Comment by bnjmnt4n** [comment]
Currently there isn't such a way to do that, you'll have to individually judge and split your content into different slides manually.
