### ISSUE TITLE
Head configuration

### ISSUE THREAD

**Issue by merlinpatt** [hakimel/reveal.js#2000]
Is it possible to configure the head.js that reveal is using?

I know it's needed for loading external dependencies, but are all the classes it adds necessary? Is there a way to turn some of them off?

**Comment by rugk** [comment]
Why do you want to do so?

**Comment by merlinpatt** [comment]
Because I like to keep things as light as possible. Maybe it won't get rid of much, but if I can lighten the weight, I would like to

**Comment by rugk** [comment]
I think if one does so, it should be included in reveal.js. But maybe you can use the (additional) head CSS classes in your presentation, or is it not that useful? (I am not sure what this CSS is anyway… 😄 )

**Comment by bnjmnt4n** [comment]
head.js is not strictly required for Reveal to function, only if you are using the `dependencies` configuration to load your scripts. Otherwise, you can just load dependencies like plugins as normal `<script>`s, although you must call `Reveal.initialize()` first.
