### ISSUE TITLE
Overriding previewLinks: in a link-per-link basis?

### ISSUE THREAD

**Issue by egrosclaude** [hakimel/reveal.js#2005]
When I want to point to some Github project from within a slide, I get:

`Refused to display 'blah' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".`

I understand this behaviour is caused at Github's side as per [this SO question](https://stackoverflow.com/questions/38068019/load-another-domain-website-in-a-iframe). I also understand this is a consequence of having set `previewLinks: true` in my config stuff. 

This is easily corrected by  defaulting to `previewLinks: false`. Now, my presentation also refers to some material which is hosted in the same server, thus previewLinks brings no problems with referring to these in an embedded iframe. This is handy as it does not interrupt the presentation flow or forces the user to navigate back to the slides. 

So, can previewLinks: status be overridden in a link-by-link basis?

**Comment by bnjmnt4n** [comment]
Yes, `previewLinks` can be overridden on a link-by-link basis by adding `data-preview-link` or `data-preview-link="false"` even if `previewLinks` is `true` or `false` in the configuration. This seems like a good idea to add a note in the docs, and I'll do that in a whille.
