### ISSUE TITLE
This project deserves it's own domain… (and HTTPS)

### ISSUE THREAD

**Issue by rugk** [hakimel/reveal.js#2007]
The current domain `http://lab.hakim.se/reveal-js` is not really nice. A domain as `reveal.js` or `revealjs.io` or whatever would be nice. Even GitHub Pages would be enough…

And, [of course, you should use HTTPS](https://doesmysiteneedhttps.com/)…

**Comment by hakimel** [comment]
I agree the project deserves its own domain. I've owned revealjs.com for two years – just moved the demo over there now. 

SSL cert should kick in in the next 24hrs.
