### ISSUE TITLE
Multiplex not working when presentation includes vertical slides

### ISSUE THREAD

**Issue by Fischermaen** [hakimel/reveal.js#2014]
Mulitplex did work fine for me until the point when I added vertical slides (section in section). So, I think there is an issue with multiplex and vertical slides.

**Comment by rugk** [comment]
No, works fine here… (at least that is not the issue…)

**Comment by bnjmnt4n** [comment]
This seems to be working fine, this could possibly be something else you added to your slides that might be causing errors.
