### ISSUE TITLE
Can I enable/disable multiplexing on the fly?

### ISSUE THREAD

**Issue by rugk** [hakimel/reveal.js#2020]
E.g. could I also pass the multiplex object to `Reveal.configure` or how'd that work?

Basically, I just want to create a flexible script, which enables multiplexing only in some cases, and for others it just shows a usual presentation. That could also be used to conditionally fetch & pass the secret or not, depending on whether the client or master is detected.

**Comment by rugk** [comment]
In other words: Can I call `Reveal.configure` with `dependencies` and it will load these, even after `Reveal.initialize`?

**Comment by bnjmnt4n** [comment]
You can always avoid loading the dependencies until after page loads, and load them further on using `head.js([ /* socket.io, multiplex*/ ])`. Note that you will have to add the `multiplex` configuration before loading those scripts either through `initialize` or `configure`.
