### ISSUE TITLE
Allow fragments to apply (custom) class when triggered

### ISSUE THREAD

**Issue by rugk** [hakimel/reveal.js#2024]
Basically I'd want a simple way to add a class when the "fragment" is show. That is very similar to "fragment highlight-red", except that I do not want to change the CSS `color` of the element, but apply my custom CSS class.

`data-state` has some similarity, but AFAIK this does not do what I want.

So e.g. (`data-fragment-class` was invented by me):
```html
<pre><code class="html bad-code fragment" data-fragment-class="bad-code" data-trim>
    <div>heading</div>
</code></pre>
```

After a click, that would add the class `bad-code`, in order to highlight the bad code example:
```html
<pre><code class="html bad-code fragment bad-code" data-fragment-class="bad-code" data-trim>
    <div>heading</div>
</code></pre>
```

That is just a thing to cover this `highlight-red` and so on, but by not just limiting it to some predefined colors, but by allow any class I want.

**Note:** I saw that to fragments the `visible` class is added, which I can use for styling, but then the problem still is that I need to define some kind of `fragment highlight-red` or so, because the fragment is otherwise hidden by default (which I do not want). The best workaround would be if I could just use a class `fragment do-nothing-on-fragment`, which would allow me to just use the `visible` class.

But I still consider this a workaround, a `data-fragment-class` attribute or similar, would be much more helpful. Anyway, I am also looking for nice workarounds, if you have any.

**Comment by bnjmnt4n** [comment]
Fragments are meant to be inherently customizable, so you can just define your own fragment that does nothing, while overriding the default fragment behaviour:

```css
.reveal .slides section .fragment.empty {
	opacity: 1;
	visibility: inherit;
	transition-duration: 0s !important;
}
```
