### ISSUE TITLE
Math plugin: configuration option to disable $ delimiters for inline math

### ISSUE THREAD

**Issue by jgm** [hakimel/reveal.js#2026]
The [math plugin](https://github.com/hakimel/reveal.js/blob/master/plugin/math/math.js#L18)  enables tex2jax and sets `$` as inline math delimiters.  This means that HTML like
```
<p>I made $4 yesterday and $5 today.</p>
```
gets mangled by being interpreted as math.  Could we have a configuration option for this?  Something like:

```js
			tex2jax: {
				inlineMath: options.inlineMath || [['$','$'],['\\(','\\)']] ,
				skipTags: ['script','noscript','style','textarea','pre']
			},
```

or for more control,

```js
			tex2jax: options.tex2jax || {
				inlineMath: [['$','$'],['\\(','\\)']] ,
				skipTags: ['script','noscript','style','textarea','pre']
			},
```

(See also jgm/pandoc#4027.)

**Comment by hakimel** [comment]
Fixed in #2045
