### ISSUE TITLE
Needs comprehensive, complete documentation

### ISSUE THREAD

**Issue by rugk** [hakimel/reveal.js#2028]
The current Readme is a nice "Getting started…" guide, but some things are just missing, so this is not a comprehensive documentation.

## What is e.g. missing…
* You can append `?notes` to the URL to instantly open the speaker notes
* Maybe there even more "secret" query strings (`?…`)?
* some [`fragment` styles](https://github.com/hakimel/reveal.js/blob/360bc940062711db9b8020ce4e848f6c37014481/css/reveal.css#L51) like `.zoom-in` or `.strike`…
* more?

## Why?

One should not need to look into the source to find out all the classes etc. the JS library provides. A simple list would already be a good progress…

**Comment by tristansokol** [comment]
Could you list which things you'd like to be documented? I'd be happy to work on a documentation PR with you.

**Comment by keesse** [comment]
What I miss in the documentation is:
* Can your presentation be in an other file then `index.html`?
   If yes, how to do this from the commandline?
* Can this file be in an other directory then `reveal.js/`?

**Comment by keesse** [comment]
@bnjmnt4n, thank you for your reply.
I orignally started with https://revealjs.com/installation/, but that more or less ends with:
  `$ npm start`  
   Open `http://localhost:8000` to view your presentation  

So how can I open an other presestation than `index.html`?  
I was unable to find any information about this in the documentation
