### ISSUE TITLE
Fragment not hidiging everything

### ISSUE THREAD

**Issue by naps62** [hakimel/reveal.js#203]
I have a slide just like this (only the text is different):

``` html
        <section>
          <h2>Title 1</h2>
          <br />
          <ul class='wide no-bullet' style='font-size: 0.9em'>
            <li>Item1</li>
            <li>Item2</li>
          </ul>
          <span class='fragment'>
            <hr />
            <br />
            <h2>Title 2</h2>
            <br />
            <ul class='wide no-bullet' style='font-size: 0.9em'>
              <li>Item 1</li>
              <li>Item 2</li>
            </ul>

          </span>
        </section>
```

What's happening is that the fragment class is not working completely. The HR and H2 are being shown from the start, even though the last list starts hidden and is shown after pressing forward

Am i missing something?

**Comment by unruledboy** [comment]
It does not work like this:

<section>
				<p class="fragment fade-in">
					<pre>
						0
						2
						4
						6
						8
					</pre>
				</p>
			</section>


or this:

<section>
<p class="fragment fade-in">
<ul>
            <li>Item1</li>
            <li>Item2</li>
          </ul>
</p>
</section>
