### ISSUE TITLE
data-background="xxx.jpg " won't take affect.

### ISSUE THREAD

**Issue by Michael-Zhang-Xian-Sen** [hakimel/reveal.js#2032]
os: win10
browser: chrome 61.0.3163.100 (64-bit)

When I code this:`<section  data-background="public/img/om/om.jpg "></section> `
There are  a blank after `public/img/om/om.jpg`.Then the jpg won't display in my chorme.

But if it's a color , it work correctly.Like this:` <section data-background="#ffffff "></section>`

A small bug, but make a disaster in my presentation.

**Comment by tristansokol** [comment]
You are looking for the data-background-image property.  Use that for images instead of the generic data-background.

**Comment by Michael-Zhang-Xian-Sen** [comment]
OK.Thank you.
