### ISSUE TITLE
weird  background color separation issue

### ISSUE THREAD

**Issue by tttuuu888** [hakimel/reveal.js#2035]
First of all, I appreciate this great package. Thanks a lot!

I found weird background color separation issue and it can be easily reproduced.

First I cloned this repository and changed demo.html file 2 part.

(18 line)
`<link rel="stylesheet" href="css/theme/black.css" id="theme">`
to
`<link rel="stylesheet" href="css/theme/moon.css" id="theme">`

and

(394 line)
`transition: 'slide', // none/fade/slide/convex/concave/zoom`
to
`transition: 'none', // none/fade/slide/convex/concave/zoom`

and then the result is as below.
![_002](https://user-images.githubusercontent.com/8042298/32690956-635f6aa2-c743-11e7-85fa-79f090f0affd.png)

I found this while looking for good combination of the transition and theme options.

**Comment by bnjmnt4n** [comment]
Hi, I don't seem to see any issue with the background. Feel free to ping back with more details.
