### ISSUE TITLE
Failed to parse image in external markdown

### ISSUE THREAD

**Issue by petehouston** [hakimel/reveal.js#2039]
At current version, 3.6.0+ , RevealJS fails to parse any image in external markdown.

```
<div class="reveal">
    <div class="slides">
        <section data-markdown="slides/external.md" data-separator="^\r\n\r\n\r\n" data-separator-vertical="^\r\n\r\n" data-separator-notes="^Note:" data-charset="utf-8"></section>
    </div>
</div>
```

Content of `slides/external.md`
```
## This is external markdown

![Sample image](../images/image.png)
```

Create a directory at root of project `images` and put an image file named `image.png`.

It's won't work.

However, for RevealJS 3.3.0 version and below, it works.

**Comment by hakimel** [comment]
I checked but images are working in external and inline Markdown in 3.6.0.

Looks like it might be a problem with your relative path to the image. If the images directory is at the project root, try `![Sample image](images/image.png)`

**Comment by petehouston** [comment]
@hakimel I verified it again. It looks like in some local Windows distribution (Korean, Japaneses..), some letters are not ANSI at all in their keyboards, ex. `!` , `[`, `]`; so markdown plugin fails to parse. Pretty interesting to know about this.

**Comment by pranshuchittora** [comment]
Make sure that the image URL should be relative to the `HTML` file not the `markdown`.
Hope it helps :+1:
