### ISSUE TITLE
Speaker notes PDF export

### ISSUE THREAD

**Issue by quicknir** [hakimel/reveal.js#2040]
I  was able to get this working following the instructions, and some slides look fine. But if the speaker notes are long enough, they simply overlap the regular slide. Is there any way to prevent this? Screenshot attached:

![screenshot from 2017-11-23 19-12-05](https://user-images.githubusercontent.com/10457096/33191011-43db1332-d082-11e7-990d-58f0f9db5947.png)

My code is available at: https://github.com/quicknir/reveal_globals_linker

**Comment by hakimel** [comment]
You can print your notes on a separate page if you prefer, from the readme:
>When showNotes is enabled notes are also included when you export to PDF. By default, notes are printed in a semi-transparent box on top of the slide. If you'd rather print them on a separate page after the slide, set showNotes: "separate-page".

For example: https://revealjs.com/?showNotes=separate-page&print-pdf

**Comment by quicknir** [comment]
Ah very sorry, must have missed that. Thanks for the quick response!
