### ISSUE TITLE
Some specific math expersion dose'nt work 

### ISSUE THREAD

**Issue by ali-ramezani** [hakimel/reveal.js#2043]
Some expressions like $x_{1}-y_{1}$ simply doesn't work and apparently the text between two underline just turn to italic (it is correct in markdown but must be off inside formula)
I tried x_1-y_1 but this one is working!
I tried several combinations and it seems the markdown parser get confused when '{' or '}' appear inside of underlines

**Comment by Lionex** [comment]
You need to escape the underscores with backslashes:

$x\_{1} - y\_{1}$

This is because markdown will not treat underscores inside of words as italics, but the curly braces count as word boundaries.

**Comment by ali-ramezani** [comment]
Unfortunately it didn't work for me. I insist there is a bug in markdown part because if I put it as normal html between <section></section> the original formaula works. It is hard to me because I wrote all my presentation in one .md file using separators and even it didn't work when I put <p></p> inside my file. Apparently I could not switch to html inside of .md file or markdown textarea

**Comment by bnjmnt4n** [comment]
When used with the Markdown plugin, the Markdown plugin appears to parse the `_` beforehand. One solution would be to wrap the whole expression in `<code>` to prevent Marked from parsing the code within, or avoiding writing slides using math with Markdown.
