### ISSUE TITLE
mouse wheel scroll

### ISSUE THREAD

**Issue by G1305** [hakimel/reveal.js#2052]
PLEASE HELP!

how to enable **mouse wheel scrolling** between UP/DOWN slides?

please insert me code of CSS for activating mouse scroll feature

**Comment by bnjmnt4n** [comment]
As mentioned in https://github.com/hakimel/reveal.js#configuration, you can run:

```js
Reveal.initialize({
	// ...
	// Enable slide navigation via mouse wheel
	mouseWheel: true
});
```
