### ISSUE TITLE
Internal links not working second time I click on them

### ISSUE THREAD

**Issue by pandisvezia** [hakimel/reveal.js#2053]
Hello,

First of all, thank you for this great framework! I encountered a problem with the internal links. I followed your instructions here to create one (section id="show-a-link"). It works first time I click on it. However, since the URL contains a hashtag afterwards, the second time I click on the link does not do anything. The code is below:

        <section id="show-a-link">
           <h1>Show a live link</h1>
	   <p>Slide 2 discussed here</p>
	   <p>See <a href="http://www.htmlcheats.com">HTMLCheats.com</a><p>
	</section>

	<section>
	   <h1>Slide 3</h1>
	   <p>How does one revisit an arbitrary slide in code?</p>
           <p>Visit internal slide<a href="#/show-a-link"> 2</a>
	</section>

Maybe there is a workaround I do not know about. Could you please help me?

Best,
Ahmet

**Comment by pandisvezia** [comment]
I solved it this way:

<p>Visit internal slide<a href='javascript:Reveal.slide(4)'> 2</a>

Your comments are very welcome if this is a troublesome solution.

Best,
Ahmet

**Comment by bnjmnt4n** [comment]
I've tested your code in a blank Reveal presentation, it seems to work for me. Perhaps you could create a repro for us to see. Otherwise closing for now.
