### ISSUE TITLE
fix width desktop / mobile RESPONSIVE DIMENSIONS

### ISSUE THREAD

**Issue by G1305** [hakimel/reveal.js#2057]
![image](https://user-images.githubusercontent.com/34474564/34071125-0e7b9dfe-e28b-11e7-8b07-8c9c7039be99.png)

reveal.js at line 42 I updated:
width: 1700,
height: 845,

DESKTOP mode is fine. but how to fix dimensions (padding/margin) in mobile full height RESPONSIVE?

**Comment by bnjmnt4n** [comment]
As mentioned at https://github.com/hakimel/reveal.js#presentation-size, you might want to vary the size of the `margin` surrounding the content to provide more breathing room around your slides.

**Comment by G1305** [comment]
thank you for answer, do you know where to find INCLUDE plugin for reveal?I think this is important plugin for anyone...
