### ISSUE TITLE
Slide numbers don't match URL 

### ISSUE THREAD

**Issue by Leftium** [hakimel/reveal.js#2067]
Apparently, the URL is 0-indexed, but the slideNumber starts at 1. It would be less confusing if they used the same numbering system.

**Repro steps:**

1. Add option `slideNumber: true` to https://github.com/hakimel/reveal.js/blob/master/demo.html
2. Compare URL/slide number in browser

![image](https://user-images.githubusercontent.com/381217/34772863-e7f3017e-f64c-11e7-9fb0-38a7c8b306e7.png)

**Comment by bnjmnt4n** [comment]
It is true that using the same numbering system is less confusing, however the 0-indexed URL system has been in use since the very first version of Reveal and hence it is unlikely that we will switch to a different system.

**Comment by Leftium** [comment]
What about changing the displayed slide numbers to also be 0-indexed?
