### ISSUE TITLE
Speaker notes don't work when running off filesystem (file://)

### ISSUE THREAD

**Issue by mischah** [hakimel/reveal.js#207]
The new postMessage speakernotes introduced with #190 aren’t working in 
- Chrome 22 (Mac)
- Firefox 16 (Mac)

I just get them working with the latest Safari on Mac. 

Discovered while testing #206, but I wasn’t introducing this bug with my changes ; ]

**Comment by carywreams** [comment]
Are speaker notes from the file system still only available in the dev branch ?
