### ISSUE TITLE
WANTED CLICKABLE CONTENTS

### ISSUE THREAD

**Issue by G1305** [hakimel/reveal.js#2070]
I'm trying insert another site's code into section e.g. DYNAMIC CONTENT CARDS.
but when I clicking on card objects, won't load... 

I think reveal doesn't support DYNAMIC pages...

for example:
https://revealjs.com/#/2/1 << /#/2/1 are  slide numbers. 
but
I need insert dynamic loading contents so:
https://revealjs.com/#/2/1/sectionCONTENTS1 (sectionCONTENTS1 is dynamic html)

ANY IDEAS? reveal external master not working for clicking

**Comment by G1305** [comment]
![screenshot 77](https://user-images.githubusercontent.com/34474564/34845120-3e7c32f0-f72d-11e7-922d-298e7e66fac0.png)
for example

**Comment by bnjmnt4n** [comment]
You'll have to modify the code of your dynamic page to work with Reveal. Personal support questions shouldn't really be asked here, as contributors to Reveal don't have the time to answer every single question relating to your own code. Please try to use the issue tracker for reporting bugs or feature requests.
