### ISSUE TITLE
restrict all slides preloading

### ISSUE THREAD

**Issue by G1305** [hakimel/reveal.js#2072]
how to preload only current slide not all? 

I have many slides, after saving website from browser, I have whole website downloaded not current slide...

**Comment by G1305** [comment]
HOW TO PREVENT ALL SLIDES LOADING AT OPEN?

**Comment by G1305** [comment]
in the inspect page source from browser, there is whole website's code, not current slide only... I think it's not recommended for me and/or others

**Comment by wjdenny** [comment]
If you are concerned about security, I think having the source HTML of all slides available at once would be the least of your worries. Can you give a specific example of why you would need this for security issues, and why a more substantial presentation software would not be a better choice?

An argument could be made at least for slides with a lot of media. Loading everything up front might take a long time, or tie up a lot of memory on older systems. Being able to configure the number of slides to preload could be useful.

**Comment by G1305** [comment]
@wjdenny  THANK you for answers. I'm beginner web-master,  and have not strong argument about web-security, U are right, hiding source code makes slow down...
also have one question:
HOW to install/run website as web-server? I would like test my edited reveal from android, or from client PC... If you know... 
best regards :)

**Comment by bnjmnt4n** [comment]
If you're trying to deploy your site, you can try something like [GitHub Pages](https://pages.github.com/) or [Now](https://zeit.co/now).
