### ISSUE TITLE
scroll lock

### ISSUE THREAD

**Issue by G1305** [hakimel/reveal.js#2074]
I have enabled mousewheelscroll in revealjs "true".
I have inserted modal inside section. open window on click modal button, where is something content with scroll-bar. I need scroll only inside modal-CONTENT, not global reveal slides.
so
I WANT MANUAL DISABLE/ENABLE SCROLL SETTINGS INSIDE SPECIFIC SLIDES. HOW DO IT?

**Comment by bnjmnt4n** [comment]
The way the current code works, you will have to disable mousewheel scrolling inside slides where you want to scroll. You can probably do something like:

```js
Reveal.addEventListener('slidechanged', function(event) {
 if (event.currentSlide.className == 'no-scroll') { // or modify to suit your needs
    Reveal.configure({ 'mouseWheel': false });
  } else {
    Reveal.configure({ 'mouseWheel': true });
  }
});
```
