### ISSUE TITLE
Mention in README that syntax highlighting requires a css

### ISSUE THREAD

**Issue by RasmusFonseca** [hakimel/reveal.js#2075]
Simply copying the [Code syntax highlighting](https://github.com/hakimel/reveal.js/#code-syntax-highlighting) example doesn't actually result in syntax highlighting. You need to also import a css (which just took me an hour to figure out). It'd be great if this was mentioned in the README

**Comment by bnjmnt4n** [comment]
Thanks for the issue, I've added a note to the docs!
