### ISSUE TITLE
FEATURE REQUEST: Support kotlin language

### ISSUE THREAD

**Issue by dodalovic** [hakimel/reveal.js#2076]
Hi, there! Thank you for all you did for us!
One thing I miss at the moment is a good support for **Kotlin** language:

![image](https://user-images.githubusercontent.com/6358061/35192496-1c991f90-fe94-11e7-9d1a-8631a7e5ad33.png)

Is there any plan for have it support somewhere near in the future? 
Many thanks!

**Comment by dougalsutherland** [comment]
reveal.js doesn't do its own syntax highlighting; that's done by [highlight.js](https://highlightjs.org).

It looks like highlight.js actually already has Kotlin support. The current version in reveal.js is 9.11.0, which was updated from 9.0.0 in https://github.com/hakimel/reveal.js/commit/fab28362ce2f46929c41cc1252281a7757b4695f; there were [a bunch of improvements](https://github.com/isagalaev/highlight.js/commits/758f5eca6de26f07e7df0dba270ab06736bab501/src/languages/kotlin.js) to Kotlin support in between there.

If you still have an issue with the Kotlin syntax highlighting, the probable place to report that is [the highlight.js issue tracker](https://github.com/isagalaev/highlight.js/issues).

**Comment by bnjmnt4n** [comment]
Yep, highlight.js takes care of the syntax highlighting. One thing you might not have done is indicate the language in your code block, you should add ```kotlin to your Markdown code blocks to indicate the language.
