### ISSUE TITLE
SHUFFLE only vertical slides, not horizontal slides. HOW?

### ISSUE THREAD

**Issue by G1305** [hakimel/reveal.js#2081]
HELLO EVERYONE. 
I WANT ENABLE SHUFFLE inside  1HORIZONTAL SLIDE ONLY
example:
> <section>Single Horizontal Slide **with** SHUFFLE</section>
		<section>
			<section>Vertical Slide 1 SHUFFLEenabled</section>
			<section>Vertical Slide 5 SHUFFLEenabled</section>
                        <section>Vertical Slide 6 SHUFFLEenabled</section>
                        <section>Vertical Slide 3 SHUFFLEenabled</section>
                        <section>Vertical Slide 4 SHUFFLEenabled</section>
                        <section>Vertical Slide 2 SHUFFLEenabled</section>
		</section>
> <section>Single Horizontal Slide **without** SHUFFLE</section>
		<section>
			<section>Vertical Slide 1 SHUFFLEdisabled</section>
			<section>Vertical Slide 2 SHUFFLEdisabled</section>
                        <section>Vertical Slide 3 SHUFFLEdisabled</section>
                        <section>Vertical Slide 4 SHUFFLEdisabled</section>
                        <section>Vertical Slide 5 SHUFFLEdisabled</section>
                        <section>Vertical Slide 6 SHUFFLEdisabled</section>

		</section>

**Comment by bnjmnt4n** [comment]
You'll have to implement your own shuffling algorithm to shuffle the vertical slides only, then call something like `Reveal.sync()`.
