### ISSUE TITLE
same elements in slideshow

### ISSUE THREAD

**Issue by G1305** [hakimel/reveal.js#2084]
HOW do repeating div elements for all slides?
example of  https://revealjs.com/#/
![screenshot 80](https://user-images.githubusercontent.com/34474564/35438921-059ea888-02b2-11e8-9561-4ad5436ab62e.png)

**Comment by G1305** [comment]
after inserting comething code between 

> <div class="slides">
and
> <section>
everything moves down... please help

**Comment by wjdenny** [comment]
Use CSS `position: absolute` on the elements you need to persist.
