### ISSUE TITLE
I have a lot of trouble when using Reveal with npm

### ISSUE THREAD

**Issue by theGABS** [hakimel/reveal.js#2086]
I dont see any information about how to use reveal.js with npm, but I found npm package https://www.npmjs.com/package/reveal.js

After in my code I wrote `import Reveal from 'reveal.js'`
It is seems to work. But I have trouble with Markdown, when I just wrote 
```
           <section data-markdown>
            	<textarea data-template>
            		## Page title

            		A paragraph with some text and a [link](http://hakim.se).
            	</textarea>
            </section>
```

it is just show me textarea with text. So I think it is because I didn't import marked.js and markdown.js 

So I try 
```
import Reveal from 'reveal.js'
import PluginA from 'reveal.js/plugin/markdown/marked.js'
import PluginB from 'reveal.js/plugin/markdown/markdown.js'
```

But I got error (Reveal is not defined), So, I change it to 

```
import Reveal from 'reveal.js'
window.Reveal = Reveal
import PluginA from 'reveal.js/plugin/markdown/marked.js'
const PluginB = require('reveal.js/plugin/markdown/markdown.js')
```

Now I haven't error, but it doesn't work (just textarea instead of beautiful text).

Maybe I should in same way initialize makrdown plugin ? (But I don't see any information about it)
Now I init only Reveal 

```Reveal.initialize()``` 

>When reporting a bug make sure to include information about which browser and operating system you are on as well as the necessary steps to reproduce the issue

I use create-react-app, macOS, chrome Version 63.0.3239.132 (Official Build) (64-bit), and open page on localhost. 
Reveal.js version 3.6.0

**Comment by bnjmnt4n** [comment]
The Reveal code wasn't written for ES6, so there are some complexities you might have to deal with. The markdown plugin depends on `Reveal` and `marked` (and possibly `highlight`) being defined as globals, so you might have to try something like this if you are using ES6 imports:

```js
import Reveal from 'reveal.js'
import Marked from 'reveal.js/plugin/markdown/marked.js'
window.Reveal = Reveal;
window.marked = Marked;
import Markdown  from 'reveal.js/plugin/markdown/markdown.js'
Markdown.initialize();
```
