### ISSUE TITLE
migrating from slides.com to pure reveal.js...

### ISSUE THREAD

**Issue by jcamp** [hakimel/reveal.js#2088]
Created a presentation in slides.com (pro), exported and over the months made many changes. I note that reveal.js and many 3rd party plugins have moved on. Now looking to separate the slides.com 'stuff' (offline.xxx, etc.) and keep the presentation but just use native reveal.js and plugins.

Is there a nice process to follow to do this? I cannot go back to the slides for css and js,etc. as have made many mods during the last few weeks so local version does not reflect what is in slides.com any more.

Need to get back to native reveal.js for some of the plugins to work properly (mainly menu system).

Cheers
Jonathan

**Comment by hakimel** [comment]
Hi Jonathan. Presentations created with Slides depend on additional styles and scripts on top of what reveal.js provides and you can't get rid of those files without affecting the presentation.

If you want to upgrade an old Slides export to a newer version of reveal.js you should be able to replace the reveal.min.js and and reveal.css files with the latest from this repository.
