### ISSUE TITLE
Reveal bugs in SPA (single page application) after remove div.reveal 

### ISSUE THREAD

**Issue by theGABS** [hakimel/reveal.js#2093]
I am not sure it is bug with reveal rather my own code.

But it is seems that if I remove DOM node with class reveal, and than add it again Reveal doesn't work anymore.  Without any error in console

**Comment by bnjmnt4n** [comment]
Hi, Reveal currently isn't built to allow initializing and then removing the whole reveal div as we do a lot of DOM manipulation which requires the div to exist. If you're trying to embed reveal in a SPA you might have better luck putting it in an iframe.

**Comment by akash-pal** [comment]
What do you mean by putting it in an iframe?
