### ISSUE TITLE
reveal.js with holoviews

### ISSUE THREAD

**Issue by Scheherzaade** [hakimel/reveal.js#2095]
I have a notebook presentation with interactive Holoviews (bokeh) plots that work fine if I use the rise slideshow. However, if I convert it to slides, the output is not displayed and the input cells start showing again. I'm using reveal.js 3.6 and I serve it locally. Even post serving through the CDN doesn't seem to help this issue.

**Comment by bnjmnt4n** [comment]
This seems more like a personal support question better suited to [StackOverflow](http://stackoverflow.com/questions/tagged/reveal.js), as Holoviews is an external library which we can't help you with.
