### ISSUE TITLE
how to INCLUDE?

### ISSUE THREAD

**Issue by G1305** [hakimel/reveal.js#2100]
I only want click to open external HTML.
example:
SLIDE#1 has two content (linked text)

after clicking CONTENT#1 loads EXTERNAL HTML#1.
P.S.  external HTML#1 is hidden inside SLIDEs - before clicking CONTENT#1

HOW DO THIS?

**Comment by G1305** [comment]
https URLs working fine.
but after linking local html files on text, comes this error:

Not Found - 404
The requested URL was not found on this server.
P.S. i'm using ampps

**Comment by bnjmnt4n** [comment]
This doesn't seem to be related to reveal, instead it seems to be some external plugin since reveal doesn't allow loading external HTML files. Please open an issue in the correct repo or ask personal support questions on StackOverflow instead.
