### ISSUE TITLE
mouse BACKward scrolling bug

### ISSUE THREAD

**Issue by G1305** [hakimel/reveal.js#2101]
I found backward move bug,
when I'm scrolling data-external-replace sections, for example:
[vertical slide 1]
slide 1,1
slide 1,2
slide 1,3

[vertical slide 2]
slide 2,1
slide 2,2
slide 2,3
backward move from 2,1 is 1,2 - not 1,3

**Comment by bnjmnt4n** [comment]
Backwards mousewheel scroll will navigate to the previously navigated slide. Hence if you've moved from 1,2 to 2,1, navigating to the previous slide will cause it to move back to 1,2 instead of 1,3.

**Comment by mschilli87** [comment]
Was this solved or closed by mistake?

**Comment by G1305** [comment]
this bug is from external reveal plugin, not revealjs by default...
anyone knows how to INCLUDE reveal?
