### ISSUE TITLE
Quote positioning

### ISSUE THREAD

**Issue by Sec91** [hakimel/reveal.js#2102]
I set a background image of the author of a certain quote to the last slide.
According to a beautiful design I need to shift the whole quote left.
At the moment it's centered as usual.

I'm not deep into CSS positioning so I would be very happy if somone could provide me some help.

**Comment by bnjmnt4n** [comment]
Try setting `style="text-align: left"` for the `section`.

**Comment by Sec91** [comment]
That's not enough. I need to shift the whole section left.

**Comment by bnjmnt4n** [comment]
Try adjusting the width and margin to suit your own needs: 

```css
.reveal blockquote {
  width: 70%;
  margin: 20px 0;
}
```

Also, the issue tracker is mostly meant for feature requests and bug reports. Try asking personal support questions on [StackOverflow](http://stackoverflow.com/questions/tagged/reveal.js) instead.
