### ISSUE TITLE
mark tag does not highlight properly

### ISSUE THREAD

**Issue by stroebitzer** [hakimel/reveal.js#2124]
On adding a marked line like this`<mark>var nodes = document.querySelectorAll( selector );</mark>` and opening the site in a browser I see the yellow highlighted text for about 200 ms and then it disappears and the text gets shown unhighlighted.

I tried this via the current master version with the demo site too. Only added the mark tags in the "Pretty Code" section - no other changes from my side. It happens in Chrome and Firefox on Windows and on MacOs.

**Comment by Arkanosis** [comment]
I have exactly the same problem. Here's a minimal reproduction case, where in the first code block (SQL), the marked word is highlighted only very briefly and in the second code block (Python), it's properly highlighted:

```html
<!doctype html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=5.0, user-scalable=no">

		<link rel="stylesheet" href="../reveal.js/css/reveal.css">
	</head>
	<body>
		<div class="reveal">
			<div class="slides">
				<section>
					<div>
						<pre><code>
USE frwiki_p;
SELECT <mark>DISTINCT</mark> ug_group
FROM user_groups;
						</code></pre>
						<pre style="height:80%"><code style="height:100%; max-height: 100%" data-noescape>
import sys
<mark>foo = {}</mark>
					</code></pre>
					</div>
				</section>
			</div>
		</div>

		<script src="../reveal.js/lib/js/head.min.js"></script>
		<script src="../reveal.js/js/reveal.js"></script>

		<script>
			Reveal.initialize({
				dependencies: [
					{ src: './reveal.js/plugin/highlight/highlight.js', async: true, callback: function() { hljs.initHighlightingOnLoad(); } }
				]
			});
		</script>
	</body>
</html>
```

**Comment by Arkanosis** [comment]
Ok, I got it: I was missing the `data-noescape` attribute in the first code block…

@stroebitzer : haven't you the same problem?

**Comment by stroebitzer** [comment]
@Arkanosis yes, for me this issue is fixed since I use `data-noescape`

**Comment by Arkanosis** [comment]
Thanks :)

I guess this issue could be closed, then.
