### ISSUE TITLE
Notes timer doesn't work when using RevealNotes.open() 

### ISSUE THREAD

**Issue by denehyg** [hakimel/reveal.js#2157]
Programatically opening the notes window using `RevealNotes.open()` fails to reference the `Reveal` object as `this` is scoped to `RevealNotes` rather than the global scope. As a result the timer function is unable to work.

https://github.com/hakimel/reveal.js/blob/a2e69a4b42f9e968406f62073d1c4bf0ea2d3361/plugin/notes/notes.js#L25

This does not occur when opening the notes window from the keyboard as `this` is scoped to the global object.

I believe this should be `notesPopup.Reveal = window.Reveal` instead.

**Comment by hakimel** [comment]
Fixed in #2158
