### ISSUE TITLE
pre element too tall?

### ISSUE THREAD

**Issue by merlinpatt** [hakimel/reveal.js#2164]
For some reason pre blocks are taking up more height than they should. In the example screenshots, the pre block is taller than the code block by about 90 pixels.

But the CSS does not seem to indicate why. pre does not have a height defined and code does not have that amount of padding, so I don't understand why it is taking up so much space.

Why is pre's height so much higher than code? Why does pre not simply wrap code and match its height?

I have images showing this issue at [StackOverflow](https://stackoverflow.com/questions/50449847/what-causes-pre-to-be-higher-than-code-in-reveal-js).

**Comment by szechyjs** [comment]
I'm having the same problem. (rev a82c4333ed8c192e26f83f1815593c3db50ab0f6)

<img width="1124" alt="screen shot 2018-06-19 at 8 45 06 pm" src="https://user-images.githubusercontent.com/847739/41631274-b92d4560-7401-11e8-8d7c-475a5e875ea3.png">

**Comment by szechyjs** [comment]
I figured it out thanks to #1874, the problem was whitespace between the `pre` and `code` tags.

**Comment by merlinpatt** [comment]
Can it only be fixed by removing the whitespace between the tags or is there another option?

I much prefer to have each tag on a separate line

**Comment by bnjmnt4n** [comment]
Currently the only solution is to remove the whitespace between the pre and code tags. This is due to the semantics of the pre element which displays all whitespace between pre tags as is.
