### ISSUE TITLE
Full screen code block

### ISSUE THREAD

**Issue by pieterjd** [hakimel/reveal.js#2168]
As I use quite large code snippets in my slides, the default width and height cause scrollbars to appear.

Given there is still plenty of space around the code block, I would like it to take up all available width and height.

I've tried the add the stretch class on the pre element, but no luck so far. Given I'm not at all experienced in CSS, I'm looking for some help!

Thanks!
Pieter-Jan

**Comment by pieterjd** [comment]
By coincidence, I stumbled on this plugin:
https://github.com/mkordulewski/reveal.js-fullscreen-code

Works like a charm!

**Comment by Trolldemorted** [comment]
are there ways to do this in vanilla revealjs?
