### ISSUE TITLE
Markdown speaker notes break notes window

### ISSUE THREAD

**Issue by LMnet** [hakimel/reveal.js#2174]
Hi! I want to write slides in the pure HTML and speaker notes in the markdown. Regarding the docs I should do something like this:
```html
<section>
    <p>Test</p>
    <p class="fragment">Test2</p>

    <aside class="notes" data-markdown>
        ###Some notes
        *In the markdown*
    </aside>
</section>
```
But it breaks my notes window - next slide Ignores fragments and notes subwindow is empty. Removing  `data-markdown` class from the `aside`  fixed the problem, but at the same time I lost markdown support in the notes.

I'm using reveal.js 3.6.0 with white theme on Chrome Version 67.0.3396.79 (Official Build) (64-bit) on linux. `marked.js` and `markdown.js` present in the dependencies.

**Comment by thomasobrien99** [comment]
I believe the expected usage to get what you're looking for is:
```
<section data-markdown>
  notes:
  ### Some Notes
  *In the markdown*
</section>
```
and that works as expected. The `<aside class="notes">` gets added afterward as part of the MD formatting and the formatter matches on `/notes?:/gmi`.

IMO this issue can be closed.

**Comment by ratnanil** [comment]
I'm not sure how https://github.com/hakimel/reveal.js/issues/2174#issuecomment-600404706 is an answer to OP's question:

> I want to write slides in the pure HTML and speaker notes in the markdown

That said, the code suggestion by @LMnet but caused issue works for me with slight adjustments (remove indent)

```diff
<section>
    <p>Test</p>
    <p class="fragment">Test2</p>

    <aside class="notes" data-markdown>
-        ###Some notes
+ ### Some notes
-        *In the markdown*
+ *In the markdown*
    </aside>
</section>
```
