### ISSUE TITLE
Is it possible to stay on current slide after reload during development?

### ISSUE THREAD

**Issue by lichtner** [hakimel/reveal.js#2175]
While I am developing a presentation, I would like to stay on the current working slide. But after saving changes page is reloaded and presentation is moved to the first slide. It is very annoying. Is there any way to force reveal.js to stay on the current working slide during development? Thanks.

**Comment by rugk** [comment]
Just set `history` to true. Then it should show it to you and reload to the same slide via `#/slide` number.

**Comment by lichtner** [comment]
Excellent, you saved my life :smile:

**Comment by melaniewalsh** [comment]
You just saved mine as well! Thank you @rugk!

**Comment by hakimel** [comment]
There's a new `hash` config option that you use to address this as well. `history: true` means each slide change is pushed to browser history. `hash: true` gives you unique URLs for each slide without pushing to the browser history.

I've updated the default index.html to include `hash: true`.
