### ISSUE TITLE
How to export an animated reveal.js presentation as video?

### ISSUE THREAD

**Issue by theabhinavdas** [hakimel/reveal.js#2178]
I would like to export a revealjs presentation as an mp4/webm. Is this possible? Can I use something like [https://github.com/spite/ccapture.js/](https://github.com/spite/ccapture.js/) to achieve this?

**Comment by holloway** [comment]
@theabhinavdas ccapture.js uses `<canvas>` and Reveal.js doesn't so 'No' to that part of your question.

Instead use a screen recorder for your platform.

**Comment by fzyzcjy** [comment]
+1 Can we have it after four years?

**Comment by vanBrakel** [comment]
I know how to do this, might make a plug-in for this.

**Comment by Lai-0602** [comment]
> I know how to do this, might make a plug-in for this.

Look forward to your plug-in!

**Comment by icariantk** [comment]
> I know how to do this, might make a plug-in for this.

Where's that plugin D=

**Comment by kapsner** [comment]
> > If you're using Chrome use a screen recorder like https://chromewebstore.google.com/detail/screen-recorder/hniebljpgcogalllopnjokppmgbhaden
> 
> Yea, i have no problem using OBS or any other to screen record something, but my implementation need to output directly the MP4 instead of the HTML+files of the reveal.js

Same here - although OBS is a very powerful tool, it seemed a waste of time to me, always having to screen-record my reveal.js slides with audio-playback when having to turn them into an mp4-video.

This is why I came up with `reveal2mp4`, a cli tool to render revealjs-slides with audio-playback (using the [audio-slideshow](https://github.com/rajgoel/reveal.js-plugins/blob/master/audio-slideshow/README.md) plugin) into an mp4 video: https://github.com/kapsner/reveal2mp4

For me, `reveal2mp4` is a game changer and perhaps, this is tool might also be useful to others.
