### ISSUE TITLE
Having a slide with 100% iframe

### ISSUE THREAD

**Issue by halukkaramete** [hakimel/reveal.js#2195]
Is it possible to create a slide section to have an HTML something like that:

`<iframe src='example.com' style='height:100%;width:100%'></iframe> ` whereby the example.com takes up the entire browser and user can scroll the iframe ( thus example.com ) ?

For a similar token, is it possible to have a slide section where a long content can be inserted to be scrolled up|down? For example, can you have an image like this `<img src='my-portrait.jpg' width=1000 height=6000>` and scroll down ( using the mouse whell or scroller ) to reveal the image?

**Comment by halukkaramete** [comment]
I got what I wanted like this:
https://bionicteaching.com/reveal-js-tweak-for-iframe-backgrounds/
that takes care of the iframe based implementation, almost perfectly. 

But still cannot figure out how to do the long content with scroll capability...

**Comment by gcalmettes** [comment]
Check out the [reveal-d3](https://github.com/gcalmettes/reveal.js-d3) plugin, you can embed full (scrollable) webpages in background iframe with it (e.g.: [demo](https://gcalmettes.github.io/reveal.js-d3/demo/#/8))

**Comment by halukkaramete** [comment]
Thank you for reply but from either the demo or from the githib Repository
I couldn't understand much. The 3D effects are nice on the the globe but I
could not figure out what does that have to do with scrollability

**Comment by gcalmettes** [comment]
The plugin let's you embed webpages anything into `<iframe>`, and supports scrollability.

e.g.: 
```
<div class="fig-container" style="height: 400px;" 
        data-file="https://example.com" 
        data-scrollable="yes">
</div> 
```

**Comment by halukkaramete** [comment]
Now that I checked the demo site ( on a desktop computer ) and realized
what that plug-in does. But as far as I can see my approach in the
including a website thru background iframe is way more superior to the one
this plugin does. Thank you for your replies...

**Comment by hakimel** [comment]
Hey! Yes, the best way to do this is to insert the iframe as a slide background (`data-background-iframe`) https://github.com/hakimel/reveal.js#iframe-backgrounds
