### ISSUE TITLE
unicode in section ids do not reload properly

### ISSUE THREAD

**Issue by vokimon** [hakimel/reveal.js#2198]
With `history=true` reloads keep the slide, which is quite nice when you are editing them. But when the id has some unicode character within, reveal rewrites the url removing such characters from the url hash and reloads to the first slide. This is quite nagging when you are writing a slide and want to see the effects of your changes you just made.

When the id is set to some value, is quite pointless [to set it to a different one](https://github.com/hakimel/reveal.js/blob/496db06441f344f3afeb00c2d62f734f44a9e3e4/js/reveal.js#L3747) as it won't go anywhere. Html5 allows "any non-space unicode character" as id. If authors use illegal ids on html4 it's on them.

The need comes from the fact that Pandoc generates section id's from titles, and some of them have such unicode characters. I could ask Pandoc the feature of removing such chars from the id, but as i understand the proper fix is on revealjs.

This is related to #1655.

**Comment by hakimel** [comment]
This should be fixed now – see comment in #2199.
