### ISSUE TITLE
Fullpage.js-like navigation menu?

### ISSUE THREAD

**Issue by natalie-perret-1986** [hakimel/reveal.js#2203]
Hi there, 

First I wanna say, this is really an amazing job! 

Is it possible though to have a fullpage.js-like vertical navigation menu on the right like in that example: https://codepen.io/ehouarn-perret/pen/jprrqx

**Comment by Martinomagnifico** [comment]
https://github.com/Martinomagnifico/reveal.js-verticator

**Comment by Martinomagnifico** [comment]
This issue can be closed.

**Comment by hakimel** [comment]
Nice plugin @Martinomagnifico!

**Comment by Martinomagnifico** [comment]
Thanks!
