### ISSUE TITLE
Feature: Additional hash / history settings

### ISSUE THREAD

**Issue by asottile** [hakimel/reveal.js#2211]
## current

Currently there are two options which behave as follows:

### `history: false` (this is the default behaviour)

- [ ] slide change adjusts hash
- [ ] slide change pushes to history stack
- [x] loading page with hash takes you to that slide

### `history: true`

- [x] slide change adjusts hash
- [x] slide change pushes to history stack
- [x] loading page with hash takes you to that slide

## desired

I'd like to be able to have the url update without pushing to the history stack, essentially `replaceState()` instead of `pushState()` (it's currently just using `window.location.hash` assignment which is ~roughly equivalent to `pushState`

Here's my desired settings (feel free to bikeshed on the new property name)

### `history: false`, `hash: false` (this is the default behaviour)

(same as `history: false` before)

- [ ] slide change adjusts hash
- [ ] slide change pushes to history stack
- [x] loading page with hash takes you to that slide

### `history: true` (implies `hash: true`)

(same as before)

- [x] slide change adjusts hash
- [x] slide change pushes to history stack
- [x] loading page with hash takes you to that slide

### `history: true`, `hash: false`

This is an illegal combination, `history: true` *implies* `hash: true`.  (technically I think `pushState` supports adding history states without modifying the url so this could be supported, but I don't think it's worth thinking about?).

### `history: false`, `hash: true`

(this is the thing that I want)

- [x] slide change adjusts hash
- [ ] slide change pushes to history stack
- [x] loading page with hash takes you to that slide

## addendum / thanks

- thanks for the project and to everyone who has contributed, really awesome stuff.  I'm currently using it heavily in my [`markdown-to-presentation`](https://github.com/anthonywritescode/markdown-to-presentation) project which converts simple markdown to a reveal.js presentation
- I'd be happy to hack on this if this is seen as a desirable feature and [usage of `replaceState` / `pushState`](https://caniuse.com/#feat=history) fits whatever browsers the project currently supports
- here's some [prior art of mine](https://github.com/tonybaloney/pep-explorer/pull/2/files) which uses `replaceState` / `pushState` with hashes -- [and in action](https://tonybaloney.github.io/pep-explorer/)

**Comment by asottile** [comment]
Via #2286

**Comment by limjh16** [comment]
Hey! I think this issue hasn't been fully solved: even with `hash: true` and `history: false`, the slide changes are written to the browser history. This happens on both the latest chrome and firefox. Should I start a new issue?

<details><summary>screen recording
</summary>

![Screen Recording 2020-05-25 at 3 02 54 PM](https://user-images.githubusercontent.com/15180396/82787681-84989b00-9e99-11ea-8ce2-85661ea93f3b.gif)

</details>

**Comment by hakimel** [comment]
@limjh16 I tested this but it's behaving as intended. Chrome's "Recently Visited" list isn't the same as browser history. If you try to press navigate a deck with `history: false` and try to press the browser back arrow, it won't step through each slide so they haven't been recorded in history.

**Comment by limjh16** [comment]
> Chrome's "Recently Visited" list isn't the same as browser history. 

Ahh okay that explains it, when I press the browser back arrow it doesn't step through every slide as well... Thanks for the quick reply!
