### ISSUE TITLE
Syntax highlighting (from external markdown file) adds closing tags

### ISSUE THREAD

**Issue by smsnheck** [hakimel/reveal.js#2235]
Hi, I am creating a slideshow from an external markdown file. This file has some XML code inside. 
When I want to show self-closing XML Tags like `<foo .../>` it is displayed as `<foo ...></foo>`

This "auto replacement" messes up the whole code. Especially if there are a lot of self closing tags consecutively: 

```
<foo ... />
<bar .../>
<baz .../> 
```
Renders to: 
```
<foo ...><bar ...><baz...>
</foo></bar></baz>
```

Is it possible to deactivate this behaviour?

**Comment by bnjmnt4n** [comment]
Seems like your code is being treated as HTML by the Markdown parser. Try wrapping your code in triple backticks:
<pre><code>```
&lt;!-- code -->
&lt;foo ... />
```
</code></pre>
