### ISSUE TITLE
data-transition not working

### ISSUE THREAD

**Issue by reagle** [hakimel/reveal.js#2237]
#1947 reports `data-transition` on vertical slides doesn't work, but I can't get convex, concave, or zoom to work on any per-slide transitions. See the slides following [this one](https://reagle.org/joseph/talks/2014/exemplar.html#/transitions).

**Comment by reagle** [comment]
To clarify, the transition effects work when they are set globally, whether horizontal or vertical. For example, this global convex setting works:

https://reagle.org/joseph/talks/2014/exemplar.html?transition=convex

The problem is with per-slide transitions. @hakimel's [demo slides](https://revealjs.com/) don't have per slide transitions (except on the background), so it's difficult to isolate.

Next step, I will download the demo slides and see if they work there.

**Comment by reagle** [comment]
When I add `data-transition` attributes to slides in the official demo set, they work on horizontal but not on vertical/nested. So #1947 is the most important bug. (My slides are generated via pandoc so there might be something there causing a problem too but that is hard to say until #1947  is addressed.)

**Comment by reagle** [comment]
I've determined my horizontal slides are not working because pandoc wraps all top level sections -- except the title-slide -- in a superfluous `<section>` element. This means all my slides suffer from issue #1947. I'll close this issue #2237, ask about this pandoc behavior on their list, and clarify #1947.

```
<body>
  <div class="reveal">
    <div class="slides">

      <section id="title-slide">
        <h1 class="title">Habits</h1>
        <p class="author">John Doe</p>
        <p class="date">March 22, 2005</p>
      </section>

      <section>
        <section id="in-the-morning" class="title-slide slide level1"><h1>In the morning</h1></section>
        <section id="getting-up" class="slide level2">
```

**Comment by ayhankesicioglu** [comment]
https://github.com/hakimel/reveal.js/issues/1515#issuecomment-432471954
