### ISSUE TITLE
Online Gui editor

### ISSUE THREAD

**Issue by rakeshkgsg** [hakimel/reveal.js#2249]
Hi, is there an online gui editor for this which we can use to integrate into our apps. Would be awesome to have this feature in a cms

**Comment by hakimel** [comment]
There's slides.com—a presentation platform and editor built around reveal.js. However the GUI editor that we've built for Slides isn't available open source so it can't be integrated into your own CMS. We're looking at options for enabling integrations like that in the future though.

**Comment by danielduckworth** [comment]
Hi @hakimel, I came across this old thread trying to answer the same question as rakeshkgsg.

Are you still looking into making an open source GUI for reveal.js? Do you know of any alternatives?

**Comment by hakimel** [comment]
Hi @danielduckworth. Sorry but I don't have any plans for building an open source graphical editor.
