### ISSUE TITLE
MathJax dosen't float well with reveal.js

### ISSUE THREAD

**Issue by changhw01** [hakimel/reveal.js#226]
Please see "www.stanford.edu/~huangwei/MySlides" and navigate to the next page.

It happens when I use the HTML-CSS output of MathJax. If we use the SVG output then it is fine. I have tried it using FireFox and Chrom.

**Comment by jasen0319** [comment]
Read and learn

**Comment by hakimel** [comment]
@XertroV If there are issues I'd to address it in the math plugin. Do you have an example where math rendering is causing issues? I tried a few combinations of math and auto-animate but it worked as intended.

**Comment by XertroV** [comment]
> @XertroV If there are issues I'd to address it in the math plugin. Do you have an example where math rendering is causing issues? I tried a few combinations of math and auto-animate but it worked as intended.

I'm currently using mathjax3 via the current master (looks like this was just released) and it's amazing -- much faster, don't need any custom logic around redrawing (I use xyjax which needed some massaging with mathjax2), and I've been able to disable all the rerendering stuff. (there are very occasional glitches, but they're tolerable and rerendering doesn't always fix them anyway.)

WRT examples, I can't provide any, sorry (code isn't public atm). But IMO mathjax3 with the new math plugin solves any substantial issues I had.

There are very occasional font-size related glitches I get when using some math across multiple consecutive slides. The font size jumps slightly when auto-animating. I can't reproduce them though -- I don't know how to trigger them in a reliable way. If you're trying to reproduce, try using a lot of `$\mathbb{A}$` (or B, C, etc) inline elements (e.g. in paragraphs, headings). Autoanimating between 3-8 slides.

I made my previous comment with the goal of sharing the code (in case anyone went looking for a soln). Rereading it, I didn't make it clear that my circumstances weren't typical. I mention xyjax above, but the deck also has about 250 slides, and plenty of mathjax sprinkled throughout (mb on 25% of slides, and multiple elements/fragments per slide where they appear).

PS. Thanks for a fantastic framework! :)

**Comment by hakimel** [comment]
Thanks a lot for the info.

Great to hear the new MathJax 3 renderer solved many of the issues for you! That makes me wish that I'd have gone with that over MathJax 2 as the default in today's 4.2.0 release. I'll likely switch to MathJax 3 in the next release instead. If you or anyone else knows of any major differences or reasons we should't default to v3 please let me know.

For the record, if anyone else encounters this and wants to switch to MathJax 3 you'll need to swap out `RevealMath` for `RevealMath.MathJax3` in your initialization:
```js
Reveal.initialize({
  mathjax3: {
    // config options
  },

  plugins: [ RevealMath.MathJax3 ]
});
```

**Comment by iamashwin99** [comment]
Does any one know what the equivalent of 
```
Reveal.addEventListener( 'slidechanged', function( event ) {
    MathJax.Hub.Rerender(event.currentSlide);
});
```
is for `RevealMath.KaTeX` ?
