### ISSUE TITLE
Cannot trigger nextFragment() using data-state on specific slides

### ISSUE THREAD

**Issue by Clifford-Yen** [hakimel/reveal.js#2264]
Hi there,

I recently want to make the first fragment in a slide automatically appears. I came up with some ways, and I found the best way to achieve is to set the data-state on the section element with an event listener to monitor it. So ideally this should work:

HTML:
```
<section data-state='autoFirstFragment'>
    <ul>
        <li class="fragment fade-in-then-semi-out" data-fragment-index="1">Item 1</li>
        <li class="fragment fade-in-then-semi-out" data-fragment-index="2">Item 2</li>
        <li class='fragment' data-fragment-index="3">Item 3</li>
    </ul>
    <table class='fragment' data-fragment-index="3">
        <tr>
            <td>Some Cell</td>
        </tr>
    <table>
<section>
```

JavaScript:
```
Reveal.addEventListener( 'autoFirstFragment', function() {
	Reveal.nextFragment();
	console.log('hey');
}, false );
```

But turns out I only can get the log, and the first fragment will not appear at all.

I try to replace the event with 'slidechanged' and it works, but this is not I want since I just want some slides to behave in this way.

Another approach is to replace the first fragment style to an undocumented 'semi-fade-out', then the first li element will appear at the beginning then semi fade out after the first fragment is triggered. But users need to take care of the data-fragment-index themselves. In this case, setting the data-fragment-index='1' is needed for the first and second fragments.

Finally, if I want to stick to my original approach, it can works with a dirty hack by an unnoticeable short delay before calling nextFragment(). So the script becomes:
```
function sleep(ms) {
	return new Promise(resolve => setTimeout(resolve, ms));
}
Reveal.addEventListener( 'autoFirstFragment', async function() {
	await sleep(100)
	Reveal.nextFragment();
	console.log('hey');
}, false );
```

Obviously, this is not a good way to implement. Since the 'slidechanged' event can correctly trigger the nextFragment(), I think it should be possible to do the same by setting data-state on a slide then monitor it. I cannot tell is this a bug or an expected behavior. Any idea?

Thanks for any suggestion.

**Comment by hakimel** [comment]
Looks like the state events are being fired too early, before reveal.js has actually switched to the next slide. So your `Reveal.nextFragment()` call is received in the context of the previous slide unless you use a timeout.

Will fix this by adjusting the event order.

**Comment by hakimel** [comment]
This issue has been fixed and I've added some tests for state events: 42e796afb2a4db10772cf0f4b517094c0fbec644

The fix is only available in the dev branch so far, but if you look at the diff you could mirror the change in your local reveal.js file.
