### ISSUE TITLE
Introduce a `Dockerfile` and/or `docker-compose` template for ease-of-use?

### ISSUE THREAD

**Issue by x10an14** [hakimel/reveal.js#2270]
Hiya!

i (and this may be construed as cursing in the church), _do not_ want to install `grunt`, `bower`, or any version of `npm` on my machine "directly" (AKA polluting my PATH variable).

Thus, would it be a welcome idea to add a `Dockerfile`/`docker-compose.yaml` file, so that people could easily spin-up their slides in a _containerized_ (pun not intended, referring to not polluting machine env(s)/PATH) manner? =)

AKA:
`git clone <this repo> && docker-compose up -d && <your browser of choice> localhost:8080`?

**Comment by x10an14** [comment]
Just added PR #2271 for this.

Would be nice with some maintainer input on what folder/location to mount into the docker container from repo, so that a user wouldn't have to re-build the docker image for each change, just reload. 

(With the `index.html` being in repo root, it's kinda all or nothing now.
Which is fine, but I want to ensure that's the intention before I add a `mount` of the whole git repo to the `docker-compose` file).

**Comment by x10an14** [comment]
Added a `Makefile` showing how I use this personally. Up to you if you want to keep it in a "final" PR or not.

Also added a `bin_wrapper.sh`, in case you want to do something like have a watch-dog process running and checking if you edit the code live (in which case a volume should be mounted instead of the `COPY . /data/` line in the `Dockerfile).

**Comment by hakimel** [comment]
Hey! Thanks for the suggestion and PR but I don't know think we need a dockerfile.

You don't need to install anything to use reveal.js. Neither grunt or npm is required. You can just download a ZIP of the [latest release](https://github.com/hakimel/reveal.js/releases), add your content to index.html and double-click to open it in the browser.

**Comment by mosabua** [comment]
I agree with @hakimel  .. needing docker is just as bad as needing docker and docker-compose when nothing is really needed..

**Comment by x10an14** [comment]
@mosabua @hakimel Fair enough that it's no longer necessary/relevant for end-users of reveal.js! (Applause earned!)

Is it still not relevant to consider wrt. enabling other developers wanting to contribute?
One _MUST_ install npm, grunt, bower, and whatever else onto their own machine if one wants to PR contribute to project without installing all of that on their own machine?

Granted, I haven't tested if the global flags have been removed/worked around.

**Comment by x10an14** [comment]
Or just when an end-user wants to utilize the documented https://github.com/hakimel/reveal.js#full-setup as described in your README.md file.
