### ISSUE TITLE
Distinct events for slide change (started/finished)

### ISSUE THREAD

**Issue by capagot** [hakimel/reveal.js#2272]
Hi guys! First, congratulations for this excellent project!

This is not an issue, but more a feature request.

I am integrating reveal.js with three.js, and currently I have several interactive 3D animations running on several slides of my presentation. In order to reduce the rendering overhead, I turn off the 3D rendering for those slides that are not visible. I do this by switching off the rendering of the slide as soon as I start navigating to the next one (through the 'slidechanged' event). 

The problem is that I would like to keep the 3D rendering animation of the previous slide running until the transition is completely finished (I don't think this is critical, but in my opinion is good looking). However, it is not possible to check when a transition is completely finished. 

Thus, I would propose the creation of two separate events for the slide transition, something like: "slidechanged_started" (triggered as soon as the transition starts) and "slidechanged_finished" (triggered as soon as the transition finishes completely). 

Cheers,
Christian

**Comment by Martinomagnifico** [comment]
I wrote a plugin for this: https://github.com/Martinomagnifico/reveal.js-transit, and then you can use slidechanged and slidechangecomplete

**Comment by capagot** [comment]
Hi Martinomagnifico
    Thank you for the plugin! I will indeed check it out! Just one question, why did you say in the plugin repo that a future version of Revel.js will make the plugin obsolete? Are you aware about the inclusion of events of this type a in feature version of Revel.js? 

    Cheers... and thank you once again!
    Christian

**Comment by Martinomagnifico** [comment]
There are multiple quests for these events to be added, so I think it's a logical evolution of Reveal.

**Comment by capagot** [comment]
Sure!!! :)
