### ISSUE TITLE
Jump to slide by keyboard text input

### ISSUE THREAD

**Issue by jozsefk9** [hakimel/reveal.js#2283]
Would it be possible to jump to slide number by entering a number with keyboard and hitting enter?

**Comment by sharegrams** [comment]
https://github.com/SethosII/reveal.js-jump-plugin

**Comment by hakimel** [comment]
Jump-to-slide functionality is now built into reveal.js. Press G to activate, then type a slide number or slide id.

https://user-images.githubusercontent.com/629429/212676187-c94ef9dc-992d-44dd-ab09-57f3d891ef0f.mp4
