### ISSUE TITLE
View presentation in custom browser (e.g. Brave)

### ISSUE THREAD

**Issue by dteiml** [hakimel/reveal.js#2284]
Hi,

I am using VS Code. I would like the option to configure a custom browser for previewing my presentation when I run `Open presentation in browser`. I for one use Brave (which runs on Chromium and hence does not have any problems displaying the presentation), but the command always opens Chrome nevertheless.

Thank you!
Dom

**Comment by LongLiveCHIEF** [comment]
This is a VS Code issue. Reveal doesn't dictate what browser it opens in.

**Comment by dteiml** [comment]
Ok thanks!
