### ISSUE TITLE
Vertical slides left and right keys.

### ISSUE THREAD

**Issue by bncfi** [hakimel/reveal.js#2289]
Is it possible to make reveal.js to work so that when in vertical slides and pressing right/left arrow keys you would go to the same section of next vertical slide section. I have a page that is in matrix formation, so when let's say in slide 1,4 and pressing right I'd go to 2,4 and not 2,1. Is it possible and how? Was trying to search for an answer online but couldn't find.

**Comment by hakimel** [comment]
This has been asked about a few times so I've added a config option for it. In future versions of reveal.js, if you include `gridNavigation: true` navigating between adjacent vertical stacks will keep you at the same vertical index. More info in the docs here: https://github.com/hakimel/reveal.js/blob/dev/README.md#vertical-slide-navigation

Note that this only available in the dev branch so far. It'll make its way out with the next release.
