### ISSUE TITLE
Autoplay video not working

### ISSUE THREAD

**Issue by Minirock** [hakimel/reveal.js#2297]
I think this is a bug: 

I have a video slide

`            <section data-background-iframe="https://www.youtube.com/embed/sGF6bOi1NfA?autoplay=1"></section>
`

When we change slide with right keyboard, then the video is well autoplayed.
When we change slide with the autoSlide every xxx ms then the iframe is there but the video is not autoplayed. 

Any ideas ?

**Comment by hakimel** [comment]
There are a number of restrictions around what videos a browser will autoplay. If the video has sound, the user needs to explicitly request the video to be started via an interaction. Here's more info about how these rules are implemented in Google Chrome: https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

**Comment by hakimel** [comment]
No problem. Yes, when you press a keyboard button the video is being played as a result of a direct user action so the browser allows it.

**Comment by Minirock** [comment]
Oh I got it, thanks.

I'm gonna look how to handle this then ;)
