### ISSUE TITLE
reveal.js.org

### ISSUE THREAD

**Issue by shinenelson** [hakimel/reveal.js#2322]
[js.org](js.org) has a [DNS service](dns.js.org) that provides short URLs that can point to websites. I think reveal.js.org could be a lot more cooler :sunglasses:

The only change that needs to be done from our part is to change the [CNAME file](https://github.com/hakimel/reveal.js/blob/gh-pages/CNAME) with the new sub-domain.

I can create a pull request for changing the [CNAME file](https://github.com/hakimel/reveal.js/blob/gh-pages/CNAME) with the custom sub-domain as well the pull request to [js-org/dns.js.org](https://github.com/js-org/dns.js.org) to assign the sub-domain to [reveal.js](https://github.com/hakimel/reveal.js).

I'm asking approval / permission to do these :point_up_2: for [reveal.js](https://github.com/hakimel/reveal.js).

**Comment by hakimel** [comment]
Thanks for the suggestion! I really like the reveal.js.org domain but from what I understand we can only have one domain in the pages CNAME file. That said, I prefer the existing "revealjs.com" so I'm not ready to let that go and switch domains.
