### ISSUE TITLE
Automatically change to next slide when video ends?

### ISSUE THREAD

**Issue by jockebq** [hakimel/reveal.js#2327]
Is it possible to have the slide change to the next slide when the video background has ended?

I cannot figure out how to do this?
Are there any JS I can use to listen for video end, and call next slide?

**Comment by dougalsutherland** [comment]
Yes, [the `ended` event](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/ended_event) is sent. Something like this should work (but I haven't tested it):

```html
<section>
  <video data-src="..." id="my-video">
</section>
<section>
  <h2>Next slide</h2>
</section>
```

```javascript
document.getElementById('my-video').addEventListener('ended', function() {
  Reveal.next();
});
```

I think this will also fire if the video stalls because it's not loading data fast enough; you could check for that in the event handler.

**Comment by jockebq** [comment]
> 
> 
> Yes, [the `ended` event](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/ended_event) is sent. Something like this should work (but I haven't tested it):
> 
> ```
> <section>
>   <video data-src="..." id="my-video">
> </section>
> <section>
>   <h2>Next slide</h2>
> </section>
> ```
> 
> ```js
> document.getElementById('my-video').addEventListener('ended', function() {
>   Reveal.next();
> });
> ```
> 
> I think this will also fire if the video stalls because it's not loading data fast enough; you could check for that in the event handler.

But if I don't know the video name beforehand, can I still check for this event? Is there any "global" event every time a video ends?
Like this one but for video ending:

```
		Reveal.addEventListener( 'slidechanged', function( event ) {
		});
```

**Comment by dougalsutherland** [comment]
@jockebq, you probably want something like (untested):
```js
for (var v of document.querySelectorAll('.reveal video')) {
  v.addEventListener('ended', function() { Reveal.next(); });
}
```

**Comment by Martinomagnifico** [comment]
This issue is solved.

**Comment by githudjibran2** [comment]
I want to change my slide but the condition is that when my first slide completely get end its automatically change to its next slide means second slide and so on, anyone who could help us 
thanks
