### ISSUE TITLE
markedjs is out-of-date

### ISSUE THREAD

**Issue by maxrothman** [hakimel/reveal.js#2329]
The `marked` library in the `markdown` default plugin is rather out of date. In particular, the fix for https://github.com/markedjs/marked/issues/488 is not in the current version. It was resolved in April 2018 and is very handy for authoring presentations in markdown.

**Comment by dougalsutherland** [comment]
It was actually updated recently in the `dev` branch: https://github.com/hakimel/reveal.js/pull/2305. It hasn't been merged over to `master` / a release yet, though.

**Comment by hakimel** [comment]
Updated in the 3.8.0 release.
