### ISSUE TITLE
Stretch/Reduce size of slides to fit mobile screen

### ISSUE THREAD

**Issue by Sahil-Ajmera** [hakimel/reveal.js#2355]
Hi , I want to know how I can have my slides fit to a mobile screen.

Currently I use
**section  data-background="images/DSC_1292.JPG"**
which does not scale well when seen on a mobile device as my image is overflowing the mobile screen.
This looks fine on an  an actual laptop device. Thanks.

My reveals.initialize looks like this:
 Reveal.initialize({
        **width: "100%",
        height: "100%",
        margin: 0,
        minScale: 1,
        maxScale: 1,**
        dependencies: [
          { src: 'reveal.js_files/plugin/markdown/marked.js' },
          { src: 'reveal.js_files/plugin/markdown/markdown.js' },
          { src: 'reveal.js_files/plugin/notes/notes.js', async: true },
          { src: 'reveal.js_files/plugin/highlight/highlight.js', async: true, callback: function() { hljs.initHighlightingOnLoad(); } }
        ]
      });
The bold content was my try at resizing the slides based on device size.

I am using the default template inside the repo (index.html")
Best,

Sahil

**Comment by Sahil-Ajmera** [comment]
@hakimel

**Comment by hakimel** [comment]
If you want to ensure the full background image is visible you’ll need to set the “data-background-size” attribute to “contain”. That way you’ll get letterboxing instead. More info about background attributes in the readme: https://github.com/hakimel/reveal.js/blob/master/README.md#image-backgrounds
