### ISSUE TITLE
Plugin docs are out-of-date

### ISSUE THREAD

**Issue by maxrothman** [hakimel/reveal.js#2360]
The plugin docs (https://github.com/hakimel/reveal.js#plugins) reference a method `registerPlugin`. As far as i can tell, no such method exists.

**Comment by hakimel** [comment]
Hey! I double checked and `Reveal.registerPlugin` is defined in dev and master. Here's the specific line where it's defined in the API: https://github.com/hakimel/reveal.js/blob/master/js/reveal.js#L6011

Can you check if looking at an older version of the reveal.js file? `Reveal.VERSION` should return "3.8.0".

**Comment by maxrothman** [comment]
I've got 3.7, so that must be it. I guess the plugin API's new? As far as I could tell, none of the existing plugins use it.

**Comment by hakimel** [comment]
Got it. The plugin API was added about a month back and was first released in 3.8.0.
