### ISSUE TITLE
data-transition>

### ISSUE THREAD

**Issue by al3github** [hakimel/reveal.js#2363]

**Comment by al3github** [comment]
I tested adding the data-transition option to a section to be "convex" (par example), and it is not changing the transition when the section has the option data-background. It is not even taking the global transition that I put in Reveal.initialize.
For example, I do:
`Reveal.initialize({
             transition: 'concave',
	     transitionSpeed: 'slow'
});`
And the sections with the data-background option, will be still using the data-transition "slide".

**Comment by hakimel** [comment]
There are separate settings for bg transitions, see https://github.com/hakimel/reveal.js#background-transitions
