### ISSUE TITLE
How to add a window/frame/overlay over an iframe.

### ISSUE THREAD

**Issue by anthonyjdella** [hakimel/reveal.js#2379]
I've added my iframe background.

But I would like a black background that is static over the iframe (such as the black overlay in the screenshot).

![image](https://user-images.githubusercontent.com/26190505/56619791-643e4300-65ec-11e9-83bd-4d8640b64608.png)

Can someone explain this to me, I don't see it in the docs. Thanks!

**Comment by koraysels** [comment]
how did you solve this? i need the same functionality..
