### ISSUE TITLE
Script error with GitHub Pages/TravisCI Deployment

### ISSUE THREAD

**Issue by HP-Nunes** [hakimel/reveal.js#2382]
Hi,

I have had no issues deploying reveal.js as a submodule with GitHub pages and TravisCI. However  of late I've had issues with content not loading after deployment: I checked whether it was a build/credential issue with TravisCI (it's not), or whether it was an issue with the size of some files that I was pushing. I'm using the gh-pages branch as the source to deploy. I even started a new repo and retraced my initial steps, but I keep getting the same console errors:

```
GET http://hpnunes.com/deploy/reveal.js/lib/js/head.min.js net::ERR_ABORTED 404 (Not Found)

Uncaught Error: Script error for: reveal.js/lib/js/head.min.js
http://requirejs.org/docs/errors.html#scripterror
    at C (require.min.js:8)
    at HTMLScriptElement.onScriptError (require.min.js:29)
```
Is there a script error with the version of reveal.js that I'm running (2019)?

**Comment by HP-Nunes** [comment]
This is how I'm installing reveal while deploying on TravisCI:

```
install:
    - pip install jupyter
    - wget https://github.com/hakimel/reveal.js/archive/master.zip
    - unzip master.zip
    - mv reveal.js-master reveal.js

script:
    - jupyter nbconvert nb.ipynb --to slides --reveal-prefix=reveal.js

after_success: |
    if [ -n "$GITHUB_API_KEY" ]; then
    git checkout --orphan gh-pages
    git rm -rf --cached .
    mv nb.slides.html index.html
    git add -f --ignore-errors index.html img reveal.js
    git -c user.name='travis' -c user.email='travis' commit -m init
    git push -f -q https://$GITHUB_USER:$GITHUB_API_KEY@github.com/$TRAVIS_REPO_SLUG gh-pages
    fi
```

**Comment by hakimel** [comment]
The `head.min.js` file is no longer needed in reveal.js 3.8.0 and was removed from the repo. I'm not sure where it's being referenced from in your deployment though.

**Comment by HP-Nunes** [comment]
Hi Hakim,

thanks for the response. I'm suspecting there might be a compatibility issue between the latest reveal.js release and [nbconvert](https://github.com/jupyter/nbconvert). The zip files between https://github.com/hakimel/reveal.js/archive/master.zip and the [latest release](https://github.com/hakimel/reveal.js/releases) are the same (I was suspecting the former link was pulling an older version). I don't find `head.min.js` referenced in either index files. 

I'm crossposting to this issue to nbconvert to confirm whether that's the case. I've done many "clean resets" (with just the notebook and .yml configuration files) to wind up with the same errors.
