### ISSUE TITLE
Add a keyboard to going back (in order)

### ISSUE THREAD

**Issue by pprw** [hakimel/reveal.js#2406]
There is a shortcut to move forward in order (not matter if it is a down or right slide): `space`

However, there is no shortcut to going back (following the order of slides). There is only the arrow keys which allow to going back but only if you keep in mind the 2D format of the presentation.

I propose to bind `backspace` to "going back inside the presentation, no matter if the previous slide is at the left or at the top of the current one".

**Comment by hakimel** [comment]
You can use the P key or Shift + Space to move backwards through all slides.
