### ISSUE TITLE
Fullscreen button

### ISSUE THREAD

**Issue by jefferyyuan** [hakimel/reveal.js#2418]
- For users who are not familiar with Reveal.js, they don't know the shortcut 'f" to switch to full screen.
- It would be great if there is a button like in <img src='https://png.pngtree.com/svg/20160707/3a6bf2578b.svg' height="20" width="20" />, so a new user can easily figure out how to switch to full screen.
- or maybe double click to switch to full screen.
- The full-screen button would especially help we embed and share the slide using an iframe. The users are usually not familiar with revealjs, and the iframe size is usually limited.

Thanks

**Comment by NitinMadhukar** [comment]
can i solve this

**Comment by denehyg** [comment]
Have a look at https://github.com/denehyg/reveal.js-toolbar - it will give you a full screen button

**Comment by jefferyyuan** [comment]
Thanks, @denehyg , Just found that yesterday, it's exactly what I am looking for.
- Thanks and close the issue now.
