### ISSUE TITLE
Possible to embed the slides in Blogger directly without using iframe?

### ISSUE THREAD

**Issue by jefferyyuan** [hakimel/reveal.js#2420]
- We can host the slides in another website or github pages, then use iframe to embed it in blogger to share and reach more users.
- It would be great if we can embed the slide directly in blogger or wordpress without having to host the slides in another website.
- I tried it by directly copying the HTML into blogger, but seems not working, the slide is not showing at all.

**Comment by earboxer** [comment]
This would be a large undertaking, I think.

There might be problems with having multiple `Reveal`s. Some external code uses Reveal in the global namespace.

#2405 would need to be solved.

**Comment by bnjmnt4n** [comment]
With [Reveal 4.0](https://github.com/hakimel/reveal.js/releases/tag/4.0.0), [multiple presentations](https://revealjs.com/initialization/#multiple-presentations) can be embedded into a single page. To embed slides directly into external systems, you would need to be allowed to include the HTML for the presentation and load Reveal’s JavaScript code. I’m not too sure about Blogger specifically, but if it’s not possible the only alternative would be to embed an iframe as mentioned.
