### ISSUE TITLE
Helper class for fitting elements to slide size

### ISSUE THREAD

**Issue by dylang** [hakimel/reveal.js#244]
I love using this for presentations of [Doodle or Die](http://doodleordie.com) because I can use live iframes of various pages instead of static screenshots. It's super nice to not have to leave the slide deck to give demos!

The only problem is that I have to do a lot of hacking o make iframes work well. 

By default iframes utilize about 1/4 of the slide area. Zooming increases that but it makes the iframe content larger as well and it's very hard to find the right spot to click to zoom.

Feature request: Native support for iframes that all themes can inherit. 

Nice to have: `<iframe class="full">` for an iframe that takes up the whole slide.

Potential issues: I also needed to disable some gesture controls because scrolling the iframe sometimes caused the slides to switch.

**Comment by reagle** [comment]
Any chance that this requirement can now be loosened? Would still love to use stretch, but my images are rarely a child of `<section>`.

**Comment by fuhrmanator** [comment]
Hello - `.stretch` is working great for me when an object is wider than it is tall. When I use it with images that are taller than wide, they're cut off on the bottom of the slide. 

I'm using [reveal with markdown via a VSCode plug-in](https://github.com/evilz/vscode-reveal), so maybe this is a bug in their implementation? 

What class should the HTML image finally have? In my cases, it's `class="plain reveal stretch"`

**Comment by fuhrmanator** [comment]
OK - I found the trouble. The `<img>` is nested in a `<p>` and I think that is what is causing the problem. I used developer tools in Chrome to move it out of the `<p>` and it's scaling properly. Seems like a bug in the markdown converter (embedding image into a paragraph).

**Comment by reagle** [comment]
It is the [expected behavior in pandoc](/jgm/pandoc/issues/3160).
