### ISSUE TITLE
IMAGE Background does not display on reveal.js

### ISSUE THREAD

**Issue by gwpl** [hakimel/reveal.js#2448]
On Image background previes:

* https://revealjs.com/#/10/1
* https://revealjs.com/#/10/2

background does not show:

![Screenshot_20190703_121027](https://user-images.githubusercontent.com/221403/60583606-85a97100-9d8b-11e9-90bd-d55e3c83d5db.png)

or

![Screenshot_20190703_121044](https://user-images.githubusercontent.com/221403/60583625-8f32d900-9d8b-11e9-804b-d9fba30e082b.png)

**Comment by boschkundendienst** [comment]
I think this is correct. Looking at the source of the presentation you see, that the image link points to `https://s3.amazonaws.com/hakim-static/reveal-js/image-placeholder.png` as stated in

```html

<section data-background="https://s3.amazonaws.com/hakim-static/reveal-js/image-placeholder.png">
   <h2>Image Backgrounds</h2>
   <pre><code class="hljs html">&lt;section data-background="image.png"&gt;</code></pre>
   </section>
```

This [image (click here to open it)](https://s3.amazonaws.com/hakim-static/reveal-js/image-placeholder.png) actually really looks like a placeholder, therefor you might think it is not showing correctly?

You can even download it, it is an image with 6.1K size of type `PNG image data, 2000 x 2000, 2-bit colormap, non-interlaced`!

```
user@linuxbox:/tmp$ wget 'https://s3.amazonaws.com/hakim-static/reveal-js/image-placeholder.png'
--2019-07-04 15:24:19--  https://s3.amazonaws.com/hakim-static/reveal-js/image-placeholder.png
Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.216.10.157
Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.216.10.157|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6255 (6.1K) [image/png]
Saving to: 'image-placeholder.png'

100%[=====================================>] 6,255       --.-K/s   in 0s

2019-07-04 15:24:20 (62.2 MB/s) - 'image-placeholder.png' saved [6255/6255]

user@linuxbox:/tmp$ file image-placeholder.png
image-placeholder.png: PNG image data, 2000 x 2000, 2-bit colormap, non-interlaced
```

Regards

Peter

**Comment by gwpl** [comment]
Sorry, I thought it's an icon of missing image displayed by browser ;P.
I now even thought of debugging, I just filed issue ;).
Therefore lesson taken , that this example image may for some be confusing with "browser error : image missing" ;).
.
Otherwise, if it's intentional , I may be odd one , so things work :).

Thank you for great project!
Best regards!

**Comment by boschkundendienst** [comment]
You should then close this issue!

**Comment by gwpl** [comment]
Sure! Was waiting for ack :) (some could consider changing image to avoid confusion, some , leave it as it is).

Closing issue :).


Thanks for very helpful project!
