### ISSUE TITLE
How to fix the H1 headers to the top of the slide

### ISSUE THREAD

**Issue by halloleo** [hakimel/reveal.js#2486]
By default (and with all the themes I tried) the complete content of each slide is vertically centered:

![Imgur](https://i.imgur.com/Iz3UGcV.jpg)

How can I set a CSS for the h1 header, so that it stays at the top of the slide while the rest is still vertically centered? I mean something like thsi:

![Imgur](https://i.imgur.com/WbjdFe9.jpg)

I tried in CSS:

```
.reveal h1 {
    position: absolute;
}
```

and I played with changing the section style:

```
.reveal .slides {
  position: static;
}
```

but I could not make it work. Any idea how to do it?

**Comment by harlyon** [comment]
I would like to work on this... is it still open?

**Comment by halloleo** [comment]
Yes it is! I haven't found a solution yet.

**Comment by harlyon** [comment]
I see all slides have an h1 tag. how do you want them to be centered

**Comment by halloleo** [comment]
The content of H1 should not be vertically centred but stay, say 100px, from the top, while all other section content is vertically centered as usual.

Hope this makes sense - maybe my sketches in the issue description help...

**Comment by vanmash** [comment]
@halloleo, try this

in CSS
```css
    section.top h1{
        margin-top: -270px;
    }
````

in HTML
```html
<section class="top" >
    <h1>At the top</h1>
</section>
```

**Comment by vimerzhao** [comment]
As for a section like this:

```
<section>
	<h2 class="special-header">Hello There</h2>
	<p class="special-body">
		reveal.js enables you to create beautiful interactive slide decks using HTML. This presentation will show you examples of what it can do.
	</p>
</section>
```

add your custom css like this:

```
.special-header {
    position: absolute;
    padding: 10px 20px 10px 20px;
    top:30px;
    left: 0px;
    z-index:500;
    /*background-color: rgba(0,0,0,0.5)*/
}

.special-body {
    margin: auto;
    position: absolute;
    top: 50%;
    left: 0%;
    /*-ms-transform: translate(-50%, 50%);*/
    transform: translate(0%, -50%);
}

.slides>section{
    width: 100%;
    height: 100%;
}

```

before
![image](https://user-images.githubusercontent.com/17337271/148648444-500f2c1c-4b74-41a4-9d21-ad2b5cd2d49d.png)


after:
![image](https://user-images.githubusercontent.com/17337271/148648433-0cfc0373-f289-40d9-9aad-43996f5ff2d0.png)

**Comment by halloleo** [comment]
@vimerzhao This works brilliantly. Thanks a lot.

**Comment by adi-t-ya** [comment]
@vimerzhao: how would your solution work for a single slide?

**Comment by vimerzhao** [comment]
> @vimerzhao: how would your solution work for a single slide?

binding css with special section id

**Comment by kejang** [comment]
@vimerzhao Thanks a lot. It looks very nice. I would like to apply this style to all slides including ones from external markdown file. Can you let us know how to do this?

**Comment by zenzike** [comment]
I wanted `h1` to remain centred vertically (because I use this for leading vertical slides), `h2` to be at the top, and all other content to be centred vertically. I got this to work by changing the display type of sections to be `flex` and making headings be `fixed` at the top.

In my `html`:
```
Reveal.initialize({
...
	display: 'flex',
 ```
and in the `css`:
```
.reveal h2 {
  position:fixed;
  top: 0px;
}
```

**Comment by zenzike** [comment]
I wanted `h1` to remain centred vertically (because I use this for leading vertical slides), `h2` to be at the top, and all other content to be centred vertically. I got this to work by changing the display type of sections to be `flex` and making headings be `fixed` at the top.

In my `html`:
```
Reveal.initialize({
...
	display: 'flex',
 ```
and in the `css`:
```
.reveal h2 {
  position:fixed;
  top: 0px;
}
```

**Comment by dhinojosa** [comment]
I have this...although not quite perfect it does ok, I will work on it more later. The key for me is `!important` so you can override the `style` hardcoded in the `<section>`

```css
section.present {
    position: relative;
    top: 0 !important;
}

section.present > h2 {
    position: absolute;
    padding: 10px 20px 10px 20px;
    top: 30px;
    left: 0;
    z-index:500;
    text-align: left;
}

section > div.slide-content {
    position: absolute;
    margin: 5em 3em 3em 3em;
    text-align: center;
}
```
