### ISSUE TITLE
Is it possible to show slides on a certain day of the week?

### ISSUE THREAD

**Issue by anthonyjdella** [hakimel/reveal.js#2512]
Throwing this out there, but is it possible to have a slide appear at a certain day of the week?

Example, on every Friday, a specific slide is shown.

**Comment by ayhankesicioglu** [comment]
```
<?php if ( date("l") == "Friday" ) { ?>
<section id="Friday">
  <h5>Friday Slide</h5>
  Lorem ipsum...
</section>
<?php } ?>
```

**Comment by anthonyjdella** [comment]
> ```
> <?php if ( date("l") == "Friday" ) { ?>
> <section id="Friday">
>   <h5>Friday Slide</h5>
>   Lorem ipsum...
> </section>
> <?php } ?>
> ```

This is php, it doesn't work with this. How is it working for you?
