### ISSUE TITLE
Wrong arrow is disabled with RTL option

### ISSUE THREAD

**Issue by poja** [hakimel/reveal.js#2518]
When using the RTL option, i.e. left arrow should be the next slide and right arrow should be the previous slide -
The wrong arrows are ".enabled"/".disabled" (the CSS class). So when the right-arrow should be ".disabled" the left-arrow is and vice-versa.

**Comment by Martinomagnifico** [comment]
See #2578

**Comment by hakimel** [comment]
@Martinomagnifico's fix in #2579 has been merged
