### ISSUE TITLE
[Feature request] Expose theme variables in CSS custom properties

### ISSUE THREAD

**Issue by quilicicf** [hakimel/reveal.js#2519]
Hi, 

I've been using reveal and I am trying to create a plugin for it that injects HTML into the DOM.

I'd like to style this injected HTML using the current theme but since I have no access to the SASS code, I can't retrieve the variables from the theme. 

I think it would be nice to inject those variables in `:root` as CSS custom properties so that plugin creators can re-use them. 

I can submit a PR if that helps,

**Comment by quilicicf** [comment]
Proposition done in PR #2521

**Comment by hakimel** [comment]
#2521 has been merged, thanks!
