### ISSUE TITLE
Using the WebRTC video plugin within a section

### ISSUE THREAD

**Issue by pascalwhoop** [hakimel/reveal.js#252]
Hello! 
First off, thanks for this great tool! Calling myself a mobile HTML5 developer while giving Powerpoint presentations is not really the way to go. Now it really looks like I mean it.

I wanted to incorporate a video-stream coming from an attached camera into my presentation. Putting an iFrame with a youtube video inside of the presentation was no big deal but using the
<video> html5 tag with the src being set up via javascript did not work for some reason.

This is the JavaScript code added to the index.html at the end of the file:

``` javascript

    navigator.getUserMedia = navigator.getUserMedia || navigator.webkitGetUserMedia ||
            navigator.mozGetUserMedia || navigator.msGetUserMedia;
    window.URL = window.URL || window.webkitURL;

    navigator.getUserMedia({video: true}, function(localMediaStream) {
        var video = document.getElementById("webcamOutput");
        video.autoplay = true;
        video.src = window.URL.createObjectURL(localMediaStream);
    }, function(error) {
        console.log(error);
    });


```

Could you maybe check out if you have the same problem and let me know how it works?

Oh P.S. you must have your files hosted by a server. file:/// dont work with webRTC. you'll get a permission denied error

**Comment by Snesi** [comment]
Hi! Thanks!

My video kept freezing, but this is what did the job `video.autoplay = true;`
