### ISSUE TITLE
Button to help code copy/paste ?

### ISSUE THREAD

**Issue by dacr** [hakimel/reveal.js#2528]
Have a way to add a copy content buttons on all code block area such as :
![image](https://user-images.githubusercontent.com/381901/68766339-fbb5c280-061e-11ea-956d-9d3d500c5305.png)
And a way to activate this feature or not, through something like that in the reveal.json file:
```
{
  "controls": true,
  "show-copy-content-button":true
}
```

reveal-md is really a great tool, very useful, I use it for training purposes, and this feature would be very helpful as it is not always very easy to copy code content using a laptop trackpad for example, we've already seen many people (during trainings) reporting issues that were not really issues because they didn't copy all the content before trying to execute it...

**Comment by Martinomagnifico** [comment]
See this plugin: [CopyCode plugin](https://github.com/Martinomagnifico/reveal.js-copycode). Something like that?
