### ISSUE TITLE
node-sass v4.11.0 download failed

### ISSUE THREAD

**Issue by TB1234** [hakimel/reveal.js#2538]
On running a npm install I got a error, that node-sass v4.11.0 could not be downloaded. If I try it direct, I got also a 404.

    npm install
    
    > puppeteer@1.12.2 install /home/tobias/Programme/reveal.js/node_modules/puppeteer
    > node install.js
    
    Downloading Chromium r624492 - 107.6 Mb [====================] 100% 0.0s 
    Chromium downloaded to /home/tobias/Programme/reveal.js/node_modules/puppeteer/.local-chromium/linux-624492
    
    > node-sass@4.11.0 install /home/tobias/Programme/reveal.js/node_modules/node-sass
    > node scripts/install.js
    
    Downloading binary from https://github.com/sass/node-sass/releases/download/v4.11.0/linux-x64-79_binding.node
    Cannot download "https://github.com/sass/node-sass/releases/download/v4.11.0/linux-x64-79_binding.node": 
    
    HTTP error 404 Not Found
    
    Hint: If github.com is not accessible in your location
          try setting a proxy via HTTP_PROXY, e.g. 
    
          export HTTP_PROXY=http://example.com:1234
    
    or configure npm proxy via
    
          npm config set proxy http://example.com:8080
    node[92348]: ../src/signal_wrap.cc:159:void node::DecreaseSignalHandlerCount(int): Assertion (new_handler_count) >= (0)' failed.
     1: 0x56392c25a041 node::Abort() [node]
     2: 0x56392c25a0e1  [node]
     3: 0x56392c307183 node::DecreaseSignalHandlerCount(int) [node]
     4: 0x56392c3072af  [node]
     5: 0x56392c1ed927 node::Environment::CleanupHandles() [node]
     6: 0x56392c1edbff node::Environment::RunCleanup() [node]
     7: 0x56392c2a0a3b node::NodeMainInstance::Run() [node]
     8: 0x56392c2274de node::Start(int, char**) [node]
     9: 0x7f81f14ed153 __libc_start_main [/usr/lib/libc.so.6]
    10: 0x56392c1b474e _start [node]
    Abgebrochen (Speicherabzug geschrieben)    

Running on ArchLinux with node.js 13.2.

**Comment by TB1234** [comment]
Fix the problem by:

1. Remove the folder
2. Checkout the repo again from git
3. edit the package.json and change `node-sass` from `^4.11.0` to `4.12.0`
4. run a `npm install`
5. run a `npm audit fix`

After that, it should work. The problem is similiar to #2473

**Comment by gusennan** [comment]
I had to update it from `^4.11.0` to `4.13.0` for it to work for me.

**Comment by hakimel** [comment]
This has been fixed in master now by upgrading to node-sass 4.13.0
