### ISSUE TITLE
problem with npm-install

### ISSUE THREAD

**Issue by serifahmet** [hakimel/reveal.js#2554]
I'm trying to install the npm in the Terminal app of my mac mojave and I get the following error during the installation:

make: *** [Release/obj.target/binding/src/binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/macpro/reveal.js/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:305:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/bin/node" "/Users/macpro/reveal.js/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/macpro/reveal.js/node_modules/node-sass
gyp ERR! node -v v13.5.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.11.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.11.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/macpro/.npm/_logs/2019-12-20T08_38_43_057Z-debug.log

**Comment by deisi** [comment]
I have the same issue

**Comment by deisi** [comment]
https://github.com/hakimel/reveal.js/issues/2473 seems to help

**Comment by serifahmet** [comment]
I sorted this problem out with nvm version manager. For those having the same problem you can try it out...

**Comment by hakimel** [comment]
This issue should fixed in master now, see https://github.com/hakimel/reveal.js/issues/2473#issuecomment-573347475

Hasn't been pushed to npm yet though. Let me know if the issue still persists when trying to `npm install` the version on master.
