### ISSUE TITLE
Request: Theme screenshot gallery

### ISSUE THREAD

**Issue by hannob** [hakimel/reveal.js#2555]
I was surprised I didn't find this anywhere: I think it'd be nice to have a visual overview of all the default themes shipping with reveal, i.e. a page where there are screenshots for all of them.

Maybe this could live in the wiki?

**Comment by ladyg19** [comment]
Don't know what your talking about!?

**Comment by Martinomagnifico** [comment]
That's actually a good idea!

**Comment by hakimel** [comment]
This is a great idea. All themes are listed in the docs, I think it'd make sense to include screenshots there: https://revealjs.com/themes/

**Comment by hakimel** [comment]
All themes are now listed with thumbnails at https://revealjs.com/themes/

Note to self: the thumbs were generated by resizing the browser to 500x500 and using the following HTML:
```html
<section style="font-size: 2em;">
	<h2>Title Text</h2>
	<p>Body text.</p>
	<a href="#">Linked text.</a>
</section>
```
