### ISSUE TITLE
Upgrade highlight.js in the highlight plugin to the latest version

### ISSUE THREAD

**Issue by Mogztter** [hakimel/reveal.js#2562]
The highlight plugin relies on Highlight.js 9.11.0.

I think we should use the latest version available 9.17.1: https://github.com/highlightjs/highlight.js/blob/master/CHANGES.md#version-9171

**Comment by Mogztter** [comment]
Actually the `dev` branch is using version 9.15.10 but the latest release of reveal.js (3.8.0) still rely on 9.11.0.

I found several issues on this subject, maybe we should not bundle highlight.js and/or provide a way to replace it with a newer version?

**Comment by Martinomagnifico** [comment]
I would also like to see highlight.js options as options in the Reveal config. In my case I would like to change the tabReplace value.

Something like: 
```
    ...
    controls: false,
    highlight: {
        tabReplace: '  '
    },
    dependencies: [
        { src: 'plugin/highlight/highlight.js' },
        ...
```

**Comment by hakimel** [comment]
reveal.js 3.9 is out and includes highlight.js 9.18.0.

I agree it'd be great to make it easier to upgrade this separately. One of the appeals of reveal.js for many people is that it requires virtually no setup to get started—you can download the repo and edit the index.html file without needing to npm install or set up a web server. That said I'm cautious about making adding any extra steps to get something like code highlighting working. Loading from a CDN could be a good option.

**Comment by Mogztter** [comment]
> reveal.js 3.9 is out and includes highlight.js 9.18.0.

Awesome, thanks @hakimel :+1: 

> One of the appeals of reveal.js for many people is that it requires virtually no setup to get started—you can download the repo and edit the index.html file without needing to npm install or set up a web server

Indeed and I think we should keep it that way. Syntax highlighting should work out-of-the-box.

> That said I'm cautious about making adding any extra steps to get something like code highlighting working. Loading from a CDN could be a good option.

We can use [cdn.jsdelivr.net](https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.18.0/build/highlight.min.js) but this prebuilt version of highlight.js only contains the 34 most commonly used languages.
I can't find a prebuilt version of highlight.js that contains all the 175 languages. So it will be a "breaking change" even if it's pretty unlikely that you will need all the 175 languages in one presentation :stuck_out_tongue_winking_eye: 

Please note that it's possible to load additional languages from https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.18.0/build/languages/.
We could provide an option to configure a list of additional languages that we want to load:

```js
highlight: {
  languages: ['arduino', 'elm', 'x86asm'],
  tabReplace: '  '
}
```

**Comment by hakimel** [comment]
As of version 4.0 we no longer have a hard coded copy of highlight.js inside of the reveal.js repo. Instead highlight.js is installed as an npm dependency, which will make it much easier to upgrade going forward. We're currently using highlight.js 10.0.3.

I still think it'd be useful to let people configure a smaller subset of highlight.js languages to decrease the file size, or load highlight.js from another origin but this issue is ✅

**Comment by FSMaxB** [comment]
> I would also like to see more highlight.js options as options in the Reveal config. In my case I would like to change the tabReplace value. Right now, some options are passed, but not all.

I've found out a (hacky) way of settings `highlight.js` options directly:
```
const highlight_plugin = RevealHighlight();
highlight_plugin.hljs.configure({tabReplace: '    '});
```

And then pass `highlight_plugin` to the list of plugins instead of `RevealHightlight`.

**Comment by rparree** [comment]
I am using hugo and are loading reveal inside the html (using go module dependency). Is there a way to override the highlightjs version without using npm?
