### ISSUE TITLE
Security vulnerability for diff

### ISSUE THREAD

**Issue by SylvainSimplonGit** [hakimel/reveal.js#2595]
In Github, a vulnerability was reported on the diff dependencies.

> WS-2018-0590 high severity
> Vulnerable versions: < 3.5.0
> Patched version: 3.5.0
> A vulnerability was found in diff before v3.5.0, the affected versions of this package are vulnerable to Regular Expression Denial of Service (ReDoS) attacks.
> Vulnerability data by WhiteSource

it probably comes from "grunt-autoprefixer": "^3.0.4".
is it possible to migrate from grunt-autoprefixer to grunt-postcss ?
[How to migrate from grunt-autoprefixer?](https://github.com/nDmitry/grunt-postcss#how-to-migrate-from-grunt-autoprefixer)

**Comment by erelsgl** [comment]
I just got the same issue

**Comment by SylvainSimplonGit** [comment]
I migrate from grunt-autoprefixer to grunt-postcss following this documentation :
[How to migrate from grunt-autoprefixer?](https://github.com/nDmitry/grunt-postcss#how-to-migrate-from-grunt-autoprefixer)
I don't modify anything in gruntfile.js, just this two lines : 
```shell
$ npm remove --save-dev grunt-autoprefixer
$ npm install --save-dev grunt-postcss autoprefixer
```
It seems ok
@erelsgl, can you test on a copy of your project ?

**Comment by erelsgl** [comment]
@SylvainSimplonGit reveal.js is not my project - I am just a user... where exactly should I run these commands?

**Comment by SylvainSimplonGit** [comment]
@erelsgl, you will run these commands in a terminal in the Reveal.js directory, where the package.json is located

**Comment by erelsgl** [comment]
I did this and the warning is gone. Thanks a lot!

**Comment by hakimel** [comment]
We switched from grunt to gulp in reveal.js 4.0 so this should no longer be a problem.
