### ISSUE TITLE
Transition doesn't work when switching to slide that is more than 3 steps away

### ISSUE THREAD

**Issue by tomconvac** [hakimel/reveal.js#260]
When switching to a slide that is more than three steps away from current position (in any direction) there is no transition. Works for moving two or three slides forward/backwards.

Steps to reproduce the issue:

1) Go to http://lab.hakim.se/reveal-js/#/
2) Add `3` to URL manually so it looks like this: http://lab.hakim.se/reveal-js/#/3 and hit Enter
3) Transition works as expected
4) Change the URL to slide 9 so it looks like: http://lab.hakim.se/reveal-js/#/9 and hit Enter
5) Transition does not work.

Same thing happens when changing slides using `Reveal.slide()`.

**Comment by martinb2** [comment]
Is it possible to preloading slides to viewDistance based on links of actually viewed slide (not by the slides contained in the code behind) ? It would be useful in a situation, when presentation uses only links to switch between slides (no auto sliding). In large presentation is problem with increasing viewDistance above 100 - loss performance, slow viewing.

**Comment by jacobqbe** [comment]
googling "reveal.js transitions not working" and "reveal.js transitions don't work" didn't bring me here, but googling syntactically incorrect "reveal.js transition don't work" brought this up.

I suggest adding to the README that the veiwDistance also affects transition effects.
