### ISSUE TITLE
the right arrow disappeared when set `navigationMode: 'linear'`

### ISSUE THREAD

**Issue by wu-kan** [hakimel/reveal.js#2608]
when navigationMode is set to 'linear', and there are only `data-separator-vertical`s and no `data-separator`s behind, the right arrow is disappear, but it shouldn't be.

![image](https://user-images.githubusercontent.com/44857941/75419506-ecaa1480-5970-11ea-9ca5-15240464eada.png)

Here it is: <https://jekyll-theme-wuk.wu-kan.cn/#/7>

Moreover, I suggest to adding a new option `controlsLayout: 'bottom-left'`

**Comment by earboxer** [comment]
This is a duplicate of #2582

**Comment by wu-kan** [comment]
Okay, I'll keep an eye on that issue.
