### ISSUE TITLE
Feedback wanted: Multiple reveal.js instances on the same page?

### ISSUE THREAD

**Issue by hakimel** [hakimel/reveal.js#2632]
I'm working on some major refactoring for reveal.js 4.0, including:
- Modernizing the JS with newer language features (we'll transpile for IE11+ support).
- Breaking up the 6k+ lines of code reveal.js file into modules which are easier to maintain.

As part of this refactor I'm considering adding support for running multiple instances of reveal.js on the same page (without using iframes). The tradeoff is supporting multiple instances adds some complexity to the reveal.js source so I want to make sure this is actually a useful feature.

So my question is; have you ever wanted to run multiple reveal.js instances on one page? If you have, what was the use case?

**Comment by TonvanderGun** [comment]
Hi Hakimel,

I just discovered JS as an option for a clean whole screen website, that can be used in two educational settings: projected on a large screen during lectures and at home on the screen of the students computer. In both cases multiple instances of JS could be of great help. During lectures one instance gives the overview (e.g questions), other instances elaborate on the details (e.g. answers) and the illustrations. During home study the same structure can be used to allow the student to 'zoom in' whenever and how much he wants. To realize one should be able to define not only multiple instances on one screen (lecture, full HD screen at home) or page (mobile, responsive), but also some linking between the instances is required. This can be done by adding an option to every slide: if loaded then load slideshow X with slide i in window j. The windows should be hierarchical ordered and slides in one window can only change windows lower in the hierarchy. If there are multiple instances on one page, it should be possible anytime to make one of these instances full screen/page until lecturer or students choose to return to the underlying multiple instances. This structure would be wonderful, but I have no idea how much work this will be for you. Sorry, if I am being impolite by overasking! 

With friendly greetings,
Ton van der Gun

**Comment by hakimel** [comment]
Hey! Support for multiple presentation instances on the same page is now available in the 4.0 release.

Appreciate the feedback. It should be possible to dynamically load and inject multiple decks using your own scripts now that we support multiple instances. It's outside the scope of what I want to built into the framework though.

**Comment by TonvanderGun** [comment]
Hello! Sorry for the late reaction, busy as always here. Thx for adding the
support for multiple instances on the same page. I will give it a try later
this month.
