### ISSUE TITLE
help me pless if you now 

### ISSUE THREAD

**Issue by rohityoyo** [hakimel/reveal.js#2634]
Traceback (most recent call last):
  File "main.py", line 497, in <module>
    os.chdir(CurrentDir+"//adb")
OSError: [Errno 2] No such file or directory: '/data/data/com.termux/files/home/PhoneSploit/PhoneSploit//adb'

**Comment by obilodeau** [comment]
This error has nothing to do with this project. `PhoneSploit`, `adb`, what are you up to buddy?
