### ISSUE TITLE
has-dack-background not applied when background-color is a color name

### ISSUE THREAD

**Issue by obilodeau** [hakimel/reveal.js#2635]
Although valid HTML, using `background-color=black` on a slide will not trigger the `has-dark-background` to be applied by reveal.js. However, using `background-color=#000` will work.

The problem seems to be that `colorToRgb` doesn't support named colors. All strings sent in that function get analyzed as hex-encoded color values.

Work-around: refrain from using named colors and use their hex-encoded version instead.

**Comment by csachs** [comment]
The merge apparently failed to close this issue automatically, @obilodeau can you maybe retry if the problem persists with the current dev version? It should now be fixed.
