### ISSUE TITLE
Software installation: Heasoft.  What does "Generate the main Makefile" means?

### ISSUE THREAD

**Issue by dimaniad6** [hakimel/reveal.js#2637]
I am trying to install a program and I'm stuck on a step. The tutorial is the following:
[https://heasarc.gsfc.nasa.gov/lheasoft/install.html](url)
and on step 3, it says:

>  run the main configure script, which will probe your system  for libraries, header files, compilers, etc., and then generate  the main Makefile.

I did: 
`bash configure`

and now I have to generate the Makefile. There is a file that is named Makefile, but I have no idea how to "generate" it.

**Comment by Katy-kaboom101** [comment]
Do you know anything about a Apple web kit?
