### ISSUE TITLE
transition per slide?

### ISSUE THREAD

**Issue by outsmartin** [hakimel/reveal.js#264]
Hello,

I'm trying to change the transition of some slides to none. I found no way of doing that. The rest of the presentation should have a fancy transition.

Is there a simple way of doing that?

**Comment by Un-knownCoder** [comment]
you can write : 
`<section data-transition="#type"></section>`
... it works fine for me

**Comment by bnjmnt4n** [comment]
Yup, recent versions of Reveal can use `data-transition="none"` or even something like `data-transition="none-in concave-out"`.
