### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by praisedpk** [hakimel/reveal.js#2642]
Hi, we are seeing lots of 404 requests in our logs for the following files:

```
/reveal/3.8.0/js/css/reveal.css
/reveal/3.8.0/js/css/theme/black.css
/reveal/3.8.0/js/js/reveal.js
/reveal/3.8.0/js/lib/js/head.js
/reveal/3.8.0/js/lib/js/head.min.js
/reveal/3.8.0/lib/js/head.js
/reveal/3.8.0/lib/js/head.min.js
```
All these errors belong to the version 3.8.0 (as you can see in the paths). Can you please check if its possible to fix these missing files?

Thanks.

**Comment by praisedpk** [comment]
The above errors are from PageCDN's public CDN logs. Here is the Reveal.js repo for list of files: https://pagecdn.com/lib/reveal

**Comment by bnjmnt4n** [comment]
Seems like someone is probably referencing your CDN and providing the wrong URLs. Doesn’t seem to have anything directly related to Reveal.js.
