### ISSUE TITLE
Check for content editable?

### ISSUE THREAD

**Issue by asajeffrey** [hakimel/reveal.js#2650]
The code which checks to see if keyboard events should be discarded includes checking `document.activeElement.contentEditable !== 'inherit'` at https://github.com/hakimel/reveal.js/blob/00b0ace3863952ce95df4430d203686fd27bfc20/js/reveal.js#L5233

I'm confused about this check, as `contentEditable` can return `"true"`, `"false"` or `"inherit"` (https://html.spec.whatwg.org/multipage/interaction.html#attr-contenteditable) so input is discarded when `contentEditable` is `"false"`.

Perhaps the test should be `document.activeElement.contentEditable === 'true'` or `document.activeElement.isContentEditable`?

This came up in https://github.com/servo/servo/issues/12776.

**Comment by hakimel** [comment]
Thanks for reporting. Didn't know `isContentEditable` existed—I've switched to that in f138f507a04da117f92ee6fc85a9e88b442b432f

The fix will be available when reveal.js 4.0 is released.

**Comment by asajeffrey** [comment]
Thanks!
