### ISSUE TITLE
slide loader

### ISSUE THREAD

**Issue by clintcfavor** [hakimel/reveal.js#2654]
hello, I'm currently adding slides dynamically. is there a way to add a loader while the slides are being generated? thanks! :)

**Comment by motyar** [comment]
You need to insert the slides into HTML and call `Reveal.sync()` to update.

**Comment by Tinup-saku** [comment]
> hello, I'm currently adding slides dynamically. is there a way to add a loader while the slides are being generated? thanks! :)


Please type your reply above this line

**Comment by Tinup-saku** [comment]
> hello, I'm currently adding slides dynamically. is there a way to add a loader while the slides are being generated? thanks! :)

Hi
