### ISSUE TITLE
No url preview for Reveal.js website

### ISSUE THREAD

**Issue by adriens** [hakimel/reveal.js#2669]
Hi,

It could be interesting to add a prveview on reveal.js new website so it would look nicer while being quoted:

![image](https://user-images.githubusercontent.com/5235127/82539087-8a8c3480-9b98-11ea-9fd4-cf5ac3b0f7fa.png)

**Comment by hakimel** [comment]
Which website are you sharing on? We provide social preview images for Twitter and open graph. If there are other meta tags we should support, or if something is broken we’d love to fix it.

Btw, the repo for the documentation is https://github.com/reveal/revealjs.com

**Comment by adriens** [comment]
Hi @hakimel , it's on linkedIn:

![image](https://user-images.githubusercontent.com/5235127/82641040-6a6f7a80-9c57-11ea-9f0c-696c4aac121d.png)


Thz github url is great (https://www.linkedin.com/posts/adrien-sales_hakimelrevealjs-activity-6669151387307405312-K-_h) , but not the website itself

**Comment by hakimel** [comment]
Thanks! The open graph tags were malformed but have been fixed now. Confirmed that it's working via Linkedins "Post Inspector" tool.

**Comment by adriens** [comment]
All good, yes 👍 

![image](https://user-images.githubusercontent.com/5235127/82841090-822d5400-9f20-11ea-8a03-b8212221f22b.png)

Thank you for maintaining this great tool ❤️
