### ISSUE TITLE
data-state in markdown file

### ISSUE THREAD

**Issue by pramodbutte** [hakimel/reveal.js#2672]
Hi I have a quick question. I know that reveal allows data-state on the sections like,

```javascript
<section data-state="this slide"></section>
```

which then allows you to use
```javascript
Reveal.on('this slide', () =>{
//do some work
}
```

I was wondering if it is possible to do the same from a markdown slide to provide data state to each section
```markdown
## Slide 1


## Slide 2
<section data-state="Slide 2">
<div> some text </div>
</section>
```

currently if I try this I get 
```html
<section data-markdown="" data-markdown-parsed="true" style="top: 0px; display: block;" class="stack present" data-previous-indexv="1">
<section data-state="Slide 2" class="future" aria-hidden="true" style="top: 123px; display: block;"> 
<div> some text </div>
</section>
</section>
```
as it is in class futures it does not trigger ```Reveal.on``` event

Any Help is appreciated,
thanks

**Comment by hakimel** [comment]
You should be able to so this using our custom syntax for slide attributes. More info: https://revealjs.com/markdown/#slide-attributes

**Comment by pramodbutte** [comment]
Aha! thanks for pointing me to the right direction!
