### ISSUE TITLE
Broken plugin warnings

### ISSUE THREAD

**Issue by PatrickMassot** [hakimel/reveal.js#2680]
The page https://github.com/hakimel/reveal.js/wiki/Plugins,-Tools-and-Hardware happily lists plugins that are totally broken since v 4.0.0, see https://github.com/rajgoel/reveal.js-plugins/issues/80.

**Comment by hakimel** [comment]
Thanks for the heads up. The API changes in 4.0 should only break a small subset of plugins. I tested the ones in @rajgoel's repo and almost all of them, except chalkboard, still work. Will follow up in that repo with more details.
