### ISSUE TITLE
How to customise the HTML to add a button?

### ISSUE THREAD

**Issue by finnito** [hakimel/reveal.js#2681]
Kia ora everyone!

I have a website that contains many Reveal.js slides created by Pandoc (https://science.lesueur.nz/) from a Markdown source.

I am looking for a way to customise the HTML output to add a "back" button, so that the user can easily exit my slides and navigate back to the topic page.

For example, the user would be on this page https://science.lesueur.nz/9scie/energy-for-life/slides/digestion-and-disease.html and I want to display a button that could navigate them to this page https://science.lesueur.nz/9scie/energy-for-life/.

Could anyone help me with this? I am very happy writing custom HTML and customising my Pandoc command, so I suspect I just need to be pointed in the right direction!

Thank you,
Finn

**Comment by finnito** [comment]
Decided to write a little JS plugin to do this.

**Comment by perikorese** [comment]
@finnito 

> Decided to write a little JS plugin to do this.

Have you published the little JS plugin here on Github?

**Comment by finnito** [comment]
It's so small and short but here you go @perikorese:

`plugin/back/back.js`
```
/**
 * Adds a simple back button to take the user up two levels.
 *
 * @author Finn LeSueur (https://finn.lesueur.nz)
 **/
var GoBack = window.GoBack || (function(){
	return {
		init: function() {
			var button = "<a class='back-button' title='Back to Unit' href='../'>Back to Unit</a>";
			var reveal = document.querySelector(".reveal");
			reveal.innerHTML = button + reveal.innerHTML;
		}
	}
})();

Reveal.registerPlugin( 'back', GoBack );
```

And then in `js/reveal.js`
```
asyncDependencies = [
    { src: '/reveal.js/plugin/back/back.js', async: true },
],
```
