### ISSUE TITLE
Allow to move the slide number container to arbitrary locations

### ISSUE THREAD

**Issue by SirkoS** [hakimel/reveal.js#2683]
*Corresponding pull request is attached [here](https://github.com/hakimel/reveal.js/pull/2682)*

In my slide deck I want to have a custom header for all slides that should also include the slide number in that header. Currently, the slide number is always added and updated in a separate container and there is no configuration parameter to move it around (besides using CSS).

I would like to have a configuration parameter or distinct HTML element to serve as the target for automatically adding the slide number wherever I need it.

**Comment by Martinomagnifico** [comment]
See this plugin: [RelativeNumber](https://github.com/Martinomagnifico/reveal.js-relativenumber)

**Comment by SirkoS** [comment]
@Martinomagnifico great. with a few CSS tweaks this also solves my problems.

I'll close here and remove the pull request.
