### ISSUE TITLE
Mathjax Unrecognized plugin format

### ISSUE THREAD

**Issue by mmaridev** [hakimel/reveal.js#2686]
Working on master, when including the math plugin, getting this error in the console

**Comment by hakimel** [comment]
Any chance you're trying to include a copy of the Math plugin from a prior version of reveal.js? The plugin syntax changed in the 4.0.

I tried a fresh copy of master and the plugin is working on my end. If you clone the latest master and open /examples/math.html do the examples there work?

**Comment by mmaridev** [comment]
Just tried again downloading 4.0.2 release and it seems to be working.
Sorry for raising this issue.
