### ISSUE TITLE
Rendering Markdown Dynamically from Script tag doesnt work

### ISSUE THREAD

**Issue by achhranitesh** [hakimel/reveal.js#2700]
I am getting a markdown, with proper syntax in API call & i try to dynamically attach <script type="text/template"></script>. But if i paste the same markdown, directly it works

Following is a snippet any issue or anything missing or feature not present.
Javascript
```
var script = document.createElement("script");
script.setAttribute("type","text/template");
var mdScript = document.createTextNode(text);
script.textContent = text;
document.getElementById("slide").appendChild(script);
console.log(document.getElementById("slide")); // The content is getting added, but not rendered
```
Html
<div class="reveal">

			<div class="slides">
                
                <section data-markdown data-separator="^\n--h-slide--\n" id="slide" data-template>
                    
                    <script type="text/template">
                        
                    </script>
                </section>
</div>
</div>

File Reference: https://github.com/hakimel/reveal.js/blob/master/examples/markdown.html
Done some modification in this file

**Comment by motyar** [comment]
For now, you need to use this code:-

```
// Update the markdown text
Reveal.getPlugin('markdown').processSlides(document) ;
Reveal.getPlugin('markdown').convertSlides() ;
Reveal.sync();
```
Or

`Reveal.toggleOverview(); Reveal.toggleOverview(); `

**Comment by achhranitesh** [comment]
Sure Let me try
