### ISSUE TITLE
Syntetic speech

### ISSUE THREAD

**Issue by jermon** [hakimel/reveal.js#2705]
Please add the the ability to generate synthetic speech(TTS) from slide notes and have it played during page loading to construct almost a automatic presentation.

**Comment by r-menezes** [comment]
@jermon, did you look into ![audio slideshow](https://github.com/rajgoel/reveal.js-plugins/tree/master/audio-slideshow) plugin ?
It might have the feature you need.

**Comment by jermon** [comment]
Yes! thats it.
