### ISSUE TITLE
Auto-Animate with transition in between

### ISSUE THREAD

**Issue by cifkao** [hakimel/reveal.js#2711]
The design of the auto-animate feature doesn't seem to allow for the following situation: Auto-animate from slide 1 to slide 2, then do a normal transition from 2 to 3, then auto-animate from 3 to 4. This seems like a perfectly reasonable thing to do, yet it doesn't seem to be possible (all pairs of consecutive slides with `data-auto-animate` get auto-animated).

Perhaps slides could have a `data-id` attribute, and the animation would kick in only if the IDs of the two slides are equal (or missing), otherwise there would be a normal transition. Another idea would be to start treating auto-animation as a kind of transition, so that we could say e.g. `data-transition="auto-animate-in slide-out"` (but `data-auto-animate` would still work as a shorthand for simple cases).

**Comment by Salvation1** [comment]
I am experiencing the same issue and currently have not been able to find a workaround other than duplicating a slide in between, which is very unsatisfactory.

**Comment by coffeenotfound** [comment]
I think the most straight forward solution is making `data-auto-animate` take an optional string so only adjacend slides with the same value (or lack thereof) get auto-animated

Like this (1-2, 3-4, 5-6):
```html
<section data-auto-animate="a">1</section>
<section data-auto-animate="a">2</section>
<section data-auto-animate="b">3</section>
<section data-auto-animate="b">4</section>
<section data-auto-animate>5</section>
<section data-auto-animate>6</section>
```

**Comment by coffeenotfound** [comment]
Turns out the `data-auto-animate` attribute is constantly overwritten with state values.
IMO the next best thing would be `data-auto-animate-id`.

I'm not in favor of `data-id` because that implies all the slide elements using the same id are the same element.
For auto-animate'd elements `data-id` does make sense because they essentially *are* the same elements across the slides but for the slides themselves it's a different story

**Comment by darcamo** [comment]
Wouldn't be possible to have a `data-auto-animate-start` that works just like `data-auto-animate`, but forces the start of a new slide? It seems easier then passing an id argument to `data-auto-animate`, IMHO.

Then we could use

```html
<section data-auto-animate>1</section>
<section data-auto-animate>2</section>
<section data-auto-animate-start>3</section>
<section data-auto-animate>4</section>
<section data-auto-animate-start>5</section>
<section data-auto-animate>6</section>
```

**Comment by coffeenotfound** [comment]
It would be easier to have an additional attribute since, `data-auto-animate` is required by the code anyways
So maybe something like this:

```html
<section data-auto-animate>1</section>
<section data-auto-animate>2</section>
<section data-auto-animate data-auto-animate-restart>3</section>
<section data-auto-animate>4</section>
<section data-auto-animate data-auto-animate-restart>5</section>
<section data-auto-animate>6</section>
```

**Comment by vcampitelli** [comment]
Yeah, that would be great!

I'm planning to open a PR to add that behavior in a few days, but until then, here's what I'm using:

```js
Reveal.on('ready', event => {
    document.querySelectorAll('[data-auto-animate][data-auto-animate-restart]').forEach(node => {
        const fakeSection = document.createElement('section');
        fakeSection.dataset.autoAnimateSkip = "";
        node.parentNode.insertBefore(fakeSection, node);
    });
});
Reveal.on('slidechanged', event => {
    if (event.currentSlide.dataset.hasOwnProperty('autoAnimateSkip')) {
        if (event.previousSlide.classList.contains('past')) {
            Reveal.next();
        } else {
            Reveal.prev();
        }
    }
});
```

It's basically doing what @Salvation1 said: creating a slide in between, then I automatically skip it when navigating forward/backwards.

So, you just need to add a `data-auto-animate-restart` attribute to your new slide, like @coffeenotfound just suggested.

**Comment by coffeenotfound** [comment]
@vcampitelli I have the code already integrated (only used it locally so far though), so I can open a PR if you want

**Comment by coffeenotfound** [comment]
I have opened #2896 that implements both restart and data-auto-animate-id

**Comment by mavyfaby** [comment]
> Yeah, that would be great!
> 
> I'm planning to open a PR to add that behavior in a few days, but until then, here's what I'm using:
> 
> ```js
> Reveal.on('ready', event => {
>     document.querySelectorAll('[data-auto-animate][data-auto-animate-restart]').forEach(node => {
>         const fakeSection = document.createElement('section');
>         fakeSection.dataset.autoAnimateSkip = "";
>         node.parentNode.insertBefore(fakeSection, node);
>     });
> });
> Reveal.on('slidechanged', event => {
>     if (event.currentSlide.dataset.hasOwnProperty('autoAnimateSkip')) {
>         if (event.previousSlide.classList.contains('past')) {
>             Reveal.next();
>         } else {
>             Reveal.prev();
>         }
>     }
> });
> ```
> 
> It's basically doing what @Salvation1 said: creating a slide in between, then I automatically skip it when navigating forward/backwards.
> 
> So, you just need to add a `data-auto-animate-restart` attribute to your new slide, like @coffeenotfound just suggested.

This doesn't work on my end.

**Comment by hakimel** [comment]
The PR from @coffeenotfound has been merged
