### ISSUE TITLE
Do not exclude css folder from npm release

### ISSUE THREAD

**Issue by theone1984** [hakimel/reveal.js#2712]
Hi Hakim,

We are using Reveal to create our own theme. Unfortunately, there is no way to get theme.scss through npm since it is in the files ignored by .npmignore. Is there any chance to get this file by using npm (we do not want to use other mechanisms since this is part of an automated build through Jenkins). Could you include it into the delivered resources again?

Best wishes,
  Thomas

**Comment by hakimel** [comment]
Thanks for the feedback. I've added those files back in so they'll be included when we release 4.1.

**Comment by Defcon0** [comment]
Are there plans for when 4.1 is released? We currently need the scss being included in the npm package badly :-(
