### ISSUE TITLE
Exclude slide from total slide count

### ISSUE THREAD

**Issue by clintcfavor** [hakimel/reveal.js#2714]
Hello, is there a way to exclude slide(s) from the totalSlide()?

**Comment by VlavoJ** [comment]
Hi, 
I could work on it. 
I suggest adding a new attribute for the section to be excluded from the total count and turn off showing slide number.  It can be useful for the first, last slide, or some kind of "divider slide".

**Comment by VlavoJ** [comment]
Hi, 
`<section data-visibility="uncounted">` should do it :)
