### ISSUE TITLE
Dynamically slide remove

### ISSUE THREAD

**Issue by clintcfavor** [hakimel/reveal.js#2716]
Hello, I'm having a problem when I dynamically added a slide and remove it after navigating to the slide next to it. 
I have this presentation structure example:
```
<section>
 <div>Slide 1</div>
</section>
<section id="insertedSection">
 <div>Slide 2</div>
</section>
<section>
 <div>Slide 3</div>
</section>
<section>
 <div>Slide 4</div>
</section>
<section>
 <div>Slide 5</div>
</section>
```
When navigating to the next slide after the `insertedSection` the section with id `insertedSection` has been removed, but when navigating to the previous slide, the navigation is somewhat broken and needs you to press the left arrow twice to reach Slide 1. It also skips Slide 4 and goes directly to Slide 5 when you navigate next. Any ideas why this is happening? I've also tried calling `Reveal.slide()` but the problem still persist.

**Comment by hakimel** [comment]
You need to call `Reveal.sync()` after adding or removing a slide.
