### ISSUE TITLE
CSS collisions

### ISSUE THREAD

**Issue by SylvainCorlay** [hakimel/reveal.js#2723]
Hello, I am a Jupyter maintainer, currently working on nbconvert (a tool to transform and export notebooks into other formats). Nbconvert comes with a "reveal" exporter that allows to transform jupyter notebooks into a slideshow.

As we are updating nbconvert to use the JupyterLab CSS, I noticed that a lot of the reveal CSS was applying to all the content, often overriding CSS rules of Jupyter. (We were working around some of that in earlier versions of nbconvert)

Have you folks considered splitting the reveal CSS into a minimal one (e.g. reveal-base.css, with only the necessary bits for reveal to work), so that we could avoid importing all of that CSS?

**Comment by interglobalmedia** [comment]
Hi, in previous versions of reveal.js, I was able to add my own custom.css file, adding some of my own custom styles to my reveal presentation. Now, when I add my custom.css styles, they are totally ignored, and only the reveal.js styles are recognized. That really sucks. How can I get my custom.css styles to be recognized again? Thanks. That is a major feature downgrade.

**Comment by interglobalmedia** [comment]
I guess I will just have to downgrade to 3.9.2 until 4.0.2 works properly. Thanks!

**Comment by interglobalmedia** [comment]
Hi, I just figured out that your set up now is more like how Jekyll works. All I had to do was import my custom styles into my theme file I am using and at it to the bottom of the file. Now my custom styles are being recognized. I just will have to live this for now. Thanks!
