### ISSUE TITLE
link to slide goes to 1st fragment

### ISSUE THREAD

**Issue by dvirtz** [hakimel/reveal.js#2726]
When I click an internal link to a slide that has fragments it navigates to the first fragment in the slide. 
It seems to be caused by the `if` block at https://github.com/hakimel/reveal.js/blob/15815efe05ca69c35ce66cfdbf93316e1db66ecb/js/controllers/fragments.js#L193 which causes `index` to be set to the first visible fragment.

**Comment by WiesnSims** [comment]
Try to use `class="fragment current-visible"` for fragment.

**Comment by dvirtz** [comment]
I can't reproduce it now for some reason. Closing.
