### ISSUE TITLE
The new build is screwed up based on dist but what if we update dist? Then build is broken

### ISSUE THREAD

**Issue by interglobalmedia** [hakimel/reveal.js#2729]
Hi,

The new build script (and markup) mostly depends on things residing in the dist folder. However, some of us us gh-pages or something similar in which we remove the old dist folder and recreate a new one whenever we have made changes to our slide deck. This then, breaks the build. There are so many other issues now as a result of the changes to reveal.js 4.0.2 that I don't even find it workable for me at this time. And I was one of the biggest proponents of reveal.js. Now, for it to work with a new slide deck, I will have to copy an existing reveal.js slide deck and change the index.html. Looking forward to when things start working properly with 4.0.2. Thanks.

**Comment by hakimel** [comment]
Hey. The `gulp serve` task only recompiles the assets it needs to based on what source files that changed. If you remove the entire /dist folder and want to recreate all of the built assets, you can run `gulp`. That will rebuild the /dist dir from scratch.

I'm not sure why the /dist folder would need to be removed but hopefully that helps.

**Comment by serpent7776** [comment]
`reset.css` is not regenerated - it only lives in `dist`. Similarly `dist/themes/fonts`.
When I removed `dist` none of these files were regenerated after invoking `gulp`.
