### ISSUE TITLE
Refresh is blanking page

### ISSUE THREAD

**Issue by reagle** [hakimel/reveal.js#2730]
Help! I just upgraded to 4.0.2 and when I refresh a [page](https://reagle.org/joseph/2020/oc/talks/050-wp-citations.html#/ref-in-prose) the screen is blanked.
I do this often as I edit slides in markdown, regenerate with pandoc, and then refresh the browser.

If I go back a slide and forward again, then the content is there again. Also, if I open a new tab and go directly to [a slide](https://reagle.org/joseph/2020/oc/talks/050-wp-citations.html#/ref-in-prose) there's a blank screen. 

This is the case with Chrome (84.0.4147.89) and Firefox (78.0.2).

**Comment by reagle** [comment]
This problem goes away if I remove the [denehyg/reveal.js-menumenu](https://github.com/denehyg/reveal.js-menu) plugin, i.e., delete the following:

```
<script src="../_reveal4.js/plugin/menu/menu.js"></script>
<script>
  Reveal.initialize({
    plugins: [ RevealMenu ]
  });
</script>
```

However, I used to use the menu plugin with reveal3.js fine.

**Comment by hakimel** [comment]
reveal.js is being initialized twice on that page and I'd assume that's what's causing your issue. You'll need to remove the second `Reveal.initialize` and include the `RevealMenu` plugin in the first initialize call instead.
