### ISSUE TITLE
"<x>" inside code snippet is taken as XML and "</x>" being automatically added

### ISSUE THREAD

**Issue by zeenix** [hakimel/reveal.js#2732]
Please see the issue in action in the attached screenshot. The code is of Rust and I explicitly mark it as such. The `</byteorder::LE>` in the last light is automatically added for me but it shouldn't.

![Screenshot from 2020-07-17 19-01-45](https://user-images.githubusercontent.com/2027/87812990-59ab4180-c861-11ea-9cd5-5be8069a7ccb.png)

**Comment by hakimel** [comment]
Thanks for reporting, we're tracking this issue in #2744, there's some more info about what's happening in my [latest comment](https://github.com/hakimel/reveal.js/issues/2744#issuecomment-689428912)
