### ISSUE TITLE
Issues embedding nglview in reveal.js presentation

### ISSUE THREAD

**Issue by jamesETsmith** [hakimel/reveal.js#2736]
## Goal

I'm trying to embed 3D molecules in my presentation using `nglview` using their documentation [here](http://nglviewer.org/ngl/api/manual/usage/embedding.html).
 
I have tried other solutions like `molview.org` where you embed via `iframe` and had no issues at all:

```html
<iframe style="width: 500px; height: 300px;" frameborder="0" src="https://embed.molview.org/v1/?mode=balls&bg=white"></iframe>
```
However, I'd _really_ like to use `nglview` since it's more flexible. Any advice would be greatly appreciated!

## What I've tried already

1. Trying to "directly" embed inside a slide:

```html
<section>
  <script src="path/to/ngl.js"></script>
  <script>
    document.addEventListener("DOMContentLoaded", function () {
      var stage = new NGL.Stage("viewport");
      stage.loadFile("rcsb://1crn", {defaultRepresentation: true});
    });
  </script>
  <div id="viewport" style="width:400px; height:300px;"></div>
</section>
```

Here I get no error messages and nothing on the slide.

2. I've tried creating a separate page for just the molecule and then embed that using `iframe`. When I do that, I can only see and interact with the molecule inconsistently.

For example I created `fe_pdi.html` in my main presentation directory:

```html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
</head>

<body>
  <section>
    <script src="js/ngl.js"></script>

    <script>
      document.addEventListener("DOMContentLoaded", function () {
        var stage = new NGL.Stage("fe_pdi", { backgroundColor: "white" });
        stage.loadFile("assets/mol_geometries/fe_pdi.mol2", { defaultRepresentation: true });
      });
    </script>
    <div id="fe_pdi" style="width:400px; height:300px; background-color: white;"></div>
  </section>
</body>

</html>
```

Then I added the following in my presentation:

```html
<section>
<iframe src="http://0.0.0.0:8000/fe_pdi.html" style="width: 500px; height: 500px;"></iframe> 
</section>
```

**Comment by Martinomagnifico** [comment]
Not a Reveal.js problem. Seems to work: https://codepen.io/martino/live/ZEQNMBX Source: https://codepen.io/martino/pen/ZEQNMBX 
You need to load the scripts at the end of the body (not inside a section, and after the loading of Reveal), and use the Reveal 'ready' event to load your molecules. 

Can you close the issue?

**Comment by jamesETsmith** [comment]
@Martinomagnifico thanks so much for the help, that worked seamlessly!
