### ISSUE TITLE
Syntax highlighting adds unwanted closing html tags and adds empty values in C++ code with templates

### ISSUE THREAD

**Issue by ziobron** [hakimel/reveal.js#2741]
My code in C++ is generated with some HTML tags added.

```cpp
template <typename TypeA, typename TypeB>
TypeA add(TypeA first, TypeB second) {
    return first + second;
}
```

turns into this:

<img width="1060" alt="Zrzut ekranu 2020-07-31 o 16 36 20" src="https://user-images.githubusercontent.com/4595135/89045598-11ede500-d34c-11ea-8e37-abbcab7a2817.png">

As I understand it is parsed as HTML file. The code is in an external MD file and is put inside triple backticks. Changing < into \&lt; fixes this issue, but I need to have the code in a syntactically correct form (it is compiled by other tools). 

This issue exist in 4.0.x version, but everything works fine in 3.9.x
Does anyone know if there is a fix to this issue?

**Comment by hakimel** [comment]
Thanks for reporting, we're tracking this issue in #2744
