### ISSUE TITLE
Markdown code auto-animation doesn't work

### ISSUE THREAD

**Issue by Bielik20** [hakimel/reveal.js#2749]
There is no, or I couldn't find a way to animate code blocks using markdown.

The reason for that is we cannot assign `data-id` attribute. Markdown plugin return empty `pre` tag:
https://github.com/hakimel/reveal.js/blob/83151f5e675f86449eab7d1df4c8ed0c12c20199/plugin/markdown/plugin.js#L430

I was able to find dirty workaround by adding:
```ts
let PreDataId = () => ({
  id: 'code-animation',
  init: () => {
    document.querySelectorAll('pre').forEach((pre) => {
      pre.setAttribute('data-id', 'code-animation');
    });
  },
});

let deck = new Reveal({
  plugins: [Markdown, PreDataId, Highlight, Notes],
});
deck.initialize();
```

So it adds `data-id` to every `pre` element. We all can see that this is not ideal.

It would be great if we could somehow add classes and attributes to both `pre` and `code` from the markdown level.

**Comment by dvirtz** [comment]
you can use [element attributes](https://revealjs.com/markdown/#element-attributes) syntax for that
```
<!-- .element: data-id="code-animation" -->
```

**Comment by Bielik20** [comment]
@dvirtz Could you provide a full example? I remember trying to get that to work with no success.

**Comment by dvirtz** [comment]
markdown: https://github.com/dvirtz/modern-cpp/blame/master/slides/03_initialization/initialization.md#L80
slides: https://dvirtz.github.io/modern-cpp/#/3/3

**Comment by Bielik20** [comment]
@dvirtz Thank you this seems to work 🙇

**Comment by bryanleejohnson** [comment]
thanks for fixing the problem we are part of a great team. keep up the good
work.
Hide quoted text
