### ISSUE TITLE
Register new language definition in highlight plugin

### ISSUE THREAD

**Issue by rajgoel** [hakimel/reveal.js#2761]
I want to add a language for code highlighting that is not available in the highlight plugin. Without the plugin I manage to make it work as follows:

```html
<!doctype html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">

	<link rel="stylesheet" href="../reveal.js/dist/reveal.css">
	<link rel="stylesheet" href="../reveal.js/dist/theme/black.css" id="theme">
	<link rel="stylesheet" href="../reveal.js/plugin/highlight/zenburn.css">

	<script src="reveal.js/dist/reveal.js"></script>
<!--	<script src="reveal.js/plugin/highlight/highlight.js"></script> -->
<script src="https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.12.0/build/highlight.min.js"></script>

</head>

<body>

<div class="reveal">
<div class="slides">
<section>
<pre><code class="ampl">
var h;
/*
A comment
*/
var h;

# Part 1:  Variable Declaration (var, set, param, etc)
maximize var BluePaint;
var BlackPaint;
# Part 2:  Objective Function

maximize Revenue:  10*BluePaint + 15*BlackPaint;
# Part 3:  Constraints 
subject to Time:   (1/40)*BluePaint  +  (1/30)*BlackPaint<= 40;
subject to BlueLimit:  0<= BluePaint<= 1000;
subject to BlackLimit:  0<= BlackPaint<= 860;

</code></pre> 
</section>
</div>
</div>


<script>
Reveal.initialize({
//	plugins: [ RevealHighlight ],
});

Reveal.addEventListener('ready', (event) => {
	hljs.registerLanguage("ampl",function(e){var r="([a-zA-Z]|\\.[a-zA-Z.])[a-zA-Z0-9._]*";return {c: [ e.HCM,e.CBCM,{b:r,l:r,k:{keyword:"maximize subject to var ",literal:""},r:90},{cN:"number",b:"\\d+(?:\\.\\d*)?(?:[eE][+\\-]?\\d*)?i?\\b",r:0}]} });

	// console.log(hljs.listLanguages());
	document.querySelectorAll('pre code').forEach((block) => { hljs.highlightBlock(block); });
});
</script>

</body>
</html>

```

Ideally I could use the built-in highlight plugin, but I don't know how. I can register the language via `Reveal.getPlugin('highlight').hljs.registerLanguage(...)`, but the code block is not processed (probably because the language is added too late). Can I add a new language before the plugin processes the code blocks? Or does the plugin need to be extended to achieve this. May it would be possible to add a configuration option for the highlight plugin allowing to add new languages? E.g. like this: 

```javascript
Reveal.initialize({
	highlight: { languages: [ { name: "ampl", definition": 'function(e){var r="([a-zA-Z]|\\.[a-zA-Z.])[a-zA-Z0-9._]*";return {c: [ e.HCM,e.CBCM,{b:r,l:r,k:{keyword:"maximize subject to var ",literal:""},r:90},{cN:"number",b:"\\d+(?:\\.\\d*)?(?:[eE][+\\-]?\\d*)?i?\\b",r:0}]} }' } ] },
	plugins: [ RevealHighlight ],
});
```

I could try to create a PR, but I do not understand the toolchain. There is the `plugin.js` file, the `highlight.js` file appears to be a minified  version with some name changes, and then there is also the `highlight.esm.js` file. So far I haven't figured out where to do changes and how to create the minified version. As far as I understand the requested feature would only need the following code in `plugin.js`:

```javascript
if ( config.languages ) {
  for ( var i = 0; i < config.languages.length; i++ ) {
    hljs.registerLanguage( config.languages[i].name, config.languages[i].definition );
  }
}
```
after the line 

```javascript
var config = reveal.getConfig().highlight || {};
```

Any help would be very appreciated :-)

**Comment by larskinn** [comment]
Diving into a similar problem, I think I found a workaround to this issue. Removing the custom highlight import from the example and using the standard `<script src="reveal.js/plugin/highlight/highlight.js"></script>`, this works:

```js
Reveal.initialize({
    highlight: { highlightOnLoad: false }, // this setting is not mentioned in the documentation
    plugins: [ RevealHighlight ],
}).then(() => {
    const hljs = RevealHighlight().hljs;
    // Here you can call functions on hljs, e.g. registerLanguage and configure
    hljs.registerLanguage("ampl",function(e){var r="([a-zA-Z]|\\.[a-zA-Z.])[a-zA-Z0-9._]*";return {c: [ e.HCM,e.CBCM,{b:r,l:r,k:{keyword:"maximize subject to var ",literal:""},r:90},{cN:"number",b:"\\d+(?:\\.\\d*)?(?:[eE][+\\-]?\\d*)?i?\\b",r:0}]} });
    // Run the plugin's highlighting code that was skipped on load
    Array.from(Reveal.getRevealElement().querySelectorAll('pre code')).forEach((block) => {
        RevealHighlight().highlightBlock(block);
    });
});
```

I haven't tried adding a language definition myself. My use case was to run `hljs.configure( ... )` before highlighting, and the above approach works for that at least.

**Comment by rajgoel** [comment]
I can highlight custom languages if  the code is in the HTML-file with the standard using
```js
const hljs = RevealHighlight().hljs;
```
However, when using code in external markdown (which is my main use case) it doesn't work - unfortunately.

**Comment by rajgoel** [comment]
After fiddling around a bit, I figured out that the workaround by @larskinn actually works. The issue was that the the language definition must not use the abbreviated keywords (as above). The below works:

```js
hljs.registerLanguage("ampl",function(hljs){
	return 	{
		contains: [ 
			hljs.HASH_COMMENT_MODE,
			hljs.C_BLOCK_COMMENT_MODE,
			{
				className: "number",
				begin: String.raw`\b(\d*\.?\d+)\b`,
				relevance:0
			}
		],
		keywords: { keyword: 'maximize minimize subject to set union inter diff symdiff cross sum in var param binary integer'} 
	};
});
```

**Comment by hakimel** [comment]
What @larskinn suggested is a good way to handle this. That said it does require some extra code so I think adding a callback makes sense too so I've merged @rajgoel's PR.

From now on you can use the following:
```js
Reveal.initialize({
  highlight: {
    beforeHighlight: () => hljs. registerLanguage(/*...*/)
  },
  plugins: [ RevealHighlight ]
})
```
