### ISSUE TITLE
Image background inside Markdown

### ISSUE THREAD

**Issue by ventolinmx** [hakimel/reveal.js#2764]
Hi

Using external markdown and I would like to define a full screen image background per slide.
Tried things like this:
`<!-- .slide: data-background-image="image.png" -->`
But its not working. I can change the background color of the slide but not put the image as background.
How can i do this?

Using Reveal full setup as local web server.

**Comment by dvirtz** [comment]
```
<!-- .slide: data-background-color="white" -->
```

**Comment by ventolinmono** [comment]
Sorry, that changes the background color to white but it does not put an image as background.
I thought maybe it was necessary to first a white color had to be established but that's not working either.

**Comment by dvirtz** [comment]
sorry, I thought you wanted to change the color. can you provide a minimal example reproducing your issue?

**Comment by ventolinmono** [comment]
No problem.

Trying to have an image background like this: https://revealjs.com/#/14/4
But i'm having all the content on an external markdown, so slide navigation is defined with line breaks.
I can insert colored background with that command included in the markdown.
But can not insert a a background image with:   on the markdown.

**Comment by sunilvb** [comment]
Hello,
Any update on this ask? or is there a workaround to enable background image using markdown?

**Comment by nabilbendafi** [comment]
@ventolinmx / @sunilvb 
You can _already_ achieve this relatively easy with , assuming your Markdown file is `slides.md`
```
    <div class="reveal">
      <div class="slides">
        <section data-markdown="slides.md" data-background-image="http://example.com/image.png"></section>
      </div>
    </div>
```
(nothing more that just adding `data-background-image` (ref. https://revealjs.com/backgrounds/#image-backgrounds).

This will add **same** image background to _all_ your slides (separated by `const DEFAULT_SLIDE_SEPARATOR = '\r?\n---\r?\n'`,
https://github.com/hakimel/reveal.js/blob/master/plugin/markdown/plugin.js#L9, if you don't override `data-separator` and/or `data-separator-vertical`).

Then you can _individually_ override slide's background image like below, in your  `slides.md` for ex.
```
<!-- .element: data-background-image="https://www.shutterstock.com/image-photo/red-ship-leader-white-following-260nw-1549083542.jpg" -->
# Title 1

## Title 1.1

---
<!-- Default image used -->

## Title 1.2

---
<!-- .element: data-background-image="https://www.shutterstock.com/image-photo/paper-ships-260nw-649498291.jpg" -->
## Title 1.3

---
<!-- Default image used -->
# Title 2

---
<!-- Default image still used -->
# Title 3
```

**Comment by gabrielbdornas** [comment]
I experience the same problem and notice that a local image path doesn't work but an URL link does. Is there a reason to not allow local image usage?

**Comment by nabilbendafi** [comment]
@gabrielbdornas 
No issue with images stored locally

```
...
    <div class="reveal">
      <div class="slides">
        <section data-markdown="slides/TRAINING.md" data-separator="^---$" data-separator-vertical="^--$" data-background-image="slides/img/background.png"></section>
      </div>
...
```

**Comment by gabrielbdornas** [comment]
> data-background-image="slides/img/background.png"

Correct! Tried another time and work fine! Sorry for that!

**Comment by Martinomagnifico** [comment]
It looks like the issue can be closed.

**Comment by ventolinmx** [comment]
Just tried is. Another work-around can also be to set a transparent image as default and set different images where needed.

**Comment by ventolinmx** [comment]
Just tried is. Another work-around can also be to set a transparent image as default and set different images where needed.
