### ISSUE TITLE
Internal web server should listen on 127.0.0.1, not 0.0.0.0

### ISSUE THREAD

**Issue by dnnr** [hakimel/reveal.js#2785]
It seems that a commit from March (5a5a5c9a) inadvertently changed the default listening interface from localhost to 0.0.0.0, meaning every network interface available.

This is an unsafe default and a potential security risk (information disclosure), especially since there appears to be no obvious/documented way to change this behavior, except for modifying the source.

Please consider making 127.0.0.1 the default again. Thanks.

**Comment by cashcat** [comment]
but how to start with 0.0.0.0?

**Comment by hakimel** [comment]
As of #3075 you can use:
```
npm start -- --host=0.0.0.0
```

Thanks @cashcat for fixing that.
