### ISSUE TITLE
A Hotfix reincluding the css folder from npm release?

### ISSUE THREAD

**Issue by Defcon0** [hakimel/reveal.js#2800]
Hello,

according to

https://github.com/hakimel/reveal.js/issues/2712

I'd like to ask if it would be possible to have a hotfix 4.0.3 (or a roadmap for 4.1.0) containing the theme files which currently are in the npmignore file making it impossible to use the node package in an extensible way :-(

Thanks in advance.

Bye Defcon0

**Comment by hakimel** [comment]
reveal.js 4.1.0 was just released and is available from npm 🚀 Let me know if there are any issues.
