### ISSUE TITLE
Dist JS has wrong version number

### ISSUE THREAD

**Issue by planetoftheweb** [hakimel/reveal.js#2810]
https://github.com/hakimel/reveal.js/blob/master/dist/reveal.js

Still has the 4.0.2 in the comments at the top instead of 4.1.0, which was throwing me off when I tried to update.

**Comment by mfakih294** [comment]
I confirm this. Just downloaded the master.zip:
https://github.com/hakimel/reveal.js/archive/master.zip
However, the contents file is different from a past version that I have downloaded some months ago.

**Comment by Martinomagnifico** [comment]
This is fixed now. The version number will be automatically updated.
