### ISSUE TITLE
Live reload doesn't refresh speaker notes in speaker view

### ISSUE THREAD

**Issue by eliasp** [hakimel/reveal.js#2822]
For editing/previewing my slides, I run `npm start` to make use of the live reload feature, to see changes on the fly.

While this works just fine for the slide content, it doesn't refresh the notes in the "Speaker View", although the slide previews in the "Speaker View" get refreshed just fine.
This happens for plain HTML notes, as well as for Markdown notes.

I can reproduce this issue in
- Mozilla Firefox 82.0/Win10 1909
- Google Chrome 86.0.4240.111/Win10 1909

Using reveal.js 0582f57 on Ubuntu 18.04 (NodeJS 12.18.4 provided through a [Nix Shell](https://nixos.org/manual/nix/unstable/command-ref/nix-shell.html) environment)

Configuration:
```JavaScript
Reveal.initialize({
    hash: true,
    plugins: [ RevealMarkdown, RevealNotes ],
    totalTime: 2100,
});
```

The output of gulp contains nothing unexpected:
```
[nix-shell:~/code-repositories/personal/eprobst/saltstack-a-history-of-systems]$ npm start

> reveal.js@4.1.0 start /home/eprobst/code-repositories/personal/eprobst/saltstack-a-history-of-systems
> gulp serve

[16:55:13] Using gulpfile ~/code-repositories/personal/eprobst/saltstack-a-history-of-systems/gulpfile.js
[16:55:13] Starting 'serve'...
[16:55:13] Starting server...
[16:55:13] Server started http://0.0.0.0:8000
[16:55:13] LiveReload started on port 35729
[16:55:13] Running server
[16:55:39] Starting 'reload'...
[16:55:40] Finished 'reload' after 82 ms
[16:55:46] Starting 'reload'...
[16:55:46] Finished 'reload' after 8.41 ms
[16:56:26] Starting 'reload'...
[16:56:26] Finished 'reload' after 16 ms
[16:56:30] Starting 'reload'...
[16:56:30] Finished 'reload' after 2.97 ms
```

**Comment by eliasp** [comment]
Maybe related/relevant for debugging this:

A live reload pushes the current position back to the 1st slide:
- in the main window
- in both previews of "Speaker View"
...but it leaves the notes at the previous position.

From this moment on, "Speaker View" doesn't react to any changes in the main window anymore.
Switching between slides in the "Speaker View" only affects the "Current" view, but has zero effect on "Upcoming" or "Notes".

**Comment by mikestopcontinues** [comment]
Same problem, using Vite to build/serve. After reload, not only do the notes not update, but the current notes _stick_. Only exiting and re-entering presenter modes shows the updates.

**Comment by mikestopcontinues** [comment]
Thanks @hakimel. You're solution actually also just solved a long-standing bug in my own app's iframe communication. :D
