### ISSUE TITLE
How can I change the speaker notes font-size permanently?

### ISSUE THREAD

**Issue by lucidBrot** [hakimel/reveal.js#2824]
I don't see all the notes in the speaker view without having to scroll.

I can change the `font-size` in the chrome developer settings so that the `speaker-controls-notes` class has `font-size: small`. That works, but does not remain permanently.

I tried editing the theme file, the `plugin/notes/speaker-view.html` css, and my `index.html` with variations of the following, but to no avail - the text stayed the same size after reloads.

```
<style>
.speaker-controls-notes {
    font-size: small;
}
</style>
```

How can I make the notes font size smaller?

**Comment by empicano** [comment]
I managed to do this (albeit not very elegantly) by adding an extra `<div>` inside the notes:

```html
<aside class="notes">
    <div data-markdown style="font-size: 14px;">
        - foo
        - bar
    </div>
</aside>
```

The same works with standard HTML notes, just leave out the `data-markdown`. Hope that helps somebody.

**Comment by hakimel** [comment]
You can customize the speaker view styles in `plugin/notes/speaker-view.html`. The notes font-size is found here: https://github.com/hakimel/reveal.js/blob/master/plugin/notes/speaker-view.html#L179

After making changes you will need to rebuild the plugins by running `gulp plugins`.
