### ISSUE TITLE
markdown plugin: data-separator does not seem to have a default value. Should it have one?

### ISSUE THREAD

**Issue by dr-leo** [hakimel/reveal.js#2832]
Hi,

I am new to this excellent framework and stumbled upon what I consider a bug either in the markdown plugin or the docs or both.

The 
[docs](https://revealjs.com/markdown/) state the following:

> ... in the external file: the data-separator attribute defines a regular expression for horizontal slides (defaults 
> to ^\r?\n---\r?\n$, ...

However, the code example for internal markdown, which does not define data-separator (thus allegedly relying on its default value) places all the text on the same slide.
Likewise, the examples/markdown.html file suggests that there is no default value for data-separator:

```
<!-- No "extra" slides, since there are no separators defined (so they'll become horizontal rulers) -->
                <section data-markdown>
                    <script type="text/template">
                        A

                        ---

                        B

                        ---

                        C
                    </script>
                </section>
```

Moreover, if there was a default value defined in the plugin, it should apply to internal MD as well, in which case the docs should make this clear (currently, they suggest that data-separator only influences the parsing of external MD).

**Comment by L0ganW** [comment]
In other words it dosen't recognize the
Input so it spits an error.

**Comment by dr-leo** [comment]
There is no error msg. The '/r/n---/r/n_ string is just not
interpreted as slide separator, but simply according to MD syntax as
horizontal rule.

(Sorry, my current keyboard does not allow backslashes.)

By contrast, when I define data-separator in the section element
enclosing the MD part

`<section data-markdown data-separator='/r?/n---/r?/n'>`,

multiple slides are generated as expected. Based on the docs quoted
above, I would just expect this behavior without defining
data-separator regex.

The behavior I observe is correctly described in
examples/markdown.html at line 56 et seq, but not in the docs.

I work with a current clone of the master branch, probably at v4.1.0.

**Comment by ee0s** [comment]
I think #2850 is related to this.

**Comment by hakimel** [comment]
Thanks for reporting. I just pushed a fix for this in https://github.com/hakimel/reveal.js/issues/2850#issuecomment-776575948
