### ISSUE TITLE
Electron 

### ISSUE THREAD

**Issue by geniuscd** [hakimel/reveal.js#2857]
### Hello, Great plugin!
I'm trying to integrate it into an **electron (nextron)** project its SSR.
the problem is that im not able to make it running.
navigator is undefined, or window is undefined.
I also tried to add it in the useEffect hook, still no luck.
any other alternative?

I'm trying to achieve a dynamic load from local file, where the slides are located in an .mdx file.
appreciate your help :) or at least some links.. i've searched a lot without finding any clue.

**Comment by hsoon01** [comment]
> ### Hello, Great plugin!
> 
> I'm trying to integrate it into an **electron (nextron)** project its SSR.
> 
> the problem is that im not able to make it running.
> 
> navigator is undefined, or window is undefined.
> 
> I also tried to add it in the useEffect hook, still no luck.
> 
> any other alternative?
> 
> 
> 
> I'm trying to achieve a dynamic load from local file, where the slides are located in an .mdx file.
> 
> appreciate your help :) or at least some links.. i've searched a lot without finding any clue.
> 
> 
> 
>

**Comment by jollyolchap** [comment]
> -run:'run_fast'

> -bundle: -v

> -ruby

??
