### ISSUE TITLE
r-fit-text and multiple lines has a spacing issue

### ISSUE THREAD

**Issue by cfjedimaster** [hakimel/reveal.js#2860]
As see in the demo here, https://revealjs.com/layout/#fit-text, the second example with multiple lines, the text of each line overlap each other. In case this is an OS issue (I'm on Windows, Edgium), here is a screen shot:

![image](https://user-images.githubusercontent.com/393660/101212798-f454c300-363e-11eb-95e6-9ad40c460967.png)

**Comment by hakimel** [comment]
Thanks for reporting! This is an issue in the revealjs.com site so I've moved the issue there https://github.com/reveal/revealjs.com/issues/22

Spent 30 minutes on it but wasn't able to figure out what's going on yet.
