### ISSUE TITLE
Animations in PDF

### ISSUE THREAD

**Issue by okenk** [hakimel/reveal.js#2873]
I would like to deliver a talk from a remark.js presentation exported to a pdf. (Unfortunately I am unable to deliver the presentation on a web browser using the html file.) When I [export the slides to pdf ](https://revealjs.com/pdf-export/), they look great, but I had many slides building up bullet by bullet, and that is not preserved. I was expecting something like beamer, where it makes a new pdf page for every incremental animation. Is this possible to do?

**Comment by PhiLhoSoft** [comment]
The pdfSeparateFragments option (that might have been added after your issue) seems to address the problem, no?
Except that what you request is now the default.
Unless I miss something?

(The issue title was confusing, I suppose you talk about fragments, not animated images on the slides.)

**Comment by okenk** [comment]
Oh thanks, honestly this was such a long time ago I found some other solution. It is possible this has been fixed, I'm not sure, but at the time if you had bullets appearing incrementally this was not preserved in the PDF version of the presentation.

**Comment by hakimel** [comment]
@PhiLhoSoft is right that this has been addressed already. The current default behavior is that all fragments/animated bullet lists are exported as separate pages.
