### ISSUE TITLE
Fragmenting a line of text by its words?

### ISSUE THREAD

**Issue by rorywalsh** [hakimel/reveal.js#2879]
Apologies if this isn't the right place to ask this, but can anyone explain how I might fragment words in a single line of text? So that each new fragment completes the next part of the sentence?

**Comment by mitchnegus** [comment]
You should be able to do this just by adding a `class="fragment"` tag to a set of `<span>` (or `<p>` or `<div>` or whatever) tags.

Pretty sure a better place to ask this would be on StackOverflow, not in the GitHub issues (See the [`CONTRIBUTING.md`](https://github.com/hakimel/reveal.js/blob/master/CONTRIBUTING.md) file).

**Comment by rorywalsh** [comment]
<span> did the trick ;) I was trying <p> but it was putting fragments on a new line. I will close this and post to stack the next time. Sorry, but thank you for the prompt reply!
