### ISSUE TITLE
Override left slide to next slide.

### ISSUE THREAD

**Issue by guneysus** [hakimel/reveal.js#288]
I want to change next slide not left slide on press left key or left arrow to avoid skip vertical slides?
How to override this, with hacking reveal*.js?

```
<a href="#" class="navigate-prev">
```

Instead of:

```
<a href="#" class="navigate-left">
```

**Comment by iandunn** [comment]
It should be possible to do this without hacking `reveal.js`.

[This gist](https://gist.github.com/iandunn/325997fb7a5b79d92627/dbbced5aa437b42eb938202dec84d268e6646a37) almost works, but it advances twice when reaching a slide that has slides nested inside it. 

`event.preventDefault()` and `Reveal.preventDefault()` didn't help; any ideas?

**Comment by iandunn** [comment]
Doh, nevermind, it's much easier than that. When calling `Reveal.initalize()`, just include

```
keyboard: {
	40: 'navigateNext',
	74: 'navigateNext'
},
```

**Comment by rip3rs** [comment]
I know this is a old post but I had to create a way of going back and forth even if they were vertical slides to just be able to press left and right and follow the sequence as intended @iandunn gave me the answer.

    keyboard: {
      39: 'navigateNext',
      37: 'navigatePrev'
	}
