### ISSUE TITLE
share video accross multiple slides or fragements w/o restarting the video

### ISSUE THREAD

**Issue by think-nice-things** [hakimel/reveal.js#2882]
Hi,

I just found that sharing a background video accross multiple slides or fragments restarts the video.
Is there a way to not restart the video but just keep it running?

#### share video accross multiple slides

If switching from the first to the second slide, the video restarts from the beginning.
I'd rather like to keep it running and not restarting it.

```html
<section>
  <section data-background-video = "myvideo.mp4" data-background-video-loop> 
    content
  </section>
  <section data-background-video = "myvideo.mp4" data-background-video-loop> 
    content
  </section>
</section>
```

#### share video with fragments

If switching to the second fragment the video restarts from the beginning.
I'd rather like to keep it running and not restarting it.

```html
<section data-background-video="myvideo.mp4" data-background-video-loop>
  <div>
    <h2>Some caption</h2>
  </div>
  <div class = 'fragment'>
    Text which appears as fragment later.
  </div>
</section>
```

any ideas?

**Comment by rben01** [comment]
I have what I believe is the same issue, but for ordinary videos, not background videos. When a `![](video.mp4)` on a slide is playing, every fragment on the slide will restart the video. I'd expect the video to just continue playing through the fragments.

**Comment by hakimel** [comment]
Multiple identical & consecutive background videos will now keep playing without interruption as of https://github.com/hakimel/reveal.js/commit/a29a9c71aed1c34abd75cd32ad373d1af23fbb1c

I have not been able to reproduce the issue with fragments restarting videos so assuming that's already been fixed.

**Comment by rben01** [comment]
> Multiple identical & consecutive background videos will now keep playing without interruption as of [a29a9c7](https://github.com/hakimel/reveal.js/commit/a29a9c71aed1c34abd75cd32ad373d1af23fbb1c)
> 
> I have not been able to reproduce the issue with fragments restarting videos so assuming that's already been fixed.

I don't think so, on master there is this: https://github.com/hakimel/reveal.js/blob/a29a9c71aed1c34abd75cd32ad373d1af23fbb1c/js/controllers/slidecontent.js#L310-L312

I believe this runs unconditionally when a fragment is advanced, and causes all videos on the slide to restart.

**Comment by hakimel** [comment]
@rben01 The `startEmbeddedMedia` accepts different target elements and will only play media elements found in that scope. When stepping through slides, we call `startEmbeddedMedia( slideElement )` which starts all media on the slide. But when going through fragments we invoke `startEmbeddedMedia( fragmentElement )` so that only media inside of the newly shown fragment play.

I did notice that video were resetting when hiding fragments though, and perhaps there are other cases I've missed. I pushed a small change that should guard against resetting any video that is already playing; 1748a55ece8395d8186cd5acc68256d942975325

**Comment by rben01** [comment]
Yes, `this.startEmbeddedMedia( { target: el } );` only starts playing the targeted element, but it is called for every video on the page whenever `startEmbeddedContent` is called. So the check you introduced is necessary.

Separately, I'm not sure if restarting videos that have finished playing is the right call — I would imagine that some people would like them to play once and never restart. Could this be controlled with an attribute like `data-allow-loop-on-fragment`?
