### ISSUE TITLE
Markdown fragments not appearing as expected

### ISSUE THREAD

**Issue by StuntsPT** [hakimel/reveal.js#2909]
I've been using reveal.js (which is awesome, BTW) for the last few years with great success.
Today I have updated the version of `reveal.js` from 3.9.2 to the latest 4.1.0. Besides the path changes I had to made (which are perfectly understandable), I noticed some changed behaviour, particularly when using external markdown, and unordered lists.
Here is what I have:

```markdown
## Title

* Item 1 <!-- .element: class="fragment" -->
* Item 2 <!-- .element: class="fragment" -->

```

If I do this, everything works as expected (each bullet point is revealed only when the right arrow is pressed).
However, if I have markdown syntax in any of the items, like this:

```markdown
## Title

* Item **1** <!-- .element: class="fragment" -->
* Item **2** <!-- .element: class="fragment" -->

```

What I get is all the text displayed as soon as the slide appears, except the markdown syntax (in this case, the numbers 1 and 2), which only appear when the right arrow is pressed.
This situation can be worked around resorting to HTML, but it is not ideal, since it requires a lot of newline hacking to make it work as intended:

```html
## Title

<ul>
  <li class="fragment">

  Item **1** </li>
  <li class="fragment">

  Item **2** </li>
  
</ul>

```

Which is by no means as readable as the "pure" markdown version.
Is this a bug, or was it intentional somewhere along the path? Is there any alternative workaround the results in something more readable than what I currently have?

Thank you in advance.

**Comment by StuntsPT** [comment]
Ok, so this is obviously a duplicate of #1848 which I somehow failed to previously find.

**Comment by Roberlanderrsilva** [comment]
tenso...??//;;
