### ISSUE TITLE
A section allways reset counter values

### ISSUE THREAD

**Issue by roy77** [hakimel/reveal.js#2919]
A section allways reset counter values. I can't figure out what the reason is. 

I added this lines to the head of the demo.html

   <style>
      .reveal h2::before { content: counter(h2,decimal) ". "; }
      .reveal h2 {
        counter-increment: h2;
        color: red;
      }
    </style>

Only inside a section the counter is incremented. In the next section the counter start again with 1. I checked the css files but cannot find the reason for this behavior

**Comment by Martinomagnifico** [comment]
```
:root {
	counter-reset: anyh2;
}
h2 { 
	counter-increment: anyh2;
}
h42::before { 
	content: counter(anyh2) ". ";
}
```

**Comment by a-i-m-a-r** [comment]
I had the same issue in "figcaption". In my style file I had:
`body {
	counter-reset: my-fig-counter 0;
}`
```
figcaption::before {
	counter-increment: my-fig-counter 1; 
	content:"Figure "counter(my-fig-counter, decimal) ": "; 
}
```
changing it to:
`:root {
	counter-reset: my-fig-counter 0;
}`
as @Martinomagnifico says, does not work for me. Instead, counter-increment is not working any more and all the figures show the same number (1).

**Comment by Martinomagnifico** [comment]
In CSS, any element that has `display:none` will not be counted. And the problem here is about counters that span multiple slides. The two solutions below can fix that:

```
.slides section {
  display: block !important;
}
```

or

```
Reveal.initialize({
  viewDistance: 100 (or the amount of slides)
});
```

However, there is a reason for hiding slides that are a few steps in the past or the future: any media in it will also not be loaded. The solutions above will load all media, and that can slow your presentation down a lot, so be carefull using them.

**Comment by Martinomagnifico** [comment]
Here's a plugin that might be what you need: https://github.com/Martinomagnifico/reveal.js-counteract 
As for the missing CSS counter functionality: they won't work on hidden slides. I think we can close the issue.

**Comment by a-i-m-a-r** [comment]
Great!
It works like a charm.
Thank you.
aimar
