### ISSUE TITLE
autoSlide exactness

### ISSUE THREAD

**Issue by galvarez421** [hakimel/reveal.js#2924]
Hello, thank you for the plugin!

I have a couple of questions and some findings regarding the exactness of the `autoSlide` option:

1. Should slide durations exactly match a value specified for the `autoSlide` option? For example, if I specify `1000` for this option, should I expect each slide affected by this option to last exactly 1000 milliseconds?
2. If not, are there known factors that explain why, either due to the plugin or something about how JS or browsers behave?

My situation is that I am working on a presentation of between 1,000-2000 slides, each with up to 5 images, with a desired auto-slide duration of 4500-6000 ms per slide. It is important that the presentation not exceed a certain total duration but also that I allow each slide to last as long as possible within the total duration, so I am hoping to achieve increased if not exact precision when it comes to estimating total duration based on number of slides multiplied by the `autoSlide` property. I used a stopwatch to measure how long a 125-slide segment would take, and the results have varied by up to a minute. Multiplied 8 to 16 times, this variation is significant for my purposes. To take a closer look at the timing, I created a test case (https://github.com/galvarez421/reveal.js-timing-tests), which seems to confirm that actual slide durations exceed the number specified by `autoSlide` and that they are not all the same. It also seems that perhaps the variation increases the more content there is on the slides.

For now, I am thinking I might calculate the average excess in duration and then account for that by specifying a lower `autoSlide` but I was hoping there is a better, more determinstic alternative!

Thank you in advance for any insights!

**Comment by galvarez421** [comment]
I think I might have figured this out. Basically, [`autoSlide` uses `setTimeout`](https://github.com/hakimel/reveal.js/blob/4.1.0/js/reveal.js#L2128-L2145), which itself can be expected to be [imprecise in various circumstances](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setTimeout#reasons_for_delays). So basically, unless this plugin uses custom code or a library (e.g., https://github.com/chrisguttandin/worker-timers, https://github.com/mrchimp/tock, https://github.com/jamiebuilds/tickedoff, etc.) to try to achieve more precise timing, `autoSlide` should be expected to be at least as inexact as `setTimeout` is in any given case.

For whatever it's worth, from my continued testing, I have found only very small variance recently when playing the slideshow fullscreen but variance as large as 2 minutes in other cases, e.g., when playing the slideshow in an unfocused tab/window. I will probably do the following: assume slideshow will last at least a little longer than expected and set an accordingly lower `autoSlide`, provide an explanation for whoever will play the slideshow that the slideshow duration should be expected to fall within a certain range, and encourage a certain methodology for playing the slideshow (reducing background processes, playing the slideshow in a focused window, etc.).

**Comment by sindhu51188** [comment]
Unsubscribe
