### ISSUE TITLE
logo option

### ISSUE THREAD

**Issue by jsdads11** [hakimel/reveal.js#2926]
Is it possible please to add a logo support option as per https://github.com/handsomeyang/reveal.js - this build refers to a much older version of reveal.js though.

thanks 
Tony

**Comment by Martinomagnifico** [comment]
This is about content and styling. Not really the scope of reveal.js. If you look at how it is done in the example you mention, it's just some CSS: 

.reveal .logo {
	position: fixed;
	display: block;
	left: 8px;
	bottom: 8px;
	z-index: 31;
  width: 80px;   
  height: 80px;
  background-image: url('../img/logo');
  background-size: 80px;
  background-position: 0% 100%;
  background-repeat: no-repeat;
}

Add this to your own CSS or include it in a <style> block, and just add a div with class 'logo' next to your slides.

**Comment by danielb2** [comment]
@Martinomagnifico this code snippet doesn't work anymore which I think highlights the need for some feature like this
