### ISSUE TITLE
MathJax not working

### ISSUE THREAD

**Issue by rinaldi6109** [hakimel/reveal.js#2932]
Following instructions at https://revealjs.com/math/ I've edited index.html inserting the line: 
`<script src="plugin/math/math.js"></script>`
and then the lines: 
```
<section>
  <h2>The Lorenz Equations</h2>
  \[\begin{aligned}
  \dot{x} &amp; = \sigma(y-x) \\
  \dot{y} &amp; = \rho x - y - xz \\
  \dot{z} &amp; = -\beta z + xy
  \end{aligned} \]
</section>
```
but MathJax doesn't work.
What's wrong? Thank you.
[index.txt](https://github.com/hakimel/reveal.js/files/6290692/index.txt)

**Comment by Martinomagnifico** [comment]
See the doc page you referred to:
`<script src="plugin/math/math.js"></script>
<script>
  Reveal.initialize({
    plugins: [ RevealMath ]
  });
</script> `

**Comment by dakewamama** [comment]
why should i do that

**Comment by Martinomagnifico** [comment]
Because the original poster might find it to be a solution for the problem. Case closed.

**Comment by kaylafrechette** [comment]
French pleas

**Comment by Martinomagnifico** [comment]
Solution provided, closing the issue.

**Comment by Mattj105** [comment]
Hey buddy.. I don't remember being there or closing anything.. whatever you
need me to do I'll do to fix it.. I'm not sure how to.. get back to me and
let me know what I have to do... Thanks.. mattj
