### ISSUE TITLE
Media (auto)playing in three copies when speaker view is open

### ISSUE THREAD

**Issue by cifkao** [hakimel/reveal.js#2936]
When the speaker window is open, media set to autoplay will play _three times_: twice from the speaker view and once from the main window. This is obviously a problem with audio, because the audience will then hear all three copies.

Is there any way to prevent media from playing in the speaker view or at least mute the audio?

**Comment by hakimel** [comment]
There are measures in place that are supposed to prevent this. Can you share a copy of the slide `<section>` where media plays inside of the speaker view? Thanks.

**Comment by cifkao** [comment]
I should have said that the audio is inside a fragment. Like this:

```html
				<section>
					<h3>Examples</h3>
					<table class="audio-table">
						<tbody>
							<tr>
								<td class="fragment">
									<audio src="https://adasp.telecom-paris.fr/rc-ext/demos_companion-pages/vqvae_examples/synth/style/ec1df0e3291259a040cc709a5acc4b92.style.mp3" data-autoplay></audio>
									style: harmonica
								</td>
								<td class="fragment">
									<audio src="https://adasp.telecom-paris.fr/rc-ext/demos_companion-pages/vqvae_examples/synth/content/ec1df0e3291259a040cc709a5acc4b92.content.mp3" data-autoplay></audio>
									content: harp
								</td>
								<td class="fragment">
									<audio src="https://adasp.telecom-paris.fr/rc-ext/demos_companion-pages/vqvae_examples/synth/vq-vae/659.mp3" data-autoplay></audio>
									output
								</td>
							</tr>
							<tr>
								<td class="fragment">
									<audio src="https://adasp.telecom-paris.fr/rc-ext/demos_companion-pages/vqvae_examples/real/style/Fergessen_TheWind_Fergessen_TheWind_Full_17_SlecGtr3a_Close.146.mp3" data-autoplay></audio>
									style: electric guitar
								</td>
								<td class="fragment">
									<audio src="https://adasp.telecom-paris.fr/rc-ext/demos_companion-pages/vqvae_examples/real/content/MR0902_JamesElder_MR0902_JamesElder_Full_13_SynthFX1.163.mp3" data-autoplay></audio>
									content: vocals
								</td>
								<td class="fragment">
									<audio src="https://adasp.telecom-paris.fr/rc-ext/demos_companion-pages/vqvae_examples/real/vq-vae/684.mp3" data-autoplay></audio>
									output
								</td>
							</tr>
						</tbody>
					</table>
				</section>
```

**Comment by cifkao** [comment]
Actually the issue seems to be different than what I thought. What I observe is that with the speaker window open, every time I go to the next fragment I hear _all_ the previous audios as well.

Also, I seem to be using version 4.0.2, so sorry if this was fixed recently.

**Comment by hakimel** [comment]
Hey. I tried your example but the <audio> tags did not play inside of the speaker view in the latest version of reveal.js. Could you try pulling the latest version of reveal.js from the dev branch and see if that fixes the problem?

On a related note, I just pushed an update which will stop playing video/audio inside of fragments when they are hidden (https://github.com/hakimel/reveal.js/commit/6d735ddaf8c15637b493bc837041a9380ead1d77).
