### ISSUE TITLE
Setting aspect ratio of presentation

### ISSUE THREAD

**Issue by Krzmbrzl** [hakimel/reveal.js#2951]
I am having a hard time figuring out how the aspect ratio of my presentation can be configured without messing up my presentation.

I have found https://revealjs.com/presentation-size/ in particular the `height` and `width` config options. I see that the default presentation size uses a 4:3 aspect ratio, but I would like to use 16:9.

With the default sizing my slide looks like this (on a 16:9 monitor):
![image](https://user-images.githubusercontent.com/12751591/117114385-15efdd00-ad8c-11eb-9836-a488676e688d.png)

If I change the aspect ratio to 16:9 by setting `width = 1920` and `height = 1080` this turns into
![image](https://user-images.githubusercontent.com/12751591/117114519-3f106d80-ad8c-11eb-9bc2-cd9ebc7f9649.png)

And if I instead set `width = 192` and `height = 108` (note that this is the exact same aspect ratio) I get
![image](https://user-images.githubusercontent.com/12751591/117114639-67986780-ad8c-11eb-8785-d65c1d696865.png)

The first thing that I noticed is that the font size decreased when using the 1920y1080 size. This was unexpected and I can't really make sense out of this.

More importantly though: When using 192x108 the presentation is completely screwed. I was under the impression that reveal.js would scale the presentation up if there was more screen space available. It seems to apply a fair bit of scaling but only to the font size. It seems as if the slide is still placed on the screen as if it was 192x108 and thus the scaling of font size leads to a massive overflow of the slide. Shouldn't the auto-resize functionality be carried out before placing the slide on the screen?

**Comment by hakimel** [comment]
The width and height config values determine the "normal" size of your presentation. That is the size the presentation is authored at. If you set use a width and height of 1920x1080, and the screen that you use to view the presentation is 960x540, the presentation will be scaled down to be 50% of its normal size.

We don't change the font size based on what resolution you configure. That means if you use a very low resolution text will look bigger, if you use a very high resolution text will look smaller. For example a 32px font size within a 3840x2160px area will look small, a 32px font size within a 192x108px area will look huge.

I'd recommend picking a resolution that fits well on the screen you're using to author the presentation and then relying on reveal.js to scale that up/down when presenting on other screens.

**Comment by Krzmbrzl** [comment]
Does this work based on the actual display size or the size of the browser's viewport? 'cause the whole resizing stuff seemed to not work very nicely when resizing the browser...

**Comment by hakimel** [comment]
It's based on the browser viewport size. Note that there's a margin around the slides too, but you can disable that by setting the `margin` config option to 0.
