### ISSUE TITLE
Display code only as wide as necessary

### ISSUE THREAD

**Issue by Krzmbrzl** [hakimel/reveal.js#2952]
When using code on my slides like
```html
<pre><code>First line
Second line
...</code></pre>
```
The code box gets stretched to fit the width of my slide. For code that does not contain any long lines, this looks super ugly as there is just an immense amount of blank space in the highlighted code area.
Thus I would like to restrict the size of the code block to just fit its content. No less and no more.
Additionally I want to have that block horizontally centered on my screen.

I have tried using
```html
<pre><code style="display: table; margin: 0 auto;">First line
Second line
...</code></pre>
```
Which almost achieves what I want, but there is still the drop-shadow of the surrounding `<pre>` element that stretches over the full width of my slide. The same trick does not work on the `<pre>` element so I am a bit clueless...

**Comment by hakimel** [comment]
This should do it
```css
.reveal pre {
  width: max-content;
}
```

**Comment by Krzmbrzl** [comment]
Yes that worked. Thank you!

**Comment by Ra-Mzes** [comment]
Yes
