### ISSUE TITLE
Master fails to build with node 16

### ISSUE THREAD

**Issue by Khoulaiz** [hakimel/reveal.js#2959]
Trying to clone the repository and do a npm install fails currently with node v.16. I had to go back to node 14 to  let the build be successful.

**Comment by hakimel** [comment]
This should be fixed now—would you mind pulling the dev branch and checking if that works for you?

The issue originated from a very outdated dependency which has now been removed (gulp-sass). Really need to migrate away from gulp for the build system soon 😅

**Comment by hakimel** [comment]
node 16 is automatically tested via actions now too https://github.com/hakimel/reveal.js/runs/2624112737?check_suite_focus=true

**Comment by Khoulaiz** [comment]
Works for me now on dev branch with node 16.1.0

**Comment by hakimel** [comment]
Great, those updates are available in master now too

**Comment by IkaFieyka** [comment]
css/print/pdf.scss

**Comment by IkaFieyka** [comment]
css/print/pdf.scss

**Comment by CD4B7** [comment]
https://github.com/hakimel/reveal.js
