### ISSUE TITLE
CSS Varaible Names are too generic

### ISSUE THREAD

**Issue by blairmacintyre** [hakimel/reveal.js#2967]
(related to issue https://github.com/hakimel/reveal.js/issues/2739, which is closed)

I'm embedding reveal in a website that _also_ uses CSS variables for configuring its CSS.  It also uses fairly generic variable names in `:root` like `--background-color`.

Since reveal is designed to be able to be embedded, perhaps the variable names should be a bit unique, such as `--reveal-background-color` ... you've taken care in your CSS to only affect elements under `.reveal`, it would be great to do this here too.

(I can do it and test in my site, and submit a PR, if this seems like a good idea to you)

(related: could monokai.css in the highlight plugin have it's style qualified with `.reveal` as well?)

**Comment by hakimel** [comment]
Good point. I think prefixing the variables to avoid potential conflicts sounds great. We're already using an "r-" prefix for layout classes so maybe we can use `--r-background-color`?

**Comment by blairmacintyre** [comment]
sounds reasonable.  I tested it out with `--reveal-`, but I assume `--r-` would work just as well.  

This is pretty simple;  do you want a PR, or do you want to just do it?

**Comment by hakimel** [comment]
Your PR has been merged—thanks!
