### ISSUE TITLE
notes (asides) are shown on the slide

### ISSUE THREAD

**Issue by rparree** [hakimel/reveal.js#2970]
Hi,

When updating from 4.1.0 to 4.1.1, all my asides are shown on the slides.

Until version 4.1.0,  the notes remained a `aside` element and the css had `display:none` for the css rule: `.reveal aside.notes`.

In 4.1.1 the `aside` containing the notes is rendered into a `section` child element  with a `notes` class. These notes are shown on the slide.

**Comment by hakimel** [comment]
Hey. I just tested this but the aside element remains hidden for notes. The style that sets `aside.notes` to `display: none` hasn't changed in years: https://github.com/hakimel/reveal.js/blame/master/css/reveal.scss#L1695-L1697

If you can upload an example presentation where this isn't working I'd be happy to take a look.

**Comment by rparree** [comment]
I  pulled the  HEAD  version and added the section below to the `index.html`

```html
<section>
	<h2>test</h2>
	<aside class="notes" data-markdown="">
		some `notes`
	</aside>
</section>
```

I guess what is happening is the latest `RevealMarkdown` swallows it up and renders a section. This was not the behaviour on version 4.1.0 and before

**Comment by hakimel** [comment]
Ah, this issue only affects notes with `data-markdown` enabled.

I've tracked down the problem and pushed a fix. Can you pull the latest master and see if that solves the issue for you?

**Comment by rparree** [comment]
yes that solved the problem. Thanks

**Comment by hakimel** [comment]
Great, this has been published in a new release.
