### ISSUE TITLE
Get the next slide section from the main slide

### ISSUE THREAD

**Issue by ljfreelancer88** [hakimel/reveal.js#2987]
Hi, I'm having hard time implementing on how to get the next or upcoming slide section from the main slide.
```html
<div id="slide-current">
  <div class="reveal">
    <div class="slides">
      <section>Slide 1</section>
      <section>Slide 2</section>
      <section>Slide 3</section>
    </div>
  </div>
</div>
<div id="slide-next">
<!-- SHOW THE NEXT SLIDE HERE -->
</div>
```
I can able to get the current slide using `currentSlide`. But I didn't see any `nextSlide`. This is what I have in my mind.
```javascript
Reveal.on( 'slidechanged', event => {
  // event.currentSlide, event.indexh, event.indexv
  console.log(event.currentSlide);
  document.querySelector('#slide-next').value = event.nextSlide; //nextSlide seems not exist though.
} );
```

Thank you in advance.

**Comment by Martinomagnifico** [comment]
event.currentSlide.nextElementSibling will work. You'll need to rewrite that if the next slide or the current slide is in a vertical stack.

**Comment by Sharni17** [comment]
Thank you 😊

**Comment by ljfreelancer88** [comment]
> event.currentSlide.nextElementSibling will work. You'll need to rewrite that if the next slide or the current slide is in a vertical stack.

Is it possible to get the styling also? Like background image etc.

**Comment by Martinomagnifico** [comment]
> Is it possible to get the styling also? Like background image etc.

You can get any attribute:
```
event.currentSlide.nextElementSibling.attributes.class
event.currentSlide.nextElementSibling.attributes.style
event.currentSlide.nextElementSibling.getAttribute('data-background-image')
```
This issue is kind of done. You can close it now.

**Comment by ljfreelancer88** [comment]
Thank you
