### ISSUE TITLE
Jump back to the top of a vertical stack

### ISSUE THREAD

**Issue by ericwongmusic** [hakimel/reveal.js#3002]
Is there a way to jump to the top of a vertical stack or vice versa to the bottom of the stack?

**Comment by Martinomagnifico** [comment]
There is a simple javascript way to do this, using the provided Reveal tools.
This example uses basic buttons with classes `.to-top` and `.to-bottom`:

```
document.addEventListener('click', function (event) {
	if (event.target.matches('.to-top')) {
		event.preventDefault();
		let currenth = Reveal.getState().indexh;
		Reveal.setState({indexh: currenth, indexv:0})
	} else if (event.target.matches('.to-bottom')) {
		event.preventDefault();
		let currenth = Reveal.getState().indexh;
		let lastnr = (Reveal.getCurrentSlide().parentNode).getElementsByTagName('section').length;
		Reveal.setState({indexh: currenth, indexv:lastnr})
	} else return
}, false);
```

I think this issue can be closed.

**Comment by hakimel** [comment]
I've added support for holding shift and pressing the up/down arrow keys to jump to the either end of a vertical stack. We already had shift+left/right bound to jumping to the first/last horizontal slide so I think it makes sense to be able to do this vertically too. 90bbe8be4f12ec56723a335d36f9be984ef7ed03
