### ISSUE TITLE
Before change hooks

### ISSUE THREAD

**Issue by elliotlings** [hakimel/reveal.js#3003]
Is it possible to add a before slide change hook, so that you can stop a slide change doing it's default functionality and move to a different a slide entirely?

**Comment by hakimel** [comment]
I've wanted a preventable event like this myself in the past. Just pushed a first iteration of it to master.

```js
// This will prevent all slide changes
Reveal.addEventListener( 'slidechange', e => e.preventDefault() )
```

What should this event be called? `slidechange` might be too similar to `slidechanged` which is dispatched after. Perhaps `beforeslidechanged`?

**Comment by Martinomagnifico** [comment]
`beforeslidechanged` sounds good to me. Maybe even `beforeslidechange`, because if a 'change' takes time, it would mean that the slide could have already started changing, but not finished changing. (which is more like `slidetransitionend`)

**Comment by hakimel** [comment]
I've renamed to `beforeslidechange`. Will add it to the docs once when the next release goes out.

**Comment by Medioman92** [comment]
it would be great if there was information about the direction in the event. Something like:
`slideChangeDirection:'left' or slideChangeDirection:'right'
slideChangeDirection:'up' or slideChangeDirection:'down'`
