### ISSUE TITLE
[END] key bug

### ISSUE THREAD

**Issue by lokpro** [hakimel/reveal.js#3007]
Pressing the [END] key should go to the last slide, but the current code doesn't work.
It won't go to my last slide (11) but to number 4. It seems like the number param is taken modulus to be the slide number.

https://github.com/hakimel/reveal.js/blob/90bbe8be4f12ec56723a335d36f9be984ef7ed03/js/controllers/keyboard.js#L338

shift+➜ too, 
https://github.com/hakimel/reveal.js/blob/90bbe8be4f12ec56723a335d36f9be984ef7ed03/js/controllers/keyboard.js#L299

should be something like
```
Reveal.slide( Reveal.getSlides().length-1 );
```

**Comment by hakimel** [comment]
Is this in a presentation with vertical slides? Any chance you could share a link to it? I tried out `Reveal.slide( Number.MAX_VALUE )` but it takes me to the correct slides in the examples I had.

**Comment by lokpro** [comment]
I found out that with loop=true, numbers larger than total slides will jump back around.

**Comment by lokpro** [comment]
```
Reveal.slide( document.querySelectorAll(".slides>section").length -1 );
```

may work.

**Comment by hakimel** [comment]
This has been fixed now. Shortcuts for jumping to the last slide now work correctly even if the presentation is looped.
