### ISSUE TITLE
[LEFT] key or [wheelUp] on first slide wrap to last slide 

### ISSUE THREAD

**Issue by lokpro** [hakimel/reveal.js#3009]
Hi,
years ago when I used v3.8, it would wrap to last slide when key [LEFT] is pressed on the first slide, which is cool.
I can't do the same in the newest version. I don't know if this change is intended.

I have investigated the source.

_useLinearMode_ is defined in this way. My slides has no V. slides.
https://github.com/hakimel/reveal.js/blob/56772afa32d481685157bc355422cb793f5a07ce/js/controllers/keyboard.js#L217
Later, _useLinearMode_ is _true_ and the left() function is never reachable[*1].  It should be the reason why I can't do [Left] on the first slide.
https://github.com/hakimel/reveal.js/blob/90bbe8be4f12ec56723a335d36f9be984ef7ed03/js/controllers/keyboard.js#L284-L295

[*1]
left() does just slide( slideNumber-1) and will wrap to the last slide.
This line in prev() prevents so.
https://github.com/hakimel/reveal.js/blob/abe9abbed7c68d1e73f5befb6cf256b71d77e769/js/reveal.js#L2275

---

Likewise, I wish mouse wheel up to do the same, but it will only do prev() here.
https://github.com/hakimel/reveal.js/blob/abe9abbed7c68d1e73f5befb6cf256b71d77e769/js/controllers/pointer.js#L100-L116

---

[Swipe left]'s 'linear' check is simple (the old way). With 'default' it will do left();
https://github.com/hakimel/reveal.js/blob/56772afa32d481685157bc355422cb793f5a07ce/js/controllers/touch.js#L140-L153

---
BTW, why don't unify these left-actions?

**Comment by hakimel** [comment]
If you want leftward navigation on the first slide to take you to the last slide you'll need to enable the `loop` configuration flag. For example: https://revealjs.com/demo/?loop=true

This isn't something that's changed in recent versions. The linear mode is a feature you can active when you have both vertical and horizontal slides but want navigation to behave as if you only had slides on a single axis. It has no impact if you only have slides on the horizontal axis.

**Comment by lokpro** [comment]
Thanks for reply, 
I've checked and I have always put loop:true in my configs. :)

Checking for _useLinearMode_ did change.
_useLinearMode_ is auto true when I have no V. slides (currently I always have none).
https://github.com/hakimel/reveal.js/blob/56772afa32d481685157bc355422cb793f5a07ce/js/controllers/keyboard.js#L217

try removing V.slides on demo/?loop=true , the [LEFT] on first slide will break :) .
```
document.querySelectorAll(".slides section>section").forEach( function( node ) {
    node.parentNode.removeChild( node );
});
```

**Comment by hakimel** [comment]
Aha, that sounds like a bug. I'll try it out soon.

**Comment by hakimel** [comment]
Just pushed a fix + test for this. Feel free to give it a try when you get a chance, thanks!

**Comment by lokpro** [comment]
It works.
