### ISSUE TITLE
the speaker view doesn't show on the demo page

### ISSUE THREAD

**Issue by steelman** [hakimel/reveal.js#3012]
The speaker view does not show up when I press "s" key as instructed on [one](https://revealjs.com/?demo#/24) of the slides on the demo page.

**Comment by mostimoti** [comment]
⭐⭐⭐⭐⭐
RECOMMENDATION

**Comment by KuenzelIT** [comment]
Hi, doesn't work for me either on the demo page. Tried it in Firefox and Chrome.

**Comment by hakimel** [comment]
Fixed.

That slide was left in from the old reveal.js website. The new site didn't have the speaker view included on the homepage but I've added it now.
