### ISSUE TITLE
feature: direct speaker notes view for development with live-reload

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [hakimel/reveal.js#3032]
when using live-reload to work on slides
then a reload tends to close the slides,

i'd like to have the browser directly open the speaker view
so i can see changes without having to reopen the speaker view

**Comment by dabrahams** [comment]
Yes please.  The speaker notes view not refreshing as I edit slides is a real time sink.

**Comment by RonnyPfannschmidt** [comment]
@dabrahams i want to have only the speaker view in the main window

My understanding is that this would not resolve the other issue, however it would render it ineffective as the live reload would be active on the single window speaker view instead of being active on the presentation view while the speakers window wouldn't have it

**Comment by dabrahams** [comment]
@RonnyPfannschmidt I agree, this is not a duplicate, and I want exactly what you want.  That would be a vast improvement.

**Comment by dabrahams** [comment]
@hakimel I started to look at how to implement this but found the speaker notes plugin so complex that I wasn't sure where to start.  If you could offer some guidance I might be able to come up with a PR.

**Comment by hakimel** [comment]
One option during development is to turn on the `showNotes` config option. This will show your speaker notes in the main window with live reloading support. It can enabled using a query param too `.../demo.html?showNotes=true`.
<img width="1246" alt="Screen Shot 2022-02-10 at 10 10 53" src="https://user-images.githubusercontent.com/629429/153375418-1c84be97-e20f-46ff-8810-bf6506096bd4.png">

The best way I can think of to run the speaker view "directly" would be to embed it inside an iframe in the main window. That way the main window can still drive it using the same `postMessage` channel that it currently uses to control and communicate with the speaker view.
