### ISSUE TITLE
Share or print a presentation with notes?

### ISSUE THREAD

**Issue by aseemk** [hakimel/reveal.js#304]
Hey @hakimel, great work again. =)

I'd like to share a Reveal.js talk online, but the way I craft my presentations, the slides are very visual and don't really convey information as much as they aid/complement it. So I'd like to include a transcript / speaker notes with the slides.

The current speaker notes mode isn't really good for that -- viewers have to press 's', and change the slides in the *original* window while switching back to the *notes* window to see the changed nodes. (The preview of the next slide also isn't really helpful in this case and just takes up screen real estate.)

I thought maybe printing to PDF could do the trick (like PowerPoint and Keynote let you print w/ notes), but not here.

So would you consider adding a feature (or tweaking an existing feature, like the speaker notes window) to support seeing and easily navigating a slideshow with notes? Thanks!

**Comment by winterstein** [comment]
What's the status on this? The thread is quite old... Is there now a best-practice route for showing slides + notes on screen?
Thanks, Dan

**Comment by hakimel** [comment]
Just added the ability to share a presentation with notes visible! This can be turned on with the `showNotes` config value. Only available in the dev branch so far but will be released in 3.2.0.

Time to close the oldest open feature request :D

<img width="1021" alt="screen shot 2015-09-09 at 14 38 25" src="https://cloud.githubusercontent.com/assets/629429/9761970/7919a548-5700-11e5-81d1-e3528276be90.png">

**Comment by aseemk** [comment]
Nice!
