### ISSUE TITLE
Way of autoanimating children of `<code>` blocks

### ISSUE THREAD

**Issue by mattgodbolt** [hakimel/reveal.js#3041]
In presentations it's often the case you want to show a code snippet and then a small change to that snippet. It would be fantastic if we could use a `<span>` and autoanimate a transition for just a region of code.

Example:

```html
            <section data-auto-animate>
                <h2>Changing an element</h2>
                <pre data-auto-animate-id="code"><code data-trim data-noescape>
struct AREA_DATA {
    <span data-auto-animate-id="changing">const char *name;</span>
    const char *areaname;
    const char *filename;
    // ...
};
                </code></pre>
            </section>
            <section data-auto-animate>
                <h2>Changing an element</h2>
                <pre data-auto-animate-id="code"><code data-trim data-noescape>
struct AREA_DATA {
    <span data-auto-animate-id="changing">std::string name;</span>
    const char *areaname;
    const char *filename;
    // ...
};
                </code></pre>
            </section>
```

Currently the transition means the whole slide is faded out and replaced. I'd ideally have just the line featuring the change fade in/out or otherwise transition.

I can sort of simulate it with multiple `<code>` blocks but that artificially breaks the code into pieces.

**Comment by mattgodbolt** [comment]
That's amazing! Thanks so much @hakimel !

**Comment by mattgodbolt** [comment]
Interestingly, I had to enable `data-line-numbers` to get the smooth transition. I don't mind this, but is it maybe a bug that the line doesn't fade in and out unless `data-line-numbers` is set?

**Comment by mattgodbolt** [comment]
(delete a dumb question that you had answered in your post about line numbers.)

**Comment by redbar0n** [comment]
@hakimel what if you want the `name` keyword in your example code to stay on screen the whole time (not fade out and in), and simply move to its new (potentially horizontal/in-line) destination? Like "Implicit" does in the [movement animations example](https://revealjs.com/auto-animate/#movement-animations) example (albeit vertically).

**Comment by redbar0n** [comment]
@hakimel Thanks for the reply. For now, I found that Keynote's Magic Move by Characters most eloquently solved the problem of inline code transformations, so I will be using those instead of Reveal.js. Alternatively PowerPoint Morph by Word, albeit it's matching algorithm is a bit worse than Keynote. They could hopefully be sources of inspiration for Reveal.js in the future. I'd love to use Reveal.js (with reveal-md) instead of a presentation tool, for code transformations.
