### ISSUE TITLE
Is it possible to start line numbering from something other than 1?

### ISSUE THREAD

**Issue by mattgodbolt** [hakimel/reveal.js#3050]
I'm using two panels side-by-side to show a ~20 line function in two parts. It would be great if I could start the line numbering of the second pane from a non-1 value. I tried setting `data-ln-start-from` per https://github.com/wcoder/highlightjs-line-numbers.js but it didn't take effect. Is this supported in reveal? Thanks!

**Comment by hakimel** [comment]
`data-ln-start-from` isn't supported in reveal.js yet because we're using an older version of the line number plugin (2.6.0). Will take a look at upgrading that soon.

**Comment by mattgodbolt** [comment]
Thanks so much @hakimel.

**Comment by hakimel** [comment]
I've upgraded the line numbers plugin now so `<code data-ln-start-from="10">` will work if you pull latest master 🚀

**Comment by mattgodbolt** [comment]
That's _amazing_ -- thank you @hakimel !
