### ISSUE TITLE
Feature request: have line highlighing "in sync" with fragment indices

### ISSUE THREAD

**Issue by mattgodbolt** [hakimel/reveal.js#3054]
More of a "is this possible" really - I have some code and I have a bullet list that pops up next to it one at a time. I'd ideally like to sync the fragment indices with the `data-line-numbers="1,2,3"` type stuff. That is I have something a bit like:

```html
<pre><code data-trim data-noescape data-line-numbers="|2,3">
first
second <span data-frament-index="1">// ooh</span>
third
</code></pre>
<div class="makes it appear next to the code">
<ul><li class=fragment data-fragment-index="1">Dont do this</li></ul>
</div>
```

(not working ^ just indicative!) Is this feasible, like a data-line-framgent-start-index=1 type thing?

**Comment by mattgodbolt** [comment]
Closing, duplicate caused by a content resubmit on a dodgy train-based internet connection. See #3055

**Comment by manzo2202** [comment]
<pre><code data-trim data-noescape data-line-numbers="|2,3">
first
second <span data-frament-index="1">// ooh</span>
third
</code></pre>
<div class="makes it appear next to the code">
<ul><li class=fragment data-fragment-index="1">Dont do this</li></ul>
</div>
