### ISSUE TITLE
Feature request - set the fragment start of the implied line numbering fragments

### ISSUE THREAD

**Issue by mattgodbolt** [hakimel/reveal.js#3055]
More of a "is this possible" really - I have some code and I have a bullet list that pops up next to it one at a time. I'd ideally like to sync the fragment indices with the `data-line-numbers="1,2,3"` type stuff. That is I have something a bit like:

```html
<pre><code data-trim data-noescape data-line-numbers="|2,3">
first
second <span data-frament-index="1">// ooh</span>
third
</code></pre>
<div class="makes it appear next to the code">
<ul><li class=fragment data-fragment-index="1">Dont do this</li></ul>
</div>
```

(not working ^ just indicative!) Is this feasible, like a data-line-framgent-start-index=1 type thing?

**Comment by hakimel** [comment]
Line number highlights are really just fragments under the hood. You can tell those line number highlights from which fragment index they should start by specifying `data-fragment-index` on the `<code>` block.

Here's a slightly revised example where two bullet points will appear in sync with the second and third line of code.

```html
<section>
  <pre><code data-trim data-noescape data-line-numbers="1|2|3" data-fragment-index="1">
    first
    second
    third
  </code></pre>
  <ul>
    <li class=fragment data-fragment-index="1">Dont do this</li>
    <li class=fragment data-fragment-index="2">Or this</li>
  </ul>
</section>
```

It isn't possible to include fragments inside of the code itself if that is what you were asking. To have the code change, you'll need to use auto-animate.

**Comment by maxpel** [comment]
> Is there an obvious way to do this from Markdown (other than just inserting the HTML)?
> 
> ```
> ```js[1|2]
> var x = 1
> var y = 2
> ```
> 
> ```
> 
> Puts the data-fragment-index on the `\<pre\>` tag, while it's needed on the `<code>` tag.

I arrived at the same issue with no solution yet for me.

**Comment by xxthunder** [comment]
Same for me. Would love to use this in markdown, too.

**Comment by unphased** [comment]
It's trivial to do this from markdown by shoving the pre code html into your markdown. 

The real issue with this is although you can synchronize bullets with the line reveal fragment indices, the data-notes is bugged and won't show up in speaker notes view.

**Comment by unphased** [comment]
My parenthesized idea totally works, which confirms the data-notes retrieval for speaker notes is done by first DOM element (likely down to how a selector is used to fetch the attribute). 

```
<span class="fragment" data-fragment-index="1" data-notes="frag 1 notes"></span>
<span class="fragment" data-fragment-index="2" data-notes="frag 2 notes"></span>
<span class="fragment" data-fragment-index="3" data-notes="frag 3 notes"></span>

<pre><code class="highlight cpp" data-fragment-index="1" data-line-numbers="1-99|2|4-16">
... code here ...
```

It *totally* works.
