### ISSUE TITLE
GUI Editor

### ISSUE THREAD

**Issue by philipbjorge** [hakimel/reveal.js#31]
Do you have any preliminary work done on a GUI editor?

**Comment by ruby232** [comment]
I am creating a open source version of slides.com, you can see the code in [slide.me](https://github.com/ruby232/slideme)

**Comment by saietha** [comment]
I am looking for GUI editor to host on our server to create online presentations any help is appreciated, if any one of you ready to help let me know

**Comment by oceatoon** [comment]
great project 
we integrated it into our social network communecter.org 
and would love to give users the freedom to build there own slides themselves with an editor 
has it been opensourced since ? is there maybe a light version which is open ?
