### ISSUE TITLE
Scale presentations to always fit within window bounds

### ISSUE THREAD

**Issue by hakimel** [hakimel/reveal.js#310]
Try moving reveal.js away from the current dynamic width layout using media queries to a solution that scales the presentation to always fit within the window dimensions. The "normal" size – the size at which the presentation was authored – should ideally be a config option.

Replaces #309 
See #304 for example implementation

**Comment by didibus** [comment]
How do you use this? My text overflows, and I'd like its size to shrink to fit.

**Comment by NicolasWebDev** [comment]
I am currently having the same problem, with my images and my text overflowing from the `<div class="slides">`.

**Comment by G1305** [comment]
how to fix it? please HELP
![image](https://user-images.githubusercontent.com/34474564/34094277-f4f9e802-e3e5-11e7-85e9-001a0259d2e0.png)
desktop browser works fine, but I want full height for mobile browsers... 
@hakimel @aseemk 
I hope this is very important issue for everyone
