### ISSUE TITLE
Slide: allow async call in `beforeslidechange` listeners

### ISSUE THREAD

**Issue by tobiasBora** [hakimel/reveal.js#3114]
In order to solve this issue https://github.com/hakimel/reveal.js/issues/3107, I need to do a call in the `beforeslidechange` listener to an async function, basically to ensure that the video seek is completed (otherwise it produces ugly glitches) before the slide is actually changed (depending on how you arive on the slide, you want to see different frames).

Unfortunately, as explained [here](https://stackoverflow.com/questions/70767676/await-dispatchevent-how-to-listen-synchronously-to-a-dispatchevent-when-listene/70768474?noredirect=1#comment125108561_70768474), I need to change `dispatchEvent` into a new async function (say `awaitDispatchEvent`) function, which also forces `slide` to be async.

Would you allow a PR that make `slide` async?  Or maybe should we create a new async version of `slide` and deprecate the non-async one? (I'm not sure how to limit potential backward incompatibilities)

**Comment by hakimel** [comment]
Hey. You can prevent slide navigation by calling `preventDefault` on the `beforeslidechange` event. Here's an example that conditionally carries out async work before proceeding to the next slide.

```js
Reveal.on( 'beforeslidechange', async ( event ) => {
  const nextSlide = Reveal.getSlide( event.indexh, event.indexv );

  // Check if we need to do async work
  if( !nextSlide.classList.contains( 'has-done-async-work' ) ) {
    // Prevent the slide navigation
    event.preventDefault();

    // Carry out our async work
    await new Promise( resolve => setTimeout( resolve, 1000 ) );

    // Indicate that the async work is completed for this slide
    nextSlide.classList.add( 'has-done-async-work' );

    // Resume the slide navigation
    Reveal.slide( event.indexh, event.indexv, event.indexf );
  }
  // else, reveal.js carries out the slide change
} );
```

**Comment by tobiasBora** [comment]
Thanks. I was thinking about something like that, but I was afraid to 
break some codes (potentially in external plugins) that would do 
something after the slide transition.
