### ISSUE TITLE
Ability to display "percent completed" instead of slide number

### ISSUE THREAD

**Issue by tammersaleh** [hakimel/reveal.js#3118]
Instead of having `1/5` or similar as the slide number indicator in the lower right-hand corner of the slides, I'd like to see the progress as a percent (`20%`).  This would really help me with timing on larger presentations with hundreds of slides.  

I don't _think_ this is possible with the `progress:` configuration option, unless we can use a custom function that returns not just the slide number (as described in the docs), but instead an arbitrary string?

> ``` js
>   progress: true,
> 
>   // Display the page number of the current slide
>   // - true:    Show slide number
>   // - false:   Hide slide number
>   //
>   // Can optionally be set as a string that specifies the number formatting:
>   // - "h.v":   Horizontal . vertical slide number (default)
>   // - "h/v":   Horizontal / vertical slide number
>   // - "c":   Flattened slide number
>   // - "c/t":   Flattened slide number / total slides
>   //
>   // Alternatively, you can provide a function that returns the slide
>   // number for the current slide. The function should take in a slide
>   // object and return an array with one string [slideNumber] or
>   // three strings [n1,delimiter,n2]. See #formatSlideNumber().
> ```

**Comment by hakimel** [comment]
Hey, this configuration turns the slide number into a progress indicator:

```js
Reveal.initialize({
  slideNumber: () => [ Math.round( Reveal.getProgress() * 100 ) + '%' ]
});
```

**Comment by tammersaleh** [comment]
Thank you so much!
