### ISSUE TITLE
Format speaker notes

### ISSUE THREAD

**Issue by tammersaleh** [hakimel/reveal.js#3119]
Is it possible to apply custom CSS to the speaker notes?

related to #2824

**Comment by hakimel** [comment]
All of the speaker view styles can be customized here: https://github.com/hakimel/reveal.js/blob/master/plugin/notes/speaker-view.html

After making changes you will need to rebuild the plugins by running `gulp plugins`. That build is slow but I'm hoping to improve that soon :)

**Comment by jhpratt** [comment]
It would be great if this was supported via a CSS file, just as formatting the actual slides is.
