### ISSUE TITLE
isAutoSliding() always returns false

### ISSUE THREAD

**Issue by studiolxv** [hakimel/reveal.js#3129]
Using 4.2.1 - Trying to bind "P" to toggle autoslide.

USER STORY:  Press "P" to pause autoslide, "P" again to start again.

 "isAutoSliding()" seems to not be doing what I expect it should. Am I missing something?

```
showcase.configure({
	keyboard: {
		80: () => { // P: Toggle autoplay
			if (showcase.isAutoSliding() !== true) {
				console.log(showcase.isAutoSliding()); // always showing false
				showcase.toggleAutoSlide(true); // not actually toggling - just restarts the slide timer
			} else {
				console.log(showcase.isAutoSliding()); // always showing false - shouldn't this be true?
				showcase.toggleAutoSlide(false);
			}
		}
	}
});
```

**Comment by hakimel** [comment]
reveal.js automatically pauses auto-sliding when the user interacts with the page (including via keyboard input). This means that auto-slide is always paused right before your custom keyboard event is triggered.

You can get around this by adding your own `keydown` listener preventing reveal.js' key handling.

```js
document.addEventListener( 'keydown', event => {
  if(event.key === 'p') {
    event.stopImmediatePropagation();
    Reveal.toggleAutoSlide();
  }
} );
```
