### ISSUE TITLE
Incorrect slide numbering when printing to PDF

### ISSUE THREAD

**Issue by csiegl182** [hakimel/reveal.js#3133]
The slide numbering is incorrect when printing to PDF. It starts with two and inserts and increments by two on a horizontal slide transition. Moreover, the numbering format (slideNumber property) is not evaluated when generating the PDF output.

**Comment by chivongv** [comment]
What browser were you using when printing to PDF? According to [the docs on PDF export](https://revealjs.com/pdf-export/), the feature has only been confirmed to work in Google Chrome and Chromium.

**Comment by csiegl182** [comment]
I am using Chrome. However, I think the issue is obvious.

Regarding the 4.3.1 tag:

In line 151 the index of the slide iteration is used for the slideNumber value. The index is not the right measuere since it increments by two on a horizontal slide change. I my personal fork I use a separate variable for slide number and increment it individually. This works fine.

Moreover, the slideNumber property needs to be considered somehow in the if-statement of line 150.

**Comment by hakimel** [comment]
This should be fixed as of https://github.com/hakimel/reveal.js/pull/3182

We don't support custom formatting of page numbers when printing.
