### ISSUE TITLE
Safari gets stuck when keyboarding through slides in Speaker view

### ISSUE THREAD

**Issue by dabrahams** [hakimel/reveal.js#3147]
Go to the reveal.js demo presentation and hit the `S` key to bring up the speaker notes.  Then go forward and backward through the slides quickly (I just hold down space/shift-space and let key repeat do the work) with the speaker notes frontmost.  At some point you will get stuck on a slide and be unable to escape it without focusing on the audience slide window.  On my Mac, this happens in Safari but not in Chrome.

**Comment by hakimel** [comment]
Looks like this is causing a security error in Safari. Will look into throttling navigations.
```
SecurityError: Attempt to use history.replaceState() more than 100 times per 30 seconds
```

**Comment by hakimel** [comment]
This has been fixed by throttling the rate at which the notes window tries to update the main presentation.
