### ISSUE TITLE
note plugin: Unexpected token o in JSON at position 1

### ISSUE THREAD

**Issue by Mister-Hope** [hakimel/reveal.js#3154]
https://github.com/hakimel/reveal.js/blob/37861335a225a3cc9f67e98977aceda3c2a9eca9/plugin/notes/plugin.js#L201-L212

These lines are every UNRESONABLE, because window message event is not revealjs ifself.

I am not sure if you heard an extension called wappalyzer

![image](https://user-images.githubusercontent.com/33315834/158174919-4b2f2b75-5bd8-4352-8085-38cc6de35460.png)

It will trigger that event handler.

![image](https://user-images.githubusercontent.com/33315834/158175051-f293e3bb-cc42-4e60-a5c8-5903f0cfc2b0.png)

Also, there are other project like giscus, are using the message event listener either.

Reveal.js Note plugin should never make sure that `event.data` is a string, and it can be successfuly `JSON.parse`.

You probably need to add a `try {} catch {}` block, and make extra check before rudely  `JSON.parse` it.

**Comment by Mister-Hope** [comment]
Here is a reproduciton link, and the console is just like a mess.

**Comment by Mister-Hope** [comment]
Any update for this one? As fixing this should be easy.

**Comment by hakimel** [comment]
Thanks for the feedback—this has been fixed.
