### ISSUE TITLE
Safari 15.4 backface bug

### ISSUE THREAD

**Issue by Martinomagnifico** [hakimel/reveal.js#3164]
Safari 15.4 dropped prefixes for backface-visibility. That might be the cause of the fact that slides that should be hidden in 3D-space are still shown. 

Browser: 
* Safari 15.4 on desktop (Monterey, Big Sur and Catalina)
* Safari 15.4 on mobile (included with the latest iOS 15.4)

Example:
https://codepen.io/martino/pen/rNpLVmE

Go back and forth a bit: hidden slides pop up again. It seems to happen only before and after the second section, which has nested sections.

It happens in the main Reveal slider as well, when you switch it to ‘convex’.

**Comment by Martinomagnifico** [comment]
Would like to know if any other Safari 15.4 user sees the same thing.

**Comment by hakimel** [comment]
I don't have Safari 15.4 installed yet but will test this out as soon as I have.

15.2 and 15.3 both run your example without issues.

**Comment by mrolli** [comment]
I can confirm the exact behaviour that you are describing on Safari 15.4. The last displayed slide from the stack of section two is reappearing on changing to "one", "three" and "four", but never on five.

**Comment by Martinomagnifico** [comment]
Hi Michael, vielen Dank! I'm still not sure what causes the behaviour, I don't see it with a simple cube on codepen (using that same Safari), although that does not have nested cubes. For now I changed every 'convex' to 'slide' in my plugins.

**Comment by Martinomagnifico** [comment]
The problem (using 'convex') is still in the latest Safari: https://codepen.io/martino/pen/rNpLVmE?editors=0110 , use SPACE to go through the presentation, so that vertical slides are also viewed.

The solution as showed above still works.

**Comment by hakimel** [comment]
Thanks @Martinomagnifico! I've added your fix.

I still don't understand how those slide remained visible even though I could clearly inspect and see that their direct parent (`secion.stack`) was set to `opacity: 0` 🤷‍♂️

**Comment by Martinomagnifico** [comment]
Hi Hakim, I don’t understand it either. It might be a browser paint issue, because the CSS seemed right. Anyway, thanks for the fix!
