### ISSUE TITLE
Force use of scale() instead of zoom()

### ISSUE THREAD

**Issue by LBrodersen** [hakimel/reveal.js#3208]
I'm having an issue with the zoom() function in my presentation. It messes with the mouse positioning of plotly graphs. Since I asked about that issue elsewhere abd the pointed to the zoom-function, I'm redirecting that issue to this project (original post  https://github.com/plotly/plotly.js/issues/6169) 

While the scale()-functions keeps the position correct, zoom() distorts it. Since the scale()-variant seems to work as well for factors larger than 1, it might be possible to use it instead. Is there a Config-option to force the usage? Or could it be implemented in the next release?

I've found other people, wo requested a functionalitly like this before, so I'm wondering if it already exists.
https://github.com/hakimel/reveal.js/issues/1490#issuecomment-273419046

Currently the only workaround I can think of is setting maxScale to 1 and using a very large  default resolution. Maybe there are better ways?

**Comment by cderv** [comment]
I believe the use of zoom has been removed in https://github.com/hakimel/reveal.js/commit/e281b3234e7991283ce4dcca705dd9a6a9ebe5d2 which is in master and not released already. 

Just saw that as I am looking to this also

**Comment by Martinomagnifico** [comment]
This is now in release 4.4.0, so we'll close this issue.

**Comment by sadikyalcin** [comment]
If you've got an issue with iframes not scaling properly on `specific` monitors / resolutions, this change will fix your issue. For some weird reason, `zoom` on iframes do not work on `specific` resolutions.
