### ISSUE TITLE
Add Code Titles

### ISSUE THREAD

**Issue by hmajid2301** [hakimel/reveal.js#3227]
Is there an easy way we can include the title of a file of a code block such as:

![image](https://user-images.githubusercontent.com/998807/173193693-6807d6d4-005e-4e74-927c-03f0158710c0.png)

**Comment by Martinomagnifico** [comment]
Just add the title as a span inside your pre, before the code. Then it will inherit the code font. Add some styling like this:

```
pre span.title {
	display: inline-block;
	width: 100%;
	text-align: center;
	padding-bottom: 0.5em;
	border-bottom: 1px solid rgba(255, 255, 255, .5);
}
```
