### ISSUE TITLE
Get MathJax to work 

### ISSUE THREAD

**Issue by twenty-seven-pockets** [hakimel/reveal.js#3229]
```
`\[ J(\theta_0,\theta_1) = \sum_{i=0} \]` #TODO
```

https://github.com/twenty-seven-pockets/reveal.js_skeleton/blob/d04fa187fdd80535fbbb85746367a041b95b8c15/slides/example.md#L37

**Comment by rajasegar** [comment]
@twenty-seven-pockets It is working, you need to add the `math` plugin to your index.html
Looks like you have commented it, did you check with running a local server?

**Comment by twenty-seven-pockets** [comment]
Yeah, I messed up with github, this was meant as a private issue. 
I'll close the issue since I'm not actively seeking support here.

Thanks for replying nonetheless.
