### ISSUE TITLE
link hash for ref inside a slide does not work

### ISSUE THREAD

**Issue by maurerle** [hakimel/reveal.js#3231]
Coming from https://github.com/jgm/pandoc/issues/8136 I found that the issue with `link-citations` comes from reveal.js as they are not resolving a link to content on a slide `id="ref-mycitation"`.

I understand that it is great and consistent behavior to have the current slide id in the url, yet it would be great to also be able to link to content on a slide and not only to slides.

Do you think that this would be possible or is it something which won't be implemented in reveal.js and pandoc should handle this correclty (create a link to the #references page instead of to the citation)?

Thanks a lot!

**Comment by maurerle** [comment]
A way to solve this for mathjax equations is shown here by finding the nearest section id: https://github.com/hakimel/reveal.js/issues/2222#issuecomment-1258980254

But this issue is quite different. It seems that linking to a ref inside a top level slide works fine, but does not work on a nested/vertical slide:

For example this slide:

```html
<section id="references" class="title-slide slide level2 unnumbered">
<h2 class="unnumbered">References</h2>
<div id="refs" class="references csl-bib-body" role="list">
<div id="ref-myref"
class="csl-entry" role="listitem">
<div class="csl-left-margin">[1] </div><div
class="csl-right-inline">My Bib Ref [Online]. [Accessed: 15-Apr-2022].</div>
</div>
</div>
</section>
```

does not work when referencing `#/ref-myref`

Is there a reason why resolving href hash refs is limited to the first 2 levels?

**Comment by t-fritsch** [comment]
I think that nested ids inside slides is not supported by reveal and the fact that the second level ids (`#/refs`) are working seems like not a feature but a bug 😅 

The code responsible for this "feature/bug" seems to be in the function `getIndices()` which uses `slide.parentNode` (either [here](https://github.com/hakimel/reveal.js/blob/master/js/reveal.js#L2005) or [here](https://github.com/hakimel/reveal.js/blob/master/js/reveal.js#L1992) ).

Anyway the fix to make this work for every nested element that has an `id` attribute (no matter how deep it is in the slide tree) seems quite simple. 

I've made a test in my local version that seems to work. I'll submit a PR. 👍
