### ISSUE TITLE
The packaged code contains... Expansion symbol which es6 supported

### ISSUE THREAD

**Issue by dongshuangshuang** [hakimel/reveal.js#3233]
... is not supported in some low performance devices，can transform ... to compatible these devices？

**Comment by Martinomagnifico** [comment]
The file `reveal.js` is run through Babel, and supports many older browsers. It is true that the other JS file, `reveal.esm.js`, uses this spread operator (…), but if you want to make a reveal presentation for older browsers, simply use the former file instead of the latter.

**Comment by dongshuangshuang** [comment]
您好，我是董双双，你的邮件已收到，我会尽快给您回复。
