### ISSUE TITLE
how can I hide the right navigation arrow on a specific slide? 

### ISSUE THREAD

**Issue by Jonathanmg1415** [hakimel/reveal.js#3245]
![image](https://user-images.githubusercontent.com/53263709/179069891-94bbeb08-5eac-449a-beaf-62cc005caa13.png)
I need for example to hide the arrow on the right and have only the down arrow left.

**Comment by Martinomagnifico** [comment]
Try this:

```
<section data-state="norightarrow">
        Content
</section>
```

and in CSS:
```
.norightarrow .controls .navigate-right {
	display: none;
}
```

I think this issue can be closed/

**Comment by Jonathanmg1415** [comment]
Yeah, thats so Good !!
