### ISSUE TITLE
Override CSP for embedded websites in iframe?

### ISSUE THREAD

**Issue by Franky1** [hakimel/reveal.js#3247]
I tried to embed a website in a reveal.js presentation as `iframe` or `data-background-iframe`. 
My goal is not to leave the presentation every time i show a website as an example.
However lots of websites seems to have some CSP (or similar) enabled, therefore i cannot embed most of the websites at all, which is quite annyoing.
Is there any solution to this?

**Comment by Martinomagnifico** [comment]
There sadly is no solution for this. For presentation reasons, you might want to try to save copies of those websites, and host them locally, but that will be a lot of work. Because this is an issue with `iframe`s and CSP headers in general, and not of Reveal.js, I'll close this issue.
