### ISSUE TITLE
Align pandas data frame output when creating Reveal slides from a Jupyter notebook

### ISSUE THREAD

**Issue by brad-stephen-shaw** [hakimel/reveal.js#3266]
Hi,

I'm looking for some help with aligning some data frame output; apologies if this is a silly question - I'm only familiar with Python.

**Context:**
I'm working with Python in a Jupyter notebook. I would like to display a `pandas` DataFrame in my `reveal.js` slides. Code for the DataFrame:

```
x = pd.DataFrame({'Year':[2019,2020,2021,2022],'Amount':[100,120,130,140]})
x
```

When I convert the notebook to slides, I get the following output:

![image](https://user-images.githubusercontent.com/86197511/187076746-12f558e4-1ce0-43e2-b63e-0c5ccc0d406a.png)

**Question:**
Can you please advise on how I can align the table output with the text?

**Comment by kolibril13** [comment]
You can open the HTML file that contains the revealjs content and then align the `div`element that contains the data frame like this: https://www.w3schools.com/css/css_align.asp
It's probably a good idea when you also read some HTML and CSS tutorials, I can recommend https://www.w3schools.com/html/default.asp

**Comment by brad-stephen-shaw** [comment]
Thank you!
