### ISSUE TITLE
Only the first "notes" class element of each slide shows up in the speaker view

### ISSUE THREAD

**Issue by TS-CUBED** [hakimel/reveal.js#3269]
I write my lecture notes and presentations using Reveal.js (well, I use org-mode or Quarto for the actual writing, but that should not be a problem, since the resulting HTML code has the right notes in it).

One nice feature is that I can define multiple "notes" sections in the Org-Mode/Markdown, which do not show up on the slides, but do show up on the HTML (as a website) or PDF export. That way can generate handouts and presentation from the same file.

The Markdown file looks like:

```md
## Note test

::: {.notes}
Some notes
:::

Some slide text

::: {.notes}
and some more notes
:::

## References
```

which is exported to Reveal.js HTML as:

```html
<section id="note-test" class="slide level2 center">
<h2>Note test</h2>
<aside class="notes">
<p>Some notes</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<p>Some slide text</p>
<aside class="notes">
<p>and some more notes</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
```

Which means that the two notes sections both get exported.

However, when I switch to Speaker Mode only the first note section on each slide is visible.

__Is it possible to make Speaker Mode collect all the notes sections on the slide?__

The Speaker Mode frame only has:

```
Notes

Some notes
```
in it. So it does not show the second notes div. I guess the parser just stops when it has found the first notes div.

It does work as expected with HTML and PDF (via PanDoc and LaTeX) where I get the notes interspersed with the slide text to get the handouts. The HTML code still has "notes" divs, but the browser simply ignores the "notes" class (no CSS for it, I assume).

```html
<section id="note-test" class="level2">
<h2 class="anchored" data-anchor-id="note-test">Note test</h2>
<div class="notes">
<p>Some notes</p>
</div>
<p>Some slide text</p>
<div class="notes">
<p>and some more notes</p>
</div>
</section>
```

**Comment by lechten** [comment]
I suggested PR #3010, which may work for you.

**Comment by TS-CUBED** [comment]
Thanks, I thought it might just be a mixing loop somewhere.

This does look straightforward enough. Any idea why this is not merged?

Will need to see if I can include that locally.
________________________________

**Comment by lechten** [comment]
I did not receive feedback on that PR, so I do not know where maintainers might want to go...

**Comment by hakimel** [comment]
Sorry about the slow reply and thanks for the PR.

I just tested and merged your changes so this issue has been resolved.

**Comment by lechten** [comment]
Many thanks!

**Comment by TS-CUBED** [comment]
Awesome. Thanks for the great work on reveal.js


________________________________
