### ISSUE TITLE
cannot change slide in any iPhone Browser when playing a background video 

### ISSUE THREAD

**Issue by mcski** [hakimel/reveal.js#3302]
Please open the demo with a recent high resolution apple iPhone
in the reveal demo, there is a slide with a background video
section data-background-video="https://static.slid.es/site/homepage/v1/homepage-video-editor.mp4" data-background-color="#000000"
inside the demo, on the video-background slide, try to swipe to next/previous slide.

most of the times, I get no response and stuck on the video background slide. 
swipe to next or previous slide is very tough,  sometimes it works but most of the times not.
chances are  you get stuck in the slide. 
inside a browser web page,  there is no keyboard so no spacebar nor arrows keys available.

the problem is accentuated by small navigational arrows.
On recent small screen iPhones have very high screen resolution wich makes navigation arrows very small.  
you get lucky if your finger can hit the arrow, most times you will miss target.

It might not be a bug, but there is an issue here,  frustration because it does not work well on an iPhone browser

this feature can be observed and repeated on an iPhone SE latest IOS 15.6 with firefox and brave browsers

**Comment by hakimel** [comment]
This has been fixed, see #3584 3584
