### ISSUE TITLE
How can I re-render the slides automatically according to the real-time markdown input?

### ISSUE THREAD

**Issue by Sleepybear32e** [hakimel/reveal.js#3314]
I want to implement a real-time markdown editor and convert it to slides using the built-in markdown plugin, but it seems there is no API for re-rendering/updating slides after it is initialized. Is there a way for achieving it ?

Here is my code, I use react, mkd is the markdown input, but changes in mkd doesn't result changes in slides. Many thanks for answering.
```
<div className="reveal">
    <div className="slides">
         <section data-markdown="">
              <script type="text/template">
                    {mkd}
               </script>
           </section>
      </div>
</div>
```

**Comment by Riezmann** [comment]
I am having the same question, do you remember how to do this?
