### ISSUE TITLE
Numbering equations not produced by mathjax3.js plugin

### ISSUE THREAD

**Issue by wesszabo** [hakimel/reveal.js#3327]
I added the option   tags: 'ams'   in mathjax3.js, see below

export const MathJax3 = () => {

    // The reveal.js instance this plugin is attached to
    let deck;

    let defaultOptions = {
        tex: {
            inlineMath: [ [ '$', '$' ], [ '\\(', '\\)' ]  ],
            tags: 'ams'
        },
        options: {
            skipHtmlTags: [ 'script', 'noscript', 'style', 'textarea', 'pre' ]
        },
        startup: {
            ready: () => {
                MathJax.startup.defaultReady();
                MathJax.startup.promise.then(() => {
                    Reveal.layout();
                });
            }
        }
    };

    function loadScript( url, callback ) {

        let script = document.createElement( 'script' );
        script.type = "text/javascript"
        script.id = "MathJax-script"
        script.src = url;
        script.async = true

        // Wrapper for callback to make sure it only fires once
        script.onload = () => {
            if (typeof callback === 'function') {
                callback.call();
                callback = null;
            }
        };

        document.head.appendChild( script );

    }

    return {
        id: 'mathjax3',
        init: function(reveal) {

            deck = reveal;

            let revealOptions = deck.getConfig().mathjax3 || {};
            let options = {...defaultOptions, ...revealOptions};
            options.tex = {...defaultOptions.tex, ...revealOptions.tex}
            options.options = {...defaultOptions.options, ...revealOptions.options}
            options.startup = {...defaultOptions.startup, ...revealOptions.startup}

            let url = options.mathjax || 'https://cdn.jsdelivr.net/npm/mathjax@3.2.0/tex-mml-chtml.js';
            options.mathjax = null;

            window.MathJax = options;

            loadScript( url, function() {
                // Reprocess equations in slides when they turn visible
                Reveal.addEventListener( 'slidechanged', function( event ) {
                    MathJax.typeset();
                } );
            } );

        }
    }

};

but the equation is not numbered. The default is not numbering. Below is the html file

<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

        <title>Inequalities for trigonometric sums</title>

        <link rel="stylesheet" href="dist/reset.css">
        <link rel="stylesheet" href="dist/reveal.css">
        <link rel="stylesheet" href="dist/theme/solarized.css">
        <link rel="stylesheet" href="css/beamerkiller/beamerkiller.css" id="theme">

        
        <link rel="stylesheet" href="plugin/highlight/monokai.css">
       
    </head>
    <body>

        <div class="reveal">
            <div class="slides">        
                <section>
                     <h3 style="color: #0080ff;">Introduction</h3>
                      <p class="fragment" style="color: black;">
                       Inequalities
                       for trigonometric sums
                       have many applications in approximation
                       theory, special functions theory. The classical one is
                       </p>
                      <p class="fragment" style="color: red;">
                      $$
                       \begin{equation}\label{eq:Snx}
                        S_n(x)=\sum_{k=1}^n \frac{\sin(kx)}{k} \gt 0\quad
                        (n\geq 1,\quad 0 \lt x \lt \pi).
                        \end{equation}
                      $$
                      </p>
                      <p class="fragment" style="color: black;">
                      The validity was conjectured by
                      Fejér in 1910 and proved one year later by Jackson. Many
                      refinements, generalization can be found in the literature.
                      </p>
                </section>
                </div>
        </div>
       

        <script src="dist/reveal.js"></script>
        <script src="plugin/notes/notes.js"></script>      
        <script src="plugin/markdown/markdown.js"></script>
        <script src="plugin/highlight/highlight.js"></script>
        <script src="plugin/math/math.js"></script>
        <script src="plugin/reveald3/reveald3.js"></script>
        <script>
            // More info about initialization & config:
            // - https://revealjs.com/initialization/
            // - https://revealjs.com/config/
            Reveal.initialize({
                hash: true,
                center: false,
                slideNumber: 'c/t',
               
                // Learn about plugins: https://revealjs.com/plugins/
                plugins: [ RevealMarkdown, RevealHighlight, RevealNotes,
                RevealMath.MathJax3, Reveald3    ],
               
            });
        </script>
    </body>
</html>

**Comment by Martinomagnifico** [comment]
This will number them:

```
Reveal.initialize({
	history: true,
	overview: false,
	width: 960,
	height: 720,
	center: true,
	controlsTutorial: false,
	transition: "slide",
	plugins: [ RevealMarkdown, RevealHighlight, RevealNotes, RevealMath.MathJax3, Reveald3 ],
	mathjax3: {
		mathjax: 'assets/libs/mathjax/es5/tex-mml-chtml.js',
		tex: {
			inlineMath: [ [ '$', '$' ], [ '\\(', '\\)' ]  ],
			tags: 'ams'
		},
		options: {
			skipHtmlTags: [ 'script', 'noscript', 'style', 'textarea', 'pre' ]
		},
		startup: {
			ready: () => {
				MathJax.startup.defaultReady();
				MathJax.startup.promise.then(() => {
					Reveal.layout();
				});
			}
		}
	}
});
```
