### ISSUE TITLE
Cannot disable progress bar or presentation control arrows via /js/config.js

### ISSUE THREAD

**Issue by its-thomas** [hakimel/reveal.js#3331]
Hi there!

This might seem a bit naive to post, but I am pretty sure that with the latest RevealJS 4.4.0, you cannot disable the progress bar nor the presentation control arrows via the /js/config.js file.

I have just tried it again on a newly downloaded instance of RevealJS 4.4.0 and set

`controls: false,`

as well as

`progress: false,`

but neither unaltered index.html nor demo.html are affected by it: it still shows both the progress bar as well as the presentation control arrows.

**My system:**

- Debian 11 (stable)
- Tested with Firefox 102.5.0esr (64-Bit) and Opera v.93.0.4585.21

I hope somebody can reproduce this issue. Otherwise, I must have made some stupid mistake ...

Thanks so much
Thomas

**Comment by its-thomas** [comment]
OK, I feel like I can reopen this issue just to clarify some things ...

I have excluded `controls` as well as `progress` from `Reveal.initialize({});` from my HTML-presentation file, which means they are not set there. Shouldn't RevealJS then fall back onto the values in the /js/config.js-file? After all, this is titled as "The default reveal.js config object".

Well, in the /js/config.js file, both parameters are set to false, yet in my HTML-presentation file where these parameters are not set at all, both the progress bar and presentation control arrows are displayed.

Can somebody reproduce this issue?

Sorry for any inconvienience!

**Comment by Martinomagnifico** [comment]
Hi Thomas,
Are you trying to build a new /custom reveal.js file inside which these settings are turned off? That is what the js/config.js is for: it is used during the build phase as an import to actually create the main reveal.js file. It is not read or used by the browser.

If not, are you running with the standard dist/reveal.js file?
In that last case, the settings are on by default and can only be turned off from within the initialize function.

**Comment by its-thomas** [comment]
Thanks for pointing that out, @Martinomagnifico!

As I am running with the standard dist/reveal.js file, I will stick to enabling / disabling those parameters via `Reveal.initialize({});` within my HTML-presentation file.
