### ISSUE TITLE
Suggestion: Lazyloading (viewDistance configuration option) not just for slides, but for fragments also

### ISSUE THREAD

**Issue by its-thomas** [hakimel/reveal.js#3332]
Hi there!

I would love to be able to lazyload not just whole slides (as is already possible via the viewDistance configuration option), but single fragments also. To understand why, let me share the following experience:

I had inserted an eye-catching CSS animation on my third slide, which was (in theory) supposed to run one time without any delay when the third slide was displayed. In reality though, the CSS animation was already running as soon as the first slide was displayed and by the time the third slide was displayed, the CSS animation had already finished and one was seeing only the final static content.

The solution here was of course to set `viewDistance: 1,` (standard value is 3) within `Reveal.initialize({})`. Now the CSS animation works as intended and starts one time without delay as soon as the third slide is displayed (and not earlier).

So imagine the creative potential one could realize (with for example CSS animations), when this lazyloading option would not just be available for whole slides, but for single fragments also ... 🔥

Or did I miss something and this is already possible for single fragments as well? Maybe a work-around, somebody has created successfully?

Looking forward to any input!

Thanks so much,
Thomas

**Comment by Martinomagnifico** [comment]
Hi Thomas,

A much easier solution would be to only run it when the slide is 'present'. The same goes for fragments, they get a class of 'visible' and 'current-fragment'. Choose which one you prefer there.

```
@keyframes example {
	from {background-color: red;}
	to {background-color: yellow;}
}
section.present .test {
	width: 100px;
	height: 100px;
	background-color: red;
	animation-name: example;
	animation-duration: 4s;
	animation-fill-mode: forwards;
}
```

**Comment by its-thomas** [comment]
Thanks so much, @Martinomagnifico!

All three classes you mentioned, do the trick they are supposed to do and it is indeed an easier, more to-the-point solution.

So, I guess I can close this issue, because I personally don't need lazyloading for fragments anymore 😉

Still, it would be great to have those available classes in the official RevealJS documentation, which to the best of my knowledge, they are not. Using the revealjs.com search field, there's not a single hit for "current-fragment". But there is a mentioning of the class "current-visible" for fragments on [https://revealjs.com/layout/](https://revealjs.com/layout/), which I have not tried out yet ...
