### ISSUE TITLE
Slide number mistake?

### ISSUE THREAD

**Issue by jonaswer** [hakimel/reveal.js#3337]
![double_icon](https://user-images.githubusercontent.com/65494730/207285740-5c9182e9-eca7-48d2-9bfb-fe4e88ee8333.png)

Is there a way to get away from the slightly visible number under the number? It seems like the page number is shown twice

**Comment by Martinomagnifico** [comment]
Hi Jonas, can you send us a minimum example of a presentation where you see this issue?

**Comment by Martinomagnifico** [comment]
Hi Jonas, the main problem on that page is that it initializes Reveal.js THREE times. That means there are 3 sets of _controls_ stacked on top of eachother, 3 sets of _slidenumbers_ and 3 sets of _progress bars_. Start to fix that first, then check the output of the console to see more errors.

**Comment by Martinomagnifico** [comment]
Closing the issue, as it is not a Reveal.js issue.
