### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by grico95** [hakimel/reveal.js#3341]
Hi,

First of all thumbs up for this awesome tool !
I am using the zip archive and directly modifying the index.html in VSCode. It works great but sometimes it does not want to do what I want it to do.
Sometimes this is due to mistakes in img names,  sometimes for something else.

Is there a way to debug the presentation (I know F12 but it does not warn me for example in case of missing file)?

I have been crawling the web but surprisingly found nothing about this topic and it may be obvious. Sorry if it is indeed !

Thanks in advance

_Originally posted by @Ca-ressemble-a-du-fake in https://github.com/hakimel/reveal.js/discussions/3306_

**Comment by Martinomagnifico** [comment]
Hi Genaro, there is no specific debug mode in Reveal.js. Opening the console of the browser will show you if there are any missing files or images.
