### ISSUE TITLE
[Bug] Importing reveal js called print style breaking

### ISSUE THREAD

**Issue by Mister-Hope** [hakimel/reveal.js#3348]
This is caused by https://github.com/hakimel/reveal.js/blob/master/css/print/paper.scss

Even if I embed reveal.js in a page, it will override ALL THE BASIC ELEMENTS with `!important`, e.g.: 

https://github.com/hakimel/reveal.js/blob/4fe3946cb43de57f79aaa7b646aee7e78f4bcc75/css/print/paper.scss#L8-L9

https://github.com/hakimel/reveal.js/blob/4fe3946cb43de57f79aaa7b646aee7e78f4bcc75/css/print/paper.scss#L39-L58

This means that output will have

```
@media print {
  html:not(.print-pdf) body {
      font-size: 20pt!important;
  }

  html:not(.print-pdf) h1 { 
    font-size: 28pt !important;
   }
}
```

So a normal page without reveal js like this:

<img width="399" alt="image" src="https://user-images.githubusercontent.com/33315834/211197125-2af644c5-fde6-4dec-8ece-b3c75bf03677.png">

Becomes like this just because reveal style is imported:

<img width="401" alt="image" src="https://user-images.githubusercontent.com/33315834/211197019-bb0aec50-e509-4590-8935-920d4a4bfc4c.png">

(I embed a reveal.js in page:)

<img width="607" alt="image" src="https://user-images.githubusercontent.com/33315834/211197140-82e888b3-629a-4bd9-beaa-8b9545fca695.png">

---

My confusion is why is that file needed as users are already asked to print with `?print-pdf`?

Also does anyone have the same confusion with me why reveal.js tries and why it should use high priority selectors and `!important` to force overriding default tag style?

**Comment by Mister-Hope** [comment]
I debug this for nearly 80mins to find out why style is breaking then I found out it's reveal's problem, that hurts beacuse it's really hard to debug with `@print` selectors as I can not debug them in devtools.

**Comment by Mister-Hope** [comment]
HI @hakimel Could you check this issue? I would like to send prs to fix, but I need to know:

> why reveal.js tries and why it should use high priority selectors and !important to force overriding default tag style?

And whether it's ok for me to remove these styles or limit inside `.reveal` class

**Comment by hakimel** [comment]
Thanks for pointing this out. Definitely not desirable that the print styles bleed into the rest of the page.

I've revised this now so that all print styles are scoped to .reveal. The only styles that are still set on the html level are required to ensure overflow is visible otherwise printing won't work.

**Comment by Mister-Hope** [comment]
Hi, can we release a new version? @hakimel
