### ISSUE TITLE
RevealHighlight plugin is not being recognized (tried on Stackoverflow but no responses)

### ISSUE THREAD

**Issue by pitosalas** [hakimel/reveal.js#3349]
While I can use other RevealJS plugins, my RevealHighlight plugin is not being recognized. [![enter image description here][1]][1]

Here is a snippet of my code:

    <script src="https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.7.0/plugin/highlight/highlight.js" integrity="sha512-KajdeBnB+EkQSLjoqtSEshAxmUaTDUsOmeS7MWgP3KagyrUOLYs/tG14PR8eVZxUeH/NxXfQQ2+lReqUGOMJZA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/highlight.min.js" integrity="sha512-bgHRAiTjGrzHzLyKOnpFvaEpGzJet3z4tZnXGjpsCcqOnAH6VGUx9frc5bcIhKTVLEiCO6vEhNAgx5jtLUYrfA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    
    <script>
        // Full list of configuration options available at:
        // https://github.com/hakimel/reveal.js#configuration
        Reveal.initialize({
            minScale: 0.2,
            maxScale: 1.4,
    
            markdown: {
                breaks: true
            },
    
            <% SLIDES_CONFIG[:revealjs_opts].each do |k, v| %>
            <%= k %>: <%= v.to_json %>,
            <% end %>
    
            // Optional reveal.js plugins
            plugins: [ RevealMarkdown, RevealHighlight ]
        })
    </script>

  [1]: https://i.stack.imgur.com/Qjh6T.png

**Comment by Martinomagnifico** [comment]
Hi Pito, your HTML looks like the > 4.0.0 syntax for loading plugins, but the Highlight plugin from the CDN is loading an older one, which does not return a promise. You might want to try downloading the plugins from the Reveal.js GitHub directly, which are always up to date, or select a newer version from the CDN.

**Comment by pitosalas** [comment]
Thanks! Fixed :) Great package by the way!
