### ISSUE TITLE
data-autoslide: Using for only one section with no jump to the next section

### ISSUE THREAD

**Issue by SithGandalf** [hakimel/reveal.js#335]
I have a section which have some Points. I set the data-autoslide for this section to autoslide the fragments. After this fragments the slide is automatically jumping to the next section, but i would like to have it that it is not jumping to the next section.

So my question: It is possible to interrupt the data-autoslide before jumping to the next section?

URL for visible example:
http://www.jens-kunter.com/index.php?id=20

Thank you for your help.

Greeting SithGandalf

**Comment by GuidoS** [comment]
Is it possible to add a data-fragment-autoslide="3000" This would be a great way to control segments within a slide.
