### ISSUE TITLE
Can we have a 'real'-black theme ?

### ISSUE THREAD

**Issue by gbraad** [hakimel/reveal.js#3366]
The name suggests black, however the background-color is not actually black:

https://github.com/hakimel/reveal.js/blob/7de6ccb65b98f657f757cb5610613ad9d4f3da2b/css/theme/source/black.scss#L19

for OLED displays that can do nice black this is 'wasteful' ;-)

**Comment by gbraad** [comment]
Note: perhaps the name should be 'true'-black. WDYT?

**Comment by hakimel** [comment]
Added in #3310
