### ISSUE TITLE
Fragment ranges

### ISSUE THREAD

**Issue by kno10** [hakimel/reveal.js#3374]
I have a use case where I would want to write the following:
```html
<div class="r-stack">
  <div class="fragment fade-in-then-out" data-fragment-index="1-3">Variant 1</div>
  <div class="fragment fade-in-then-out" data-fragment-index="4-6">Variant 2</div>
</div>
... individual fragments for 1 to 6.
```
I.e., have (stacked) fragments for the first three fragments, then for the subsequent 3.

This is possible, e.g., in latex beamer via `\only<1-3>{Variant 1}` and that is elegant to use. Even multiple ranges may be given, e.g., `\only<1-3,7>`. To not confuse users, it would be okay to add this as `data-fragment-range`, too. But maybe it makes sense to copy some more concepts from beamer, e.g., differentiate between visibility (opacity) and disappearing (display:none). E.g. `data-visible-range` and `data-only-range`? Because these are no longer "fragments" of a page as originally intended with `.fragment`.

I do not want to make three copies of that fragment because it contains a MathJax equation.

**Comment by hakimel** [comment]
You can make a fragment appear and disappear at different indices by nesting fragments. Try this:

```html
<section>
 <div class="r-stack">
  <div class="fragment" data-fragment-index="1">
   <div class="fragment fade-out" data-fragment-index="4">
    1-3
   </div>
  </div>
  <div class="fragment" data-fragment-index="4">
   <div class="fragment fade-out" data-fragment-index="7">
    4-6
   </div>
  </div>
 </div>
 <p class="fragment" data-fragment-index="1">1</p>
 <p class="fragment" data-fragment-index="2">2</p>
 <p class="fragment" data-fragment-index="3">3</p>
 <p class="fragment" data-fragment-index="4">4</p>
 <p class="fragment" data-fragment-index="5">5</p>
 <p class="fragment" data-fragment-index="6">6</p>
</section>
```

**Comment by hamed5962** [comment]
بله درست است

در تاریخ شنبه ۳۰ اوت ۲۰۲۵،‏ ۲۳:۳۶ Matt Godbolt ***@***.***>
نوشت:
