### ISSUE TITLE
step-by-step highlights doc example broken on iPhone 

### ISSUE THREAD

**Issue by borisovg** [hakimel/reveal.js#3376]
from https://revealjs.com/code/

![1C52F0B3-7F8C-46C9-B23C-E8D1ED7C8621](https://user-images.githubusercontent.com/3171327/223543150-353d7082-8eed-4355-88a3-0a1c134357ab.jpeg)

iOS 16

**Comment by hakimel** [comment]
All code samples on revealjs.com are glitchy because of a build error in the docs site. Looking into it now.
