### ISSUE TITLE
Q: Change color of progress bar and navigation items

### ISSUE THREAD

**Issue by yannikschaelte** [hakimel/reveal.js#3378]
Brief question: What is the easiest way of changing the colors of in particular the progress bar and the forward/backward navigation items? I.e. where are these defined.

**Comment by Martinomagnifico** [comment]
They are CSS variables that can be overridden.
The easiest way is to simply add a style block and override the variable like this:

```
<style>
	:root {
		--r-link-color: orange;
	}
</style>
```

**Comment by Martinomagnifico** [comment]
If you inspect any reveal page with the developer tools, you can see a list of variables at the bottom of the 'styles' pane.

**Comment by yannikschaelte** [comment]
Thanks a lot, that solved it!
