### ISSUE TITLE
how to use line number offset with markdown?

### ISSUE THREAD

**Issue by hesxenon** [hakimel/reveal.js#3386]
adding an element comment at the end only adds the attribute to the `pre` element but it's needed on the `code` element?

**Comment by mattcen** [comment]
After some digging, I've determined this issue is resolved by #3409, but that hasn't landed in a released version yet. The syntax is also documented on [Revealjs.com](https://revealjs.com/markdown/#line-number-offset) as of May 
12 this year: https://github.com/reveal/revealjs.com/commit/46e2d22.

**Comment by hakimel** [comment]
Fixed in #3409
