### ISSUE TITLE
Running on localhost (blank / buried on page reload)?

### ISSUE THREAD

**Issue by victoriastuart** [hakimel/reveal.js#3396]
Can I run a reveal.js presentation in a localhost?

`http-server -S -C ~/.ssl/localhost-cert.pem -K ~/.ssl/localhost-private_key.pem --cors -p 8082 /mnt/Vancouver/`

`http-server  -p 8082 /mnt/Vancouver/`

`php -S localhost:8001 -t /mnt/Vancouver/`

If I load the following URL in a fresh tab it loads (ditto default `demo.html` file). 

`http://localhost:8001/reveal_js/reveal.js-master/test_02.html`

However, when I refresh those servers (page reload), the content is buried below a blank page.

That demo / my test pages run fine in a non-webserver (i.e. regular) browser tab.

I am not using NPM; just the `reveal.js` files, directly (cloned repo).

I'm concerned as later I'll be running a presentation on my website (Apache server).

**Comment by victoriastuart** [comment]
I researched this issue this morning with a MRE (below), which worked in other browsers (Opera; Brave).

In Firefox (my default browser) I have an extension - `Overlay Remover Auto` - which by default is disabled on "undefined" Firefox pages / tabs.  When I open a localhost, that extension kicks in (on a timer) - which explains the observed behavior (blocked the reveal.js presentation).

When I disabled `Overlay Remover Auto`  on the localhost tab (`Disabled on: localhost:8001`), the MRE below ran, fine! 

---

**Minimal reproducible example**

<html>

  <head>
    <link rel="stylesheet" href="dist/reveal.css">
    <link rel="stylesheet" href="dist/theme/white.css">
  </head>
  <body>
    <div class="reveal">
      <div class="slides">
        <section>Slide 1</section>
        <section>Slide 2</section>
      </div>
    </div>
    <script src="dist/reveal.js"></script>
    <script>
      Reveal.initialize();
    </script>
  </body>
</html>

**Comment by mosabua** [comment]
Just fyi @victoriastuart .. here is an example of a setup I have been using for years. It allows you to have one GitHub repo with multiple slide decks that are running as they are in github pages off the same main branch as well as with a script that runs the same thing on localhost for testing or demos and so on.

https://github.com/trinodb/presentations
https://trinodb.github.io/presentations/

There are runlocalserver scripts for windows and macos/linux

Reveal is isolated into its own directory so I can easily update version with minimal impact on the presentations .. 

Hope that helps
