### ISSUE TITLE
hide browser toolbar and tabs to get real full screen?

### ISSUE THREAD

**Issue by floswald** [hakimel/reveal.js#3405]
hi there
when displaying google slides, on can (apparently) hide the enclosing browser window by adding parameter `?r=minimal`. on a projector, the browser window eats up quite a lot of space.

https://support.google.com/docs/thread/27261658/while-in-presentation-mode-slides-is-there-a-way-to-prevent-turn-off-the-tool-bar-from-popping?hl=en

is there any way we could emulate this behaviour in reveal? thanks

**Comment by Martinomagnifico** [comment]
Press F for real full screen. That will hide tabs and browser controls.

**Comment by floswald** [comment]
oh. that's almost embarrassing. thanks!
