### ISSUE TITLE
Feature request : DARK MODE

### ISSUE THREAD

**Issue by emnachouchane** [hakimel/reveal.js#3412]
A great idea would be to implement a "dark mode" option for presentations. This feature would give presenters to option to alternate between dark and light color schemes so that they could present in different lighting conditions. And this, throughout a button or even a keyboard shortcut. This would help in increasing the framework's adaptability for different types of users.

**Comment by libralibra** [comment]
have you tried the plugin called Menu?
https://github.com/denehyg/reveal.js-menu

It enables the user to change the theme and transitions on the fly.
![aaaaaaaaaaaaaa](https://github.com/hakimel/reveal.js/assets/875627/ae8cda55-a296-4cf6-af45-79b320d703c2)
