### ISSUE TITLE
ReferenceError: navigator is not defined

### ISSUE THREAD

**Issue by Proliecan** [hakimel/reveal.js#3417]
I followed the installation guidelines at https://revealjs.com/installation/#installing-from-npm, but for some reason I got this error when I tried to run the script:
![image](https://github.com/hakimel/reveal.js/assets/65495509/c84fb051-255c-445a-af4f-01023f1229c3)

**Comment by Proliecan** [comment]
**Here is my small code: https://github.com/Proliecan/reveal-js-minimal-template/commit/48b348b1cc46179e4dd6fa6f62eb73f96f050a34**
The issue should be reproducible without any challanges.

**Comment by MartenBE** [comment]
What was your solution?

**Comment by Proliecan** [comment]
I discontinued my project.
The response was just too underwhelming.
