### ISSUE TITLE
canvas not reponding correctly in section

### ISSUE THREAD

**Issue by jamespinto** [hakimel/reveal.js#346]
![cross](https://f.cloud.github.com/assets/3690808/190812/cc8c7dec-7f10-11e2-82ac-a3a4f93fcd64.JPG)
![cross1](https://f.cloud.github.com/assets/3690808/190813/dde077e2-7f10-11e2-8067-06ed2013aef2.JPG)

I have created a quiz in html 5 canvas and it works perfectly as an html but when I put the code into a reveal js section and click on the last option the tic kor cross icon appears on the wrong position on the canvas.

Im attaching screenshots the first is of the simple html without reveal js
and second is inside reveal js

I copied the canvas code into the section for the first slide.

As you can see in the second image when I click on the last option the cross icon shows on the second last option.

this happens only in reveal js

**Comment by faaaaabi** [comment]
I ran into the same Problem.
Dividing the the mouses position (relative to the canvas element) by `Reveal.getScale()`, worked for me.
