### ISSUE TITLE
Notes plugin: notes from inactive fragments mess with slide-level notes

### ISSUE THREAD

**Issue by skyboyer** [hakimel/reveal.js#3478]
If we have notes inside fragments through `<aside class="notes">` like

```html
<section>
	<p>1</p>
	<p class="fragment">
		2
		<aside class="notes">fragment 2 notes</aside>
	</p>
	<p class="fragment">
		3
		<aside class="notes">fragment 3 notes</aside>
	</p>
</section>
```

We have:

* all fragment-level notes are combined and shown as slide-level notes("fragment 2 notes fragment 3 notes")
* when reaching fragments with notes, their notes are *not* shown exclusively

If we use `data-notes` instead, everything works fine:

```html
<section>
	<p>1</p>
	<p class="fragment" data-notes="fragment 2 notes">
		2
	</p>
	<p class="fragment" data-notes="fragment 3 notes">
		3
	</p>
</section>
```

Root cause: [plugin's logic](https://github.com/hakimel/reveal.js/blob/master/plugin/notes/plugin.js#L111C8) treats all the `aside.notes` as slide-level notes, even if they are wrapped into `.fragment`:

```js
let slideElement = deck.getCurrentSlide(),
	notesElements = slideElement.querySelectorAll( 'aside.notes' ),
```

**Comment by skyboyer** [comment]
Would it be better to detect `aside.notes` inside of `.fragment` and process them separately? (more flexibility and consistent approach). Or it would be enough to document in docs that for in-fragment notes only `data-notes` method is allowed?

**Comment by hakimel** [comment]
I've fixed this so that `<aside class="notes">` works inside of fragments as well: db2523db277bea632c218a7d836f27079a1be7f9
