### ISSUE TITLE
Extra blank slide when trying to print

### ISSUE THREAD

**Issue by timbrock** [hakimel/reveal.js#3483]
As [discussed on the quarto-dev pages](https://github.com/quarto-dev/quarto-cli/issues/3997), [this (page-)break-after value](https://github.com/hakimel/reveal.js/blob/db2523db277bea632c218a7d836f27079a1be7f9/css/print/pdf.scss#L70) seems to lead to an extra blank slide at the end when trying to print. I think it [can be fixed](https://github.com/quarto-dev/quarto-cli/issues/3997#issuecomment-1729966165) by overriding on last-child or last-of-type, but there may be a more elegant solution. 

Tested in Chrome on Ubuntu.

**Comment by libralibra** [comment]
I find the same problem. I have to manually change the print page range in the printing dialog to explicitly avoid printing the last page.

**Comment by hakimel** [comment]
This should be fixed in the latest copy in master and will be released with the next version.
