### ISSUE TITLE
RevealSearch plugin can't find diacritics character

### ISSUE THREAD

**Issue by jpggithub** [hakimel/reveal.js#3492]
I try to search some usual characters "ç", "é" and "è" in some french Reveal slides coming from an external markdown.
It does not work: theses characters are not found and my cpu works at 100%.

**Comment by t-fritsch** [comment]
Hello

Thanks for the report !
The regexp that is used in search plugin don't take into account any diacritics. I'm working on a PR, should be ready soon. 🤞

**Comment by lechten** [comment]
Great to see that a PR is on the way :+1: 
Do you also plan to address issue #2331?

**Comment by jpggithub** [comment]
Thank you very much @t-fritsch for the fix!
