### ISSUE TITLE
Generated PDF file is untagged.

### ISSUE THREAD

**Issue by libralibra** [hakimel/reveal.js#3495]
I just found that in the generated PDF file, there is no bookmarks (structure of the file) items. And the text cannot be selected in the pdf. Does that mean the pdf generation is kind of screenshots of each slide?

Is there any method that I can have the following?

1. bookmarks (titles of each slides as the bookmark item) to show the document structure
2. selectable text in each slide rather than displaying each slide as an image

**Comment by libralibra** [comment]
Can anyone shed some light on this issue, please?

**Comment by hakimel** [comment]
I just tried exporting the demo presentation in reveal.js master and text is selectable. Does this PDF work for you?
[reveal-demo.pdf](https://github.com/hakimel/reveal.js/files/13345969/reveal-demo.pdf)

PDF exports are not screenshots. Make sure you follow the instructions here and are using Google Chrome when printing:  https://revealjs.com/pdf-export/

**Comment by hakimel** [comment]
Forgot the bookmarks. That's not something we support. We rely on the browser to convert presentations from HMTL -> PDF and I don't know if it's possible to make it insert bookmarks.

**Comment by t-fritsch** [comment]
> I don't know if it's possible to make it insert bookmarks.

it seems the answer is : no 😅  cf. https://stackoverflow.com/a/60063688
