### ISSUE TITLE
Fragment index jumps from -1 to 1, skipping fragment with index 0

### ISSUE THREAD

**Issue by kenneho** [hakimel/reveal.js#3496]
Hi. 

I have this in my React component: 
```
<section>
     <p className="fragment" data-fragment-index="1">
          Appears first
     </p>
     <p className="fragment" data-fragment-index="2">
          Appears second
     </p>
     <p className="fragment" data-fragment-index="3">
          Appears last
     </p>
</section>
```

When rendering this in the browser, the initial code is this:
```
<section style="top: 228px; display: block;" class="present" data-fragment="-1">
   <p class="fragment" data-fragment-index="0">Appears first</p>
   <p class="fragment" data-fragment-index="1">Appears second</p>
   <p class="fragment" data-fragment-index="2">Appears last</p>
</section>
```
Note that the first element when rendered gets an index of `0`.

When I click the right arrow in the slide, the code now looks like this:
```
<section style="top: 228px; display: block;" class="present" data-fragment="1">
  <p class="fragment visible" data-fragment-index="0">Appears first</p>
  <p class="fragment visible current-fragment" data-fragment-index="1">Appears second</p>
  <p class="fragment" data-fragment-index="2">Appears last</p>
</section>
```
The section's `data-fragment` now skips to `1`, thus revealing both the first and second item in the list at the same time. 

So it looks like either there's a bug that causes the section's `data-fragment` to skip `0`, or there's a bug that starts the fragments on `0` instead of `1`. 

Likely this is not a bug in Revealjs itself but rather some local issue or some issue with how Reavealjs and React interoperates, but in any case I'd appreciate some advice on how to get this working.

**Comment by kenneho** [comment]
This isn't an issue when I run the production build of NextJS, so it's likely got something to do with RevealJS being initialized twice when I'm running the development server (`npm run dev`), so it's a React issue rather than a RevealJS issue. Any suggestions for getting RevealJS to work properly while running the development server will be appreciated.

**Comment by kenneho** [comment]
Moved things from NextJS's `/app` folder to `/pages` and things are working fine even on the development server. So perhaps there's some issue with server components.

**Comment by waterchinap** [comment]
Hi kenneho:
I googled on how to make revealjs work on nextjs, found no detailed introductions.
I tried initialize the reveal in useEffect(), but failed. Do you have any resouse on how to setup revealjs in the latest nextjs ?

**Comment by kenneho** [comment]
> Hi kenneho: I googled on how to make revealjs work on nextjs, found no detailed introductions. I tried initialize the reveal in useEffect(), but failed. Do you have any resouse on how to setup revealjs in the latest nextjs ?

I see you already found the [discussion is posted](https://github.com/hakimel/reveal.js/discussions/3488), so hopefully you've got things up and running. Happy coding!
