### ISSUE TITLE
jumpToSlide does not work with an external markdown file

### ISSUE THREAD

**Issue by jpggithub** [hakimel/reveal.js#3501]
Hi
I have `jumpToSlide: true,` in my index.html.
If I create slides in the index.html file, I can use the jump-to-slide feature with the `g` key.
If I use an external markdown file, I always go to the first slide defined by the external file by using the `g` key. `g2` does not work for example.
Please can you fix that or indicate this limitation in the documentation?
Regards

**Comment by hakimel** [comment]
I just tried this in a fresh copy of reveal.js master using the file in `examples/markdown.html` and it works. It's possible to jump to slides defined in external Markdown by both their slide number and title.

Can you share a copy of your presentation where this isn't working? Thanks.

**Comment by jpggithub** [comment]
Thanks for your attention. I have investigated more. Everything is fine with `slideNumber: "h/v",`.

A problem occur when you use `slideNumber: "c",`.

For example with `markdown.html` in the `examples` folder, add the `slideNumber: "c",` option in the `Reveal.initialize` part. You won't be able to reach the 3rd slide "External 1.2" with `g3`. `g3` display the 4th slide (with the content "External 2/Content 2.1".

**Comment by hakimel** [comment]
As of 3d7d3152a455515d84974031e25a2c9411231854 jump-to-slide adapts to match the slide number format.

If you use `slideNumber: 'c'` you'll be able to jump to any slide by the same number as shown on the slide.
