### ISSUE TITLE
Speaker View does not display the correct Upcoming Slide

### ISSUE THREAD

**Issue by hhkit** [hakimel/reveal.js#3512]
When I press the 'S' key on the [demo](https://revealjs.com/?demo) site to open the Speaker View, the preview of the Upcoming Slide shows the wrong slide. In some cases it is the current slide, and in others, it is the previous slide.

Tested on Firefox 119 and Chrome 118.0.5993.118 in Windows 11.
Also tested with the instructions for `Full Setup` and `Installing from npm` as described in the [Installation](https://revealjs.com/installation/) tutorial. The version tested in the latter is `@latest`, that is, 5.0.0.

4.6.0 appears to be working as intended; could this be a regression?

<details>
<summary>Issues as described in the Demo</summary>

![image](https://github.com/hakimel/reveal.js/assets/38537881/a551f9e7-bfe3-4e70-b27a-e2557b9e3bed)
The opening slide does not render the next slide.

![image](https://github.com/hakimel/reveal.js/assets/38537881/b92a9fd9-e926-48eb-a097-58f924255e85)
Here, the gif slide is supposed to come before the background slide.

</details>

**Comment by hakimel** [comment]
Thanks for reporting! A fix for this has been released in 5.0.1.

(The demo in the revealjs.com docs hasn't been updated yet but will be.)
