### ISSUE TITLE
Arrow keys work only for fragments but not for slides in scroll-view (v.5.0.0)

### ISSUE THREAD

**Issue by its-thomas** [hakimel/reveal.js#3515]
In the latest v.5.0.0 of RevealJS, the keyboard arrow keys (up & down) seem only to be able to navigate through fragments, but not through slides. See [https://slides.com/news/scroll-mode/scroll](https://slides.com/news/scroll-mode/scroll) and test for yourself.

I think it would be advantageous to have  keyboard arrow keys work to navigate through slides as well.

**Comment by jpggithub** [comment]
The space bar no longer works for navigation either (except through fragments). 
Strange behavior, I don't understand how to use the view scroll mode. The scroll bar is so thin.

**Comment by hakimel** [comment]
I agree it should be possible to navigate via keyboard shortcuts in the scroll mode too. It's on my backlog.

**Comment by leftys** [comment]
If it helps with debugging, it's interesting that not even `Reveal.next()` works (was looking for a workaround, haha). Also URL is not updated after slide changes, which breaks slide creation with live-reload.

**Comment by hakimel** [comment]
Fixed in 5d131cea2074759d8781b167844ef35dafb99657

**Comment by tingstad** [comment]
> Fixed in [5d131ce](https://github.com/hakimel/reveal.js/commit/5d131cea2074759d8781b167844ef35dafb99657)

@hakimel Great, will this be in a release soon?
