### ISSUE TITLE
How to use js/reveal.js instead of dist/reveal.js in html

### ISSUE THREAD

**Issue by elnisi** [hakimel/reveal.js#3518]
the index.html in the master.zip
have the line `<script src="dist/reveal.js"></script>`

I change it to `<script src="js/reveal.js"></script>` in order to be able to do some minor modifications
but I get the error 

> Uncaught SyntaxError: Cannot use import statement outside a module

I change it to  `<script type="module" src="js/reveal.js"></script>`  then I get the error
> Uncaught TypeError: Failed to resolve module specifier "fitty". Relative references must start with either "/", "./", or "../".

I also try 
```
<script type="module" >
import * as Reveal from "js/reveal.js";
</script>
```
I get the error
> Uncaught TypeError: Failed to resolve module specifier "js/reveal.js". Relative references must start with either "/", "./", or "../".

**Comment by t-fritsch** [comment]
Hello

the js files are in two versions in reveal : `js` folder is for "source" files, and `dist` folder for the "compiled" version. 

If you want to edit the source code you should leave `dist/reveal.js` in your html and run the development server to compile it every time you change the source code.

The instructions to run the development server are in the "full setup" installation instructions here : https://revealjs.com/installation/#full-setup

**Comment by StoneCypher** [comment]
@elnisi - if you want to do this, use a bundler like rollup
