### ISSUE TITLE
Background of nested section leaks to section

### ISSUE THREAD

**Issue by Martinomagnifico** [hakimel/reveal.js#3520]
Since 5.0.0 there is a flash of color when navigating between slides, when a nested section in the second stack has a custom color. It happens only the first time, and no longer when going back and forward. I've tried to change backgrounds.js, but can't get it to work without breaking the backgrounds that are set with a data-attribute. See this pen: https://codepen.io/martino/pen/eYxvjQV

**Comment by hakimel** [comment]
Thanks for reporting @Martinomagnifico! Fixed this in 1e1e22868023ea3af7d22c2d090c6cdae7f9bd07 and released v 5.0.2.

**Comment by Martinomagnifico** [comment]
Thanks for the fast fix! There is still a 'present' class in a (nested) background that is in the future though. But the flash is gone :-)
