### ISSUE TITLE
code alignment was lost after turning on 'data-line-number'

### ISSUE THREAD

**Issue by libralibra** [hakimel/reveal.js#3523]
The code alignment would stop working as long as the 'data-line-numbers' was turned on. Please take a look at the screenshots before and after.

![1](https://github.com/hakimel/reveal.js/assets/875627/d0cbbeba-252c-4da3-b347-18b696217515)
![2](https://github.com/hakimel/reveal.js/assets/875627/58e7485c-394c-4fe6-b8c9-f1f5b9c16714)

**Comment by hakimel** [comment]
Can you include the code for both of those code blocks so I can test?

**Comment by libralibra** [comment]
no worries, maybe I messed up some CSS code blocks. It was left-aligned after specifying left aligned text with !important as a new rule for pre > code. It seems working fine now.
