### ISSUE TITLE
Incompatibility Scroll view & reveal.js-menu

### ISSUE THREAD

**Issue by jpggithub** [hakimel/reveal.js#3525]
When in scroll view, reveal.js-menu [^1] does not display anymore the titles in the menu with reveal.js version 5.0.2

On smartphone, the scroll view is put on by default and the menu become useless.

Question: how to deactivate the scroll view in the responsive scroll view?

[1]: https://denehyg.github.io/reveal.js-menu/

**Comment by hakimel** [comment]
You can deactivate the responsive scroll view by setting `scrollActivationWidth` to 0 or null.

`Reveal.initialize({ scrollActivationWidth: null })`

**Comment by jpggithub** [comment]
Precision: reveal.js-menu become useless with scrollview because it does not display the title as attended.
Il would be nice to have scroolview and reveal.js-menu working together!
