### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'classList')

### ISSUE THREAD

**Issue by FlippingBinary** [hakimel/reveal.js#3539]
I'm getting an error in console when swiping slides while simulating Samsung Galaxy S8+ in Vivaldi (Chromium-based) on Windows 10 using Reveal.js 5.0.2. I haven't checked to see if it affects mobile interaction more broadly.

```raw
Uncaught TypeError: Cannot read properties of null (reading 'classList')
    at _t.deactivatePage (reveal.esm.cd96fbcf.js:13:28379)
    at Object.deactivate (reveal.esm.cd96fbcf.js:13:21463)
    at _t.deactivateTrigger (reveal.esm.cd96fbcf.js:13:28524)
    at reveal.esm.cd96fbcf.js:13:26152
    at Array.forEach (<anonymous>)
    at _t.syncScrollPosition (reveal.esm.cd96fbcf.js:13:25865)
    at _t.onScroll (reveal.esm.cd96fbcf.js:13:28829)
```

The problem appears to occur at this line:
https://github.com/hakimel/reveal.js/blob/9d491c6d2f413fbb91b2754fffe1a6970d7f6a7c/js/controllers/scrollview.js#L805

`page.backgroundElement` is assumed to be an object containing a `classList` property, but it is `null` instead. I tried adding a null-check, but I'm getting a RollupError and don't know anything about gulp so it's a rabbit-hole I'm not prepared to dive into right now.

**Comment by hakimel** [comment]
Thanks for reporting. I was able to recreate this in Mobile Safari and have fixed it. The exception didn't prevent or affect navigation as far as I could see.
