### ISSUE TITLE
Mobile navigation broken when `data-fragment-index` skips index 0

### ISSUE THREAD

**Issue by FlippingBinary** [hakimel/reveal.js#3540]
This seems to only affect mobile navigation, even as simulated in Vivaldi on Windows 10. When the `data-fragment-index` property is set to something higher than 0 and there is no element with a `data-fragment-index` of 0, the pages won't swipe.

Here is the error that appears in the browser console:

```raw
scrollview.js:431 Uncaught TypeError: Cannot set properties of undefined (setting 'range')
    at scrollview.js:431:19
    at Array.forEach (<anonymous>)
    at scrollview.js:430:32
    at Array.forEach (<anonymous>)
    at L.setTriggerRanges (scrollview.js:421:22)
    at L.syncPages (scrollview.js:379:8)
    at L.layout (scrollview.js:257:9)
    at Object.Be [as layout] (reveal.js:1037:15)
    at L.activate (scrollview.js:133:15)
    at Be (reveal.js:1025:47)
```

The obvious solution is to fix the `data-fragment-index` assignments in the presentation, but it wasn't obvious that this was the reason why slide navigation broke on mobile. I hope this helps someone else.

**Comment by hakimel** [comment]
Thanks for the report! Fixed in d5896c968b2406126ca0beafecdffe219230b6b4
