### ISSUE TITLE
Scroll mode: Help and pause screens only shown on first slide

### ISSUE THREAD

**Issue by personalizedrefrigerator** [hakimel/reveal.js#3542]
# Summary

In a presentation with scroll mode enabled, pressing <kbd>?</kbd> shows help, but only on the first slide.

Similarly, pressing <kbd>.</kbd> only pauses the presentation on the first slide.

# Steps to reproduce

1. Navigate to https://revealjs.com/scroll-view/
2. Focus the first example presentation
3. Open the second slide
4. Press <kbd>?</kbd>
5. Repeat steps 3 and 4 for the first slide.

**Comment by hakimel** [comment]
Thanks for reporting this. Just pushed a fixed for it.
