### ISSUE TITLE
Potential XSS vulnerability with `data-background-video` attribute

### ISSUE THREAD

**Issue by EastSun5566** [hakimel/reveal.js#3546]
Hi @hakimel 

Thanks for all your hard work! 

we've encountered a potential security issue related to XSS (Cross-Site Scripting) when using the `data-background-video` attribute in slides. It appears that the way Reveal.js handles this attribute might allow for the execution of injected scripts, even when the attribute value is **HTML entity-encoded**.

Consider the following example where we use an encoded string in the `data-background-video` attribute:

```html
<section data-background-video="&quot;&gt;&lt;/video&gt;&lt;iframe srcdoc=&quot;&lt;script src='https://www.google.com/complete/search?client=chrome&q=123&jsonp=alert(document.domain)//'&gt;&lt;/script&gt;&quot;&gt;&lt;/iframe&gt;&lt;img src=wtf:&gt;&lt;a data-x=&quot;">
	<h2>🍦</h2>
</section>
```

The script will be executed despite being encoded. because `getAttribute` will [decode entities](https://stackoverflow.com/a/11224418) even if they are already escaped:
https://github.com/hakimel/reveal.js/blob/c23964274c17225d94be104289fa918eff1fbbd4/js/controllers/slidecontent.js#L102

And then concat in `innerHTML` will cause XSS:
https://github.com/hakimel/reveal.js/blob/c23964274c17225d94be104289fa918eff1fbbd4/js/controllers/slidecontent.js#L144-L152

---

Fix is pretty easy I think. Just replace `innerHTML` with attribute assignment, as shown below:

```js
backgroundVideo.split( ',' ).forEach( source => {
    let type = getMimeTypeFromFile(source);
    let sourceElement = document.createElement('source');
    sourceElement.setAttribute('src', source);
    if( type ) {
        sourceElement.setAttribute('type', type);
    }

    video.appendChild(sourceElement);
});
```

Using `setAttribute` ensures that the source remains a plain string.

If this approach seems suitable, I would be happy to create a PR to address this. Thank you for your consideration!

**Comment by hakimel** [comment]
Thanks for reporting this @EastSun5566! Your proposed fix looks great. If you want to submit it as a PR I'll be happy to merge.
