### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'classList')

### ISSUE THREAD

**Issue by dvmoomoodv** [hakimel/reveal.js#3551]
I appreciate your kind response in issue #3539.

However, I'm still facing the issue when I didn't include the following configuration during Reavel.initialize() setup. It seems that a default setting might be necessary. I would be grateful if you could take a look.

`view: 'scroll'`

**Comment by dvmoomoodv** [comment]
used lateast version

**Comment by hakimel** [comment]
Did you try the latest version from the master branch or from npm? The fix from #3539 hasn't been released in a version yet and is only available if you pull from this repo.

**Comment by dvmoomoodv** [comment]
I proceeded with the installation of the latest version using 'npm install' as you suggested. Is issue #3539 not yet available for npm distribution?

**Comment by hakimel** [comment]
No, the fix is not available on npm yet. It's only available here in the github repo. I'll get a new release out soon.

**Comment by dvmoomoodv** [comment]
Thank you for explaining. Have a great day!

**Comment by hakimel** [comment]
No problem! I just published 5.0.3 with this fix. Should appear on npm shortly: https://github.com/hakimel/reveal.js/releases/tag/5.0.3
