### ISSUE TITLE
data-background-image disappears on mobile 

### ISSUE THREAD

**Issue by brnkgabriel** [hakimel/reveal.js#3554]
He team, 

Thought it was my code that was the issue till I checked the official documentation and saw the same thing

The data-background-image as well as data-background-color shows on desktop but somehow doesn't on mobile. 

You simply get a black screen on mobile le

**Comment by hakimel** [comment]
Fixed in 5ee1f729bd67e71a53057d29cb56762db8025426, thanks for reporting!
