### ISSUE TITLE
Bug: `isSwipePrevented` disables swiping when `data-background-audio` or `data-background-video` is played

### ISSUE THREAD

**Issue by jeertmans** [hakimel/reveal.js#3584]
Hello,

I maintain a tool that generates video slides, and one of the export formats is RevealJS.

All slides are played as `data-background-video`, see https://eertmans.be/manim-slides-starter/ for example.

I am not the first to notice that swiping on touch devices does not work on that kind of slides, see #3302 or https://github.com/jeertmans/manim-slides/issues/384 (for a similar issue on my repo).

After searching a bit, it seems like the faulty lines are there:

https://github.com/hakimel/reveal.js/blob/63e0a37a8896071c9ccf4e56acc9df3f8c51abd4/js/controllers/touch.js#L80-L96

Looking at the comments, the fact that this function returns `true` for `data-background-*` contents seems to be an undesirable side effect, because we do not have the timeline for both the audio and the video when they are put in the background.

If that is an intended effect of the function, then it might be nice to add an optional attribute to force swipe-enabling? I.e., something that does the opposite of `data-prevent-swipe`.

Thanks!

**Comment by hakimel** [comment]
Fixed in 6ef138b61f7e143bded38b522ea4cdcaa6451edf — thanks for reporting!

From now on swiping will only be prevented if you're interacting with a video that has controls visible.

**Comment by jeertmans** [comment]
Thanks for fixing this @hakimel and for this great tool!

**Comment by jeertmans** [comment]
Hello @hakimel, do you think it would be feasible to release a new version with your patch (https://github.com/hakimel/reveal.js/commit/6ef138b61f7e143bded38b522ea4cdcaa6451edf)?

I'd love to integrate that fix in my slides! Thanks!

**Comment by hakimel** [comment]
Just published reveal.js 5.1.0 with this fix 🚀

**Comment by jeertmans** [comment]
Thank you!!
