### ISSUE TITLE
data-auto-animate in react app → Uncaught TypeError: Cannot read properties of null (reading 'hasAttribute')

### ISSUE THREAD

**Issue by brandontrew** [hakimel/reveal.js#3592]
Getting error 
`Uncaught TypeError: Cannot read properties of null (reading 'hasAttribute')
    at k.run (reveal.esm.js:12:22298)
    at Xe (reveal.esm.js:12:92017)
    at Object.bt (reveal.esm.js:12:98202)
    at T.onDocumentKeyDown (reveal.esm.js:12:55350)`

When trying to use data-auto-animate inside a react app. This same approach used to work before converting to a react Section component. But now animation fails.

I have the following Section output, which comes from a Section component, in a react-embedded reveal.js:

`<section data-hash="d0aeb172" data-slide-number="40" data-auto-animate="" data-first-string="Animate selected objects during slide transitions with animate" id="animate-selected-objects-during-slide-transitions-with-animate" class="flex flex-col h-full overflow-hidden present" style="display: block;"><h1 id="animate-selected-objects-during-slide-transitions-with-animate" class="slidetitle">Animate selected objects during slide transitions with <code>animate</code></h1>
<div data-layout="parent" class="items-center justify-center text-left   h-full w-full flex flex-col flex-grow flex-shrink  "><div data-layout="entity" class="w-2/3 h-full text-3xl ml-auto mr-auto mt-20 flex flex-col flex-grow flex-shrink text-6xl"><ul data-id="animation-id">
<li>Item 1</li>
<li>Item 3</li>
<li>Item 4</li>
</ul>
</div></div><div data-layout="footer" class=""></div></section>`

Here's the React component code that generates it:
`return (
		tempDivAttributes && slideOutput && (
			<section
			  ref={slideRef}
			  data-hash={section.hash}
			  data-slide-number={section.slideNum}
			  {...tempDivAttributes}
			  {...(tempDivAttributes['data-auto-animate'] ? { 'data-auto-animate': "1" } : {})}
			>
			  {typeof slideOutput === 'string' ? parse(slideOutput) : slideOutput}
			</section>
		  )
	);`

**Comment by hakimel** [comment]
From your error message it looks like reveal.js is trying to run an auto-animate where one of the slide elements no longer exists. I've added a null check to prevent this 62297e625981e8f74e0aa280b5838cdd191677fe, can you try the latest version from master and see if it works?

**Comment by brandontrew** [comment]
I'n npm installed - if i npm install reveal.js/latest, will that pick it
up?

**Comment by brandontrew** [comment]
I loaded master:

ERROR:
```
Uncaught TypeError: Cannot read properties of null (reading 'hasAttribute')
    at k.run (reveal.esm.js:8:22293)
    at Xe (reveal.esm.js:8:91994)
    at Object.yt (reveal.esm.js:8:98001)
    at T.onDocumentKeyDown (reveal.esm.js:8:55147)
```

REACT COMPONENT RENDER:
```

return (
divAttributes && slideOutput && (
<section
ref={slideRef}
data-hash={section.hash}
data-slide-number={section.slideNum}
{...divAttributes}
>
<ErrorBoundary>
{typeof slideOutput === 'string' ? parse(slideOutput, {replace:
replaceObjects} ) : slideOutput}
</ErrorBoundary>
</section>
)
);
```

DOM element (error only shows in console when changing slides to this
slide, or others with data-auto-animate
````
<section data-hash="7d425fe5" data-slide-number="16" data-auto-animate=""
data-first-string="Animating code paths" id="animating-code-paths"
class="flex flex-col h-full overflow-hidden present" style="display:
block;"><h1 id="animating-code-paths" class="slidetitle">Animating code
paths</h1>
<div data-layout="parent" class="pl-5 pr-5 text-left   h-full w-full flex
flex-col flex-grow flex-shrink  "><div data-layout="entity" class="w-full
flex flex-col flex-grow flex-shrink "><pre data-id="animation-id"
class="code-wrapper"><code data-line-numbers="" class="hljs
javascript"><table class="hljs-ln"><tbody><tr><td class="hljs-ln-line
hljs-ln-numbers" data-line-number="1"><div class="hljs-ln-n"
data-line-number="1"></div></td><td class="hljs-ln-line hljs-ln-code"
data-line-number="1">  <span class="hljs-function"><span
class="hljs-keyword">function</span> <span
class="hljs-title">answerToTheUniverse</span>(<span
class="hljs-params"></span>) </span>{</td></tr><tr><td class="hljs-ln-line
hljs-ln-numbers" data-line-number="2"><div class="hljs-ln-n"
data-line-number="2"></div></td><td class="hljs-ln-line hljs-ln-code"
data-line-number="2">    <span class="hljs-keyword">let</span> answer =
<span class="hljs-number">0</span>;</td></tr><tr><td class="hljs-ln-line
hljs-ln-numbers" data-line-number="3"><div class="hljs-ln-n"
data-line-number="3"></div></td><td class="hljs-ln-line hljs-ln-code"
data-line-number="3">    <span class="hljs-keyword">for</span>(<span
class="hljs-keyword">let</span> i = <span class="hljs-number">0</span>; i
&lt; <span class="hljs-number">7</span>; i++) {</td></tr><tr><td
class="hljs-ln-line hljs-ln-numbers" data-line-number="4"><div
class="hljs-ln-n" data-line-number="4"></div></td><td class="hljs-ln-line
hljs-ln-code" data-line-number="4">        answer += <span
class="hljs-built_in">Math</span>.pow(<span class="hljs-number">2</span>,
i);</td></tr><tr><td class="hljs-ln-line hljs-ln-numbers"
data-line-number="5"><div class="hljs-ln-n"
data-line-number="5"></div></td><td class="hljs-ln-line hljs-ln-code"
data-line-number="5">    }</td></tr><tr><td class="hljs-ln-line
hljs-ln-numbers" data-line-number="6"><div class="hljs-ln-n"
data-line-number="6"></div></td><td class="hljs-ln-line hljs-ln-code"
data-line-number="6">    <span class="hljs-keyword">return</span>
answer;</td></tr><tr><td class="hljs-ln-line hljs-ln-numbers"
data-line-number="7"><div class="hljs-ln-n"
data-line-number="7"></div></td><td class="hljs-ln-line hljs-ln-code"
data-line-number="7">  }</td></tr></tbody></table></code></pre>
</div></div><div data-layout="footer" class="w-full  px-1 pt-1 pb-4 "><div
data-layout="extra" class=""><p>Code:</p>
<pre class="code-wrapper"><code class="hljs css">```<span
class="hljs-selector-attr">[]</span>
    <span class="hljs-selector-attr">[Original Code]</span>

```
..<span
class="hljs-selector-attr">[animate]</span></code></pre></div></div></section>
````

**Comment by brandontrew** [comment]
auto-animate just started working. Not sure if it was my code refactor, or
the changes you made. But thanks either way!
