### ISSUE TITLE
CSS Translation not working

### ISSUE THREAD

**Issue by eigenmannmartin** [hakimel/reveal.js#3627]
Hi all.

With the new Chrome Version 126.0.6478.7 (Official Build) beta (64-bit) translation won't work anymore. Works in Firefox 126.0

Demo: https://slides.com/martineigenmann/deck-222005

Anyone an idea why?

**Comment by hakimel** [comment]
I'm seeing this issue in Chrome beta too but haven't been able to figure out what's causing it yet.

**Comment by hakimel** [comment]
I just tested this Chrome Canary (127.0.6494.0) and there's no issue there so I'm going to assume this is a temporary hiccup in Chrome Beta (126.0.6478.7). Will keep an eye out for it though in case the problem makes it into a stable release.

**Comment by eigenmannmartin** [comment]
@hakimel awesome! fair point
