### ISSUE TITLE
Uncaught SyntaxError: missing ) after argument list @ notes.js:1:45020 with v5.1.0

### ISSUE THREAD

**Issue by Lucas-C** [hakimel/reveal.js#3659]
Hi 🙂

I just want to report an issue that I have when launching the latest release of reveal.js ([5.1.0](https://github.com/hakimel/reveal.js/releases/tag/5.1.0)).

I'm using Firefox 127.0.2 but also reproduced the same issue with Chrome 126.0.6478.183

When launching the demo page, I get a blank white screen and this error in the console:
```
Uncaught SyntaxError: missing ) after argument list
[notes.js:1:45020](http://localhost:5500/plugin/notes/notes.js)
Uncaught ReferenceError: RevealNotes is not defined
    <anonymous> http://localhost:5500/index2.html:36
```
![Capture d'écran 2024-07-21 115822](https://github.com/user-attachments/assets/68b985a9-ad1a-43a5-af3f-2167f3333378)

The interesting thing is that I tried to pinpoint the origin of this error by prettifying `plugin/notes/notes.js` using [beautifier.io](https://beautifier.io/), and when putting the prettified code in `plugin/notes/notes.js` this error disappear, and Reveal.js launches properly!

**Comment by MartenBE** [comment]
I'm also experiencing this when using livereload. Exact same error.

**Comment by hakimel** [comment]
I tried running the demo.html presentation from 5.1.0 in both Chrome and Firefox but haven't been able to reproduce this yet. Also tried triggering a few livereloads. If you have any other info to share about when this error happens I'd appreciate it.

**Comment by Lucas-C** [comment]
This is really strange...
The problem seems to come from this unminified line: https://github.com/hakimel/reveal.js/blob/master/plugin/notes/plugin.js#L34

Specifically, based on my tests, the error disappear when removing the `<head>...</head>` portion of the `speakerViewHTML`.
And even just having `<head></head>` is enough to trigger the error.

**Comment by Lucas-C** [comment]
I figured it out!

In my case, this was due to my use of `livereload`, that performs `</head>` tag replacement "on-the-fly":
https://github.com/lepture/python-livereload/blob/master/livereload/server.py#L40

**Comment by MartenBE** [comment]
Python-livereload was the package I was using also, good catch @Lucas-C  !

**Comment by hakimel** [comment]
Thank you for tracking this down @Lucas-C!

Let me know if any changes are needed to make this work on the reveal.js end.
