### ISSUE TITLE
mhchem support

### ISSUE THREAD

**Issue by jsaponara** [hakimel/reveal.js#3664]
Hi, I see mhchem support has been discussed #2559 and @burgerga had mhchem support in #2677 but it wasn't merged.  Are there instructions for incorporating mhchem (or equivalent) into reveal.js slides?

**Comment by burgerga** [comment]
Hi @jsaponara,
It's not documented but based on https://github.com/hakimel/reveal.js/blob/472535065c7525abf0cc9df51c66f19fd2d2204f/plugin/math/katex.js#L71 I think having `extensions: ["mhchem"]` in your config should work, like this:

```
Reveal.initialize({
  katex: {
    extensions: ['mhchem'],
  },
  plugins: [RevealMath.KaTeX],
});
```

**Comment by jsaponara** [comment]
Thanks @burgerga,  that works!
