### ISSUE TITLE
Nasty message when visiting the link provided to Highlight.js

### ISSUE THREAD

**Issue by elsatch** [hakimel/reveal.js#3676]
As I was visiting the documentation for code highlighting at https://revealjs.com/code/

Looking for available thems I got to: https://revealjs.com/code/#theming

Text there right now is: A full list of available themes can be found at https://highlightjs.org/static/demo/

If you click on that demo link, you are directed to: https://highlightjs.org/not-a-cdn

![image](https://github.com/user-attachments/assets/5ce5fb8e-9d48-4fe5-858b-f11b1f65899d)

Possible fix: I think the correct link should point to https://highlightjs.org/demo/

**Comment by hakimel** [comment]
https://github.com/reveal/revealjs.com/pull/67
