### ISSUE TITLE
`gulp package` not working anymore after updating to gulp 5

### ISSUE THREAD

**Issue by dennybiasiolli** [hakimel/reveal.js#3692]
It gives an error like

`Error: ENOENT: no such file or directory, scandir 'reveal.js/lib'`

But even if I change the `package` task to this

```js
gulp.task('package', gulp.series(() =>

    gulp.src(
        [
            './index.html',
            './dist/**',
            './plugin/**',
            './slides/**',
            './**/*.md'
        ],
        { base: './' }
    )
    .pipe(zip('reveal-js-presentation.zip')).pipe(gulp.dest('./'))

))
```

It doesn't work properly, the zip file contains broken jpg images included in the `slides` folder

**Comment by hakimel** [comment]
fixed in https://github.com/hakimel/reveal.js/pull/3693
