### ISSUE TITLE
Issue with slidechange event in scrollmode

### ISSUE THREAD

**Issue by Martinomagnifico** [hakimel/reveal.js#3715]
Hi Hakim, I noticed an issue with the `slidechanged` event in scrollmode. It happens only on the last page of the presentation, and usually only when it is preceded by a stack of sections. 

The `slidechanged` is not fired at all.

See this codepen: https://codepen.io/martino/pen/dyLGRmp?editors=1011

**Comment by hakimel** [comment]
Thanks for reporting Martino. Are you seeing this every time or intermittently?

I tried your demo as well as my local copy of reveal.js, but the last slides is being logged in both. Tried Chrome + Safari.

**Comment by Martinomagnifico** [comment]
I see it sometimes when actually scrolling, and **always** when clicking the 'down' button to navigate.

**Comment by hakimel** [comment]
I'm seeing the issue when pressing the down arrow too, thanks. Will debug and get back to you.

**Comment by hakimel** [comment]
Fixed now!
