### ISSUE TITLE
Absolute position in slide causes flashing

### ISSUE THREAD

**Issue by PDLDYNAMICS** [hakimel/reveal.js#380]
Hi,

I know this may be a browser issues but though id ask just in case...

If I place a container div in a slide and position items absolute within that container as the slide transitions the container flashes,  only seems to occur with absolute.

I have just put a work around in to fade in the item after the transition but just wondering if there were any other work arounds?

**Comment by Timidfriendly** [comment]
I have the same flashing issue on a slide containing an animated GIF

**Comment by bnjmnt4n** [comment]
Flashing seems to indicate some browser rendering issue, maybe you could try to optimize it by accelerating it to the GPU layer - maybe using `will-change` or `translate3d`.
