### ISSUE TITLE
Change the style transition between two slides?

### ISSUE THREAD

**Issue by xbelanch** [hakimel/reveal.js#39]
Is there any exemple of how can I change the default transition style for a specific slides? Can I define a "local transition style" between two slides?

Thanks for advance!

**Comment by patrickallaert** [comment]
Bump. Same question as @arnekeunecke about vertical slides... Thanks!

**Comment by jonkri** [comment]
+1

**Comment by hakimel** [comment]
When I try this on master `data-transition` is working with vertical slides. Source of the presentation I tested:

```html
<html>
	<head>
		<link rel="stylesheet" href="css/reveal.css">
		<link rel="stylesheet" href="css/theme/black.css">
	</head>
	<body>
		<div class="reveal">
			<div class="slides">
				<section>Slides in</section>
				<section>
					<section data-transition="fade">Slides horizontally<br>Fades vertically</section>
					<section data-transition="fade">Fades vertically #2</section>
					<section data-transition="fade">Fades vertically #3</section>
				</section>
				<section>Slides in</section>
			</div>
		</div>
		<script src="js/reveal.js"></script>
		<script>Reveal.initialize();</script>
	</body>
</html>
```

**Comment by s-bernard** [comment]
I found that "zoom" transition is not working on vertical slides but working well on horizontal ones.

On the contrary, "fade" is working on both kind.

**Comment by robertop87** [comment]
I am using Polymer and I have everything working, excepts the transitions, it just works when I use keyboard.

**Comment by robertop87** [comment]
HELP, I see that transitions are just working when I use a keyboard and if a press left, and work too when is the last slide.
@hakimel any idea about this?
