### ISSUE TITLE
Recommended remote/clicker?

### ISSUE THREAD

**Issue by raboof** [hakimel/reveal.js#390]
Not really an 'issue' but this seemed like a reasonable place for this question.

I've recently given my first 2 presentations with reveal.js slides and absolutely love it.

Can you recommend a USB remote clicker to go with reveal.js? Most only appear to have left/right buttons, not up/down. 

Of course I could use my smartphone but that introduces too many variables for me to be comfortable with (even though being able to read notes off my smartphone is pretty cool).

I'd really love to have a remote that can (be configured to) emit proper left/right/up/down keypresses, without needing software to re-map some keys while presenting.

**Comment by henning-koch** [comment]
Here is a presenter that has 4 directional buttons (up, right, down, left):
https://www.amazon.de/Aplic-Presenter-kompatibel-Desktop-PC-Media-Player/dp/B01LLLJY9Y/ref=cm_cr_arp_d_product_top?ie=UTF8

You might also want to consider a very small keyboard (held like a gamepad) that has accessible cursor keys:
https://www.amazon.de/SEGURO-Wireless-Schnurlos-Kabellose-Multimedia-Tasten/dp/B01L25KD30/

**Comment by brendancooley** [comment]
It's a little clunky, but this universal remote works out of the box: https://www.amazon.com/gp/product/B014R8EAPG

**Comment by 404answernotfound** [comment]
Not sure if anyone is still wondering about nice remote presenters but I bought this one and it works perfectly with all major softwares for presentations and reveal.js!

https://www.amazon.it/gp/product/B07NM2PR9Z/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1
