### ISSUE TITLE
Editing and Serving Locally

### ISSUE THREAD

**Issue by alexy** [hakimel/reveal.js#399]
I'd like to develop my presentation locally, in a separate markdown file included from the main index.html per README.  Do I have to run my own local webserver or is there a grunt config to do that?  Do I have to hit reload for preview or would grunt reload?  When I'm done, what is the minimal set of files I need to upload to an external hosting server to have my presentation available globally?

**Comment by maxmeyer** [comment]
@alexy Maybe you are happy using [`middleman-presentation`](https://github.com/fedux-org/middleman-presentation) for this. It's based on `reveal.js` and supports as much files as you want to split up your presentation. But it's implemented in `ruby`.

And if you hesitate to install and run a webserver. This is provided by `middleman-presentation` as well - ok from `middleman`. And if you want to give away your presentation, you can add [`local_webserver`](https://github.com/fedux-org/local_webserver) to your presentation-archive. This is a webserver serving the directory in which it was placed. There are pre-compiled executables available - see the README.md for this.

Both projects are developed by me to serve `reveal.js`-presentations + some additions to make creating presentations much more comfortable.
