### ISSUE TITLE
Disable arrow keys and enable only page up and page down

### ISSUE THREAD

**Issue by eusonlito** [hakimel/reveal.js#401]
There are any way to disable arrow keys and enable only page up and page down?

I have a presentation with several sublevels, but I want that users only can view the presentation in order, no jumps allowed because is in live and can be confused to assistants.

Can be some thing like force arrow next and arrow down to work always as page next and arrow up and arrow previous work as page previous?

Regards!

P.D.: Great work!!

P.D. 2: This is my presentation http://anavallasuiza.com/share/presentations/conecom-2013/ to expose in 24 april in a m-commerce conferences.

**Comment by peter-kehl** [comment]
Suggest https://revealjs.com/config > `keyboardCondition`. That function receives an `event` parameter. See https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_key_values and related.
