### ISSUE TITLE
Presenter mode

### ISSUE THREAD

**Issue by kuba-orlik** [hakimel/reveal.js#404]
It would be cool if the user was able to add notes to each slide and then open the presentation in two separate windows, one with the full-screen presentation (that would be displayed on the projector) and one with previews of current/next slides and notes for current slide (that would be displayed on a computer screen only the speaker can see.

**Comment by ronilaukkarinen** [comment]
Hello! I noticed this yesterday with macOS Mojave. Had to keep browser minified during my presentation because of this. Any workarounds?

**Comment by ronilaukkarinen** [comment]
It seems currently only way to do this is to check "Displays have separate spaces":

![Screenshot](https://i.imgur.com/w0xCNPN.png)
