### ISSUE TITLE
fullscreen video or image

### ISSUE THREAD

**Issue by ghost** [hakimel/reveal.js#440]
Hallo could you please help me to use a fullscreen image or youtube video as background? it seems not working properly with this beautiful plugin and im not so deep inside html5 ;( thanks a lot!

**Comment by astorije** [comment]
> Check this out for more info http://www.raymondcamden.com/index.cfm/2012/7/23/Adding-a-background-image-to-a-revealjs-presentation

This is now a 404 😢
@jonlow, do you happen to have an alternative link or snippet?

**Comment by egrosclaude** [comment]
seems to be https://www.raymondcamden.com/2012/07/23/Adding-a-background-image-to-a-revealjs-presentation

**Comment by astorije** [comment]
I ended up successfully using `data-background="img/my-image.jpg"` by the way. I haven't tried with other types of media but this worked well.

**Comment by divan** [comment]
`data-background` doesn't work with videos, but `data-background-video` does.

```html
<section data-background-video="http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4" 
              data-background-color="#000">
</section>
