### ISSUE TITLE
support for d3.js transitions

### ISSUE THREAD

**Issue by jlegewie** [hakimel/reveal.js#456]
Hi, 

it would be great if reveal.js provides better support for d3.js (and possibly vega) visualizations. The idea would be that users can embed d3.js graphs in slides (which is already possible). But the important addition is that pressing the button for next slide runs a certain transition instead of changing to the next slide. So there should be some standard way in which the user defines the container for a figure such as `<div id="fig-name" class="fig-container">`, and a standard way in which each step of the transitions are saved such an array of transition functions. reveal.js then checks each figure for transitions and instead of changing to the next slide, runs this transitions. To enable back and forth, there could be a second array of transitions that reverses the previous one. So which figure could be a javascript object a function for `create` (run at the beginning to create the vis), an array `t` with functions for each step of the transitions, and an array `t_inv` for the inverse functions that revers the transitions. 

Does that make any sense? I think it would be a beautiful way to add dynamic visualizations to presentations and d3.js (and possibly vega) are just the right tools for that!

**Comment by demoneaux** [comment]
Closing this for now as there’s a working demo of this. Feel free to implement this as a plugin.

**Comment by flying-sheep** [comment]
nice. in modern:

```js
import Reveal	from 'reveal.js'

export default function registerD3Slides(config) {
	Reveal.addEventListener('slidechanged',	e => handleEvent(config, true))
	Reveal.addEventListener('fragmentshown',	e => handleEvent(config, false))
	Reveal.addEventListener('fragmenthidden',	e => handleEvent(config, false))
}

function handleEvent(config, isSlideEvent) {
	const currentSlideId = Reveal.getCurrentSlide().id
	const currentFragment = Reveal.getIndices().f
	
	if (!currentSlideId || !(currentSlideId in config))
		return
	
	const functions = config[currentSlideId]
	
	if (isSlideEvent && 'init' in functions) {
		functions.init()
		delete functions.init
	}
	
	if (currentFragment in functions) {
		functions[currentFragment]()
	}
}
```

**Comment by gcalmettes** [comment]
very useful, thanks @ptamarit.

**Comment by jlegewie** [comment]
Has anyone worked on this more? A Reveal plugin for @ptamarit solution would be great.

**Comment by jlegewie** [comment]
I put together a reveal.js plugin that integrates d3.js with transitions seamlessly into reveal.js presentations. The plugin is [here](https://github.com/jlegewie/reveal.js-d3js-plugin).

Here is a [demo](http://jlegewie.github.io/reveal.js-d3js-plugin/demo/index.html).

**Comment by flying-sheep** [comment]
it’s broken: [“event” is not defined](https://github.com/jlegewie/reveal.js-d3js-plugin/blob/aa804f44755e22f2d2520f1340c05354bd4ddf00/d3js.js#L69)

**Comment by jlegewie** [comment]
Should be fixed...

**Comment by ptamarit** [comment]
@jlegewie: you should add a link to your project in the [Plugins page](https://github.com/hakimel/reveal.js/wiki/Plugins,-Tools-and-Hardware).

**Comment by gcalmettes** [comment]
I have been inspired by @jlegewie's work and I made a D3 plugin that fully support the Reveal fragments. It also plays back the last transition when navigating back from another slide to render the last state of the visualization. The plugin itself doesn't have any `D3` dependencies and could be used for any other javascript visualization library. See the [repo](https://github.com/gcalmettes/reveal.js-d3) and [demo](https://gcalmettes.github.io/reveal.js-d3/demo/).
