### ISSUE TITLE
Loop: true and autoSlide correctly display fragment roll-in only the first time.

### ISSUE THREAD

**Issue by BillBradwohl** [hakimel/reveal.js#473]
I'm working on a presentation that will scroll continuously in a kiosk environment. 

```
     <section>
        <h2>What we offer:</h2>
        <p class="fragment roll-in">Porsche</p>
        <p class="fragment roll-in">BMW</p>
        <p class="fragment roll-in">Ferrari</p>
     </section>
```

Under non loop conditions, and the first time through under loop conditions it plays as expected. All other times through the loop, the roll in is not done as all items are already rolled in and fully visible when the slide loads.

**Comment by MohammedAmine** [comment]
Thanks, worked !
