### ISSUE TITLE
CLI print pdf

### ISSUE THREAD

**Issue by quasiben** [hakimel/reveal.js#482]
Is there any recommended method for command line pdf printing?  I've looked at both wkpdf and wkhtmltopdf and neither worked very well

**Comment by pintman** [comment]
"PhantomJS development is suspended..." I read on their [webpage](http://phantomjs.org/).  Is there any alternative?

**Comment by aflueckiger** [comment]
It is already an old issue, may other people end up here as well: 
Check out this: https://github.com/astefanutti/decktape
