### ISSUE TITLE
Consider publish to npm registry

### ISSUE THREAD

**Issue by webpro** [hakimel/reveal.js#506]
@hakimel, would you consider publishing reveal.js to npm?

I think it opens up some nice possibilities. After `npm install -g revealjs`, e.g.:
- `node plugin/notes-server` could become `reveal-notes`
- `node plugin/multiplex` could become `reveal-multiplex`

Apart from that, I now have a "reveal-md" server running, which does the following:
1. `reveal-md example.md` opens the default browser with slides from `./example.md` in the current folder (using `plugin/markdown`).
2. `reveal-md` opens the default browser and shows all Markdown files recursively in the current folder (e.g. `**/*.md`) which are directly linked to open like 1)
3. Probably it would be easy to also support e.g. `reveal example.html` to open any HTML reveal slide file.

It's like a "Markdown server" to open Markdown files as reveal slides. My "plugin" could be put in a separate repository, or included as a plugin in this repo.

In any case, to be able to make all of this happen, it's great if reveal.js is in the npm registry. How about it?

**Comment by jzf2101** [comment]
Will later versions be published to npm?

**Comment by hyunwoona** [comment]
https://www.npmjs.com/package/reveal.js doesn't show up when I google 'reveal.js npm'. Is there a way to make it appear on the top of the search results?

**Comment by theGABS** [comment]
>https://www.npmjs.com/package/reveal.js doesn't show up when I google 'reveal.js npm'.
The same trouble. First I found that discussing, and only after it I found 'reveal.js npm'
