### ISSUE TITLE
Idea: Simplify workflow for presentation author

### ISSUE THREAD

**Issue by docwhat** [hakimel/reveal.js#511]
Currently, the workflow for a new slide deck is a bit of a pain:
1. Clone the repo.
2. Edit the `index.html`
   1. Set the author and description.
   2. Edit the configuration if desired.
   3. Remove all the demo slides.
   4. Reformat if you don't like the HTML indentation.
3. Remove the `.git` directory.
4. `git init`
5. Commit your initial state.
6. Start working on the slides.

Updating `reveal.js` on a slide deck you've already created is also a pain (because of above).

Ideally, the workflow would be something like:
1. Install `reveal.js` (`git clone`? Or maybe `curl http... | bash`?)
2. Run a command to create your new slide deck: `reveal-js init myslides`
   1. It asks for Author (or uses system values to get it)
   2. Asks for description
3. `cd myslides`
4. `$EDITOR slides.html` or `$EDITOR slides.md`

Optionally, the author might:
- Edit `config.js` to change Author, Description, or the configuration.

The only files in the `myslides` directory should be the bare minimum to run the site dynamically.  It doesn't have to be efficient to load! If they want efficiency then a static site should be generated.
- `slides.html` or `slides.md`
- `config.js`
- `index.html` -- a bare template that loads everything else.

If the author wants to make the site static, e.g. for archiving or sharing, there should be a command to do this: `reveal-js freeze static-directory-name`

I posted  this issue because I wasn't sure if it was something that should be reveal.js itself, or if it is something that should be external to reveal.js that consumes reveal.js.

If it is the latter, I might do it myself using ruby.

**Comment by anantshri** [comment]
I have attempted to solve a simmilar problem using my limited bash skills. a blog post highlighting what i have done is here http://blog.anantshri.info/automated_revealjs_setup and github repo of the same : https://github.com/anantshri/automated_revealjs/

Basically i am using external-markdown for presentation creation and keeping reveal.js seperately in filesystem and runtime linkage allows for smother workflow.

I am working on a more simpler version where pre cloning of script would also not be required and we can keep stuff much neater and cleaner.

**Comment by rparree** [comment]
Hi,

Just our approach to this:

- Installed reveal as a bower package (left untouched)
- using assemble.io to relief presentations from having the reveal
boilerplate
- generate presentations using gulp/assemble.io

I can't share that repo, but have  isolated the solution and push it to:
https://github.com/edc4it/revealjs-assemble




Raphaël Parrée
EDC4IT Europe BV
(m) +33 673 75 34 62
@rparree <https://twitter.com/intent/user?screen_name=rparree> | LinkedIn
<http://fr.linkedin.com/in/rparree>


On Tue, Feb 3, 2015 at 5:37 AM, Anant Shrivastava <notifications@github.com>
wrote:

> I have attempted to solve a simmilar problem using my limited bash skills.
> a blog post highlighting what i have done is here
> http://blog.anantshri.info/automated_revealjs_setup and github repo of
> the same : https://github.com/anantshri/automated_revealjs/
>
> Basically i am using external-markdown for presentation creation and
> keeping reveal.js seperately in filesystem and runtime linkage allows for
> smother workflow.
>
> I am working on a more simpler version where pre cloning of script would
> also not be required and we can keep stuff much neater and cleaner.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hakimel/reveal.js/issues/511#issuecomment-72591544>.
>

-- 
EDC4IT Europe BV is a company registered in the Netherlands. Registered 
number: 58704663. Registered office: Leeghwaterstraat 25, 2811 DT Reeuwijk. 
| This communication is for use by the intended recipient and contains 
information that may be privileged, confidential or copyrighted under 
applicable law. If you are not the intended recipient, you are hereby 
formally notified that any use, copying or distribution of this e-mail, in 
whole or in part, is strictly prohibited. Please notify the sender by 
return e-mail and delete this e-mail from your system. Unless explicitly 
and conspicuously designated as " E-Contract Intended", this e-mail does 
not constitute a contract offer, a contract amendment, or an acceptance of 
a contract offer. This e-mail does not constitute a consent to the use of 
sender's contact information for direct marketing purposes or for transfers 
of data to third parties. | info@edc4it.com.

**Comment by ashneo76** [comment]
Hi,

I have written a python tool that allows you to write the entire presentation as a YAML file. It converts that into the HTML file, just like in the template. All you need to do is drop the generated HTML file in the code checked out from this repo and use 'grunt serve'

YAML source: http://src.ashishshah.net/yaml_reveal
Website source: http://src.ashishshah.net/presentations

**Comment by ashneo76** [comment]
I also updated the Gruntfile.js to live reload any .htm file as well. I am working to automatically generate the HTML file when the yaml source changes.

**Comment by jonhoo** [comment]
I find that I usually do the same as @berteh, namely "include" reveal as a submodule, and then link to it from an HTML file in the parent directory. The big drawback of this is that speak notes don't work as the Gruntfile expects the presentation to be in the same directory as reveal. My current solution is to

```cp -r index.html reveal.js/index.html; cd reveal.js; grunt serve; cd ..```

But this is not particularly satisfactory. The ability to `grunt serve` and pass it a path to the `.html` file would be much nicer.

**Comment by demoneaux** [comment]
Thanks for all the info! I feel that this issue should be closed after 3 years of stagnation, as we want to keep the Reveal core lean, so we want to offload such code to other tools. Any useful tools should be added to [this page](https://github.com/hakimel/reveal.js/wiki/Plugins,-Tools-and-Hardware) to be shared with others.
