### ISSUE TITLE
data-background attribute not working

### ISSUE THREAD

**Issue by shammellee** [hakimel/reveal.js#518]
The following doesn't seem to work. Am I missing something?…

```
<section data-background="#FF0000">
  <h2>Hello!</h2>
</section>
<section>
  <h1>Goodbye!</h1>
</section>
```

**Comment by marcstober** [comment]
Just in case anyone stumbles across this as I did, quotes and parentheses in the background image URL need to be escaped with a backslash or the attribute also won't seem to work. Basically you're following the rules for an unquoted URL in the CSS url() syntax, some info here: http://stackoverflow.com/questions/2168855/is-quoting-the-value-of-url-really-necessary?lq=1
