### ISSUE TITLE
named internal links?

### ISSUE THREAD

**Issue by benjythehunted** [hakimel/reveal.js#55]
I know we can internally link to a numbered slide (href="#/2"), but is there a way to give anchor names to slides, so that if I move a slide that is linked to, I won't have to also change the link?

Thanks so much for this, by the way...fantastic work.

**Comment by mrmanc** [comment]
This is awesome.

Is there any way to use this feature to link to a specific slide when you are [using Markdown](https://revealjs.com/markdown/) to author your slides? I tried adding things like `<!-- .slide: id="some-name" -->` but I couldn’t see it appear on the rendered section element in the DOM. Apologies if I’m being naive!

My solution in the meantime is to take advantage of the fact that each heading is given a lower-kebab-case id which I can link to, but this is a little more fragile as the link breaks when the heading changes.
