### ISSUE TITLE
Embed Option

### ISSUE THREAD

**Issue by bretterer** [hakimel/reveal.js#552]
I would love the ability to embed Reveal inside of a div so it does not take up the full screen. This would be useful in putting reveal slides within a blog post.

**Comment by drewpotter** [comment]
Does this feature, reveal.js inside a div, have basic functionality? And how can I try it out?

**Comment by rundef** [comment]
any updates on this ?

**Comment by sascha1337** [comment]
+1 .. please PLEASE add embed div inline mode that i can append in bootstrap column

**Comment by sergioedo** [comment]
+1

**Comment by annasimoniaine** [comment]
+1 yes please add this

**Comment by QHose** [comment]
+1

**Comment by hyunwoona** [comment]
+1

**Comment by glfmn** [comment]
It works on [slides.com](https://slides.com/angiejones/code-reviews#/), why can't we do it here?

**Comment by Martinomagnifico** [comment]
Embedding presentations was included as a new feature in version 4.0.0. See https://github.com/hakimel/reveal.js/releases/tag/4.0.0
