### ISSUE TITLE
External Markdown doesn't work in reveal.js-2.4.0

### ISSUE THREAD

**Issue by paulvi** [hakimel/reveal.js#559]
External Markdown doesn't work in reveal.js-2.4.0 from https://github.com/hakimel/reveal.js/releases

```
        <div class="slides">

            <section data-markdown="markdown.md" data-separator="^\n\n\n" data-vertical="^\n\n"></section>
```

markdown.md file is

```

## Test1

test2

```

I get error

```
ERROR: The attempt to fetch markdown.md failed with the HTTP status 0. Check your browser's JavaScript console for more details.

Remember that you need to serve the presentation HTML from a HTTP server and the Markdown file must be there too.
```

In web console

```
[16:05:05.726] not well-formed @ file:///C:/Users/weibl/git/businessmodelsharing/reveal.js/markdown.md:2
```

![reveal-markdonw-error](https://f.cloud.github.com/assets/1614482/967653/1d4c7f1e-0582-11e3-9fb5-4db9f912b7c7.png)

From REAME.md
#### External Markdown

You can write your content as a separate file and have reveal.js load it at runtime. Note the separator arguments which determine how slides are delimited in the external file.

``` html
<section data-markdown="example.md" data-separator="^\n\n\n" data-vertical="^\n\n"></section>
```

What is the problem with external Makrdown?

**Comment by IroNEDR** [comment]
Is there a workaround for this, if I am using it in combination with Github Pages? I get the same error.

**Comment by noraj1337** [comment]
it works with grunt but not with others web servers, I can't host my presentation.

**Comment by johnwry** [comment]
Has anybody got this to working by any chance?

**Comment by paulvi** [comment]
Open new issue, this one is 7 years old

welcome to reference here though

**Comment by ooker777** [comment]
Get this problem at 2024: https://github.com/hakimel/reveal.js/issues/3653
