### ISSUE TITLE
Support for external HTML

### ISSUE THREAD

**Issue by Crell** [hakimel/reveal.js#572]
It's great that Reveal.js supports including partial files using Markdown.  However, I don't use Markdown.  I prefer to work in straight HTML.  It would be very helpful to have the same capability for straight up HTML, especially if it can be done client side.

My first thought is XInclude, which although it's a pure-XML tool should work fine with well-written HTML.  I don't know of any browsers that support XInclude tags natively, but it looks like Mozilla has some sample code that could do it:

https://developer.mozilla.org/en-US/docs/XInclude

I haven't tried using it yet, but I'd definitely love to see such a feature.

(Background: My company is starting up training offerings and I'm pushing for us to standardize on Reveal.js for them to make it easier to collaborate on slides via Git, but some people dislike having 3 people's slides all in one file.  If we could break them out by "chapter" (first-level section) that would make it easier to collaborate as well as easier to mix-and-match chapters for different presentations.)

Thanks for the great tool!

**Comment by yorch** [comment]
You can use HTML inside Markdown, so you would just need to enclose all the content of the `md` file in an HTML tag (like `<div>` or `<section>`):

    <section data-markdown="section-1.md"></section>

Where `section-1.md` is:

    <div>
      <h2>Title</h2>
    </div>

**Comment by Crell** [comment]
It looks like Cal Evans has a simple solution here: https://blog.calevans.com/2015/12/09/load-external-html-into-reveal-js-presentations/

I've not tried it yet, but he references this issue. :smile: @hakimel, your thoughts? Is that a good approach? Should it be left as a stand-alone script or is it simple enough that it makes sense to fold in?

**Comment by demoneaux** [comment]
@calevan’s solution seems fine. Closing this for now since there’s a plugin for it.

**Comment by maxnoe** [comment]
@bnjmnt4n The linked solution is no longer available

**Comment by sam-crawley** [comment]
@maxnoe The repo is still available: https://github.com/calevans/external

**Comment by nathan-fourrier** [comment]
For anyone wondering how to include files, there is my little tip.
Modify the initializing of reveal from that 

```javascript
 Reveal.initialize({
          hash: true,
          plugins: [RevealMarkdown, RevealHighlight, RevealNotes],
        });
``` 
to this 

```javascript
      function loadIncludes() {
        return Promise.all(
          [...document.querySelectorAll("include")].map((include) => {
            return fetch(include.getAttribute("src"))
              .then((response) => response.text())
              .then((html) => (include.outerHTML = html))
              .catch(console.err);
          })
        );
      }
      loadIncludes().then(() => {
        Reveal.initialize({
          hash: true,
          plugins: [RevealMarkdown, RevealHighlight, RevealNotes],
        });
      });
``` 
Basically it replace all the include tag by the content of the file at the specified src, and all of this before the revealjs proccess. (btw "include" and "src" could be replaced by whatever you want)

So you can use it like below 

```html
 <div class="reveal">
      <div class="slides">
        <include src="src/html/intro/section0.html"/>
      </div>
 </div>
```

**Comment by Chostakovitch** [comment]
Hi @nathan-fourrier, thanks for your amazing solution :)
Just a quick note : custom tags require a closing tag because only a [few elements](https://html.spec.whatwg.org/multipage/syntax.html#syntax-elements) are allowed to self close. Browsers will interpret self-closing custom tags as an opening tag.
