### ISSUE TITLE
Auto start slideshow

### ISSUE THREAD

**Issue by dottodot** [hakimel/reveal.js#59]
Does this have the ability to start automatically and go through the slides without using the controls?

**Comment by Rubel-hossain** [comment]
Yes it's possible , you can try it...........

         // Slide every five seconds
          Reveal.configure({
        autoSlide: 5000
          });

**Comment by vinitpatel03** [comment]
is it possible to apply autoslide for each slide?
i.e 
for first slide - 2 sec
for second - 3 sec

**Comment by trondkla** [comment]
@vinitpatel03 check out  data-autoslide attribute:
<section data-autoslide="1000">

**Comment by AliHid** [comment]
Hey,, I am sorry, is it possible to put animated gif in it?

**Comment by robertop87** [comment]
I have enable autoSlide for a video slide.

The video duration is 10 seconds, and my autoSlide 3, but currently the video still playing until finished it.

@hakimel any idea to solve this???

**Comment by florentroques** [comment]
for automatically going to next slide after youtube video (loaded by iframe) has ended:

```javascript
var tag = document.createElement('script');
tag.src = "//www.youtube.com/player_api";
var firstScriptTag = document.getElementsByTagName('script')[0];
firstScriptTag.parentNode.insertBefore(tag, firstScriptTag); 

function onYouTubeIframeAPIReady() {
  function onPlayerStateChange(event) {
    if (event.data == YT.PlayerState.ENDED) {
      Reveal.next();
    }
  }

  function createYouTubePlayersEventListeners() {
    var selectors = [
      ".slide-background-content > iframe[data-src*='www.youtube-nocookie.com/embed/']"
      ,".slide-background-content > iframe[data-src*='www.youtube.com/embed/']"
    ].join(', ');
    var iframeYouTubePlayers = document.querySelectorAll(selectors);

    iframeYouTubePlayers.forEach(function(iframeYouTubePlayer) {
      iframeYouTubePlayer.onload = function() {
        new YT.Player(iframeYouTubePlayer, {
          events: {
            'onStateChange': onPlayerStateChange
          }
        });
      }
    });
  }

  createYouTubePlayersEventListeners();         
}
```
