### ISSUE TITLE
Possible to stop animated gifs when navigate away from section?

### ISSUE THREAD

**Issue by eabigelow** [hakimel/reveal.js#592]
Hi--

I love working with reveal.js--very easy and flexible to use. Thanks so much for that!

I was wondering if it is possible to have animated gifs only play when the user navigates to the particular section that the animated gif is on? Currently, you can do this with videos (works great), but it would also be very useful if animated gifs only ran when the user was on that section were the gif is. It would make the slider work more smoothly because the gifs would not all be playing in the background.

Any thoughts about this? Or fixes? Again, thanks for the great work!

**Comment by ynuska** [comment]
How can I pause/start from that point an animated gif  ?
