### ISSUE TITLE
How to switch the horizontal sections into vertical scroll?

### ISSUE THREAD

**Issue by JeanHules** [hakimel/reveal.js#602]
I am looking to change reveal so that instead of the main sections being horizontal, that they are vertical. and so that the sub sections (<section><section>) are horizontal.

Is this possible?

I noticed:

var SLIDES_SELECTOR = '.reveal .slides section',
HORIZONTAL_SLIDES_SELECTOR = '.reveal .slides>section',
VERTICAL_SLIDES_SELECTOR = '.reveal .slides>section.present>section',
HOME_SLIDE_SELECTOR = '.reveal .slides>section:first-child',

and tried swapping the variable values, but it removes the slide transition and messes up the "Overview" state that occurs when you hit the 'Escape' key.

Any ideas on how to make it as clean as the original horizontal orientation?

**Comment by markmarijnissen** [comment]
@JeanHules I want this too! Did you solve it and are you willing to share your solution?

**Comment by brianwood** [comment]
this would be a fantastic addition to the framework

**Comment by Giovanni-Mattucci** [comment]
Not sure why this wouldn't be added, when RTL (right to left) is included.

**Comment by stevepowell99** [comment]
+1

**Comment by bnjmnt4n** [comment]
Due to the amount of work required, this feature probably won't make it into Reveal core. If you do want to experiment with vertical scrolling by default, feel free to release a [plugin](https://github.com/hakimel/reveal.js/wiki/Plugins,-Tools-and-Hardware) to share with others.
