### ISSUE TITLE
Firefox transition performance

### ISSUE THREAD

**Issue by reagle** [hakimel/reveal.js#603]
I'm using FF (23.0+build2-0ubuntu0.13.04.1 0) and when I use most of the transitions (e.g., cube and linear) the moving text exhibits jitter: vibrating up and down very quickly until it seats into its final position. The transition isn't at all smooth. Am I alone on this, can others replicate (or is this a known issue)?

**Comment by rubenCodeforges** [comment]
Same for me , found this article 
http://alexmatchneer.com/blog/2012/08/07/speeding-up-ff-css3-transform-transitions-with-rotate/

**Comment by rubenCodeforges** [comment]
FF v 37.0.2 on Ubuntu 14.04

**Comment by demoneaux** [comment]
The [Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=663776) appears to be fixed, so I’m closing this.
