### ISSUE TITLE
Exported PDF has messed up background

### ISSUE THREAD

**Issue by karolsojko** [hakimel/reveal.js#619]
When I've created my presentation on slid.es and exported it as pdf - some of the pdf readers (and also when you upload it to slideshare) it looks really messy - has this odd grid on it.

My presentation: http://slid.es/zoja87/it-should-bdd-in-practice

This is how it looks like after export: http://d.pr/i/zfuB

**Comment by demoneaux** [comment]
This is probably a problem with the exported PDF or the tool used, and not specifically with Reveal.js. Closing this for now, as Reveal.js now has better support for exporting PDFs.
