### ISSUE TITLE
Request option to use the same data-state value on successive slides

### ISSUE THREAD

**Issue by StewartNoyce** [hakimel/reveal.js#623]
I would like the option to set the same data-state on successive slides in a presentation.  Currently, a "continue stateloop" command (line 1446 in reveal.js today) kicks out of the stateloop in the slide function before dispatching the state event.  This line can be commented out as a workaround, but a longer term solution would be better for all.

Thanks,

**Comment by fuhrmanator** [comment]
I'm curious about persistent `data-state`, too. I'm using markdown and want to avoid redefining it in `<!-- slide: data-state="myStyle" -->` for each slide.  Is there a way to define this so it "sticks" for all following slides, until it's redefined? The use-case is doing sections of a presentation, where each section has a background color/icon/etc.
