### ISSUE TITLE
alignment issue (markdown)

### ISSUE THREAD

**Issue by nocquidant** [hakimel/reveal.js#629]
I am using reveal with markdown for my next presentation (great tool!) and I just noticed a mis-alignment issue. In the exemple slide below, I was expecting the three bullets to be aligned. But the first is "disconnected" from the 2 others.

Thanks.

<pre>
- Basic code fragment for a client:

    Socket client = new Socket("localhost", 1234);

- Let us send a message from the client, and have the server print it out. 
- On server, add

    InputStream inputStream = socket.getInputStream();
    InputStreamReader isReader = new InputStreamReader(inputStream);
    BufferedReader inputReader = new BufferedReader(isReader);
    System.out.println("Client wrote: " + inputReader.readLine());
</pre>

**Comment by demoneaux** [comment]
This doesn't seem to be a Reveal issue, more of a Markdown issue. Probably marked doesn't think that a single indented line is part of a code block, causing it to separate it.
