### ISSUE TITLE
Remove video when printing the slides

### ISSUE THREAD

**Issue by mrshu** [hakimel/reveal.js#637]
I was asked to provide a PDF from my talk created in reveal.js. After following the instructions I found out that the resulting PDF has 63 MB.

That's quite a lot.

Later I realized that there were some videos included in my talk and that they actually increased the size of the resulting PDF rapidly.

So I believe that the videos (i.e. every video tag) should be removed in the print style sheet. I haven't tested it yet but just givint the video tag display:none might help in this case.

**Comment by hussam1soufi** [comment]
Hello @hakimel , I'm a fan of your work.
quick question,
if  i would to remove each video in the PDF and substitute it with a link. how can i do that (even if the video was from Youtube with the tag <iframe>.
