### ISSUE TITLE
Fragment differential timing

### ISSUE THREAD

**Issue by danowen** [hakimel/reveal.js#653]
As Hakim said today all markup with class="fragment" are displayed for the same amount of time, namely autoSlide: #### in millliseconds. Since this value is designated once, all slide fragments (and non-fragmented slides) are of the same duration.

Would it be possible to have the value of autoSlide point to an XML file through a class or ID? Or could a new variable be added like specificSlide (with an arbitrary time indicated) to allow autoSlide to be overridden on a case by case basis?

If one wanted to provide individual duration control on a slide by slide and fragment by fragment basis what would be the best way to go about it?

Contrarily, is there something about reveal.js that would prevent this altogether no matter what the design approach?

Thank you.

**Comment by bailz** [comment]
Can you please advise if there is support for multiple <li> autoslide elements?

The following configuration does not appear to work

 <ul>
    <li class="fragment" data-autoslide="5000">1</li>
    <li class="fragment" data-autoslide="5000">2</li>
    <li class="fragment" data-autoslide="5000">3</li>
</ul>

Thank you
