### ISSUE TITLE
Provide workarounds for local files (offline mode)

### ISSUE THREAD

**Issue by nwin** [hakimel/reveal.js#673]
This is related to #610. I think it is an important issue because a presentation has to be usable offline from a random computer. Unfortunately it is impossible to fix that bug since it depends heavily on the browser. Luckily workarounds exist and a manual how to use them should be provided instead of this error message. 

I could make a pull request for that but first I wanted to collect the workarounds for different browsers/OSes

Mac: 
Safari: Developer menu->Disable local file restrictions (tested)
Chrome: start with: --disable-web-security ()
Firefox: works

**Comment by Lucas-C** [comment]
Here is a workaround that may be useful to others: https://chezsoi.org/lucas/blog/2016/10/12/en-server-less-reveal-js-slides/

**Comment by jaxne** [comment]
I came across an iOS app -- [HTML Presenter](http://www.htmlpresenter.com/)  that allows you to load your reveal.js presentation offline after they are synced and cached.  It uses a DropBox folder to sync your presentations. Took me about 10 min to setup, connect to DropBox,  zip up my reveal.js presentation files, and sync to the app. I had the presentation loaded full screen on my iPad and running and it works great. Just an FYI for anyone looking to present on iOS offline. The standard app is $4.99 -- Pro is $24.99
