### ISSUE TITLE
"in" and "out" transiton definitions

### ISSUE THREAD

**Issue by srigi** [hakimel/reveal.js#674]
Sometimes I need to present code evolution - on first slide there is a basic code, then there is some change highlighted on next slide. Between this two slides should be no transition so I set `data-transition="none"` on both.

But by this first slide is not nicely animated when I navigate to it from prev. slide. And so the second slide in not nicely kick-outed when moving to next section.

Best demonstrated on [live example](http://plnkr.co/edit/Uhh6osTzhFjObopyudCG?p=preview). Ad you can see code on second slide kicks-in not nicely. Then there is code evolution demonstration and then code kicks-out without animation.

I propose:
- new transition definition `data-transition-in` & `data-transition-in`
or
- some kind of logic between when two `data-transition` definitions meets on sibling slides.

**Comment by obama** [comment]
+1

**Comment by hakimel** [comment]
Support for separate in/out transitions was added by @jammon in #1106
