### ISSUE TITLE
Zoom in then out moves slide transition controls out of browser window

### ISSUE THREAD

**Issue by ugm6hr** [hakimel/reveal.js#679]
FF22.0 on Windows XP, 1280x1024 screen (maximised window)
To reproduce: Zoom in (Alt+click) then zoom out (alt+click)
Effect: Slide transition controls in bottom right corner reappear lower than initially, so only up-arrow is visible.
Expected effect: Slide transtion controls should reappear in bottom-right corner, in identical location to prior to zoom.

This stops moving to next / previous slide after any zoom. Resizing browser window has no effect.

**Comment by demoneaux** [comment]
Can't reproduce this issue on recent Firefox builds, closing for now.
