### ISSUE TITLE
Transition End Event

### ISSUE THREAD

**Issue by Colir** [hakimel/reveal.js#694]
Hi,
i would like to know if there is an Event fired when a slide transiton end.

thanks a lot.

**Comment by silversonicaxel** [comment]
This could be a quick solution, but it's necessary to create a hook for IE9, becaue it does not support transitions, so it will never enter in the end slide event.


```
      var b_check_sections = {};

      // Event start load section on slide
      Reveal.addEventListener('slidechanged', function(event) {
        var sectionID = Reveal.getCurrentSlide().id;
        b_check[sectionID] = true;        
      });

      // Event end load section on slide
      $(".reveal .slides").on('transitionend webkitTransitionEnd oTransitionEnd otransitionend MSTransitionEnd', function(event) {
        var sectionID = Reveal.getCurrentSlide().id;

        if(b_check[sectionID]){
          /* your code for transition end */

          b_check[sectionID] = false;
        }
      });
```

**Comment by phiresky** [comment]
I think it would be great to have an option to start loading lazy content (i.e. embeds) after the transition has finished to avoid frame skipping

**Comment by Martinomagnifico** [comment]
This is in Reveal since 4.0.0. 

This issue can be closed.

**Comment by hakimel** [comment]
More info at https://revealjs.com/events/#slide-transition-end
