### ISSUE TITLE
zoom does'nt work with alt key

### ISSUE THREAD

**Issue by flyinva** [hakimel/reveal.js#700]
Tested with chromium 30.0.1599.10 and firefox 27.0a2 :+1 on debian: 

I had to replace alt key by shift in zoom.js because event.altKey return always false. With alt key pressed, mousedown event doesn't seem to be triggered.

**Comment by reagle** [comment]
It would be good if zoomKey was documented. I'd like this to be supported by pandoc.

**Comment by reagle** [comment]
FYI: gm/pandoc#4249 adds configuration for this. It'd still be nice if this was documented.
