### ISSUE TITLE
Moving text to border of screen

### ISSUE THREAD

**Issue by lcottereau** [hakimel/reveal.js#710]
I am trying to devise CSS properties to move content to the border of the screen. Two use cases are : 
- a copyright notice when the background image has a license requiring it
- the title when I have a slide with just title and image and I don't wan't the title in the middle

I have tried `position:absolute` but this just moves the content inside the `<section>` which does not fill the screen.

Is that possible with the current HTML design of the page ? If so, could anybody point me in the right direction ? If not, would you please consider doing the necessary changes ?

**Comment by rofrol** [comment]
My solution https://github.com/hakimel/reveal.js/issues/180#issuecomment-173543708
