### ISSUE TITLE
Print with notes

### ISSUE THREAD

**Issue by lcottereau** [hakimel/reveal.js#719]
I would love to print the presentation with (when available) a page of notes for each page of slide.

**Comment by anantshri** [comment]
this would be an awesome addition. We can also think around having a layout where first half of page is occupied by slide and second half contains the slide notes and all that could be css controlled. this way if someone wants to distribute visual style slides it would be very easy for them.

**Comment by demoneaux** [comment]
You can [enable the `speakerNotes` option when printing](https://github.com/hakimel/reveal.js#share-and-print-speaker-notes)/

**Comment by lcottereau** [comment]
bravo !
