### ISSUE TITLE
Add fragment "strike"

### ISSUE THREAD

**Issue by pnsantos** [hakimel/reveal.js#737]
Hi, I don't know if there's a "nice way" to do this now, but it would be nice if one of the available options for fragment was to "strike" the text (i.e. identical effect to putting the text within the fragment between the &lt;del&gt; tag).

Something like this:

```
<p class="fragment strike">strike</p>
```

First:

strke

Then:

~~strike~~

**Comment by fgather** [comment]
I can confirm the issue. It is broken in the latest release. 
As a workaround I added "visibility: visible;" in the scss to the corresponding .fragment.strike class definition.

**Comment by hakimel** [comment]
Thanks for reporting. This has been fixed in dev – the fragment is now visible before being striked out.

**Comment by fgather** [comment]
thanks for the extremely fast response! (And for the great presentation framework)
