### ISSUE TITLE
'?' to show keyboard shortcuts

### ISSUE THREAD

**Issue by docwhat** [hakimel/reveal.js#743]
Can we add a `?` keyboard command to show all the keyboard keys?

I don't always remember them all and it'd be handy to have the definitive list from reveal.js itself.

Ciao!

**Comment by Delapouite** [comment]
Hi @navateja, did you make any progress on this help menu so far? Thanks

**Comment by navateja** [comment]
@Delapouite IIRC, it was merged to dev branch quite sometime back. Here's the PR for your reference
https://github.com/hakimel/reveal.js/pull/943

**Comment by hakimel** [comment]
Yep, this was released with 3.0 and can be tested by pressing the '?' key at http://lab.hakim.se/reveal-js

**Comment by Delapouite** [comment]
Great news! Thanks to both of you. So I guess this issue can be closed?

**Comment by hakimel** [comment]
Oh yeah, closed!

**Comment by VladimirAlexiev** [comment]
Thanks @hakimel , but could you include more of the info from http://vladimiralexiev.github.io/reveal.js/reveal-help.html? Eg
- PgUp, PgDown are not mentioned
- SPACE doesn't do exactly the same as N
