### ISSUE TITLE
Automatically Appearing Fragments based on Time

### ISSUE THREAD

**Issue by chrisspiegl** [hakimel/reveal.js#744]
Is there a way to let fragments appear automatically based on a time.

Something like:

```
<p class="fragment fade-in" data-autotransition="500">I am the text that will appear 0.5 seconds after the last fragment or slide appeard</p>
```

This would be very helpful.

**Comment by alanafoleykeane** [comment]
Is there a way to load fragments automatically when in the viewport rather than on click?
