### ISSUE TITLE
Fullscreen video/iframe

### ISSUE THREAD

**Issue by uhaveamsg** [hakimel/reveal.js#751]
Is this possible, i applied the class="stretch" but it seems to be still not taking the full width & height of the slide.

**Comment by laishi** [comment]
I use 
<section>
<iframe frameborder=0 width=95% height=586 marginheight=0 marginwidth=0 scrolling=no src="pages/music.html"></iframe>
</section>

give me  width 960 ,  I want width 95% in my page,how can fix it!

**Comment by hakimel** [comment]
Closing. This is in master since 3.0 was released.

**Comment by amenk** [comment]
You mentioned it is in master, but was is the way now to do an iframe as background but with controlls enabled? Can't seem to find it in the docs. data-src is mentioned to work only without being able to controll the iframe contents. And `class="stretch"` does not use the full screen, but only the max slide content width.

**Comment by nevesnunes** [comment]
If anyone wants background video with controls, you can apply this workaround:

```js
(new MutationObserver(function(mutations, observer) {
    if (mutations[0].addedNodes.length) {
        mutations[0].addedNodes.forEach(function(el) {
            if(/video/i.test(el.tagName)) {
                el.controls = true;
            }
        });
    }
})).observe(document.body, {
    childList: true,
    subtree: true
});
```
