### ISSUE TITLE
Scrolling on the slides

### ISSUE THREAD

**Issue by JasonWagner47** [hakimel/reveal.js#756]
I would like the slides to be able to be larger than the screen size - so that users could scroll down to read more content on mobile? Is this possible?

**Comment by cmoulliard** [comment]
@JasonWagner47 FYI, I have added a scrollbar class into a div to allow oversizing. Here is the css definition

````
.scrollbar {
    border: 1px solid #eee;
    height: 670px;
    overflow: auto;
    margin: 5px 0 0;
    padding: 5px 10px 10px 10px;
}
````
