### ISSUE TITLE
`data-transition` does not work

### ISSUE THREAD

**Issue by coolwanglu** [hakimel/reveal.js#760]
Setting `data-transition="zoom"` for a slide, it works when the `transition` in config is `default`, but does not when it is `linear`

Seems that the reason is `.reveal.linear .slides>section.future` precedes `.reveal .slides>section[data-transition=zoom].future`

Both rules have the same specificity (according to http://specificity.keegan.st/) and the first rule is define later in the css file.

Tested on Firefox/Chrome/IE on win 8, and I remember that it worked before. Did I do anything wrong?

**Comment by robertop87** [comment]
@hakimel  Related question:
The transitions just works if I use the keyboard to change between slides, but with autoSlide does not works. Is this a expected behavior?
