### ISSUE TITLE
Webpage as slide

### ISSUE THREAD

**Issue by justmytwospence** [hakimel/reveal.js#786]
Would it be possible to have one slide be an entire (full-screen) webpage? Basically an iframe that takes up the full screen with the navigation controls/progress bar overlaid. This would be a wonderful feature for lots of different things, fluidly demonstrating a visualization on bl.ocks.org for example.

**Comment by chacalle** [comment]
It would be nice to be able to be able to use `data-preview-link` for images, headers, etc. Seems like currently it just opens the link outside of the presentation. Is there a way to do this? @hakimel 
```
<section>
	<a href="http://hakim.se" data-preview-link>
		<img class="stretch" src="/images/presentations/Hakim.jpg">
	</a>
</section>
```

**Comment by jcamp** [comment]
Yep, **second that** - would be a brilliant feature, perhaps with some parameters or options to adjust the size of the iframe, etc....
