### ISSUE TITLE
Feature request: Export to single HTML

### ISSUE THREAD

**Issue by paulodiovani** [hakimel/reveal.js#788]
Write presentations in Markdown is a great time-saving, but since they can only run from the Grunt server, it makes impossible to write it on an usb flash drive to present somewhere else or save on github `gh-pages`.

I think that an optio to export a single HTML file presentation would be wellcome, converting Markdown, adding scripts and styles. Even imagem can be attached with base64 notation.

**Comment by rohithpr** [comment]
+1

**Comment by Leftium** [comment]
**I tried a few different inlining tools; I think this one might work: [html-inline](https://www.npmjs.com/package/html-inline).**

However, there is a problem with resources that are referenced inside JavaScript options, for example:

- [Parallax Background](https://github.com/hakimel/reveal.js#parallax-background)
- Reveal.js [dependencies](https://github.com/hakimel/reveal.js#dependencies)


Parallax backgrounds are no big loss, but lack of dependencies means I can't use markdown slides.

I tried loading the markdown plugins as regular script files so the inliner would find them (and commented out the dependencies). The file works fine *before* inlining, but not after. The inlined version gets this error: `inlined.html:1868 Uncaught SyntaxError: Invalid or unexpected token` where inlined.html:1868 is [this line](https://github.com/hakimel/reveal.js/blob/539e774d31f91676bcc3f75e28168921cd27d819/plugin/markdown/markdown.js#L52) from function `getMarkdownFromSlide()`:

 		text = text.replace( new RegExp( SCRIPT_END_PLACEHOLDER, 'g' ), '</script>' );

Any ideas why? What would be different between loading markdown.js as a script file and inlining it?

I'm so close to creating single-file reveal.js presentations that are simple to share!

**Comment by Leftium** [comment]
I did it! Here is [reveal.js/plugin/markdown/example.html](https://github.com/hakimel/reveal.js/blob/master/plugin/markdown/example.html) as a single, inlined html file: [example-modded-inlined.html](https://gist.githubusercontent.com/Leftium/f27c831cb603c23497d1350c9c5a093d/raw/0782f546b5ffba052ab8a67e45ef6a4f2ac8bab8/example-modded-inlined.html). *The example.md file is not inlined, but everything else is~*

Here are the steps to inline your own presentations into a single file:

1. Modify the html file so the markdown plugin JS files are loaded via &lt;script&gt; tags. Like my [example-modded.html](https://gist.githubusercontent.com/Leftium/f27c831cb603c23497d1350c9c5a093d/raw/0782f546b5ffba052ab8a67e45ef6a4f2ac8bab8/example-modded.html).
2. Process this html file with [html-inline](https://www.npmjs.com/package/html-inline).
3. Replace all occurrences of `</script>'` with `<\/script>'` so the HTML is not parsed incorrectly. There should only be two places. (Alternatively, modify markdown.js before inlining.)

**Comment by webmaven** [comment]
Awesome, @leftium!

**Comment by hkdobrev** [comment]
@Leftium I see you haven't inlined the dependencies in the Reveal.js configuration. Have you found a way to address this?

**Comment by Leftium** [comment]
@hkdobrev I'm not sure if this will work for all the dependencies, but I just replaced the Reveal.js dependency configuration with actual script tags. The order required is:

1. marked.js
2. markdown.js
3. reveal.js

I don't use that many dependencies, but I haven't noticed feature degradation at all. Touch swipe gestures, zoom, etc all seem to work.

**Comment by hkdobrev** [comment]
I can now confirm this approach seems to be working.

For reference here's an example of using reveal.js with [inliner](https://github.com/remy/inliner):

https://github.com/hkdobrev/service-providers-slides

In the `master` branch you will see the source of the presentation. Reveal.js and the inliner are npm dependencies. Once you run `npm install` you can run `npm run-script dist` to prepare the `dist.html` with everything inlined. You will find the published version in the `gh-pages` branch in a single `index.html` file.

**Comment by ostcar** [comment]
@jhofker You tipp worked perfectly. It would be nice, if the inliner command would be added to the Grundfile of if this tip would be mentioned in the readme.

**Comment by niklaas** [comment]
You know that @rstudio/revealjs does exactly that, don't you? The only thing is that it normally uses Rmarkdown as input, and not HTML. However, you can also use raw HTML in these files (giving you back flexibility). Anyway, maybe digging into their way of packing everything in one file will help here.

**Comment by demoneaux** [comment]
Thanks for all the useful tools and tips! I'm closing this issue for now, but you can add some of the tools to the Plugins page to share it with others!

**Comment by NicolasWebDev** [comment]
To make @Leftium solution work, I had to load reveal.js before the other two markdown scripts.
```html
<script src="lib/js/head.min.js"></script>
<script src="js/reveal.js"></script>
<script src="plugin/markdown/marked.js"></script>
<script src="plugin/markdown/markdown.js"></script>
```

With that, everything worked like a charm.

**Comment by s1n** [comment]
I tried this and when I relocated the file, it failed to process data-markdown nested sections. Does this only work if I use HTML directly?

**Comment by Leftium** [comment]
Is @s1n trying to inline external markdown files? I write my content directly in the HTML file, and it works fine. Like this:
``` html
<section data-markdown data-separator="^\n---\n$"
         data-separator-vertical="^\n--\n$"
         data-element-attributes="\|s*?([^|]+?)\|">
  <script type="text/template">

# Markdown

  </script>
</section>
```

Also see @hkdobrev's [example using Markdown](https://github.com/hkdobrev/service-providers-slides/blob/master/source.html).

---

If you're trying to inline an external Markdown file, that won't work unless the inliner is smart enough to recognize Reveal.js's special syntax referring to the external file. I opened an issue for [inliner](https://github.com/remy/inliner).

If you need to work with external Markdown files, a work-around may be to use [Pandoc](https://github.com/jgm/pandoc/wiki/Using-pandoc-to-produce-reveal.js-slides):

```
pandoc -t revealjs -s -o myslides.html myslides.md
```

**Comment by s1n** [comment]
I think the thing that finally worked for me was adding the `--nocompress` option that I wasn't using previously. When you have that, it smashes the markdown and it no longer looks as it did before. 

+1 for inliner!

**Comment by hkdobrev** [comment]
@s1n Correct, `--nocompress` is crucial when using Markdown 😉 Cheers!
