### ISSUE TITLE
Vertical Centering is off with Header + Image

### ISSUE THREAD

**Issue by stylerw** [hakimel/reveal.js#789]
Vertical centering works great for text, but when there's an image on the slide, the image's dimensions aren't respected when centering.  As such, it's not uncommon for there to be a large gap at the top of the slide, with the text underneath the image not visible.  I've been trying to find a CSS solution, but haven't yet.  Help!

**Comment by ArVar** [comment]
Same problem. It is hard to reproduce. For me it looks like under some circumstances the rescaling is not working properly for images. When I add an empty section in my markdown:
```
<section data-markdown>
</section>
```
the slide is scaling properly.
