### ISSUE TITLE
Lazy load media

### ISSUE THREAD

**Issue by akaleeroy** [hakimel/reveal.js#793]
I'd like to suggest this enhancement. For presentations heavily laden with images and videos, integrate a lazy load plugin. Maybe lazy-load-xt?

**Comment by abhinandankothari** [comment]
@hakimel Is this available in 3.1 release or Still in dev branch ?

**Comment by mb21** [comment]
Is there ever a reason not to use lazy-loading?

Wondering whether pandoc should output `<img data-src` instead of `<img src` when generating reveal.js slides from markdown, see https://github.com/jgm/pandoc/issues/2283 Some feedback would be great before we make the change...

**Comment by reagle** [comment]
@mb21 see @hakimel above:
> Unfortunately that's the only way to do it. If the presentation markup hits the browser with normal src attributes it's too late, the browser will already have started loading them. Otherwise they could have been replaced entirely via JS.

**Comment by reagle** [comment]
Or are you asking if reveal.js has run into bugs/problems with lazy loading? I've been using it since it became available without problem.

**Comment by mb21** [comment]
Yes, I'm asking whether there are any use-cases where it's preferable to not use lazy-loading when making a reveal.js slideshows...

**Comment by gelinger777** [comment]
Hi There, the lazy loading is cool, but what about  following problem. Let's say we have 10.000-20.000 pages in the presentation, which we need to optimize. The lazy loading only will not help. We need to on moving right or left add the actual HTML of the upcoming 4-5 sections  and sections before to the  dom and remove tem as user move back and forth. Any implementation or plugin for this sofar?

**Comment by robertop87** [comment]
I'm using videos with lazy loading, but at the beginning all then are loaded in memory, is it OK?
I supposed that lazy loading means to have only play asset in the memory.

**Comment by dberardo-com** [comment]
is lazy loading also working with regular html code? lets assume having some very heavy animation, or heavy script tags that need to be executed when the slides shows, is it possible to use lazy loading without iframe in such case ?

and if iframes are required, can regular HTML code be embedded within them ?
