### ISSUE TITLE
New PDF export issue

### ISSUE THREAD

**Issue by trws** [hakimel/reveal.js#808]
I have been using, and loving, reveal.js and the pdf export functionality for a couple of weeks now, but something strange started happening yesterday, I think after a chrome update (I'm currently running Google Chrome version 33.0.1750.117).  The issue is that the currently selected slide prints to pdf fine, but several slides before or after it end up blank or with just the background.  After some number of slides it starts working as expected again.  Just to check and see if it was my local copy somehow being corrupted, I printed the example presentation from the official site, and got this.

https://www.dropbox.com/s/hg4hloglims45sp/reveal.pdf

There are no errors in the javascript log, and everything looks normal except printing.  I'm at a loss, any thoughts on how I might debug this?

**Comment by EoinTravers** [comment]
I have a workaround for preserving fragments in your exported slides, tested on Ubuntu.
This requires two command line tools, `scrot`, for saving screen shots, and xdotool, so automating progress through your slide show.

First, create a version of your presentation with all animated transitions removed (it might be enough to add `?transition=none` to your url). Then, create the following bash script, called `screenshot.sh`:

```sh
mkdir -p screenshots            # Creates it if missing

echo "Now open up your presentation and set it to fullscreen."
echo "You have 10 seconds."
t=10
while [ $t -gt 0 ]; do
      echo "$t..."
      sleep 1
      t=$(($t-1))
done

i=1
pause=1
while true; do
    scrot -d $pause "screenshots/shot$i.png"
    xdotool key space
    i=$(($i+1))
done
```

Open your presentation, set it to full screen mode, and finally open up a terminal, execute your script (`sh screenshot.sh`), and quickly full screen your presentation again, on the first slide. After 10 seconds, scrot will capture your screen every second (adjust `pause` to change this), and xdotool will simulate a press of the spacebar, advancing the slide.

Once your presentation is done, just switch back to the terminal and kill the script with `Ctrl+C`. The new `screenshots/` folder will contain images of your presentation, which you can combine into a single PDF!

**Comment by i3visio** [comment]
That did the trick for us under Ubuntu with the dependencies already satisfied by doing:
```
sudo apt-get install scrot xdotool pdftk
```
Thanks a lot, EoinTravers. ;)

**Comment by poonam6785** [comment]
I am facing same issue .few blank pages in my pdf .My file already having this code
                   <script>
			var link = document.createElement( 'link' );
			link.rel = 'stylesheet';
			link.type = 'text/css';
			link.href = window.location.search.match( /print-pdf/gi ) ? 'css/print/pdf.css' : 'css/print/paper.css';
			document.getElementsByTagName( 'head' )[0].appendChild( link );
		</script>

but its showing blank pages in my pdf file.

**Comment by tiagoweber** [comment]
Based on the simple and yet ingenious solution EoinTravers proposed, I made a little script that follows his recipe and adds an additional spice: checking when the last screenshot is equal to the previous using DIFF and also ordering the slides so that no 1 to 11 and similar jumps occurs when listing slides by name. When two consecutive screenshots are the same, the process stops automatically and the last screenshot is removed. In the original script, the process would go on indefinitely until the user pressed CTRL+C, which required me to stay looking at the screen for a long time to halt the process in the right time.

```
mkdir -p screenshots            # Creates it if missing
rm screenshots/*                # erases previous slides

echo "Now open up your presentation and set it to fullscreen."
echo "You have 10 seconds."
t=10
while [ $t -gt 0 ]; do
      echo "$t..."
      sleep 1
      t=$(($t-1))
done

i=0
previousi=-1
pause=1
slidesareequal=0

while [ $slidesareequal == 0 ]; do
    scrot -d $pause "screenshots/shot$i.png"
    if [ $previousi -ge 0 ]; then
	answer=`diff "screenshots/shot$i.png" "screenshots/shot${previousi}.png"`
	if [ -z "$answer"  ]; then
	    slidesareequal=1
	    rm "screenshots/shot$i.png"
	fi
    fi
    if [ $slidesareequal == 0 ]; then
	previousi=$i
	xdotool key space
	i=$(($i+1))
    fi
done

for name in screenshots/*.png; do convert $name screenshots/`basename $name .png`.pdf; done

list_of_files=""
for i in $(seq 0 $previousi)
do
    list_of_files+=" screenshots/shot$i.pdf"
    echo $list_of_files
done

pdftk $list_of_files cat output Presentation.pdf
```

**Comment by Quakedaragh** [comment]
@hakimel https://csser.space/questions/website-loses-its-css-after-printing
