### ISSUE TITLE
Audio as Fragment

### ISSUE THREAD

**Issue by stylerw** [hakimel/reveal.js#810]
I'm unable to arrange a slide such that audio files play sequentially as fragments (e.g. Slide, click, Audio 1 plays, click, audio 2 plays, next slide..

If I use...
    ---

```
## Contrastive Nasality in Lakhota

### ‘seed’  [su]    
### ‘braid’ [sũ]
```

   `<audio data-autoplay class="fragment" src="sounds/della_su-396.wav"></audio>` 
   `<audio data-autoplay class="fragment" src="sounds/della_su-397.wav"></audio>`

   ---`

Both sounds play at the same time at the start of the slide.  If I take out the "data-autoplay", nothing happens at all when I click through the fragments.

Please help!  I've fallen in love with reveal.js, but I teach about language and sound, so this is a much needed feature.

**Comment by jonathanrobie** [comment]
FWIW, I allow audio playback within fragments using a button that users can select.

A button looks like this:

``` xml
<button data-audio="audio/00-Slide2li2.mp3">▶</button>
```
Here's the JavaScript:

```js
document.addEventListener("click", function(e){ if(e.target.matches("button[data-audio]")){
  new Audio(e.target.dataset.audio).play(); }});
```

**Comment by jschildgen** [comment]
When the audio should play when another fragment is shown:

```javascript
audio = null;
Reveal.addEventListener( 'fragmentshown', function(event) {
  if(event.fragment.id == "play_myaudio") { 
    audio = new Audio("myaudio.mp3"); 
    audio.play(); }
  if(event.fragment.id == "stop_myaudio") { 
    audio.src=""; 
  }
} );
```

```html
<div class="fragment fade-out" data-fragment-index="2" id="stop_myaudio">
    <div class="fragment fade-up" data-fragment-index="1" id="play_myaudio">
       ...
```
