### ISSUE TITLE
vertical slide indicator and desktop swipe

### ISSUE THREAD

**Issue by criesner** [hakimel/reveal.js#822]
Hi,

I've got two feature requests that I think could enhance the experience of reveal.js

Vertical slide indicator;
Most of the presentations take place in the horizontal manner however sometimes I mix in verticals, could there be an option to have something to the left of the screen that indicates that you should scroll down to see more. It could be something as simple as the dot representation found in most sliders, such as this: http://www.idangero.us/sliders/swiper/demos.php

Desktop swipe;
Have you considered adding the ability to click and drag (mimicking the actions of mobile) to swipe between slides with the little grabber hand icon (see link above for how this works). Could be a nice.

Thanks for your considerations!

**Comment by raducoravu** [comment]
+1

**Comment by Delapouite** [comment]
Currently the progress bar at the bottom moves for both normal slides, and vertical slides.

It could have small ticks for delimiting each normal slides. This way we could deduce how many vertical slides are left by watching the progress between each ticks.

**Comment by mikecharles** [comment]
This would be great, it seems too easy for a user not to realize there are vertical slides. Any motion on this?

**Comment by demoneaux** [comment]
The slides controls will light up the down button if there are vertical slides, which serves as an indicator.

**Comment by mikecharles** [comment]
> The slides controls will light up the down button if there are vertical slides, which serves as an indicator.

They are pretty subtle depending on the theme, but I guess that's left to the user to change in the CSS.
