### ISSUE TITLE
highlight.js plugin messes format on <code> sections with tab characters

### ISSUE THREAD

**Issue by Ferk** [hakimel/reveal.js#852]
I'm not sure about what's going on in this presentation: https://gist.github.com/Ferk/0e750a3e6b0bf7b87bff

(I would put it up on slid.es, but I don't see how to include the highlight.js plugin)

The indentation of the resulting slide is wrong and there are huge paddings right after some characters in some of the lines.
For example:

```
        cpu@0 {
            device_type = "cpu";
```

Shows up as:

```
        cpu     @0 {
        device_type =       "cpu";
```

This only happens when highlight.js is loaded.

I would disable highlight.,js, but I would like to use it at least in some other code tags.

EDIT: Solved it by replacing all TAB characters with spaces. Seems like highlight.js doesn't behave well with tabs?

**Comment by CaptainCodeman** [comment]
For anyone who finds this ...

I found using "tab-size" css property works to control how much space a tab character takes up (either to indent or to convert to regular space-like behavior)
