### ISSUE TITLE
Auto-play/pause no longer works with YouTube embeds

### ISSUE THREAD

**Issue by reagle** [hakimel/reveal.js#856]
This is a bug related to the feature implemented in #388 . If you look at the two slides following [1](http://reagle.org/joseph/talks/2013/exemplar.html#/video) in Chrome 33.0.1750.152 you see that neither iframe nor video pause upon advance. In FF 28 the video will pause, and the youtube iframe will not be displayed at all. Using a fresh git pull. It did used to work for me, but stopped at some point relatively recently.

**Comment by nilshg** [comment]
Sorry for resurrecting such an old issue, but the fix doesn't work for me (i.e. when not adding `enablejsapi=1` to the embed URL in my iframe the video doesn't pause upon navigating away from the slide).
Further, I can't get the video to autoplay when I enter the slide; when I add `&autoplay=1` to the URL, the video will start once I start the presentation, not once I reach the slide that it's on.

**Comment by deevus** [comment]
Same issue as above. YouTube videos will autoplay when `autoplay=1` is set in the embed url, but it starts when the presentation is loaded.

**Comment by glopesdev** [comment]
Exactly the same issue more than two years later. Maybe it makes sense to reopen the issue? Youtube iframes with `&autoplay=1` will start playing once the presentation is loaded. Is there any updated workaround for this?
