### ISSUE TITLE
Absolute position of elements is really difficult

### ISSUE THREAD

**Issue by cfjedimaster** [hakimel/reveal.js#857]
Every now and then I have the need to absolutely position an element. For example, I may be using a slide background where I want an h1 to be in the upper right, or left corner. While negative css values could work, my concern is how they would show up at a different resolution (like when presenting). It seems like it should be simpler to do this. My friend Rey created this work around (https://gist.github.com/planetoftheweb/9903168), and I made it a bit more generic (https://gist.github.com/cfjedimaster/9903495), but is there a simpler way?

**Comment by rofrol** [comment]
My solution https://github.com/hakimel/reveal.js/issues/180#issuecomment-173543708
