### ISSUE TITLE
Slide number not updated in URL fragment

### ISSUE THREAD

**Issue by lvh** [hakimel/reveal.js#867]
[My presentation](http://www.lvh.io/TwistedMixing/) updates the slide number in the bottom right of the screen, but does not update the slide number in the fragment of the URL (the thing after the `#`). This breaks the back button when I go to video :-(

It works for me fine in the demo reveal.js presentation, even with the exact same version of reveal.js, but I can't figure out the difference in HTML source.

**Comment by juhp** [comment]
Why is the default `false` btw?

**Comment by jorgetutor** [comment]
Same issue on OSX (10.12.3 (16D32)) + Chrome (Version 58.0.3029.81 (64-bit))
Previos versions of revel worked for me, last one not even changing the history param.
In firefox is works.
Any clue?
