### ISSUE TITLE
[feature-request] please, add a command line option

### ISSUE THREAD

**Issue by kemelzaidan** [hakimel/reveal.js#882]
It would be nice to have different html or markdown files, and be able to use them with a command line option, like this:

``` sh
$ revealjs my_presentation.html
$ revealjs another_presentation.md
```

**Comment by anantshri** [comment]
i hope my butting in here is not considered rude however @kemelzaidan you might find this project of mine useful 
https://github.com/anantshri/automated_revealjs/
as @hakimel suggested i am consuming reveal.js here to have a simple flow for creating presentations using external markdown features.
