### ISSUE TITLE
Multiple fragments in same class name

### ISSUE THREAD

**Issue by abelnation** [hakimel/reveal.js#889]
I understand that it complicates the data-fragment-index feature, but it would be handy to be able to specify multiple fragment steps for a single element using multiple classes on the element instead of the nesting method.  

This would allow multiple fragments in markdown as well.  Don't know if it's possible, but would be useful.

**Comment by HimbeersaftLP** [comment]
You can do this using the CSS subsequent-sibling combinator:
```html
<style>
    .fragment.custom.my-frag-1, .fragment.custom.my-frag-2 {
        display: none;
    }
    .fragment.custom.my-frag-1.visible ~ .my-element {
        color: red;
    }
    .fragment.custom.my-frag-2.visible ~ .my-element {
        color: green;
    }
</style>
<div>
    <span class="fragment custom my-frag-1"></span>
    <span class="fragment custom my-frag-2"></span>
    <div class="my-element">My text</div>
</div>
```

Note that if you want to use this multiple times on one slide, you will either need to wrap the entire thing into an element (like in my example) or use the next-sibling combinator (`+`) instead (but in that case, you need to consider the second fragment span e.g. `.fragment.custom.my-frag-1.visible + .fragment.custom.my-frag-2.visible + .my-element`).
