### ISSUE TITLE
How to justify-left the content with markdown

### ISSUE THREAD

**Issue by xautjzd** [hakimel/reveal.js#890]
I'm using markdown to write my presentation, but I find  contents in the slides are center-aligned. How to left-align it?I have read the documents, but still cann't find the answer.

**Comment by eugeniax** [comment]
Sorry, I am a new comer. Do you mean I need to edit css file or I can incorporate the above code in the markdown file? If it is the latter, where should I insert the above code? Thank you!

**Comment by show0k** [comment]
@eugeniax If you want to override the CSS, you can simply and te above snippet in the head of your html file, after the import of your theme stylesheet.
But, the the above snippet is outdated, now you cans simply add 
```html
<!-- .slide: style="text-align: left;"> -->  
 
``` 
In your markdown.
