### ISSUE TITLE
Decorate slides with .previous and .next classes

### ISSUE THREAD

**Issue by hakimel** [hakimel/reveal.js#903]
These two classes will only be applied to one slide at a time: the one immediately before the present slide and the one immediately after it.

**Comment by maxim-torba** [comment]
If I'm not mistaken, there are already classes: past, present, future

**Comment by hakimel** [comment]
That's right – previous/next classes were intended for the one slide that comes directly before and the one slide that comes directly after the current slide. Whereas past/future applies to ALL prior or later slides. 

That said, I opened this in 2014 and haven't needed it since so will close :)
