### ISSUE TITLE
Online edited slides not working same on local machine.

### ISSUE THREAD

**Issue by sidtechnical** [hakimel/reveal.js#921]
Hello, I created my slides online, but when I downloaded and changed the code ( By copy pasting") in the export option, at some places the text is going beyond the screen, it was not happening like that in the online editor. Rest all looks fine, what and where should I tweak.

Here is my slide http://slides.com/sidnext2none/bitcoin/
Attached the image when I am using it in local machine along how it looks online.
![out_of_the_frame_on_local machine](https://cloud.githubusercontent.com/assets/2378582/3007385/b66a49dc-de81-11e3-9ed2-1df3c87a6053.png)
![samepageonline](https://cloud.githubusercontent.com/assets/2378582/3007386/bacccc70-de81-11e3-95b0-2e784e2dfc5d.png)

**Comment by demoneaux** [comment]
The slides.com output is probably different from just plain Reveal, hence it is difficult for us to help you figure out the issues. There doesn't seem to be a clear error, just formatting issues, so you might have to check out the CSS yourself.
