### ISSUE TITLE
Data separator and data vertical don't work with external markdown

### ISSUE THREAD

**Issue by ocombe** [hakimel/reveal.js#929]
I tried the following and it worked:
```
<section data-markdown data-separator="^\n----\n$" data-vertical="^\n---\n$">
  <script type="text/template">
    ###Title

    ---

    ####Title 2
    * 1
    * 2
  </script>
</section>
```

![capture d cran 2014-05-29 15 41 35](https://cloud.githubusercontent.com/assets/265378/3118007/00fdbe94-e737-11e3-96f3-6fbf5b1a0152.png)

But if I use an external markdown file:
```
<section data-markdown="slides/test.md" data-separator="^\n----\n$" data-vertical="^\n---\n$"></section>
```
Everything is stacked in one page, the vertical slides are not created ...
![capture d cran 2014-05-29 15 40 43](https://cloud.githubusercontent.com/assets/265378/3118001/e07a1758-e736-11e3-8c38-baabe04a1cc8.png)

Any idea ? Is it a bug or a config problem ?

**Comment by callahad** [comment]
Haven't fully debugged, but I think this is a configuration issue. My own presentation to works just fine without using Grunt, yet @ocombe's test case does not work. Still digging...

**Comment by callahad** [comment]
Oh, @ocombe's test actually works just great for me after renaming `data-vertical` to `data-separator-vertical` (per changes from https://github.com/hakimel/reveal.js/commit/015468c3a2d1d4092f33920ac555a0e288e6213f, released in 3.0 on Jan 9, 2015).

I believe @rhhamburg correctly diagnosed the issue: if I switch my `slides.md` file between Unix and Windows line endings, it works (Unix) and fails (Windows).

Updating the regex to include an optional `\r` fixes it for me regardless of line endings: `data-separator="^\r?\n----\r?\n$" data-separator-vertical="^\r?\n---\r?\n$"`

Similarly, the following regex works with both line endings: `data-separator="^----$" data-separator-vertical="^---$"`

**Comment by callahad** [comment]
@hakimel I suggest updating the `DEFAULT_SLIDE_SEPARATOR` in [markdown.js line 29](https://github.com/hakimel/reveal.js/blob/3.0.0/plugin/markdown/markdown.js#L29) with `^\r?\n---\r?\n$` (or just `^---$`) and closing this as a configuration issue.

FWIW, in my own decks I use `^\s{0,3}-\s*-\s*-[-\s]*$` and `^\s{0,3}\*\s*\*\s*\*[\*\s]*$`, which let me use a line of three or more hyphens or asterisks to indicate horizontal or vertical separations, respectively, which matches up nicely with [Markdown's horizontal rule syntax](http://daringfireball.net/projects/markdown/syntax#hr).

**Comment by hakimel** [comment]
@callahad Thanks for debugging this. I've updated the default slide separator regex as you suggested.

Closing.

**Comment by timcsmith** [comment]
Did this bug creep back into the latest version. I cannot get a vertical slide to work - in either the external or md file. 

For external 
<section data-markdown="example.md" data-separator="^\r\n----" data-vertical="^\r\n---">
And in this file...
###Title

----

####Title 2
* 1
* 2
* 3

This produces a seperate slide, 

but this
###Title

---

####Title 2
* 1
* 2
* 3

Doesn't produce a new vertical slide, but instead the following "stacked" (single slide) 

![capture](https://cloud.githubusercontent.com/assets/20436471/17353140/4dc44842-5913-11e6-82b7-263dc068af53.PNG)

**Comment by soundspawn** [comment]
Try with data-separator-vertical instead of data-vertical - worked for me on 3.3.0

Check markdown.js plugin around line 239
`verticalSeparator: section.getAttribute( 'data-separator-vertical' ),`

**Comment by noraj1337** [comment]
it's not `data-vertical` but `data-separator-vertical`

**Comment by yveskerbensd** [comment]
If you are using windows, this should work:
<section data-markdown="presentations/qualys/weekly_update.md"
					data-separator="^\r\n\r\n\r\n"
					data-separator-vertical="^\r\n\r\n"
					data-separator-notes="^Note:"
					data-charset="iso-8859-15">

**Comment by iphone-web-appcorrection** [comment]
@tlyim https://lnkr.fun/50a1a67
