### ISSUE TITLE
Mathjax preloading

### ISSUE THREAD

**Issue by bartbog** [hakimel/reveal.js#939]
Mathjax is now loaded on the moment a slide appears. 

This causes transitions to slow down significantly. 

It would be better if mathjax loads all math for all slides when the presentation is started. 

I use a local mathjax instalation with latex, on Ubuntu 12.04,with chromium and/or Firefox

**Comment by demoneaux** [comment]
Yup, I don't see how this can be fixed easily, as we have to hide slides until they are displayed. Closing for now.
