### ISSUE TITLE
Overview mode is laggy

### ISSUE THREAD

**Issue by owenversteeg** [hakimel/reveal.js#94]
When I open overview mode with a slideshow that has about 20 pictures, it lags and glitches. Suggested fix: changing images so that they resize to a smaller size immediately before overview mode is opened.

I might submit a pull request to fix this sometime in the next few days if someone else doesn't.

**Comment by drammock** [comment]
over 3 years later, here is a possible workaround for anyone still running into this: disable transitions in overview mode.  Change the code [here](https://github.com/hakimel/reveal.js/blob/18b644cf8f1ae04b16f962655b99cb786f08ef2c/css/reveal.css#L1043-L1045) to:

``` css
.reveal.overview-animated .slides {
  -webkit-transition: none;
          transition: none; }
```

(changing it in the SCSS source [here](https://github.com/hakimel/reveal.js/blob/18b644cf8f1ae04b16f962655b99cb786f08ef2c/css/reveal.scss#L1047-L1049) probably makes more sense, but it seems that changes to that file aren't picked up by `grunt css-themes` so for an end-user hack editing the compiled css might be easier).

**Comment by burnpanck** [comment]
@drammock: I think the grunt task for the main css is simply called `grunt css`. I might be wrong.

I have made a shot at implementing a thumbnail based overview mode (#1827). The thumbnails can be generated using PhantomJS, as in #1826. However, as of now, the latter is missing a grunt task, and the former fallback mechanisms in case of missing thumbnails.
