### ISSUE TITLE
Reveal.js does not react on keypress when paused.

### ISSUE THREAD

**Issue by bartbog** [hakimel/reveal.js#941]
I use a logitech R400 presenter. 
It has a "pause presentation (blank screen)" button. 

However, this sends the key 186 (:) to the active program. 
I can use the initalisation in reveal to remap this key to the "togglepause" button using

keyboard: {
39: 'next',//Presenter (right arrow is next)
37: 'prev',  //Presenter (left arrow is prev)
186: 'togglePause' //Presenter blank screen
},

This works perfectly, pushing the button causes the screen to blank. 
However, this button cannot be used to "unpause" the presentation since reveal only listens to "b" to unpause...

**Comment by hakimel** [comment]
Fixed by @davidbanham in #959
