### ISSUE TITLE
Horizontal position (overlapping images)

### ISSUE THREAD

**Issue by rparree** [hakimel/reveal.js#945]
Hi,

I would like to sometimes use overlapping images (for dynamic building up of a complex image).

The standard "hack" for this is something along the lines of:

``` html
<div style="position: relative" >
   <img class="img-inline"  src="foo1.png" />
   <img class="img-inline" style="position: absolute; top: 0; left: 0;" src="foo2.png" />
</div>
```

When the slide is rendered the second image is  25px to the left. I know i can add a `left: 25px`  but i am afraid this "magic number" won't be responsive to browser and device.

I am aware absolute positioning is troublesome in reveal, but is there not a way for reveal to treat these two image the same way?

tx.,

**Comment by demoneaux** [comment]
Maybe you could try positioning the slide itself as `position: relative`.
