### ISSUE TITLE
Adding support for bower or reveal.js-contrib?

### ISSUE THREAD

**Issue by maxmeyer** [hakimel/reveal.js#955]
Hi there,

would it be possible to include something like https://www.npmjs.org/package/grunt-bower into reveal.js/grunt? 

This way one can add all the frameworks she/he needs, but leaves reveal.js-core lean. Maybe there could be a reveal.js-contrib-repository setup with the external dependencies which are awesome but which do not need to be part of reveal.js-core, e.g. #917.

What do you think?

Cheers,
max_meyer

**Comment by demoneaux** [comment]
I think a simple solution would be to use npm modules, which are now typically used not just for JS files but also all sorts of assets.
