### ISSUE TITLE
Print slides in the middle of the page

### ISSUE THREAD

**Issue by dnister** [hakimel/reveal.js#962]
As a user I want possibility to print content of slide in the middle of the pdf page like It can be done by setting attribute `center: true,` in initialization of reveal.js

Have It can be done?

**Comment by ewirth** [comment]
Doesn't working in Firefox for me :/

http://lab.hakim.se/reveal-js/?print-pdf

Most content is still in the top in most pages.

**Comment by bnjmnt4n** [comment]
Yep, PDF printing still has some issues in some browsers, but most features should be fine in most modern browsers. For now we recommend using in Chrome which is where most features work, including centering for now. I'll try to look at the code for printing to see what there is to do to improve things in Firefox.

**Comment by ewirth** [comment]
I am using an external Markdown file inside reveal.js, and it seems that it only works in Firefox.
