### ISSUE TITLE
Fragment Index via Reveal.getIndices() Incorrect

### ISSUE THREAD

**Issue by RichFromGalvanize** [hakimel/reveal.js#967]
I have rolled my own solution, and this seems to be undocumented, but I just wanted to bring this to your attention.

I have the follow slide data:

``` html
<section>
  <h1>Introduction</h1>
  <p>My product discussed here</p>
</section>
<section id="show-a-link">
  <h1>Show a live link</h1>
  <aside class="notes">
    Oh hey, these are some notes. They'll be hidden in your presentation, but you can see them if you open the speaker notes window (hit 's' on your keyboard).
  </aside>
</section>
<section>
  <h2>Test Code</h2>
  <pre data-lang="javascript" data-fragmented><code data-fragment-index="0">(function() {</code>
  <code data-fragment-index="1">var meta = {
      title: document.getElementsByTagName('title')[0].innerHTML
    },
    titleElm = document.getElementById('footerTitle'),
    authorElm = document.getElementById('footerAuthor');</code>

  <code data-fragment-index="2">var info = document.getElementsByTagName('meta');</code>
  <code data-fragment-index="3">for (var i=0; i < info.length; i++) {</code>
    <code data-fragment-index="4">if(info[i].getAttribute('name')) {
      meta[info[i].getAttribute('name')] = info[i].getAttribute('content');
    }</code>
  <code data-fragment-index="3">}</code>
<code data-fragment-index="0">})();</code></pre>
</section>
<section>
  <h1>Slide 3</h1>
  <p>How does one revisit an arbitrary slide in code?</p>
  <p>Visit internal slide<a href="#/show-a-link"> 2</a>
</section>
```

So, obviously Reveal is not really designed for such a complicated fragment setup like this, but it appears that an index is skipped when retrieving the fragment index via `Reveal.getIndices()`.

I am messing around with multiplexing, which is how I found the issue. The Reveal fragments work great normally. They come in in order and all of them work as expected. However, I noticed my "clients" in multiplexing was skipping a fragment and digging into the multiplexing code I found it is using `Reveal.getIndices().f` to get the fragment index. The multiplexing code is actually pretty simple code, so there is nothing else I can see to be the issue. I did some console logging (of course) and have confirmed `Reveal.getIndices().f` is skipping an index for some reason.

My "monkey patch" solution I am using (I am fine with it. Doesn't bother me.) is:

``` javascript
var indexf = evt.fragment.getAttribute('data-fragment-index');
```

So Reveal is handling the elements correctly and everything. Its just that function that seems to be a little wonky.

If I am missing something, just let me know. I certainly could have missing something, somewhere.

**Comment by madduck** [comment]
This still seems to be a problem. If I enter a page with fragments, the fragment index is -1. If I have one element on the page with `data-fragment-index="2"`, then advancing will show the element, but set the fragment index to 0.
