### ISSUE TITLE
Disable fragments when scrolling back

### ISSUE THREAD

**Issue by Phyks** [hakimel/reveal.js#972]
Hi,

Usually, when one scrolls back through a presentation, he wants to get to a specific slide (I know about the overview mode, but sometimes it just happens that you slided to much and have to go back one or two slides) and has already passed by the previous slides. Then, maybe it could make sense to have an option to disable fragments when scrolling back through slides, and only enable them when scrolling forward.

What about it ?

**Comment by kiryph** [comment]
One can use the event [`fragmentshown`](https://revealjs.com/fragments/#events) to remove the class `fragment` from the html element as following:
```javascript
Reveal.on( 'fragmentshown', event => {
    event.fragment.classList.remove("fragment");
} );

```

A full example is:
```html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

        <title>reveal.js</title>

        <link rel="stylesheet" href="dist/reset.css">
        <link rel="stylesheet" href="dist/reveal.css">
        <link rel="stylesheet" href="dist/theme/black.css" id="theme">

        <link rel="stylesheet" href="plugin/highlight/monokai.css" id="highlight-theme">
    </head>
    <body>
        <div class="reveal">
            <div class="slides">
                <section>Slide with fragments
                    <p class="fragment" >Point 1</p>
                    <p class="fragment" >Point 2</p>
                </section>
                <section>2nd Slide fragments
                    <p class="fragment" >Point 1</p>
                    <p class="fragment" >Point 2</p>
                </section>
            </div>
        </div>

        <script src="dist/reveal.js"></script>
        <script src="plugin/notes/notes.js"></script>
        <script src="plugin/markdown/markdown.js"></script>
        <script src="plugin/highlight/highlight.js"></script>
        <script>
        Reveal.initialize({
            hash: true,
            plugins: [ RevealMarkdown, RevealHighlight, RevealNotes ]
        });

        // =============== REVEAL FRAGMENTS ONLY ONCE  ===============
        // Nobody wants to see the same joke twice.
        // Following the example of https://shwr.me/?full#11
        Reveal.on( 'fragmentshown', event => {
            event.fragment.classList.remove("fragment");
        } );
        // ===========================================================
        </script>
    </body>
</html>
```

Related issue: https://github.com/hakimel/reveal.js/issues/1071

**Comment by s9w** [comment]
This is a friendly request to maybe consider making this an option. The back behavior of reveal.js is 1) different than any other similar software I've used and 2) very inconvenient. I would argue that if you go back in an actual presentation setting (and not while just fiddling with it), you almost always want to go back slides and not bother with animations.

**Comment by hakimel** [comment]
I recently added support for holding alt while navigating to skip fragments. That way you can choose if you want to view them or not which should help when navigating back.

I'm open to making this a configurable option as well but wouldn't want to change the default behavior. It's important to remember that fragments are used for many different types of animations—including hiding and stacking content. In those situations, disabling fragments when going back would make some content unreachable.

**Comment by s9w** [comment]
I'm completely on board with that. I just tested the new alt-back and it works great. But I'm not sure if that's always feasible. Presentations are often done on other peoples computers, sometimes even with these little widgets you hold in your hand. I guess rebinding things would work. But I'm +1 for adding this as an option.

**Comment by jmuheim** [comment]
Is there any documentation on using `alt`? I don't really seem to understand how I can use it (or what effect it has exactly).
