### ISSUE TITLE
Automatically resume autoslide?

### ISSUE THREAD

**Issue by shababo** [hakimel/reveal.js#973]
Is there a parameter that resumes autoslide if there is no user input for some number of milliseconds? If not, do you have a suggestion for implementing this?

Thanks so much.

**Comment by soichih** [comment]
I really want this feature also.

@shababo Were you able to come up with a script that does this?

Right now I have setInterval set to call Reveal.toggleAutoSlide(true) periodically (like every 10 minutes).
