### ISSUE TITLE
Weird looking polish characters

### ISSUE THREAD

**Issue by Biegal** [hakimel/reveal.js#989]
Hi!

At first, thanks for nice piece of code! Appreciate it

Although I have small problem.
While creating new presentation, it looks like Polish characters are not rendered right, like on the screen:
![screenshot](https://cloud.githubusercontent.com/assets/1469159/3872939/772b592c-2126-11e4-920e-45fb7972dea5.jpg)

First, I've though it's problem with the font itself, but I've checked on
http://www.fontsquirrel.com/fonts/League-Gothic
and it looks like font covers those chars too.

So I'm wondering, if it's only some subset of that font used to reduce size of download, or maybe there is some 'post processing' of the text, that could lead to such results ?

Thanks in advance for any hint!

Regards,
Marcin

**Comment by hakimel** [comment]
You're right – the existing version of the font was subset. I've generated new versions of these font files and tested with some sample Polish text to confirm that it works.

The files were updated in the dev branch, it'll make its way into master with #1093

**Comment by keradus** [comment]
great to hear!

**Comment by steelman** [comment]
Capital X looks funny too. 
![image](https://user-images.githubusercontent.com/77683/136261118-fbc47adb-17c8-4802-b874-25fcd308d991.png)
